subiquity/client/controllers/filesystem.py
subiquity/common/apidef.py
subiquity/server/controllers/filesystem.py

In the following patch:
4c59e1ee never return a PROBING response from guided_POST
we fixed a UI crash occurring when a storage probing operation was ongoing while the user would enter the partitioning screen with "Use an entire disk".
To address the issue, we made `POST /storage/guided` return the last (cached) successful probe result rather than returning a potential PROBING status result.
That being said, when "Custom Storage Layout" is selected, we are using a different HTTP call: GET /storage which can also return a PROBING status result. So our fix was only partial.
This patch adds a "use_cached_result" parameter (which defaults to false) to GET /storage. This makes the call return the last successful probe result.
When the client selects "Custom Storage Layout" we now explicitly …

storage: make GET /storage return the last successful probe result when requested

---

subiquity/client/controllers/filesystem.py
subiquity/common/apidef.py
subiquity/server/controllers/filesystem.py

* cherry-picked 0a954645d6 from #1456 - to fix UI crash when reaching the custom disk layout screen if a storage probing operation is ongoing. https://launchpad.net/bugs/1993257

Kinetic merge 2022-10-18

---

documentation/autoinstall-reference.md
documentation/autoinstall-schema.md
documentation/autoinstall.md

This PR updates the autoinstall-reference documentation with the new keys that were added after the 20.04 release.

autoinstall reference documentation update

---

documentation/autoinstall-quickstart-s390x.md
documentation/autoinstall-quickstart.md
documentation/autoinstall-reference.md
documentation/autoinstall.md

This PR namely updates the quickstart guides (both the generic one and the one specific for s390x).
The instructions still apply well with the new kinetic release. I did testing with 1024MiB of RAM and it worked surprisingly well but I still decided to bump this value to 2048MiB ; which seems reasonable, The s390x quickstart guide already used 2048MiB of RAM so it is now consistent.
I didn't find a good way to avoid making the documentation dependent on a specific ubuntu release. Therefore, the documentation explicitly mentions 22.10 / kinetic but the instructions work the same on a jammy or focal image (tested).
It also fixes a mistake in the shutdown autoinstall section ; where the default value that I documented was wrong.
I think once I address any potential comments, the document …

Autoinstall doc update

---

subiquity/models/filesystem.py

If subiquity detects it should not add a swapfile (e.g., swap partition present, or root filesystem on btrfs), it renders this curtin config:
```
swap:
swap: 0
```
But that should be:
```
swap:
size: 0
```
Per the curtin docs [1]:
```
swap
size: <Size string>
Configure the exact size of the swapfile. Setting size to 0 will disable swap.
```
[1] https://curtin.readthedocs.io/en/latest/topics/config.html#swap
Tests: (build snap/modify ISO as in README.md)
- before:
```
$ cat /proc/swaps
Filename	... 
/swap.img	... 
/dev/vda3	...
$ sudo grep -A1 ^swap: \
/var/log/installer/curtin-install/subiquity-partitioning.conf
swap:
swap: 0
```
- after:
```
$ cat /proc/swaps 
Filename	... 
/dev/vda3	...
$ sudo grep -A1 ^swap: \
/var/log/installer/curtin-install/subiquity-partitioning.conf
swap: 
size: 0 …
```

filesystem: fix curtin config to disable swapfile

---

examples/answers-lvm-dmcrypt.yaml
subiquity/client/controllers/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/filesystem/lvm.py
subiquity/ui/views/filesystem/tests/test_lvm.py
subiquity/ui/views/identity.py
subiquitycore/ui/form.py
system_setup/ui/views/identity.py

The identity screen implements a mechanism to make sure that the confirmation password is the same as the original password. This implementation leans on hard-coded field names (i.e., "password" and "password_confirm") which is perfectly understandable since this is what we have in the identity screen.
Nevertheless, in the storage screen, we decided to import this mechanism and use it as-is to compare passphrases. The implementation prevents us from using different field names such as "passphrase" and "passphrase_confirm" ; which makes the code confusing.
To make things more developer-friendly (is that a thing?), I exported the confirmation mechanism from the identity screen to `subiquitycore.ui` and made it a method of `BoundFormField`.
Before:
```python
class FormWithPassphrase(Form): …
```

Refactor how we handle confirmation fields - use passphrase instead of password where relevant

---

examples/answers-tpm.yaml
examples/snaps/v2-systems-classic.json
examples/snaps/v2-systems-defective.json
examples/snaps/v2-systems-mandatory.json
examples/snaps/v2-systems-prefer-encrypted.json
examples/snaps/v2-systems-prefer-unencrypted.json
examples/snaps/v2-systems-unavailable.json
examples/tpm-sources.yaml
scripts/runtests.sh
subiquity/client/controllers/filesystem.py
subiquity/common/serialize.py
subiquity/common/types.py
subiquity/models/source.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapdapi.py
subiquity/tests/api/test_api.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/filesystem/probing.py

This is definitely missing a few pieces (it should display an error in some situations vs just crashing) but it's a start. I'd also like to provide sample data for various different varieties of system and some integration (at least...) tests.
The main decision here are that we will change the source catalog to indicate the snapd label for the system being installed. We should probably extend this check if the system being installed defines a kernel and gadget snap -- a system that does not do this probably does not require any extra effort.

Start of UI for TPM-backed FDE

---

apt-deps.txt
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

* fixed implementation of `disk.available_for_partitions` that always considered the disk had a GPT.
* fixed bug forcing the user to hard-code all offsets when using storage version 2 with a partition with `size: -1`. https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1991413
* fixed sometimes wrong size assigned to a partition that had `size: -1`. The value `-1` (that is an valid integer) was used accidentally in the computations to determine the appropriate size for the partition. https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1991929
* fixed my recent unit tests that were not specifying the partition table type. This resulted in a GPT partition table (that use different alignment and space constraints).
I am now able run a successful autoinstall with the data from …

Multiple fixes for size: -1 partitions

---

apt-deps.txt
documentation/.gitignore
documentation/Makefile
documentation/autoinstall-quickstart-s390x.md
documentation/autoinstall-quickstart.md
documentation/autoinstall-reference.md
documentation/autoinstall-schema.md
documentation/autoinstall.md
documentation/substitute-links.py

Before we start adding or extending existing autoinstall sections, we should keep a copy of the autoinstall doc in the ubuntu/kinetic branch. 
--
This patch is an aggregate of all the following documentation updates from the main branch as of 66a55ad39bbb9e81e6e76775b3ee00d1e4be9a2a.
doc: import autoinstall markdown documents from discourse
doc: make links to anchors work with pandoc
doc: build with pandoc
doc: use better links in s390x page
doc: implement link substitution mechanism
doc: escape asterisks in markdown
doc: import latest JSON schema in autoinstall doc
doc: consistency fixes for autoinstall doc
doc: document "source" section in autoinstall-reference
doc: document "drivers" section to autoinstall-reference
doc: document "ubuntu-pro" section in autoinstall-reference
doc: …

doc: backport documentation updates for kinetic

---

autoinstall-schema.json
documentation/autoinstall-reference.md
documentation/autoinstall-schema.md
subiquity/common/apidef.py
subiquity/common/types.py
subiquity/models/codecs.py
subiquity/models/subiquity.py
subiquity/server/controllers/__init__.py
subiquity/server/controllers/codecs.py
subiquity/server/server.py

Subiquity now supports a new endpoint that can be used by the desktop installer to configure whether the `ubuntu-restricted-addons` package should be installed. This package contains third-party codecs commonly used on a desktop install.
```bash
$ curl --unix-socket /run/subiquity/socket http://a/codecs
{"install": false}
$ curl --unix-socket /run/subiquity/socket http://a/codecs -d '{"install": true}'
$ curl --unix-socket /run/subiquity/socket http://a/codecs
{"install": true}
```
I was considering naming this endpoint something else than `codecs`, like `restricted-addons` maybe?

codecs: add ability to install ubuntu-restricted-addons

---

subiquity/server/controllers/filesystem.py
subiquity/server/mounter.py
subiquity/server/tests/test_mounter.py
subiquity/tests/api/test_api.py

For the systems currently being tested, the live installer environment is stacked on the one being installed and so the system definition for the system being installed is already available. That's not going to be true in full generality though, so add some helpers to make all systems defined in the source available in the live installer environment before calling into snapd to find out about them.

bind mount systems from before asking snapd about them

---

subiquity/server/controllers/refresh.py
subiquity/server/controllers/tests/test_refresh.py

The point of switching snap channel based on .disk/info is so that we can avoid releasing updates to point release media if they won't work there. If the snap is not tracking ubuntu/stable-XX.YY then there is funny business afoot and we are not on point release media, so switching channels as if we are is just unhelpful (for example, if you are working on a project that is going to involve giving someone an image with a subiquity from a non default track).
If the channel to switch to comes from the kernel command line or autoinstall though, it should still be honoured.

do not switch snap channel from .disk/info if not on ubuntu/stable-XX.YY

---

subiquity/models/source.py
subiquity/server/server.py

The code in subiquity main could plausibly be offered as an upgrade to users installing focal server and focal server ISOs do not have a source catalog so we need to support that. But we will never support a desktop ISO that does not have a source catalog so we can remove some slightly confusing code that attempted to cover that case.

remove any support for a desktop installer without a source catalog

---

subiquity/client/controllers/filesystem.py

The integration tests with TPM answers are flaky at the moment. It causes some workflows to fail.
@mwhudson added a patch as part of https://github.com/canonical/subiquity/pull/1485 that addresses the issue:
https://github.com/canonical/subiquity/pull/1485/commits/97901a78a254ff3aa55e97a578dceae4ea2e3574
Make it part of an independent pull request so that we can merge it ASAP.

Cherry-pick patch - fix answers race (maybe)

---

subiquitycore/utils.py

When executing a command via arun_command with check=True, we forge and then raise a `CalledProcessError` exception if the command exits abnormally (i.e., exit code != 0).
When doing so, we only instantiate the exception with the exit code and the command executed. This means that we lose access to any output captured so far. This is usually fine for stdout but stderr oftentimes contains invaluable information to understand what caused the command to exit abnormally.
Back in Python 3.5, `stdout` and `stderr` were introduced as new attributes for `CalledProcessError`.
We now also include `stdout` and `stderr` in the `CalledProcessError` instances that we forge. This allows us to access stderr (if any) when catching the exception with:
```python
try:
...
except CalledProcessError as exc: …
```

utils: inc. captured stdout / stderr when forging CalledProcessError

---

subiquity/client/controllers/ssh.py
subiquity/common/apidef.py
subiquity/common/types.py
subiquity/server/controllers/ssh.py
subiquity/server/controllers/tests/test_ssh.py
subiquity/ui/views/ssh.py

The proxy settings specified by the user were ignored when importing SSH keys from github / launchpad. This PR fixes the issue by explicitly passing the https_proxy environment variable when a proxy is set.
The calls to `ssh-import-id` used to be done on the client side of Subiquity. Our design makes it difficult to know in a given screen what proxy settings are required to access the network.
I decided to move the calls to `ssh-import-id` on the server side and expose an API to do it. Not only does it allow us to pass the relevant proxy variables in the environment, it could also be used to pass locale-related variables (e.g., LC_MESSAGES) which we are not doing as part of this PR.
From the client's standpoint, the behavior should be identical to status quo when no proxy is needed. The …

Fetch SSH keys through the configured proxy

---

examples/answers-tpm.yaml
examples/tpm-dr-config.yaml
scripts/runtests.sh
subiquity/cmd/server.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/dryrun.py
subiquity/server/server.py

Subiquity attempts to bind-mount `/var/lib/snapd/seed/systems` from the source to the host. Unfortunately, in standard ubuntu-server installs, the directory does not exist so the install crashes early with a `CalledProcessError` (mount: No such file or directory). 
https://bugs.launchpad.net/subiquity/+bug/1997538
This PR essentially checks if the directory exists before trying to bind-mount it.
Unfortunately, adding this check impacts dry-run executions (and unit tests) because the behavior becomes dependent on the presence of `/var/lib/snapd/seed/systems` on the host (in dry-run mode, the source path is set to `/` so we look for the `systems` directory on the host).
I took the opportunity to introduce a configuration object that controls what Subiquity does in dry-run mode (I have …

Fix crash when /var/lib/snapd/seed/systems does not exist on source

---

subiquity/ui/views/ubuntu_pro.py

Upon reaching the Ubuntu Pro screen that shows the user-code, we need to initiate a contract selection. If we are navigating to the screen a second time though, we need to cancel existing contract selections before initiating a new one.
Failing to do so results in a UPCSAlreadyInitiatedError.

ubuntu-pro: cancel any contract selection before initiating a new one

---

examples/dr-config-magic-attach.yaml
subiquity/cmd/schema.py
subiquity/server/controllers/tests/test_ubuntu_pro.py
subiquity/server/controllers/ubuntu_pro.py
subiquity/server/dryrun.py
subiquity/server/tests/test_ubuntu_advantage.py
subiquity/server/ubuntu_advantage.py

This PR adds the ability to test Subiquity with magic-attach in dry-run mode against the staging (or another) environment.
As part of https://github.com/canonical/ubuntu.com/pull/11974, the web and design team deployed a demo web portal that connects to the staging environment.
To test Subiquity with magic-attach in dry-run mode, one simply needs to:
* pass the `--dry-run-config examples/dr-config-magic-attach.yaml` option
* navigate to https://ubuntu-com-11974.demos.haus/pro/attach instead of https://ubuntu.com/pro/attach when instructed to.
When testing, I noticed a crash when going back. I will investigate and fix the issue as part of a different PR.

MagicAttach: add ability to test in dry-run against the staging environment & demo web portal

---

subiquity/server/controllers/filesystem.py
subiquity/server/snapdapi.py

This kind of change is a bit of a problem with the current approach to talking to snapd I guess -- deserialization will fail if we encounter a new value for one of these fields.

add a new member of the snapdapi.Role enum

---

subiquity/common/filesystem/boot.py
subiquity/common/filesystem/sizes.py
subiquity/common/filesystem/tests/test_sizes.py
subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py

I'm like 99% sure that all call paths to here align the size properly, apart from the one in apply_system, which I want to be able to create improperly sized partitions.

do not round up partition size in add_partition

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapdapi.py

The data passed to on-volumes needs to indicate, for each "structure" (partition) defined by the gadget the path to the underlying device. The current code attempts to this by tracking the partition for each role but this doesn't work: there maybe be more than one partition with no role. So refactor to have the controller convert the "volume" structure to an "on-volume" structure early and update the device fields after curtin runs.

fix the value passed as on-volumes to snapd

---

subiquity/server/controllers/snaplist.py
subiquity/server/controllers/ssh.py

If and when the desktop installer adds a snaps screen, we should probably fetch information for a different set of snaps for a desktop install. But for now this is OK.

skip ssh and snaplist screens for desktop install

---

examples/mixed-sources.yaml
subiquity/client/controllers/drivers.py
subiquity/server/controllers/drivers.py
subiquity/tests/api/test_api.py

The list of drivers suggested to the user may vary based on whether we are installing a server or desktop image.
In the current implementation of the drivers controller, the value of the source variant (e.g., server or desktop) is read early in the initializer.
This is a problem because it happens before the client gets the opportunity to tell us what we are installing.
As the result, we always suggest drivers for the server variant because it is the default value in Subiquity.
This PR makes sure to query the list of drivers when the source variant is set (or set again).
Launchpad bug: https://bugs.launchpad.net/subiquity/+bug/1998376

Drivers: make sure we suggest non-GPGPU drivers to the desktop installer

---

subiquity/client/client.py
subiquity/journald.py
subiquity/server/controllers/install.py
subiquity/server/curtin.py

Per python 3.10 changelog[1], passing a loop around is no longer considered a good idea.  Remove the loop argument and request the running loop.
[1]: https://docs.python.org/3/whatsnew/3.10.html#removed

journald: stop passing a loop

---

examples/mixed-sources.yaml

I intended to include this patch in my original PR (https://github.com/canonical/subiquity/pull/1505) but forgot to push the change before merging.

mixed-catalog: rework description and name of entries

---

console_conf/cmd/tui.py
subiquity/cmd/tui.py
subiquitycore/tui.py

I implemented these a long time ago to help working on parts of the ui by allowing a way to script moving past some screens. I haven't used them in ages, it's pretty bad code and probably a fragmentary answers file is a better solution to the same problem. What do you think?

remove --script/--click command line arguments

---

subiquity/ui/views/ssh.py
subiquitycore/tests/test_view.py
subiquitycore/view.py

`BaseView.remove_overlay()` would crash with `AttributeError` if no overlay was found. We now add a `not_found_ok` parameter (defaulting to ~~True~~ False) that makes the function silently return if the overlay could not be found.
~~Passing `not_found_ok=False` and~~ catching `OverlayNotFoundError` can be helpful in some scenarios to do something different if no overlay was found.

ui: avoid crashing when removing overlay that does not exist

---

system_setup/client/controllers/summary.py

From the summary controller when installation is in progress. The shell is inoperable on WSL due the fake snap environment.

Removes the switch to shell widget

---

subiquity/models/tests/test_subiquity.py
users-and-groups

Ensure the first user is in the users group and not in the lxd group.  This is necessary for new installs to support unprivileged lxd

Ensure the first user is in the users group and not in the lxd group

---

subiquity/ui/views/refresh.py

Cancelling the installer self refresh does not work. Clicking on the button simply goes back to the screen asking the user if they want to update ; but the refresh operation still continues in the background.
Since we do not have a simple way to implement refresh cancellation at the moment, we are just removing the button.

refresh: remove the cancel update button since it is broken

---

subiquitycore/utils.py

Specifying the value of `subprocess.PIPE` as the `stdin` argument of `astart_command` did not have any effect. This happened because the parameter was not forwarded to the subprocess function. The parameter was effectively unused.

utils: fix unused stdin parameter in astart_command

---

subiquity/ui/views/ubuntu_pro.py
subiquitycore/ui/confirmation.py
subiquitycore/view.py

While working on mirror testing, I realized that I needed  yet another confirmation dialog to display.
I decided to rework the implementation I did for Ubuntu Pro and moved it to subiquitycore to create these confirmation dialogs.
Using the new helpers, we can open a confirmation dialog with the following code and receive the decision from the user:
```python
confirmed = await view.ask_confirmation(title="Exit",
question="Are you sure you want to exit?",
cancel_label="On second thought...",
confirmation_label="Yes, I am sure!")
if confirmed:
print("The user confirmed his decision to exit")
else:
print("The user reconsidered his decision")
```
If the confirmation overlay gets closed as the result of the user pressing ESC, the confirmation coroutine returns False.

Add helper to create confirmation dialog and use it for Ubuntu Pro

---

examples/answers.yaml

As part of our integrations tests, we import mwhudson's public SSH key(s) from GitHub. At the moment, however, the GitHub API is rate limiting the number of queries from our CI.
Upon exceeding the rate limit, our HTTP queries are responded with a 403:
```
┌────────────────────────────────────────────────────────────────────────┐
│  Importing keys failed:                                                │
│                                                                        │
│  2023-01-08 23:43:40,562 ERROR GitHub REST API rate-limited this IP    │
│  address. See https://developer.github.com/v3/#rate-limiting .         │
│  status_code=403 user=mwhudson                                         │
└────────────────────────────────────────────────────────────────────────┘
```
Currently, …

integration-tests: import SSH keys from LP instead of GH

---

snapcraft.yaml

Once we do this, there is no reason to use the 'python' plugin, so switch to the 'nil' plugin with an override-build that calls pip for each of the subiquity, curtin, and probert parts.

snapcraft.yaml: Get all Python dependencies from the archive

---

subiquity/server/mounter.py

In dry-run mode, we used to only copy `etc/apt/sources.list` to the fake overlay. However, if the host uses deb822, the sources.list file is usually empty.
This patch also makes sure to copy the deb822 sources from `etc/apt/sources.list.d/`

apt: in dry-run code, also copy etc/apt/sources.list.d

---

system_setup/server/controllers/configure.py

Recent changes in GUI turned possible to have that field as None, leading to a crash.
This avoids the crash while preserving the default behavior of installing the language packs, unless the client sets otherwise.

Fix wslsetupotions being None

---

subiquity/server/geoip.py
subiquity/server/tests/test_geoip.py

This is non-fatal, and users find the Traceback confusing.
Sample log statement:
```
2023-01-17 18:18:19,958 DEBUG subiquity.server.geoip:113 geoip lookup
failed: ClientConnectorError(ConnectionKey(host='lmao', port=443,
is_ssl=True, ssl=None, proxy=None, proxy_auth=None,
proxy_headers_hash=None), gaierror(-5, 'No address associated with
hostname'))
```

geoip: do not raise on geoip failure

---

subiquity/server/contract_selection.py
subiquity/server/controllers/snaplist.py
subiquity/server/geoip.py

Since Python 3.3, log.warn has been deprecated in favor of log.warning. Running the unit tests raises the following warning:
subiquity/server/tests/test_geoip.py::TestGeoIPBadData::test_lookup_error
/home/olivier/dev/canonical/subiquity/subiquity/server/geoip.py:112:
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
log.warn("geoip lookup failed: %r", le)
I replaced all the calls to log.warn by calls to log.warning

logging: replace deprecated calls to log.warn by log.warning

---

examples/autoinstall-short.yaml
subiquity/server/server.py
subiquity/tests/api/test_api.py

With autoinstall, a controller that was not interactive would decline
outright to provide the response to GET queries, with the notion that the
controller needed to be skipped.  Limit this behavior to only when
`x-make-view-request: yes` is set, which lets the client be able to get
the real response, or the skip info, depending on need.

autoinstall: adjust x-make-view-request behavior

---

subiquity/client/controllers/ubuntu_pro.py

The version of ubuntu-advantage-tools present in focal-updates contains all we need with regard to the magic attach implementation.
Although we are still missing the ubuntu.com/pro/attach screens, they should get active in the near future. It should be enough for testing.

ubuntu-pro: enable for LTS releases

---

snapcraft.yaml

From subiquity, we sometimes execute entry point python scripts such as:
* `usr/bin/ubuntu-advantage`
* `usr/bin/ssh-import-id`
Those scripts require pkg_resources on core20 to run properly:
```python
from pkg_resources import load_entry_point
```
On core22, the scripts will be a bit more flexible but for now, we need python3-pkg-resources in the snap.

snapcraft: add pkg_resources to the snap

---

examples/dr-config-magic-attach.yaml
scripts/runtests.sh
subiquity/client/controllers/ubuntu_pro.py
subiquity/cmd/schema.py
subiquity/cmd/server.py
subiquity/server/controllers/tests/test_ubuntu_pro.py
subiquity/server/controllers/ubuntu_pro.py
subiquity/server/dryrun.py
subiquity/server/server.py
subiquity/server/tests/test_ubuntu_advantage.py
subiquity/server/ubuntu_advantage.py
subiquity/ui/views/ubuntu_pro.py

The patchset includes:
* a bugfix for ubuntu pro: b070c30
* more ways to test ubuntu pro in dry-run mode: fa6fcd7 (which is not ubuntu pro specific) + cd38c06 and 1bb8f60
* the activation of the ubuntu pro screens on LTS releases: d999b7b
The addition of the dryrun machinery can feel out of place but it only affects dry-run so it should have very low risk on normal installs.

Cherry-pick Ubuntu Pro patches for 23.02.1

---

subiquity/models/mirror.py
subiquity/models/tests/test_mirror.py
subiquity/server/controllers/mirror.py
subiquity/server/controllers/tests/test_mirror.py
subiquity/ui/views/mirror.py

I noticed a few things:
* if a mirror check fails and the error gets logged in response to a GET /mirror/check_mirror/progress call, the type of the error is not printed. This makes exceptions that do not have a description appear as blank; which does not make the diagnostic easy. Print the type of exception as well using `%r` instead of `%s`.
* Some types hints are wrong (or not accurate) in the UI / view.
* the `primary` and `disable_components` were not present in the generated autoinstall configuration. This was a regression introduced by [c13edb07f, 8c29f3475]
I also added more tests to cover `MirrorController.run_mirror_testing`. The code only runs in autoinstall and testing in manually in dry-run is clunky.

Fixes and more tests for mirror testing

---

examples/answers.yaml
subiquity/server/geoip.py
subiquity/server/tests/test_geoip.py

* cherry-picked 11d89ec from #1535.  Users sometimes run into a Subiquity crash, see the geoip tracebacks, and mistakenly view that traceback as the cause of the crash, when the answer is later in the log.
* cherry-picked ec80a1c from #1527.  Works around CI glitch due to rate limiting

kinetic merge - geoip, CI fix

---

bin/subiquity-service

During TUI launch, turn systemd ShowStatus off. We don't want to do that earlier, if we did then the easier path would be quiet boot or something similar. This is done here so that service completion messages don't overwrite the console.

tui: turn off systemd ShowStatus

---

subiquity/models/locale.py
subiquity/models/tests/test_locale.py
subiquity/server/apt.py
subiquity/server/controllers/locale.py
subiquity/server/tests/test_apt.py
subiquitycore/utils.py

When a mirror test failure occurs, the user is expected to read the apt-get output to determine what the root cause could be. Users who don't use English as their installer's language should get the output of apt-get translated (provided there is a translation available).
I made 3 changes to make it possible:
1. when we execute a command through `arun_command` or another helper, the environment is passed to `subiquitycore.utils._clean_env()` ; which unconditionally hard-coded the value of LC_ALL to C. This behavior is still preserved by default, but the _clean_env function now takes an optional locale boolean, which can be set to False to disable the override of LC_* variables. The helpers have been updated to take an optional `clean_locale` boolean (defaulting to True).
2. in an …

Make sure mirror test output is translated if translation is available

---

subiquity/common/apidef.py
subiquity/common/types.py
subiquity/models/ad.py
subiquity/models/subiquity.py
subiquity/server/controllers/__init__.py
subiquity/server/controllers/ad.py
subiquity/server/server.py
subiquity/tests/api/test_api.py

This is a skeleton implementation of the Active Directory endpoint API. There is more to come, but this was growing too buch to bite in one single code review.
The current state just implements the endpoint `/active_directory` backed by an optional controller, since AD is an opt-in feature. The endpoint is connected to the subiquity server to allow growing and testing the API simultaneously, but should not cause any disruption in current workflows.
Don't bother with the almost empty `POST` method by now. The next pull request will be dedicated to it to validate the user input before configuring the controller, following the ideas implemented in Ubiquity.
A third pull request will address the autoinstall schema to allow interactive section to prefil the admin and domain controller names, …

Active Directory API Part 1

---

subiquity/tests/api/test_api.py

I have several API test cleanups I keep putting off, so let's start them in smaller chunks.
All tests should have the @timeout decorator.

test/api: mark all with timeout

---

subiquity/common/apidef.py
subiquity/server/controllers/filesystem.py
subiquity/tests/api/test_api.py

Previously unformatted partition creation was blocked, but supplying None does seem to do the right thing, and we want to support creation of unformatted partitions.  Allow it and add a API test to help document it as an intended feature.

storage/v2: allow unformatted partition creation

---

subiquitycore/controllers/network.py

```
$ SNAP=foo netplan generate --root /bar
Call failed: Access denied
File "/usr/sbin/netplan", line 23, in <module>
netplan.main()
File "/usr/share/netplan/netplan/cli/core.py", line 50, in main
self.run_command()
File "/usr/share/netplan/netplan/cli/utils.py", line 231, in run_command
self.func()
File "/usr/share/netplan/netplan/cli/commands/generate.py", line 46, in run
self.run_command()
File "/usr/share/netplan/netplan/cli/utils.py", line 231, in run_command
self.func()
File "/usr/share/netplan/netplan/cli/commands/generate.py", line 73, in command_generate
raise RuntimeError(
RuntimeError: failed to communicate with dbus service: error 1
```
https://github.com/canonical/netplan/blob/eb0ff44490f5d04fbf3fdabfc11513f9134e3222/netplan/cli/commands/gene …

network: reset SNAP when calling netplan in dry-run mode

---

subiquity/tests/test_timezonecontroller.py

I've upgraded my desktop to lunar and sadly this broke all the async unittests that use parameterized.
Until what needs fixing is fixed, I will run unittests in a chroot. Sadly, there is one test that fails because its behavior is dependent on the presence of /run/systemd/system ; so I'm making sure to does not.

Fix unittest using timedatectl failing in chroot

---

examples/answers.yaml
subiquity/server/controllers/ssh.py
subiquity/server/controllers/tests/test_ssh.py
subiquity/server/dryrun.py
subiquity/server/ssh.py
subiquity/server/tests/test_ssh.py

We now have 3 different dry-run strategies for ssh key imports:
* success: fake a successful key import
* failure: fake a failed key import
* run-on-host: actually run ssh-import-id
Through a dry-run-config file, we can choose which strategy applies based on the username.
By default, the policy is as follows:
* username 'heracles' uses the fake successful key import
* username 'sisyphus' uses the fake failed key import
* any other username runs ssh-import-id

Stop calling ssh-import-id as part of the CI - use mock responses instead

---

subiquity/client/client.py
subiquity/client/controllers/filesystem.py
subiquity/client/controllers/network.py
subiquity/client/controllers/progress.py
subiquity/server/controllers/cmdlist.py
subiquity/server/controllers/install.py
subiquity/server/controllers/locale.py
subiquity/server/controllers/network.py
subiquity/server/controllers/shutdown.py
subiquity/server/controllers/snaplist.py
subiquity/server/server.py
subiquity/ui/views/drivers.py
subiquity/ui/views/error.py
subiquity/ui/views/help.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/keyboard.py
subiquity/ui/views/zdev.py
subiquitycore/core.py
subiquitycore/tui.py
subiquitycore/ui/views/network.py
system_setup/client/controllers/summary.py
system_setup/server/controllers/shutdown.py

create_task has the following note:
Important: Save a reference to the result of this function, to avoid a
task disappearing mid-execution.
Convert existing usage of create_task to run_bg_task, if that create_task is not actually storing the result.

many: s/create_task/run_bg_task/

---

autoinstall-schema.json
documentation/autoinstall-reference.md
documentation/autoinstall-schema.md
subiquity/common/apidef.py
subiquity/common/types.py
subiquity/models/mirror.py
subiquity/models/tests/test_mirror.py
subiquity/server/controllers/mirror.py
subiquity/server/controllers/tests/test_mirror.py
subiquitycore/models/network.py

Subiquity now supports 3 different fallback actions if the automatic mirror selection did not find any usable mirror:
* aborting the install (this is the default)
* continuing anyway (which I would hardly recommend doing)
* reverting to an offline install
The fallback action can be configured via autoinstall:
```yaml
apt:
fallback: offline-install   # accepted values are "offline-install", "continue-anyway" and "abort"
```
and it can also be changed via the HTTP API:
```bash
curl --unix-socket socket http://a/mirror/fallback -d "offline-install"
```
If the mirror selection fails during an autoinstall, the fallback action is automatically executed.
If the mirror selection fails and the mirror model was marked configured via /meta/mark_configured, the fallback action is automatically …

Optionally fallback to offline install if no usable mirror provided

---

subiquity/common/types.py
subiquity/server/controllers/ad.py
subiquity/tests/api/test_api.py

In tandem with the Ubiquity this implements a "ping" to the domain controller during validation. It allows clients to validate not only if the DC name is "syntatically" correct, but also whehter it's reachable in the network.
The "ping" relies on realmd, which is part of the minimal layer. The package is not staged in Subiquity nor UDI at this point.
Here it is the domain name validation in action (running in a locally built ubuntu desktop installer snap):

Active Directory API Part 3 - Pinging the Domain Controller

---

subiquity/common/filesystem/tests/test_gaps.py
subiquity/common/filesystem/tests/test_manipulator.py
subiquity/models/tests/test_filesystem.py
subiquity/models/tests/test_keyboard.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/controllers/tests/test_kernel.py
subiquity/server/controllers/tests/test_keyboard.py
subiquitycore/tests/parameterized.py
subiquitycore/tests/test_async_helpers.py

parameterized async tests run into cpython bug gh-101486
We use parameterized.expand, which works by creating new functions and inserting those into the list of tests.  It's a wonder this worked at all before for the async tests.
Update the function generation to create a coroutine function, if appropriate.
LP: #2007554

tests: patch parameterized to handle async

---

examples/dr-config-apt-local-mirror.yaml
scripts/runtests.sh
subiquity/server/controllers/mirror.py

Two changes:
1. do not run apt-get update on host when running autoinstall.yaml as part of the CI
2. when sleeping after a failed mirror candidates, make the sleep call be affected by SUBIQUITY_REPLAY_TIMESCALE

make sure mirror selection does not cause timeouts on CI

---

scripts/runtests.sh

Integration tests are becoming very slow to run. 
At least for the test using autoinstall.yaml, disabling tracemalloc yields to a 5-fold runtime speed improvement.
This reverts commit 813448683c971cf6acdc998b684d5ddea83aabe3.

Revert "Enable tracemalloc in integration tests with at most 3 frames" to speed up integration tests

---

subiquity/models/filesystem.py

When creating a virtual group, all disks and partitions that could be used as a raid device were also offered as a potential LVM physical volume.
However, tiny disks and partitions (i.e., < 1 MiB) are too small to store the LVM header. They make the get_lvm_size() function potentially return a negative value; which in turn causes math errors.
We now make sure to only offer disks/partitions that are big enough to store the LVM header.
Technically speaking, a 2MiB disk is still useless as a physical volume since it is not big enough to store any PE (which are 4MiB by default). We can come up with better rules later but this is good enough to prevent subiquity from crashing.
Steps to reproduce the crash:
1. `make dryrun`
2. navigate to the filesystem screen
3. select "Custom storage layout" …

filesystem: don't offer tiny partitions / disks as potential PVs

---

scripts/runtests.sh
subiquity/models/subiquity.py
subiquity/server/apt.py
subiquity/server/tests/test_apt.py

We got multiple bug reports in the past stating that the installer is not honoring some part of the apt settings; either supplied by means of autoinstall (e.g., pinning) or via the subiquity UI (e.g., proxy).
What happens under the hood is that curtin overwrites the APT settings as part of the curthooks stage ; effectively discarding earlier settings applied in the apt-config stage.
Curtin does so because we pass debconf_selections directives to curthooks. In the past, curtin used to handle debconf_selections separately but nowadays it considers that they are part of the APT config. As a result, it decides to run apt-config again (but with a close to empty configuration) as part of the curthooks stage.
We now pass debconf_selections as part of the apt-config stage. This should hint curtin …

debconf-selections: pass to curtin's apt-config rather than curthooks

---

snapcraft.yaml

the goal is to pull the curthooks fixes:
* canonical/curtin@cc232497 apt-config: stop returning cfg object in translate_old_apt_features
* canonical/curtin@90177706 apt-config: fix wrong value printed in debug log
* canonical/curtin@ce9ca977 apt-config: fix curthooks unconditionally triggering apt-config
but it also pulls the following changes:
* canonical/curtin@5af09277 add SLES support
* canonical/curtin@a6960887 integration: use sfdisk as the source of info
* canonical/curtin@c56c51aa block/v1: handle msdos+swap
* canonical/curtin@8c5f87ed block_meta: all fields on a disk action must match with v2 config
* canonical/curtin@6d114064 apt: use string.format instead of f-string

snapcraft: bump curtin rev to fix curthooks always running apt-config

---

subiquity/server/apt.py

Sadly, passing an alternative config file to apt using -o CLI options does not work because apt:
1) Reads the configuration file first
2) Reads CLI options (and override specified settings) second
Therefore, the default configuration file is always read, instead of the one we supply.
To specify an alternative configuration file, the recommendation from the apt maintainer is to supply an APT_CONFIG variable, hinting apt to read said file instead of the default.
We now generate a temporary file, write the directives we need to it using the python apt library, and then execute apt-get with a path to this temporary file set in APT_CONFIG.

Fix how we pass an alternative apt configuration file for mirror testing

---

snapcraft.yaml
subiquity/server/controllers/install.py
subiquity/server/controllers/tests/test_install.py

When installing a package, instead of using a single call to `curtin system-install [package]`, we now call:
* `curtin system-install --download-only [package]` (up to three times with a delay between iterations)
* `curtin system-install --assume-downloaded [package]`
curtin's merge request: https://code.launchpad.net/~ogayot/curtin/+git/curtin/+merge/437897

when installing packages, try the download operation up-to 3 times

---

documentation/autoinstall-reference.md
subiquity/server/controllers/filesystem.py

To support the same behaviour that was available with d-i/preseed.

Support LUKS with 'lvm' autoinstall storage layout

---

subiquity/server/apt.py

When apt-get is run as root, it tries to drop privileges by setuid-ing to the APT::Sandbox::User user (i.e., _apt by default). This does not work for us when doing mirror testing because the default sandbox user does not have access to the overlay. Therefore, APT produces a warning and reverts to unsandboxed downloads.
Let's force apt to use unsandboxed downloads by setting root as the sandbox user. This has the same result but avoids showing a warning in the APT output during mirror testing.

apt: force downloads to be unsandboxed when running mirror testing

---

subiquity/common/apidef.py
subiquity/common/filesystem/manipulator.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Provide a list of disk IDs that are plausible boot targets.
This could also be full disk objects if that makes things simpler.

storage/v2: endpoint for boot-plausible disks

---

Makefile
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquitycore/async_helpers.py
subiquitycore/tests/test_async_helpers.py

LP: #[2009797](https://bugs.launchpad.net/subiquity/+bug/2009797) has the following backtrace:
```
2023-03-09 06:54:49,973 DEBUG subiquity.server.server:456 request to /storage/v2?wait=true crashed
File "/snap/ubuntu-desktop-installer/820/bin/subiquity/subiquity/common/api/server.py", line 134, in handler
File "/snap/ubuntu-desktop-installer/820/bin/subiquity/subiquity/server/controllers/filesystem.py", line 656, in v2_GET
return await self.get_v2_storage_response(self.model, wait)
File "/snap/ubuntu-desktop-installer/820/bin/subiquity/subiquity/server/controllers/filesystem.py", line 642, in get_v2_storage_response
probe_resp = await self._probe_response(wait, StorageResponseV2)
File …
```

Single instance task wait

---

subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py

Currently subiquity ignores any device that has a mounted partition when enumerating block devices. This is done to exclude the install media, which is something we are going to need to be more nuanced about.
This fairly simpleminded change does not exclude these devices when scanning the probe data but instead filters them out before presenting them to the UI. This should allow an autoinstall file to install to a gap on the install media, at least. It's a bit hard to know that it never shows the install media in any corner of the UI though.

allow autoinstalls to use the disk the installer booted from

---

subiquity/common/api/defs.py
subiquity/common/api/server.py
subiquity/common/api/tests/test_server.py
subiquity/common/apidef.py
subiquitycore/core.py

In LP: 2009797, an exception of this form happens:
AttributeError: 'FilesystemController' object has no attribute '_start_task'
The installer client, u-d-i, is asking for storage information ASAP after the socket starts listening, and in this case that happened before all controllers were started.  The sync primitive the probe is waiting on wasn't created yet.
With one known exception, /meta/status, we really shouldn't be responding to random API calls, and the startup sequence of the controllers should be relatively quick (sub 1 second to be sure). Just delay them, except for the special one.
A more aggressive version of https://github.com/canonical/subiquity/pull/1595

api: delay most endpoints until controllers start

---

.github/workflows/build.yaml
bin/subiquity-cmd
bin/subiquity-server
bin/subiquity-service
scripts/slimy-update-snap.sh
snapcraft.yaml
subiquity/server/tests/test_runner.py
subiquitycore/tests/test_utils.py
system_setup/ubuntu-wsl-setup

Bump the base snap to core22 so we only have a single core on live-server isos.
It took me a while to come up with a working hack for override-build. The problem is that in debian and ubuntu, we patched python3.10's sysconfig so that running `sysconfig.get_preferred_scheme('prefix')` returns `posix_local`. Unfortunately, this also affects `pip install` even when we specify a prefix.

snapcraft: upgrade to core22

---

subiquity/common/types.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/tests/api/test_api.py

We should absolutely not land this anywhere that will be picked up by ubuntu-desktop-installer for 23.04 partly because this is an API change and partly because this area of the code is not the best tested! Still I'd like @jpnurmi to see this as they start to think about the canary installer.

move from use_lvm flag on guided fs things to more generic capabilities

---

subiquity/server/controllers/ad.py

Due to how top-level interactivity is determined:
https://github.com/canonical/subiquity/blob/903299fb84bf95904bba36f9f7c615b2efc9aebb/subiquity/server/server.py#L655
Simply marking this controller as interactive is not sufficient to address the autoinstall flow.
I am proposing this change now to fix non-active directory autoinstalls being hung waiting on the ad controller.

ad: add hack to fix non-autoinstall cases

---

.github/workflows/build.yaml

If the linter is broken in the distro in the devel series but not the LTS, such as right now, it's interesting to allow the LTS linter to finish.

workflow: run both linters always

---

subiquity/server/apt.py
subiquity/server/controllers/drivers.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/install.py
subiquity/server/controllers/mirror.py
subiquity/server/controllers/source.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/controllers/tests/test_mirror.py
subiquity/server/tests/test_apt.py

Coming changes for the canary image for 23.04 mean that we won't know the precise source for the install until after the storage config is confirmed, so we can't create one curtin source handler and hang on to it.

create source handlers and apt configurers more on-demand

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

and only take actions (like setting storage_version to 2) when we know we are installing a core boot classic system.

only examine system from snapd when source is selected

---

subiquity/server/ad_joiner.py

LP: #2013079
Found during beta testing that the live session is joining, instead of the target.

(fix) Join target instead of live session

---

examples/desktop-sources.yaml

The values were extracted from desktop daily-live 20230327.1:
```
$ curl --unix-socket /run/subiquity/socket a/source
{"sources": [{"name": "Ubuntu Desktop (minimized)", "description": "A minimal but usable Ubuntu Desktop.", "id": "ubuntu-desktop-minimal", "size": 6135083008, "variant": "desktop", "default": false}, {"name": "Ubuntu Desktop", "description": "A full featured Ubuntu Desktop.", "id": "ubuntu-desktop", "size": 7604871168, "variant": "desktop", "default": true}], "current_id": "ubuntu-desktop", "search_drivers": false}
```
and livecd-rootfs:
```python
cat <<-EOF > config/minimal.catalog-in.yaml
name: "Ubuntu Desktop (minimized)"
description: >-
A minimal but usable Ubuntu Desktop.
id: ubuntu-desktop-minimal
type: fsimage-layered
variant: desktop
locale_support: langpack
EOF …
```

Add test source catalog for desktop variants

---

snapcraft.yaml

Make a copy of this file to INSTALL, as the organize step renames it, causing it to disappear from the source directory.

system-setup: fix disappearing ubuntu-wsl-setup

---

subiquitycore/controllers/network.py

netplan isn't staged in the snap, and the environment variables being passed around don't help it.

network: run `netplan apply` without snap env

---

snapcraft.yaml

Depends on https://code.launchpad.net/~ogayot/curtin/+git/curtin/+merge/439863

snapcraft: bump version of curtin to pickup ventoy fix

---

subiquity/cmd/server.py
subiquity/cmd/tui.py
subiquitycore/tests/test_utils.py
subiquitycore/utils.py

LD_LIBRARY_PATH is populated with snap things, that we don't want for the commands that run orig_environ.  Saving LD_LIBRARY_PATH to an ORIG variable like I did https://github.com/canonical/ubuntu-desktop-installer/pull/1747 was not going to work, as that particular variable already has the snap things set to it, but does work as intended for PATH and PYTHONPATH.

Ld lib path vs cmds

---

system_setup/server/controllers/configure.py

UDI snap ships the language-selector-common package, thus its data directory is part of the snap.
For recent releases we use subiquity snap, which does not ship the package. Instead we have it seeded in the root filesystem.
This change tries l-s-c data directory in the base system, outside of the snap.

[system_setup] (fix) Falls back to seeded l-s-c

---

subiquity/server/ad_joiner.py

This concludes LP: 2013079.
`realm --install <target>` requires system bind-mounts to work properly.

[Active Directory] Bind mounts in the joining context manager

---

snapcraft.yaml

Note: when backporting to ubuntu/lunar, the sha1 needs to be updated to follow what's in https://code.launchpad.net/~curtin-dev/curtin/+git/curtin/+ref/ubuntu/lunar

snapcraft: update curtin to fix disk lookups with wwn extensions

---

documentation/autoinstall-reference.md
subiquity/common/filesystem/sizes.py
subiquity/common/tests/test_types.py
subiquity/common/types.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/tests/api/test_api.py
subiquitycore/utils.py

Add an API that ubuntu-desktop-installer can use and an autoinstall key to control the size allocation for how much of a VG is allocated to the root LV.
Thanks to Ryan Mounce as well for the related PR #1588

 Sizing policy

---

snapcraft.yaml
subiquity/server/ad_joiner.py
system_setup/server/controllers/configure.py

* cherry-picked cd6e69187a48c7d9ed1ec4b78db87d6e09756225 from https://github.com/canonical/subiquity/pull/1618
* cherry-picked 37f33481355b2e2e63b8cba5e4b7c58041aeab91 .. cda5a0f25003f7945971b2047b39fd32fdaaa8bc from https://github.com/canonical/subiquity/pull/1627
* cherry-picked 1105da2368bdbf9b9ce54641d5d5e4dd6ef1fed2 from https://github.com/canonical/subiquity/pull/1617
* cherry-picked 4c4ab16f7d3fd0b333d62b5e8cc08cfd7ef5c2b2 from https://github.com/canonical/subiquity/pull/1631 (adjusted to track curtin's ubuntu/lunar branch)
NOTE: with the comment I added in snapcraft.yaml, I expect future cherry-picks adjusting the curtin revision to conflict. This is on purpose, we don't want to pull new revisions of curtin from master (this would potentially introduce new features). To fix the …

Lunar 2023 04 03

---

subiquity/common/apidef.py
subiquity/common/filesystem/labels.py
subiquity/common/types.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Mark the disks as can_be_boot_disk, instead of a separate API call.

Bootable disks

---

subiquity/common/apidef.py
subiquity/common/filesystem/labels.py
subiquity/common/types.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

* cherry-picked c8e30bc..965a49f from #1634

Lunar 2023 04 04

---

subiquity/common/types.py
subiquity/models/keyboard.py
subiquity/models/tests/test_keyboard.py
subiquity/server/controllers/keyboard.py

The XKB configuration guide shows that multi-layout configuration is possible, as in the following example:
Option "XkbLayout" "us,cz,de"
Option "XkbVariant" ",bksl,"
which translates to:
* layout "us" with no variant
* layout "cz" with variant "bksl"
* layout "de" with no variant
The same applies to /etc/default/keyboard.
We do make use of this ability to automatically set an alternative keyboard layout for non latin keyboard layouts (e.g., Arabic "ara" becomes "us,ara" so that users can toggle between American and Arabic keyboard layouts.
In the following commit:
13cae2488 keyboard: validate layout and variant
.. we started implementing early validation of the keyboard layout, but we did not consider that multi-layouts are supported.
As a result, subiquity fails at keyboard selection …

keyboard: fix use of multi-layout keyboard layout

---

subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/tests/test_gaps.py
subiquity/tests/api/test_api.py

Gap sizing in extended had a flaw when there was a partition after it.  We need the ebr space in between.
Emerged in the private bug LP: #2015521, where a user was given a guided resize option based on a logical partition that was not physically last.  The result was that the end position of the newly created partition was the same spot as the offset of the next partition.

gaps: fix gap size in extended

---

subiquity/models/network.py
subiquity/models/tests/test_network.py
subiquity/server/controllers/network.py

When doing a netboot autoinstall on the desktop installer, NetworkManager (through cloud-init) and subiquity compete to configure the network. When an autoinstall file does not include a network section, make sure subiquity does not try to configure the network if NetworkManager is installed and enabled.

network: don't run netplan apply if no autoinstall and nm is enabled

---

subiquity/server/controllers/mirror.py
subiquity/tests/api/test_api.py

The API tests unconditionally did a POST request to /source.
This is fine in interactive scenarios, but for autoinstalls, it results in the source controller being "configured" twice:
* once after the apply_autoinstall_config coroutine finishes executing
* once after the POST request is handled
By the time the POST request is handled, other models might have started (or even finished) applying their own autoinstall configuration. If that happens, changing the source model will likely invalidate their configuration, resulting in various bugs. Subiquity does not currently support re-running the apply_autoinstall_config coroutines, so it seems fair to say that doing a POST to source in a fully automated install is a pretty bad idea, unless it's done veryyyyy early.
A recent …

Fix assertion in autoinstall API test

---

subiquity/common/filesystem/manipulator.py
subiquity/tests/api/test_api.py

When we create a swap partition using v2_add_partition, the mount parameter always has the value of None.
We do however, create a fake mountpoint object and assign it the value of "" (empty string) so we know the swap partition is used although it's not really mounted anywhere in the filesystem hierarchy.
Subsequently, when editing the swap partition, the mount parameter is set to the empty string, not None.
This causes trouble in the create_mount function, which normally returns immediately upon encountering None as the mountpoint.
Fixed by skipping the call to create_mount for a swap partition.
https://bugs.launchpad.net/subiquity/+bug/2002413

filesystem: fix crash when editing swap partition in v2

---

subiquity/server/apt.py

For mirror testing, we run apt-get update on the host. By default, external commands run by subiquity inherit the environment variables set by the snap (including LD_LIBRARY_PATH).
We don't ship apt-get or its dependencies in the subiquity snap, so we want to reset LD_LIBRARY_PATH and other variables when running the command.
Not doing so leads to the following error when running the subiquity snap on a focal-based system:
```
apt-get: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/subiquity/4675/usr/lib/x86_64-linux-gnu/libsystemd.so.0)
apt-get: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /snap/subiquity/4675/usr/lib/x86_64-linux-gnu/libsystemd.so.0)
apt-get: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not …
```

mirror: clean environment before running apt-get

---

subiquity/common/apidef.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/tests/api/test_api.py

At least in the desktop installer with storage v2, things go bad if a probert storage run finishes during partitioning. Unless storage is already configured, we automatically discard any change done so far upon receiving a response from a probert storage run. This leads to various problems.
This PR aims at making sure the storage configuration is not reset by a probert run while we are in the middle of partitioning.
Essentially, any request that modifies the partitioning configuration will now ensure that a transaction is started. If we receive the result of a probert run in the middle of a transaction, the new data is not applied. Instead it is stored and will only be used if the user asks for a reset/refresh.
It also introduces a new endpoint storage/v2/ensure_transaction that a client …

storage: don't let probing discard storage config in the middle of partitioning

---

subiquity/server/controllers/filesystem.py
subiquity/tests/api/test_api.py

This is just a follow-on PR for: https://github.com/canonical/subiquity/pull/1660 addressing a requested change, and improving the wording of some comment/docstring.

Cosmetic fixes for asynchronous probert runs fix

---

snapcraft.yaml
subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/labels.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

Some people who installed a previous version of Ubuntu on a DOS partition table ended up with a logical, ESP partition (which is marked bootable).
This is an unsupported use-case. An ESP partition should always be a primary partition. Ideally, an ESP partition should be on a GPT.
However, curtin's storage_config makes it clear that expecting the flag of a logical partition to be set to 'logical' is a bad idea.
```
```    
Other people want to create a swap partition in an extended partition. This is a perfectly valid use-case and we set flag='swap' for those partitions.
Therefore, in subiquity code, we cannot just check if a partition has a flag set to 'logical'. We need to look at the partition number too.
Going forward, it feels better to make partitions support multiple flags.
Depends …

filesystem: fix logical+swap or logical+boot partition not considered logical

---

snapcraft.yaml
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquitycore/prober.py
subiquitycore/tests/test_prober.py

Depends on https://github.com/canonical/probert/pull/135

prober: move to asyncio for probert storage

---

subiquity/models/subiquity.py

By default, curthooks will automatically reorder the UEFI boot entries so that the media used during installation is set as the first boot entry.
This is something that MAAS wants because MAAS typically boots over the network.
This is not typically something we would want for a server or desktop installer though. Most of the time, the media is a removable device. Ideally, we would want the new installed grub to be the first boot entry.
Furthermore, on some UEFI implementations, the BootCurrent does not correspond to a Boot#### entry when booting from a removable media. When this happens, curtin fails at making the media the first boot entry, resulting in the following error:
Invalid BootOrder order entry valueXXXX
^
efibootmgr: entry XXXX does not exist
Fixed by disabling the UEFI boot …

install: request curthooks not to reorder UEFI boot entries

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

* Fix label / variation name specification so that we select the correct system.
* Mount the snaps dir, the v2/systems call expects it.

canary: fixes for v2/systems call

---

examples/snaps/v2-systems-enhanced-secureboot-desktop.json
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/tests/api/test_api.py

* Update sample systems response to match current canary ISO
* Address bug in creation of the rootfs partition for smaller disks, where code that expected a single gap to exist handled multiple gaps poorly and produced a negative size for that rootfs partition.

Fix canary disk layout

---

subiquity/server/controllers/filesystem.py
subiquity/server/mounter.py
subiquity/server/tests/test_mounter.py

bind_mount_tree really wants to mount to places that don't exist yet,
and to unmount them later.  Simply creating these files or directories
gets weird.  Manage this process in the Mounter, so that any of these
temporary mountpoints get cleaned up on unmount.

mounter: handle destination not existing 

---

snapcraft.yaml

This will pull the fixes for the utf-8 partition names.

snapcraft: use latest curtin and probert

---

subiquity/server/controllers/install.py
subiquity/server/controllers/tests/test_install.py

curtin_install before this assembled a list of steps and then executed them one by one. As far as I can tell/remember (I was at least partly responsible for this) there is no reason to do it this way: it feels more Pythonic to just execute the steps!
This required removing some indirection in how the config for each step was constructed, which I think also makes things a bit clearer.

simplify InstallController.curtin_install a bit

---

apt-deps.txt

The pep8 binary package was a transitional package. It would install a symlink /usr/bin/pep8 -> pycodestyle
pep8 does not exist anymore in mantic.
pycodestyle would be the right binary package going forward. That said, we stopped using the pep8 command back in 2018 with this commit:
af9427561 Make tox and Makefile more similar.
Let's drop the dependency instead.

apt-deps: drop pep8 which is unused and does not exist anymore in mantic

---

subiquity/common/apidef.py
subiquity/server/server.py
subiquity/server/tests/test_server.py
subiquity/tests/api/test_api.py

A feature request for Desktop was to add the ability to retrieve, all at once, the raw interactive-sections value from autoinstall.

meta: add interactive_sections endpoint

---

subiquity/server/controllers/drivers.py
subiquity/tests/api/test_api.py

The /drivers GET endpoint is supposed to have `{"drivers": null}` when the list of drivers has not (yet) been retrieved.
However, this behavior got broken by the following patch:
66c82b322 drivers: query again list of drivers if the source variant changes
.. which resets the drivers variable to an empty list when (re)querying the list of drivers (this happens automatically when the user submits on the source screen)
Therefore, instead of getting `{"drivers": null}`, we would get `{"drivers": []}` which has a different meaning.
The patch also incorrectly declared the drivers variable in the initializer (not taking None into account). The variable was actually already declared as a class variable with the right type.
Fixed by resetting the variable to None when re-querying the list of …

drivers: fix empty list of drivers shown when it has not yet been retrieved

---

snapcraft.yaml
subiquity/common/types.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/install.py
subiquity/server/controllers/tests/test_install.py
subiquity/server/mounter.py

This depends on this change to curtin: https://code.launchpad.net/~mwhudson/curtin/+git/curtin/+merge/444008 as you can't copy symlinks to a vfat partition.
No idea how to test this useful in CI but maybe I'm just not being imaginative enough. I have run almost exactly this code in a VM though and it works reasonably well.

allow creation and population of a recovery partition via autoinstall

---

bin/console-conf-wrapper

Prefer use of `/var/lib/snapd/modeenv` when determining snapd recovery run mode.
`modeenv` is used by `snapd` as a source of _true_ about the device state.
This change solves the issue when install mode can be performed during a single boot, at which case the `/proc/cmdline` can hold the wrong mode information.

bin/console-conf-wrapper: prefer use of snapd/modeenv

---

subiquity/common/types.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/tests/api/test_api.py

Fairly soon v2/guided will return information about guided targets that are not, in fact, possible.

rename GuidedStorageResponseV2.possible to targets

---

doc/README.md

Clarify that doc is the go-forward folder.

doc: update README

---

subiquity/common/apidef.py
subiquity/common/types.py
subiquity/models/oem.py
subiquity/models/subiquity.py
subiquity/server/controllers/__init__.py
subiquity/server/controllers/oem.py
subiquity/server/server.py
subiquity/server/tests/test_ubuntu_drivers.py
subiquity/server/ubuntu_drivers.py
subiquity/tests/api/test_api.py

This is one step towards what we need for OEM. Natural next steps are:
* Making sure that the drivers screen does not list OEM meta-packages (metapackages are not drivers and should be installed unconditionally).
* the `--no-oem` option could come to the rescue but currently we use the ubuntu-drivers command from the target rootfs. Old ISOs will not have it and will fail on installer refresh.
* Installing the OEM meta-packages. This is tricky because:
* running `ubuntu-drivers install oem-somerville-tentacool-meta` or alike does not work - the package does not get installed
* running `ubuntu-drivers install` will install third-party drivers even if the user decided not to do so.

Add controller + model listing OEM meta-packages

---

apt-deps.txt
examples/umockdev/dell-certified+nvidia.yaml
examples/umockdev/xps-9320.yaml
scripts/umockdev-wrapper.py
subiquity/server/dryrun.py
subiquity/server/tests/test_ubuntu_drivers.py
subiquity/server/ubuntu_drivers.py

Context: when testing ubuntu-drivers related stuff (i.e., third-party drivers & OEM) in dry-run mode, we have a way to run the `ubuntu-drivers` command on the host. This behavior can be enabled by adding `run-drivers` to the `SUBIQUITY_DEBUG` env variable.
We now support wrapping the call to `ubuntu-drivers` in `scripts/umockdev-wrapper.py`. This is a new script that will essentially modify the list of devices that the system sees. Therefore it can make ubuntu-drivers suggest relevant third-party drivers / OEM meta-packages reliably without being hardware dependent.
That said, third-party drivers / OEM meta-packages are only suggested if they exist in the archive. OEM meta-packages are only available in LTS series (and with the -updates pocket enabled). Also, different third-party drivers …

ubuntu-drivers: add ability to run ubuntu-drivers in dry-run with umockdev

---

subiquity/server/apt.py

Before starting the actual installation, we make changes to etc/apt directory in an overlay so that the packages are pulled from the media instead of the network.
At the end of installation, we need to revert these changes. We used to replace the etc/apt directory on the target by the etc/apt directory from the configured overlay.
This is a simple way to revert the temporary changes. Unfortunately, it also removes configuration files that extra packages may have installed in etc/apt. For instance, when installing an OEM meta-package, a etc/apt/sources.list.d/<oem-meta-package>.list gets installed.
If we reset etc/apt to its content from the configured overlay, we lose this file.
Fixed by selectively discarding changes to the files that subiquity modified.

apt: reset only diverted files on deconfigure

---

subiquity/server/server.py
subiquity/server/tests/test_server.py

If a cloud-config is sent that adjusts the users but creates no default user, Subiquity crashes with a exception while mishandling the None.
cloudinit.distros.ug_util.extract_default is documented as returning None in the event that the default user cannot be found.
Example bad from the Subiquity point of view but otherwise valid cloud-config:
```yaml
users:
- name: ubuntu-server
```

server: fix when cloud-config has no default user

---

subiquity/server/controllers/install.py
subiquity/server/tests/test_ubuntu_drivers.py
subiquity/server/ubuntu_drivers.py

* Available OEM meta-packages are now installed unconditionally.
* If online, the meta-packages will also get upgraded to their version from the OEM archive - essentially pulling a kernel with it.
* We don't call `ubuntu-drivers install --no-oem` because it would also install third-party drivers on systems affected by https://bugs.launchpad.net/ubuntu/+source/ubuntu-drivers-common/+bug/1966413
* We don't call `ubuntu-drivers --no-oem install` either because it would crash on affected systems
* Instead we implement more or less the same logic as in ubuntu-drivers-common - using subsequent apt commands

Install (and optionally upgrade) available OEM meta-packages

---

subiquity/models/kernel.py
subiquity/models/oem.py
subiquity/server/controllers/install.py
subiquity/server/controllers/kernel.py
subiquity/server/controllers/oem.py
subiquity/server/kernel.py
subiquity/server/tests/test_kernel.py
subiquity/tests/api/test_api.py

On certified hardware, we now honor the Ubuntu-Oem-Kernel-Flavour attribute. If the value is "oem", then we install the OEM kernel flavor. If the value if "default", then we install the kernel flavor that was originally requested.
This was a problem on ubuntu-server because the OEM meta-packages that have `Ubuntu-Oem-Kernel-Flavor: default` have a Depends on `linux-hwe-generic` whereas in ubuntu server, the default is to use the `generic` flavor (not hwe). We decided to disable listing and installation of OEM meta-packages in the server installer (and also if we're running on core boot classic).
Depends: #1700

Override requested kernel flavor on certified hardware

---

apt-deps.txt
autoinstall-schema.json
documentation/autoinstall-reference.md
documentation/autoinstall-schema.md
snapcraft.yaml
subiquity/models/kernel.py
subiquity/models/oem.py
subiquity/server/controllers/install.py
subiquity/server/controllers/kernel.py
subiquity/server/controllers/oem.py
subiquity/server/kernel.py
subiquity/server/tests/test_kernel.py

Some more testing is needed but it looks mostly ok.
Depends: #1702

OEM: ensure only one kernel gets installed

---

subiquity/client/controllers/filesystem.py
subiquity/common/types.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/tests/api/test_api.py
subiquity/ui/views/filesystem/guided.py

Currently the client special cases the core boot capabilities and does not offer manual partitioning for them. This change makes things a bit more regular, and also prepares the ground for other install methods that cannot be customized.
Next up: a major rewrite of subiquity/ui/views/filesystem/guided.py!

add a target/capability for manual partitioning

---

snapcraft.yaml

Updating curtin to address https://bugs.launchpad.net/curtin/+bug/2026225. Sadly, I didn't manage to test the fix because of https://bugs.launchpad.net/subiquity/+bug/2025535 but I think it will at least be an improvement.
canonical/curtin@168c4fd3 curthooks: fix exception when passing 'kernel: null'
This will also pull the following changes:
canonical/curtin@4587fd40 extend grub config object to handle all config under the 'grub' key
canonical/curtin@6386240f swap: API improvement, fixes, and tests for can_use_swapfile
canonical/curtin@b4ff4c37 version to 23.1.1
canonical/curtin@58b0c50d use a config object in uefi boot entry code
canonical/curtin@3b353cac modernize efi boot entry handling code
canonical/curtin@96ab8c1d tox.ini: update pylint

snapcraft: pickup curtin's 'kernel: null' fix

---

doc/.gitignore
doc/conf.py
doc/index.rst
doc/reference/autoinstall-reference.rst
doc/reference/index.rst
doc/tutorial/index.rst
doc/tutorial/intro-to-autoinstall.rst

I think much of this content should be moved into other sections, but as a start I'm bringing in the existing autoinstall doc into rst format.  I couldn't help with some editorial improvements along the way, if that becomes a problem I'll resplit.
Deviations from existing autoinstall doc:
* quick start page not listed yet, we don't have that in rst yet
* reference to autoinstall-generator dropped - that project needs some help
* Interactions between Autoinstall and Cloud-init section rewritten
* possible future direction section dropped, we should consider a proper roadmap but it surely doesn't need to be in a tutorial
Note that the docs are written assuming that they are housing all ubuntu install documentation, but is only starting with autoinstall.   I don't know if that will be …

docs: autoinstall tutorial

---

documentation/autoinstall-reference.md

There is no such thing as `ubuntu-server-minimized`. It should be `ubuntu-server-minimal`.
See for example here:
https://github.com/canonical/subiquity/blob/f8bf1105bf96e044b013e7c30b688e4c89de2f47/examples/sources/install.yaml#L4
Another piece of evidence is found in the Ubuntu ISO:

Fix typo in reference: minimized --> minimal

---

documentation/autoinstall-reference.md

Before, the reference documentation was inconsistent with boolean values. It sometimes used true/false and other times yes/no.
This changes makes it so that the reference documentation is consistently using true/false.

Use true/false instead of yes/no for bools

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

launchpad bug: [1952926](https://bugs.launchpad.net/subiquity/+bug/1952926)
This change should make it so that user supplied grub config in the autoinstall data will be used even when the layout option is supplied.
This would allow users to supply the simpler storage configs (see launchpad bug) and disable the grub reordering (which currently moves network boot devices to the first boot item making the newly installed os not the default boot option)

load grub config from ai_data

---

subiquity/common/filesystem/boot.py
subiquity/common/filesystem/tests/test_actions.py
subiquity/common/filesystem/tests/test_manipulator.py
subiquity/common/types.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

The way the client server split was done for the server tui's filesystem screens was pretty hackish, basically repeating the conversion from what probert + curtin gives us to model objects in the client. This cleans this up ever so slightly by adding a way to indicate that particular attributes should be serialized over the client/server API (and not when rendering the curtin config) and using that mechanism to transfer the udev information associated with disks, partitions and raids to the client.

specialize how fs model objects are sent across API

---

subiquity/client/controllers/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/filesystem/probing.py

Drive various decisions that used to be keyed off core boot capabilities and special purpose bits of the API by the new guided capability stuff. I tried to think of a way to do this incrementally and failed. It might be easier to review the new code rather than the diff in places.

rewrite guided disk selection to be more general

---

subiquity/server/controller.py
subiquity/server/controllers/identity.py
subiquity/server/controllers/snaplist.py
subiquity/server/controllers/ssh.py

Also skip identity screen when installing neither server nor desktop (i.e. core).

generalize the way screens are skipped when installing desktop

---

subiquity/client/controllers/mirror.py
subiquity/common/types.py
subiquity/server/controllers/mirror.py

The commit history is a bit messy but well. Maybe worth a look?

do not do any mirror configuration when installing core

---

subiquity/server/controllers/filesystem.py
subiquity/tests/api/test_api.py

For https://github.com/canonical/ubuntu-desktop-installer/issues/2252

filesystem: fix ~6GB extra pad on classic min size

---

subiquity/common/filesystem/boot.py
subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

And as a bonus make the VariationInfo nicer.

Only consider size not in use when considering disks for guided reformat

---

subiquity/common/filesystem/manipulator.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Address action ordering with zpool/zfs objects - these objects are 'Mountlike' objects and may represent a viable mountpoint, which affects rootfs detection and the required ordering of curtin storage actions.

Zfs action ordering

---

subiquity/server/controllers/install.py

I have a use case for wanting to manipulate the rp contents in a late-command.

mount rp at predictable path and leave it mounted

---

tox.ini

Skips the install when it's already there, does the right thing if .tox not present / old dependency / missing dependency.

tox: use skip_install to speed up black/isort

---

bin/subiquity-cmd
snapcraft.yaml

Make it so that probert and curtin can be run from the snap.  Invoked as subiquity.probert and subiquity.curtin respectively.

snapcraft: fix probert, add curtin runners

---

subiquity/server/controllers/shutdown.py
subiquity/server/runner.py
subiquity/server/tests/test_runner.py

With recent changes, the `journalctl -b` command would fail to run:
```python
File "subiquity/server/controllers/shutdown.py", line 118, in copy_logs_to_target
await self.app.command_runner.run(
File "subiquity/server/runner.py", line 98, in run
proc = await self.start(cmd, **opts)
^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DryRunCommandRunner.start() got an unexpected keyword argument 'stdout'
```
Fixed by making sure that:
* the output of `journalctl -b` is captured instead of going into the journal (which in itself feels like a bug).
* the command runner expects the `stdout`, `stderr` and other possible keyword arguments.

Make sure journalctl -b is properly captured on shutdown

---

subiquitycore/tui.py

persist rich mode across updates

---

subiquity/ui/views/filesystem/partition.py
subiquity/ui/views/filesystem/tests/test_partition.py
subiquitycore/ui/form.py

Currently, the partition form stores the size as a human readable value (e.g., 123456K, 1.1G, 1.876G, 100G). When we exit the size field (i.e., upon losing focus), we convert the value to a number of bytes and then align it up to the nearest MiB (or whatever the alignment requirement is).
Unfortunately, after computing the aligned value, we turn it back into a human-readable string and store it as is. It is not okay because the conversion does not ensure that the alignment requirement is still honored.
For instance, if the user types in 1.1G, we do the following:
* convert it to a number of bytes -> 1181116006.4 (surprise, it is not even an integer).
* round it up to the nearest MiB -> 1181745152 (this is the correct value)
* transform it into a human readable string and store it as is -> …

filesystem: store the actual size in bytes alongside the human readable size

---

subiquity/server/controllers/oem.py
subiquity/server/controllers/tests/test_oem.py

```python
File "subiquity/server/controllers/oem.py", line 161, in load_metapackages_list
self.model.metapackages = [
File "subiquity/server/controllers/oem.py", line 164, in <listcomp>
wants_oem_kernel=await self.wants_oem_kernel(
File "subiquity/server/controllers/oem.py", line 115, in wants_oem_kernel
flavor = line.split("=", maxsplit=1)[1].strip()
IndexError: list index out of range
```

oem: fix IndexError when using OEMController.wants_oem_kernel

---

subiquity/common/filesystem/boot.py
subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/tests/test_gaps.py
subiquity/models/tests/test_filesystem.py

This is basically @medicalwei's #1764 with potentially useful functionality factored into a method.

Use the first fitting gap for ESP, instead of the largest gap

---

scripts/bind-patch.sh

scripts/bind-patch.sh is useful for modifying the snap in the live environment, for quickly testing changes or for things that are too obscure to test in other ways.

scripts: add bind-patch.sh

---

subiquity/cmd/server.py
subiquity/server/controllers/filesystem.py
subiquity/tests/api/test_api.py

It disables all core boot types really.  But this is the only planned core boot type at this point.
LP: #2030852

several: add --no-enhanced-secureboot flag

---

subiquity/cmd/server.py

Detecting the bootloader is an obvious choice for real installs, but is a source of glitches in CI.  Default to UEFI, and if tests want something else they should pass a specific --bootloader.

server: default uefi on dryrun

---

examples/sources/desktop.yaml
subiquity/common/filesystem/sizes.py
subiquity/common/filesystem/tests/test_sizes.py
subiquity/server/controllers/filesystem.py
subiquity/tests/api/test_api.py

* if a source entry has variations, use the install_min of the largest of the variations
* several tweaks to suggested min install size
* clearer logging of this outcome
* refresh the desktop install sources yaml
analysis of the above
```
10G drive tests
no case here creates a swapfile
CORE_BOOT_ENCRYPTED, canary iso build 20230831.7
$ df -h -x tmpfs
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda2       721M   61M  609M   9% /run/mnt/ubuntu-boot
/dev/vda1       749M  3.7M  745M   1% /run/mnt/ubuntu-seed
/dev/dm-0       8.3G  4.4G  3.5G  56% /
/dev/dm-1        20M  120K   18M   1% /var/lib/snapd/save
suggested install minimum size: 8.339G
catalog size: 4.042G
calculated min_size (end offset of last partition): 5.497G
LVM_LUKS, canary iso build 20230831.7
$ df -h -x tmpfs …
```

Min size revisited

---

subiquity/server/apt.py
subiquity/server/mounter.py

When doing an offline install, ubuntu-drivers would sometimes list a package that is available in the archive but not present in the pool. This would lead to a failed install when trying to download/install such package.
This is not something we would expect since we run apt-get update (with only the pool configured when offline) in the install tree.
However, it turned out that we create the overlay with the lower layers specified in the wrong order - which essentially makes APT indexes visible in the source tree also visible in the OEM/third-party driver overlay.
When calling `setup_overlay(lowers=[a, b, c])`, Subiquity invokes mount with `lowerdir=c:b:a` (in the reverse order).
This means that c is top, b is middle and a is bottom.
For the OEM and third-party drivers, we build overlays …

oem+drivers: fix wrong order or lower layers when building overlays

---

snapcraft.yaml

Includes the following changes:
Dan Bungert (2):
swap: add logging
docs: link to sources.list manpage for apt deb822
Michael Hudson-Doyle (2):
distro: remove disabling of deb-src lines in apt_update
distro: remove even more code from apt_update

snapcraft: update curtin for apt distro fix

---

subiquity/common/api/server.py
subiquity/common/api/tests/test_server.py

When the server raises an exception in a HTTP request handler context, more often than not, the exception is sent back to the client in the body.
Additionally, the message of the exception (if any), is also copied as is in a `x-error-msg` HTTP header.
That said, HTTP headers must obey strict rules. The `"\r\n"` sequence indicate the end of the current HTTP header. When using aiohttp, the library rejects any header that has a `"\r"` or `"\n"` in its value:
```python
ValueError: Newline or carriage return character detected in HTTP status message or header. This is a potential security issue.
```
As an example, any `curtin.util.ProcessExecutionError` exception will contain `"\n"` characters when converted into a string.
We now encode the error message as JSON before copying it in the HTTP …

api: encode x-error-msg as JSON - so it does not contain <CR> or <LF>

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

In LP: #2034270, a 1MiB disk is present.  This is triggering a crash while attempting to decide if we can do a guided install.

storage: fix crash when guided and a small disk

---

subiquity/server/controllers/network.py
subiquity/server/server.py
subiquitycore/models/network.py

Steps to reproduce (works in dry-run mode too):
1. Navigate to the network page.
2. Create a bond
3. Go to the help menu
```python
File "subiquity/common/api/server.py", line 164, in handler
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "subiquity/server/server.py", line 117, in ssh_info_GET
ips.extend(map(str, dev.actual_global_ip_addresses))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "subiquitycore/models/network.py", line 394, in actual_global_ip_addresses
for _, addr in sorted(self.info.addresses.items())
^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'addresses'
```

network: fix crash upon accessing Help menu after creating a bond

---

subiquitycore/models/network.py
subiquitycore/models/tests/test_network.py

Addresses https://bugs.launchpad.net/subiquity/+bug/2012659 and other private bugs with similar stracktraces.
When a network interface is disconnected from the system (e.g., physically removed if it's a USB adapter), probert asynchronously calls the del_link() method.
Upon receiving this notification, Subiquity server wants to send an update to the Subiquity clients. The update contains information about the interface that disappeared - which is obtained through a call to netdev_info.
Unfortunately, for Wi-Fi and Ethernet interfaces, netdev_info dereferences the NetworkDev.info variable. Interfaces that no longer exist on the system (and also interfaces that do not yet exist), have their "info" variable set to None - so an exception is raised when dereferencing it.
Wi-Fi interface:
``` …
```

network: fix crash when Wi-Fi or eth interface gets removed from the system

---

subiquity/server/controllers/network.py
subiquity/server/pkghelper.py
subiquity/server/server.py
subiquity/server/tests/test_pkghelper.py

When a Wi-Fi interface is present in the machine configuration (e.g., mwhudson.json), the GUI seemingly ignores it. This happens because there is a filter on the server side which only returns Wi-Fi interfaces if the wlan_support_install_state() function returns
PackageInstallState.DONE.
However, calling the /network endpoint shows that the state is set to the wrong value:
```json
{"wlan_support_install_state": "NOT_NEEDED"}
```
This turns out to be inconsistent because:
* we lean on a PackageInstaller instance to tell if wpasupplicant is installed (this is what the wlan_support_install_state() function reflects) ; but
* in dry-run mode, we pretend to install wpasupplicant without actually relying on the PackageInstaller instance.
Fixed by using the PackageInstaller instance to install …

network: fix Wi-Fi interfaces not listed in dry-run

---

documentation/autoinstall-reference.md
subiquity/common/types.py
subiquity/server/controllers/drivers.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/source.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/ui/views/filesystem/guided.py

This disables core boot options if the user selected "search for third party drivers".
It also adapts the recent fix to not offer core boot options on non-UEFI systems to indicate that this is happening via a disallowed guided option.

Disallow core boot if searching for third party drivers

---

scripts/runtests.sh
snapcraft.yaml
subiquity/models/mirror.py
subiquity/models/tests/test_mirror.py

A regression was introduced as part of mirror testing.
On new Ubuntu installations, the -security pocket is accessed through the primary mirror instead of being accessed through security.ubuntu.com/ubuntu (or ports.ubuntu.com/ubuntu-ports)
This happens because when no `security` section is provided to curtin, the value configured in the `primary` section is reused.
We now ensure that the right URI is used for the security repository.
It has a slight impact on the behavior of mirror testing though. Instead of downloading content from the primary repository only, we would download content from the primary+security repository. Therefore, we would try all the candidate mirrors without success is the security repository is unreachable. To work around this issue, we now disable the -security …

Ensure the security archive is set to the proper URL

---

.github/workflows/snap.yaml
subiquitycore/models/network.py

The snap build is broken at the moment.
Fix the build, and add CI showing the build working.
Samples of current build failure:
https://github.com/dbungert/subiquity/actions/runs/6126545979/job/16630745991#step:3:89
https://launchpadlibrarian.net/686174599/buildlog_snap_ubuntu_jammy_amd64_subiquity_BUILDING.txt.gz

Fix snap build, and CI enforce it

---

.github/workflows/build.yaml

Remove remaining Checkout v2 usage to address the nodejs12 deprecation warnings

workflows: to checkout@v4

---

scripts/runtests.sh
subiquity/models/mirror.py
subiquity/models/tests/test_mirror.py

backport of PR: #1790 to ubuntu/lunar with intention to do one last stable release for that branch.
The curtin portion of that PR is related to Deb822 handling, so not critical.

lunar: security archive

---

subiquity/server/controllers/install.py

Testing shows minimal steps causes unattended-upgrades to take ~14 minutes, and ~4 minutes without. 
Tested using `ubuntu-22.04.1-live-server-amd64`
Relevant portions of `subiquity-server-debug.log`:
With minimal steps:
```
2023-09-14 23:25:21,035 DEBUG root:39 start: subiquity/Install/install/postinstall/run_unattended_upgrades: downloading and installing all updates
2023-09-14 23:25:21,035 DEBUG subiquitycore.utils:112 astart_command called: ['systemd-run', '--wait', '--same-dir', '--property', 'SyslogIdentifier=subiquity_log.1776', '--property', 'PrivateMounts=yes', '--setenv', 'PATH=/snap/subiquity/3698/bin:/snap/subiquity/3698/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/subiquity/3698/bin', '--setenv', …
```

Make unattended upgrades run faster by disabling minimal steps

---

subiquity/client/controllers/filesystem.py
subiquity/models/filesystem.py

Making an install that used an existing RAID failed because of an attempt to log the size of the RAID when rendering the curtin config.
This turns out to be because when the client sends the storage objects back to the server it loses all the "api only" data including the udev data that is needed to display the size.
In some sense this is a bit silly, we could just drop the log statement and it would be fine but I think it's probably better to always have the full storage objects in the server (until we can get away from this hackish API anyway).

include api-only data when sending storage objects from client to server

---

subiquity/server/controllers/install.py
subiquity/server/controllers/shutdown.py
subiquity/server/controllers/tests/test_install.py

For ZFS, we recently introduced a call to `umount --recursive /target` slighly before shutting down or rebooting. Unfortunately, on s390x, we also had a very late call to `chreipl` to make the firmware boot from the installed system.
The call to `chreipl` reads data from `/target/boot`, and it fails if the filesystem is no longer mounted.
Fixed by calling `chreipl` earlier in the installation, during the postinst phase rather than after the user clicks "reboot".
[LP: #2029479](https://bugs.launchpad.net/subiquity/+bug/2029479)

s390x: ensure chreipl is called before unmounting /target

---

snapcraft.yaml

This curtin rev adds the following:
Dan Bungert (3):
extract: log source information
tests/data: 4k sector disk
storage_config: handle partitions on 4k disk
Nick Rosbrook (1):
apt: disable default deb822 migration

snapcraft: rev curtin for deb822, large sectors

---

doc/intro-to-autoinstall.rst
subiquity/server/server.py
subiquity/server/tests/test_server.py

This change allows for specifying the location of the autoinstall.yaml file in the kernel command line via `subiquity.autoinstallpath`. So, something like `subiquity.autoinstallpath=path/to/autoinstall.yaml`.
I have additionally changed the precedence for the various ways the autoinstall file may be passed from:
```
1. root of the drive
2. subiquity cmdline
3. cloud config
4. root of cdrom
```
To:
```
1. subiquity cmdline
2. kernel cmdline
3. root of the drive
4. cloud config
5. root of the cdrom
```
For the tests:
1. I've added a test for the kernel command line case.
1. Reordered them to align with precedence changes
1. Used explicit "missing" values where possible (e.g., `None` for the subiquity arg when the case is no arg is passed), instead of simply leaving them undefined.

Allow for specifying the autoinstall file over the kernel command line

---

snapcraft.yaml

```
$ git log a7640fd..64ea5fbe --oneline --no-decorate
64ea5fbe block_meta: also add recovery key if zkey is used
13c1b8ad vmtests: make loading error verbose
4595c03d vmtests: +python3-debian dep
abebab1e vmtests: add mantic after jammy
91f147b0 vmtests: add jammy after focal
2a45c899 vmtests: remove hirsute
6c5ad6aa vmtests: remove impish
```

Bump curtin rev for recovery key on systems using zkey

---

subiquitycore/tests/test_tui.py
subiquitycore/tui.py

We recently made sure that after doing a snap refresh, the rich mode (i.e., either rich or basic) is preserved. This was implemented by storing the rich mode in a state file. When the client starts, it loads the rich mode from said state file if it exists.
Unfortunately, on s390x, it causes installs to default to basic mode. This happens because on this architecture, a subiquity install consists of:
* a first client (over serial) showing the SSH password
* a second client (logging over SSH) actually going through the installation UI.
Since the first client uses a serial connection, the state file is created with rich-mode set to basic. Upon connecting using SSH, the state file is read and the rich-mode is set to basic as well.
Fixed by storing the rich-mode in two separate files, one for …

ui: have a distinct state file for rich mode over serial

---

doc/reference/autoinstall-reference.rst
documentation/autoinstall-reference.md

Regarding [LP #2037133](https://bugs.launchpad.net/subiquity/+bug/2037133): The documentation incorrectly states that locale is implicitly interactive if any other session is interactive. This is not true (anymore), nor the intended behavior.

locale is not implicitly interactive with other interactive sessions

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

When v2/orig_config is called too early, the load_probe_data function will fail because probe_data is None:
```python
File "subiquity/common/api/server.py", line 164, in handler
File "subiquity/server/controllers/filesystem.py", line 1029, in v2_orig_config_GET
model = self.model.get_orig_model()
File "subiquity/models/filesystem.py", line 1428, in get_orig_model
orig_model.load_probe_data(self._probe_data)
File "subiquity/models/filesystem.py", line 1894, in load_probe_data
for devname, devdata in probe_data["blockdev"].items():
TypeError: 'NoneType' object is not subscriptable
```
Make sure we don't dereference model._probe_data if it is None.

filesystem: don't crash if v2/orig_config is called early

---

subiquity/server/controllers/filesystem.py

In LP: #2009141, we are hitting kernel limits and pyudev buffer limits.
We don't care about specific events, so much as getting one event,
waiting for things to calm down, then reprobing.
Outright disable the event monitor, and re-enable later.  If there is a
storm of events, testing has shown that stopping the listener is not
enough.

filesystem: revamp udev handling

---

doc/intro-to-autoinstall.rst
doc/reference/autoinstall-reference.rst
documentation/autoinstall-reference.md
snapcraft.yaml
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/oem.py
subiquity/server/server.py
subiquity/server/tests/test_server.py
subiquity/tests/api/test_api.py
subiquitycore/snapd.py
subiquitycore/tests/test_tui.py
subiquitycore/tui.py

* cherry-picked aaaf873..28dd55f from #1803
* cherry-picked 22b6d12 from #1805
* cherry-picked 5a573f2 from #1804
* cherry-picked c95261e from #1802
* cherry-picked 4ba59a5 from #1807
* cherry-picked 7de6f05 from #1808
* cherry-picked 59849f7 from #1809
* cherry-picked b11726d from #1806

Mantic merge 2023-09-27

---

examples/autoinstall/fallback-offline.yaml
scripts/runtests.sh
subiquity/common/pkg.py
subiquity/models/ad.py
subiquity/models/codecs.py
subiquity/models/locale.py
subiquity/models/network.py
subiquity/models/ssh.py
subiquity/models/subiquity.py
subiquity/server/controllers/install.py
subiquity/tests/api/test_api.py

ubuntu-restricted-addons is a multiverse package and is not included in the pool. Therefore, trying to get it installed when offline leads to an obvious error.
Instead of making the whole Ubuntu installation fail, we now warn and skip installation of the package when performing an offline install. In a perfect world, we should not have offered to install the package in the first place, but in practice, we can run an offline installation as the result of failed mirror testing (bad network for instance).
NOTE: I've reused what I did for https://github.com/canonical/subiquity/pull/1795 so no wonder if the code looks similar :)

codecs: skip installation when running an offline install

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

If we ask for reboot before the installation has started (i.e., if curtin install was not invoked at least once), the following call fails and prevents the system from rebooting.
$ umount --recursive /target
Make sure we check that /target exists and is mounted before calling umount.
Another approach would be to check the return value of umount but the values are not documented.
`LP #2037539`

shutdown: do not try to unmount /target if install was not started

---

subiquity/server/controllers/cmdlist.py
subiquity/server/controllers/tests/test_cmdlist.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/controllers/tests/test_install.py
subiquity/server/controllers/tests/test_refresh.py
subiquity/server/controllers/tests/test_snaplist.py
subiquitycore/tests/mocks.py
subiquitycore/utils.py

LP [#2032961](https://pad.lv/2032961): We are not cleaning the environment provided to subprocesses correctly. When trying to invoke a program that should run outside of the snap context, the `LD_LIBRARY_PATH` variable is pointing to the linker on the snap, which causes errors like:
```
curl: /lib/x86_64-linux-gnu/libc.so/6: version `GLIBC_2.33` not found (required by /snap/subiquity/x1/usr/lib/x86_64-linux-gnu/libpsl.so.5)
```
We had a similar issue solved in #1300. This fix similarly uses `orig_environ` to clean the environment before running commands in the respective command controllers. 
I would especially appreciate some input if the license header on the new test file looks correct. It's an exact copy and paste from one of the other new tests files from this year, but I just want …

autoinstall: Don't use snap env when invoking early and late commands

---

subiquity/server/controllers/shutdown.py
subiquitycore/file_util.py
subiquitycore/tests/test_file_util.py

The cloud init log files are originally owned by syslog:adm, but that user ID is not necessarily the same on the target system.  Normalize that owning user id of the file to root.

Cloud init log

---

subiquity/server/controllers/install.py

CVE-2023-5182
As autoinstall-user-data contains a password hash hash for a user with sudo access, create the autoinstall-user-data as 0400 root:root.
The old permissions are 0640 root:adm, and the adm group does not by default have sudo access, so cracking that hash could lead to privilege escallation for someone in the adm group.
Thanks to Patric Åhlin and Johan Hortling for identifying and reporting the issue.

install: create autoinstall-user-data 0400

---

subiquity/server/controllers/source.py

When handling a POST request to /source, Subiquity sends a 'source configured' event. This signals other controllers / models that they need to restart their tasks that depend on the source being used.
However, if the user of the installer goes back all the way to the source page and submits it again without changing the settings, there should be no reason to restart the machinery.
If a call to source ends up doing no modification to the model (i.e., not changing the source used or the search_drivers setting), we now avoid emitting the 'source configured' event ; except if the model has not been configured yet.
NOTE: this is theoretically more of an optimization than a bug fix (unless it significantly speeds up the install) and may or may not be suitable for a merge to ubuntu/mantic.

source: do not fire a configured event again if nothing changed

---

doc/custom_conf.py
doc/howto/autoinstall-quickstart-s390x.rst
doc/reuse/substitutions.txt

Fixes [FR-5578](https://warthogs.atlassian.net/browse/FR-5578).
* Adds support for variable substitutions in Sphinx docs.
* Adds an initial `substitutions.txt` file with a couple of definitions.
* Modifies a sample howto to use the variables in place of version numbers and release code names.
This should be merged after #1822 as it's based off those additions (just to keep it orderly).
[FR-5578]: https://warthogs.atlassian.net/browse/FR-5578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support for Sphinx substitutions

---

subiquity/server/apt.py

logfile hardening changes have resulted in a warning appearing when running c-n-f about not being able to read sources.list.  Write this file as 644.

apt: fix source.list mode

---

.github/workflows/ci.yaml
.github/workflows/snap.yaml

Fixes [FR-5673](https://warthogs.atlassian.net/browse/FR-5673)
This change excludes changes in the `doc/` directory from the following GH Actions workflows:
* `ci.yaml`
* `snap.yaml`
[FR-5673]: https://warthogs.atlassian.net/browse/FR-5673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FR-5673: exclude doc/ from CI and Snap checks.

---

doc/google8dda472a993637b7.html

Fixes [FR-5544](https://warthogs.atlassian.net/browse/FR-5544)
Adds the Google Consople verification file to allow us to link the Console to the Google Analytics account.
[FR-5544]: https://warthogs.atlassian.net/browse/FR-5544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Google Console verif. file

---

doc/custom_conf.py
doc/explanation/operate-server-installer.rst
doc/index.rst
doc/reference/autoinstall-reference.rst
doc/tutorial/basic-server-installation.rst
doc/tutorial/screen-by-screen.rst

Fixes [FR-5664](https://warthogs.atlassian.net/browse/FR-5664)
See $subj.
[FR-5664]: https://warthogs.atlassian.net/browse/FR-5664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixes invalid links reported by linkcheck in docs

---

doc/.sphinx/_static/github_issue_links.js
doc/.sphinx/_templates/footer.html
doc/.sphinx/_templates/header.html
doc/custom_conf.py

* Header titles & links
* Footer links
* Feedback button
(Fixes [FR-5543](https://warthogs.atlassian.net/browse/FR-5543))
[FR-5543]: https://warthogs.atlassian.net/browse/FR-5543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update and fix project navigation in docs

---

.github/workflows/automatic-doc-checks.yml
doc/.wordlist.txt
doc/Makefile
doc/index.rst
doc/reference/autoinstall-reference.rst

This adds the following automated docs checks to GH Actions:
* spellcheck
* linkcheck
* inclusive-language check
(Fixes [FR-5662](https://warthogs.atlassian.net/browse/FR-5662))
[FR-5662]: https://warthogs.atlassian.net/browse/FR-5662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add docs checks to GH workflows

---

DESIGN.md
README.md
scripts/kvm-test.py
scripts/test-this-branch.sh

As reported in LP:#2039966, the instructions we provide to test local changes in KVM were not enough to cover changes in curtin or probert.
Updated README.md with some pointers and also replaced uses of `snapcraft snap` by `snapcraft pack` to avoid deprecation warnings.

Update instructions to test local changes in kvm

---

.github/workflows/ci.yaml
.github/workflows/snap.yaml

The CI jobs today are split over 20.04 and 22.04 runners.  Some of the test setup actually fails when run against the 22.04 runners, which is why the haven't been moved all to 22.04 yet.
The 20.04 runners are consistently being run before the 22.04 ones, so move everyone to 20.04 for now.
Runner for typing left on 22.04, that one matters.

workflow: runners to 20.04

---

scripts/runtests.sh
subiquity/cmd/server.py
subiquity/cmd/tui.py
subiquity/common/errorreport.py
subiquity/server/apt.py
system_setup/cmd/tui.py

Some name and file location changes to be consistent with the (to be upload) updated subiquity hook in apport.
The only source of the traceback - if any - is the one in memory that we grab and manually attach to the report. We also need to explicitly write out the traceback information when we crash, otherwise a call to `ubuntu-bug` or similar won't be able to pick it up.

Update apport reporting 

---

apt-deps.txt

Fixes issue reported at https://github.com/canonical/ubuntu-desktop-installer/issues/2385
Based on the Log included with the ticket, the cause of the issue is "`ModuleNotFoundError: No module named 'debian.deb822`". 
This PR fixes it by including `python3-debian` in `apt-deps.text`.

Added python3-debian in apt-deps.txt

---

snapcraft.yaml

Full changelog:
* canonical/curtin@64b2744dc4c7c57e18beb46423cf6b563ccd76ab
* canonical/curtin@a349105809af6188cb394e300a99846df3d117f0

snapcraft: update curtin for the efivarfs statfs workaround

---

doc/.custom_wordlist.txt
doc/howto/autoinstall-quickstart-s390x.rst
doc/howto/autoinstall-quickstart.rst
doc/howto/index.rst
doc/howto/report-bugs.rst
doc/index.rst
doc/tutorial/basic-server-installation.rst

* Heading markup made consistent with starter pack
* Proper inline markup used; semantic where possible
* Language scrubbed
(Fixes [FR-5768](https://warthogs.atlassian.net/browse/FR-5768))
[FR-5768]: https://warthogs.atlassian.net/browse/FR-5768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Review howtos

---

doc/howto/autoinstall-quickstart-s390x.rst
doc/howto/autoinstall-quickstart.rst

Fixes internal references in docs.

Docs links fixed

---

subiquity/ui/views/mirror.py

I was improving the French translation when I noticed this one.

mirror: fix wording when mirror testing has not yet started

---

doc/.custom_wordlist.txt
doc/intro-to-autoinstall.rst

The use of spellexception means we have some links that look like: intro-to-autoinstall.html#autoinstall-by-way-of-cloud-spellexception-config-spellexception
Also these are already wordlisted, so we can fix by just dropping the inline spellexception.
Also fix the `debian-installer` wordlist, just `debian` is correct.

doc: fix some link headings

---

CONTRIBUTING.md
README.md

I added a link in the readme to our contribution guidelines and in the contribution guidelines I included a section about the Ubuntu Code of Conduct and updated the Contributor License Agreement text. These two sections are almost entirely lifted from [ubuntu-desktop-installer's readme](https://github.com/canonical/ubuntu-desktop-installer/blob/c030903a00e3819c094efa30d89467e6071985fe/CONTRIBUTING.md#contributor-license-agreement) because it sounds nice and it'd probably be good to have something consistent across the projects. 
I also added some information about where and how to submit bugs, as well as where to submit PRs.

readme: make a contributing section and point to CONTRIBUTING.md

---

scripts/kvm-test.py

Booting Desktop and server live installer ISOs comes with different platform requirements. When running kvm-test, we now accept the name of a profile via the --profile option.
Profiles provide default settings for memory, disk size and extra QEMU options. For now, two profiles are hard-coded: "server" - which is the default and "desktop".
For desktop, we use two vCPU, 8 GiB of RAM, a 20 GiB disk and pass the -device qxl option.

kvm-test: have different profiles for server and desktop

---

subiquity/ui/views/identity.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/mirror.py
subiquity/ui/views/proxy.py
subiquity/ui/views/snaplist.py
subiquity/ui/views/source.py
subiquity/ui/views/ssh.py
subiquity/ui/views/ubuntu_pro.py
subiquity/ui/views/zdev.py
subiquitycore/ui/views/network.py

* Unifies installer screen titles to use '&lt;Topic&gt; configuration' (where approapriate).
* Fixes minor lang. problems and typos (commas, Ubuntu Po -> Pro, Internet -> internet, ...).
(Fixes [FR-5900](https://warthogs.atlassian.net/browse/FR-5900))
[FR-5900]: https://warthogs.atlassian.net/browse/FR-5900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Unify UI screen titles and minor lang. fixes

---

debian/changelog
debian/rules

core24 started to ftbfs as it build the consoleconf deb and that is now failing with noble's debhelper, as it installs systemd units into usr/lib now.

Upgrade to noble, systemd files are now in /usr/lib

---

subiquity/server/controllers/network.py
subiquitycore/controllers/network.py

In Python < 3.11, when passing a coroutine to `asyncio.wait`, it would automatically be scheduled as a task. This isn't the case anymore with Python 3.11. Now passing coroutines to `asyncio.wait` fails with:
```
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```
Let's ensure we schedule the coroutines as tasks before passing them on to `asyncio.wait`.
LP:#2045663

network: ensure we pass tasks to asyncio.wait

---

scripts/validate-autoinstall-user-data.py
subiquity/server/controllers/install.py
subiquity/server/controllers/tests/test_install.py
subiquitycore/tests/mocks.py

We write out the autoinstall data to make the install repeatable but this should also include a reference to the autoinstall documentation to increase usability.

ai: include link to docs in post-install user data

---

subiquity/server/controllers/filesystem.py

We know that running os-prober on some systems is slow, potentially very slow, especially when multiple removable devices are present.
This results in many bug reports showing "block probing crashed with TimeoutError".
For now, I suggest we double the probert timeout when os-prober is involved.

filesystem: double probert timeout when running os-prober

---

subiquity/server/apt.py
subiquity/server/tests/test_apt.py

We backup the sources.list to a file in sources.list.d to be able to insert our source first; if we do not have a sources.list this is not necessary.
If an image uses ubuntu.sources, this logic also works fine as sources.list that we write will be sourced before the ubuntu.sources.

apt: Only backup/restore sources.list if it exists

---

debian/rules

In some situations build might fail on  `mkdir $(CURDIR)/debian/console-conf/usr/lib/systemd/system/getty@.service.d` as the leading directory does not exist.
Combine `mkdir` and `install` into `install -D`

debian: use 'install -D' instead 'mkdir + install'

---

README.md

We currently have a hosted version of our documentation ( https://canonical-subiquity.readthedocs-hosted.com/en/latest/ ) but it's not listed anywhere. Let's put it in the README so it can be found.

Update README with hosted documentation

---

subiquity/models/ssh.py
subiquity/server/controllers/ssh.py
subiquity/server/controllers/tests/test_ssh.py

The /ssh endpoint was, I think, meant to return a list of authorized_keys but it didn't. 
Fixed the issue and also removed a variable that probably has been unused for years now.

Fix emtpy list of authorized_keys in /ssh endpoint

---

.github/workflows/ci.yaml
scripts/test-in-lxd.sh
subiquity/ui/views/identity.py

Enable the noble series in the workflows, along with some prerequisite fixes:
* `cloud-init status` == 2 is not fatal
* Address a multiple inheritance problem where a change to urwid is having the side effect that an initializer isn't running.

workflow: +noble

---

autoinstall-schema.json
autoinstall-system-setup-schema.json
subiquity/server/autoinstall.py
subiquity/server/controller.py
subiquity/server/controllers/tests/test_cmdlist.py
subiquity/server/controllers/tests/test_codecs.py
subiquity/server/controllers/tests/test_debconf.py
subiquity/server/controllers/tests/test_drivers.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/controllers/tests/test_identity.py
subiquity/server/controllers/tests/test_keyboard.py
subiquity/server/controllers/tests/test_locale.py
subiquity/server/controllers/tests/test_mirror.py
subiquity/server/controllers/tests/test_network.py
subiquity/server/controllers/tests/test_oem.py
subiquity/server/controllers/tests/test_package.py
subiquity/server/controllers/tests/test_proxy.py
subiquity/server/controllers/tests/test_refresh.py
subiquity/server/controllers/tests/test_reporting.py
subiquity/server/controllers/tests/test_shutdown.py
subiquity/server/controllers/tests/test_snaplist.py
subiquity/server/controllers/tests/test_ssh.py
subiquity/server/controllers/tests/test_timezone.py
subiquity/server/controllers/tests/test_updates.py
subiquity/server/controllers/tests/test_userdata.py
subiquity/server/server.py
subiquity/server/tests/test_controller.py
subiquity/server/tests/test_server.py
subiquitycore/tests/mocks.py

Adds a special exception for Autoinstall related failures and a
specific implementation for autoinstall validation failures.
When a user passes incorrect autoinstall data, the generated
bug report will be titled:
"Autoinstall crashed with AutoinstallValidationError"
Where the traceback will start with a hint on the offending
section. For example:
"Malformed autoinstall in 'apt' section"
Information from the original jsonschema ValidationError is
also available in the traceback to point to specific issues
with the provided data.
The section reporting is a little crude in the validation
of the base schema done by SubiquityServer, which can't discern
between the 'interative-sessions' and 'version' keys, but for now
the scope is pretty limited and can be fixed up at a later time.

AutoinstallError exception  

---

subiquity/cloudinit.py
subiquity/server/server.py
subiquity/tests/test_cloudinit.py

Add version checks for cloud-init to know if we can read status in JSON format or not.  If so, use that for a superior answer to the legacy format.  Handle legacy code paths also.

cloudinit: handle format=json status

---

console_conf/controllers/identity.py
console_conf/models/identity.py

In preparation for running console-conf as a strictly confined snaps, review of
the existing code has shown that user's key fingerprints are not being used or
displayed anywhere. Since we would not be able to read those public keys anyway,
we may as well drop the code which attempts to device the key fingerprints.
See #1873 for context

console_conf: do not attempt to obtain user's public key fingerprints

---

subiquitycore/snap.py
subiquitycore/tests/test_snap.py

Add helpers for probing if the process is executing inside a snap.

subiquitycore: helpers for probing for snap execution environment

---

bin/console-conf-wrapper

Modify the wrapper to consider consol-conf installed as snap.
Prepare sshd finger prints to be used by consol-conf snap.

console_conf: modify wrapper helper to consider consol-conf as snap

---

console_conf/controllers/identity.py
console_conf/controllers/tests/test_identity.py
console_conf/core.py

Set a console-conf as project name, which ensures that the early app setup creates a relevant state directory under /run. Update code where /run/console-conf was hardcoded to use the app level helpers to derive the correct state directory location.
The intention is to supersede #1869

console-conf: set project name, consistently use as state directory

---

console_conf/controllers/identity.py
subiquitycore/ssh.py
subiquitycore/tests/test_ssh.py

In strict snap confinement, sshd config or host keys are not accessible.
If strict confinement is detected, instead allow reuse of the host keys fingerprints already prepared by invoking process. Prepared fingerprints are stored in: `/run/console-conf/host-fingerprints.txt`
Additionally, in strict snap confinement, snap can not access the other user's ssh keys or authorised keys.
Do not read those, it does not seem like we are displaying them at the moment anyway.

console_conf: identity: use prepared fingerprints

---

subiquity/client/controllers/tests/test_ubuntu_pro.py
subiquity/client/controllers/ubuntu_pro.py
subiquity/ui/views/ubuntu_pro.py

The /etc/lsb-release file currently on noble shows:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu Noble Numbat (development branch)"
```
Therefore, the Ubuntu Pro pages get skipped. This makes testing on noble difficult, so make an exception for noble now and we'll drop it once it's marked LTS.

ubuntu-pro: enable on noble, although it's not yet marked LTS

---

subiquity/client/controllers/filesystem.py
subiquity/ui/views/identity.py
subiquity/ui/views/mirror.py
subiquity/ui/views/ubuntu_pro.py

* cherry-picked 76f04697058e1b0b969c835f987d3ba31d4e98ca from #1884 (just a fix for answers-based testing)
* cherry-picked 81c16f5a83dae9b3173ab7b5fefe7e011331a0ec from #1865 
* cherry-picked 4b7101fb2aa43c3c20eb76e31e761a257b38d17c from #1864
* cherry-picked 97409bea6cfa4ef84526100fd5332dc0ba95ce11 from #1876
* Refreshed number of machines covered by Pro for free, inspired from 4e81b0d81dc4e7312384aa842a63ba75df9a8e0e

Mantic merge 2024 02 12

---

console_conf/controllers/identity.py
console_conf/controllers/tests/test_identity.py
console_conf/core.py
subiquitycore/snapd.py

When running in strict snap confinement `snap` client binary is not accessible.
Additionally, the output format of `snap` client binary is not guaranteed not to change.
snapd REST API should be used instead when communicating to the snapd and expecting a parsable response.
This also improves error handling for this call.

console_conf: identity: use snapd unix socket

---

doc/reference/autoinstall-reference.rst
subiquity/common/types.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

This changeset will allow reset_partition to accept int or human-readable disk size (e.g. "12G"), so that the size of reset partition can be fixed.  This will be used for some OEM deployments and automated testing where overwriting or updating reset partition is necessary.

Accept a fixed partition size for reset partition in autoinstall.yaml

---

.github/workflows/ci.yaml
subiquity/models/network.py
subiquity/models/tests/test_network.py
subiquity/server/controllers/tests/test_network.py

Since netplan 0.106.1, Netplan YAMLs should have file permissions with mode 0o600 (owner RW only) and root owner.

permissions: update netplan configs to 0600

---

subiquity/server/controllers/install.py
subiquity/server/controllers/tests/test_install.py

This resolves https://pad.lv/2051099
The reason removing EFI boot entry is because any of our known factory workflow is not able to create EFI boot entry on the target machine.
GRUB boot entry is that we would like to adjust kernel boot commands in the reset partition.  Do we have any concern using chainloading?

factory-reset: remove EFI boot entry, retarget GRUB entry to chainload Reset Partition GRUB

---

subiquity/models/network.py

Previously we had stripped the wifi config and wrote it separately with stricter permissions than normal to avoid leaking sensitive data, but now at first glance this seems redundant with all the netplan config file permissions being the same. The reason we didn't collapse everything back to one file with the permissions change is that there are scenarios in which the 00-installer-config.yaml file could purposefully be shared, so we should continue to strip known private information from that file.

update rationale for netplan config permissions

---

subiquitycore/controllers/network.py

Subiquity has a mechanism to detect the presence of netplan. It does so by checking the existence of the file `/lib/netplan/generate`. This mechanism is used in the network screen to validate the YAML configuration.
However, since netplan 0.107 (present in mantic and noble), the file `/lib/netplan/generate` is no longer present. It used to be provided as an alias for `/usr/libexec/netplan/generate` ; starting in jammy.
This made Subiquity unable to detect that netplan is running ; and therefore skip the YAML validation against netplan.
Since we support focal in Subiquity, let's change the detection code so that we look for both locations. When we stop supporting Focal in the future, we can drop the reference to `/lib/netplan/generate`.

network: fix detection of netplan on recent Ubuntu releases

---

subiquity/server/server.py

Mirror and proxy are not in plan to be shown in the UI, so stop requiring them.

server: fix desktop INSTALL_MODEL_NAMES

---

bin/console-conf-wrapper

The changes in https://github.com/canonical/subiquity/commit/66e8222a09da0fbc27ada889acab28ba8374cf42 and https://github.com/canonical/subiquity/commit/f3043cde88d04bc4c33d2c0f50e27b5e69262910 introduced established /run/console-conf as the project runtime directory. Make sure that the wrapper uses the same location.
Also a small fix for a bug that was fixed in master once and then reintroduced accidentally in https://github.com/canonical/subiquity/pull/1656.  We generally expect /var/lib/snapd/modeenv to exist, but in case it does not, fall back to picking up the mode from kernel command line (just like snapd does it).

bin/console-conf-wrapper: use /run/console-conf, fix mode extraction

---

subiquity/common/types.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Clarify that the implemented mechanism is the keystore setup.  An implementation that doesn't use native ZFS encryption is plausibly interesting, which is a better use of the term ZFS_LUKS.

types: rename ZFS_LUKS -> ZFS_LUKS_KEYSTORE

---

subiquity/server/server.py
subiquity/server/tests/test_server.py

Inspect cloud-init status for disabled. When disabled do not call stages.Init due to a side-effect that cloud-init tries to rediscover any viable datasource when none are previously discovered.
LP: #2055077

bug(cloudinit): do not call cloudinit stages.Init when disabled

---

subiquity/models/subiquity.py

Currently, installations of Ubuntu Server and Ubuntu Desktop 24.04 both fail on UEFI-based systems because of a grub2 bug. This is a workaround to avoid failing installs until grub2 migrates to the release pocket.

debconf-selections: work around grub2 bug until it is fixed

---

examples/answers/nvme-over-tcp-rootfs.yaml
snapcraft.yaml
subiquity/models/filesystem.py
subiquity/ui/mount.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/partition.py

Now that curtin more or less supports NVMe over TCP with the rootfs on remote storage, relax the contraints set by subiquity.
We still need the /boot (and /boot/efi) partitions on local storage though.
We probably want to display a warning somewhere "Please note that NVMe over TCP is experimental and in active development" for instance.
Depends on https://code.launchpad.net/~curtin-dev/curtin/+git/curtin/+merge/461452

filesystem: accept to place the rootfs on remote storage for NVMe-o-TCP

---

subiquity/client/client.py
subiquity/client/controllers/progress.py
subiquity/client/controllers/tests/test_progress.py
subiquity/common/apidef.py
subiquity/common/types.py
subiquity/server/nonreportable.py
subiquity/server/server.py
subiquity/server/tests/test_server.py
subiquity/tests/api/test_api.py
subiquity/ui/views/error.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/tests/test_installprogress.py
test_data/autoinstall/bad-early-command.yaml
test_data/autoinstall/invalid-early.yaml

The original attempt to make a new class of non apport reportable errors in #1897 didn't quite cover everything needed, especially in regards to the changes needed in the API to inform the client of the nuance of the error state. These changes include:
- A refactor to make the apport generation suppression generic and tested
- Changes to the /meta/status API response object (`ApplicationStatus`) to include a new field `nonreportable_error`
- Reportable errors are still available under the `error` field, so disambiguating the error difference requires checking which of `error` and `nonreportable_error` isn't `None`
- The endpoints `/meta/restart` (POST) and `/meta/ssh_info` (GET) are now available before the server has finished loading all of its controllers. 
- The server now sets the …

Support for Non Reportable Errors

---

doc/.custom_wordlist.txt
doc/reference/index.rst
doc/reference/ubuntu-image.rst

In order to make `ubuntu-image` documentation available to users (considering that a) `ubuntu-image` has no online presence other than its GH repo, and b) following the transition to packaging `ubuntu-image` only as a Snap, it doesn't have a man page), I'd like to add basic reference info about it to the Installation Guide.
While at this point, the IG contains only Autoinstall/Subiquity docs, the plan is to expand it to include other kinds of installation-related content. This makes `ubuntu-image` docs a good candidate for addition.
This PR only adds a single reference page with basic info about the `ubuntu-image` tool and its command-line options. It's derived from the erstwhile `ubuntu-image` man page, but the plan is to add other reference and how-to content relating to the tool …

Add ubuntu-image reference

---

subiquity/models/subiquity.py
subiquity/models/tests/test_subiquity.py
subiquity/server/controllers/identity.py
subiquity/server/controllers/tests/test_identity.py
subiquity/server/controllers/tests/test_userdata.py
subiquity/server/controllers/userdata.py

For Desktop we want to be able to not require creating a user.  To this end the existing use cases were enumerated, existing behavior confirmed, and the new scenario added.

Allow skip identity

---

snapcraft.yaml

Full changelog:
* canonical/curtin@3d0994a3bfb47318bd8b4c0aa5e345e198eabe77
* canonical/curtin@a5b815bc688fcc18877ef2cd05ea56bc58d7fe00
This should address LP:#2056570 and LP:#2056308

snapcraft: bump curtin revision for the SYSTEMD_OFFLINE handling and deb822 sources

---

subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Fix matching raids as part of layout-style storage autoinstall, along with some related issues
* add logging to match handling, it's a bit inscrutable
* raise AutoinstallError on a failed match.  Today layout style match just fails with a `None` deref, and config style raises a generic `Exception`

filesystem: autoinstall reformat_disk match raids

---

snapcraft.yaml
subiquity/models/subiquity.py
subiquity/models/tests/test_subiquity.py

Move copying of installation media metadata (i.e., things in `/cdrom/.disk/`) to Curtin. Includes fix for [LP: #2037038](https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/2037038). 
Curtin [MP 462092](https://code.launchpad.net/~cpete/curtin/+git/curtin/+merge/462092)

Move metadata collection to Curtin

---

snapcraft.yaml

Full changelog:
* canonical/curtin@54cc7d980b9300339e773dc579daa5f11fd12fd0
* canonical/curtin@4b3395bd71960406498cb8ee09db2f26fea9680c
* canonical/curtin@cf8f7a48905109dbc28808db90fd63c3d6ec37f6
* canonical/curtin@69e315408e3b33010e00387e624680cd66056c61 (unrelated but should be harmless)
LP:#2056730

Bump curtin rev for conditional nvme-stas installation

---

scripts/test-system-setup-loopback-only.py

When ensuring that the system-setup process can only be connected to on the loopback interface, we spawn a bunch of `curl --interface ...` processes. If the connection times out (which is the expectation in most scenarios), the curl processes ended up not being terminated. Not only this is small waste of resources, this is also causing errors on noble:
```python
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x745692661300>
File "/usr/lib/python3.12/asyncio/base_subprocess.py", line 126, in __del__
self.close()
File "/usr/lib/python3.12/asyncio/base_subprocess.py", line 104, in close
proto.pipe.close()
File "/usr/lib/python3.12/asyncio/unix_events.py", line 568, in close
self._close(None)
File …
```

tests: terminate curl processes on timeout

---

subiquity/cmd/server.py
subiquity/cmd/tui.py

By default, warnings emitted by warnings.warn() will show on stderr. For a TUI application, this is a problem because they will be displayed over the UI and create visual glitches.
For parts of the UI that are regularly redrawn, the text of the warning will eventually go away (sometimes instantly, making the warning impossible to read).
For parts of the screen that are *not* regularly redrawn, the text of the warning will stay until the user sends a Ctrl-L sequence.
We now make use of logging.captureWarnings() to redirect the warnings to the log files. This prevents the UI glitches and if any warning is emitted, we can actually find it in the logs.
NOTE I witnessed this issue after upgrading to noble. urwid started throwing warnings and they weren't readable.

logging: capture warnings emitted using warnings.warn()

---

subiquity/server/controllers/filesystem.py
subiquity/tests/api/test_api.py

This should not result in a format object being created, which curtin doesn't like.  Normalize to None as the fstype to skip format object creation.
LP:#2058394

filesystem: handle empty string fstype partitions

---

snapcraft.yaml

Full changelog:
* canonical/curtin@4d9513d60ae2e74fd88918c821b93ff17c8ababa
* canonical/curtin@a02daee21e8508622ea9755fa667dd2c70335f53
LP:#2058741

snapcraft: bump curtin revision for apt-config warning fix

---

subiquity/client/client.py
subiquity/server/controllers/reporting.py
subiquity/server/controllers/tests/test_reporting.py
subiquity/server/event_listener.py
subiquity/server/server.py
subiquity/server/tests/test_server.py
subiquitycore/context.py
subiquitycore/tests/mocks.py

Adds new reporting type events "INFO", "WARNING", and "ERROR" to be used for context logging. These can be invoked with the new `.info`, `.warning`, and `.error` methods on the context object accordingly. Useful for warning/errors on autoinstall configurations.
The first two commits can probably be squashed, but I left them there for reviewability. It took me some time to fully understand what's going on with the code, so I wrote some tests to make sure I didn't change the reporting behavior during the refactor.

Improve context logging

---

subiquity/client/controllers/progress.py
subiquity/ui/views/installprogress.py

The improved context logging from #1945 can also be useful in interactive installs when reading through the log in the progress view.

Display new reporting events in the TUI

---

doc/reference/autoinstall-reference.rst
subiquity/server/server.py
subiquity/server/tests/test_server.py

Subiquity currently ignores invalid top-level keys, but this has likely been a major source of confusion of autoinstall capabilities.
In future versions, the following autoinstall config will throw an AutoinstallValidationError:
```yaml
version: 2
interactive-sections:
- identity
literally-anything: lmao
```
This patch adds warnings for version 1 and will begin to throw an AutoinstallValidationError on these instances in version 2 once it has been enabled.

Enforce top-level keys

---

subiquity/models/subiquity.py

To workaround a grub2 bug (LP: #2055294) causing 24.04 installations to fail, we added a default debconf-selection in Subiquity.
grub2 2.12-1ubuntu4 fixes the issue and migrated to the noble release pocket on 2024-03-06.
We can now drop the workaround.
https://launchpad.net/ubuntu/+source/grub2/2.12-1ubuntu4
This reverts commit cffce3230500526af8a1100ac149b0883a17b092.
NOTE: if the three conditions are true for you, you will need to download a new installer ISO:
1. you are using an old ISO that does not have grub2 2.12-1ubuntu4 (or more recent) in the pool
2. you update the installer using the self-refresh mechanism
3. you perform an offline install
LP:#2055294

Revert grub2 workaround for cloud_style_installation

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

When a partition is mounted in the live environment (either by casper or another process) and is selected for resize, curtin will fail when running e2fsck (or equivalent) with an error such as:
```
Resize requested for format ext4
Resizing /dev/sdb4 of type ext4 down to 12546211840
Running command ['e2fsck', '-p', '-f', '/dev/sdb4'] with allowed return codes [0] (capture=False)
/dev/sdb4 is mounted.
e2fsck: Cannot continue, aborting.
An error occured handling 'disk-sdb': ProcessExecutionError - Unexpected error while running command.
Command: ['e2fsck', '-p', '-f', '/dev/sdb4']
Exit code: 8
```
This is what happens when casper creates a partition on the installer media to store /var/log and /var/crash. Usually the partition is large enough to install Ubuntu so a GuidedStorageTargetResize …

filesystem: don't suggest target resize if part is mounted

---

subiquity/cloudinit.py
subiquity/server/server.py
subiquity/server/tests/test_server.py
subiquity/tests/test_cloudinit.py
subiquity/ui/views/error.py
subiquitycore/context.py

Users attempting to do autoinstall may incorrectly send autoinstall directives as cloud-config, which will result in cloud-init schema validation errors. When loading autoinstall from cloud-config, we now check to see if there are any cloud-init schema validation errors and warn the user. Additionally, if the source of the error is from a known autoinstall error, we inform the user and halt the installation with a nonreportable AutoinstallError.
Requires #1945 and #1947.

Cloud init schema failures

---

doc/.custom_wordlist.txt
doc/.wordlist.txt
doc/intro-to-autoinstall.rst
doc/reference/autoinstall-reference.rst
scripts/validate-autoinstall-user-data.py
subiquity/server/server.py
subiquity/server/tests/test_server.py

Allows autoinstall to be passed with a top level `autoinstall` key like the following:
```yaml
autoinstall:
version: 1
identity:
...
```
in all autoinstall delivery methods. The old format, with no top level `autoinstall`, is still supported. 
I've updated the docs to reflect this change by adding the top-level `autoinstall` to most of the examples, adjusted the directions to default use this structure, and removed the note about not using it in non-cloud-config cases. I also included a small note in the reference section about this structure not technically being a strict requirement in non-cloud-config scenarios and that the old way is still supported, but it also encourages users to use the new format.
In the examples, I think there are still cases where we don't necessarily need to …

Allow top-level autoinstall in all delivery methods

---

subiquity/ui/views/filesystem/partition.py

In cda6c54b87b81edaf6b2623902eb16b6d86e5a75, we introduced the accurate size vs human readable size for the size form fields. Unfortunately, we also introduced a regression when the size gets capped (when it exceeds the maximum size defined on the form). Currently, specifying a size that is beyond the maximum value fails when submitting the form with:
```python
[...]
File "urwid/wimp.py", line 543, in keypress
self._emit('click')
File "urwid/widget.py", line 461, in _emit
signals.emit_signal(self, name, self, *args)
File "urwid/signals.py", line 265, in emit
result |= self._call_callback(callback, user_arg, user_args, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "urwid/signals.py", line 295, in _call_callback
return bool(callback(*args_to_pass)) …
```

storage: fix UI crash when partition size gets capped

---

.pre-commit-config.yaml
doc/pre-commit-spell-check

Tired of forgetting to run `make spelling` before committing changes to the documentation? This is why we have pre-commit!
The downside is that the spell check can take a little while, but I think it's better than waiting for CI to yell at you. I recently had a PR that was unnecessarily noisy due to fixing spelling errors.

pre-commit: add spelling check

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Partial implementation of LP:#2057837.  To create a specific dataset for /home/$user, this requires moving where and when users are created, which is not in plan for 24.04.
FR-7081

filesystem: datasets for /root and /home

---

.pre-commit-config.yaml
doc/Makefile
doc/pre-commit-spell-check

* improve the doc makefile so `make install` multiple times DTRT
* fix deps of other targets, most so spelling -> install works but fix others while I'm here
* now the spelling check can be just `make -C doc spelling`

Doc makefile

---

subiquity/models/subiquity.py
subiquity/models/tests/test_subiquity.py

On first boot, there appear to be cases where the cc_dpkg_grub module in cloud-init is not doing the right thing, which are to be sorted out. But for first boot to happen we have a working boot config, so let's not perturb that.
LP:#2060695 / FR-7389

models/subiquity: disable cc_dpkg_grub

---

doc/reference/autoinstall-reference.rst
subiquity/models/mirror.py

Automated installations and desktop installations will now switch to an offline installation by default. In this mode, only packages from the pool will be fetched.
This should allow the installation to proceed when installing from a private network without external access to the internet.
This is similar in essence to #1816 but applies the policy to automated server installs as well.
If you are doing a desktop installation (or an automated server installation) in a private network with no Internet access, the mirror connectivity test will eventually timeout and the installer will switch to an "offline" installation. (let's call it semi-offline). 
Going forward, I think we should have a new directive in autoinstall configuration mimicking `use_during_installation` from #1968, so that users …

mirror: switch default policy to OFFLINE_INSTALL by default

---

subiquity/models/subiquity.py

Grub provides "quiet splash" for GRUB_CMDLINE_LINUX_DEFAULT out of the box, but curtin rewrites that value and drops both "quiet" and "splash". On desktop, retain "quiet splash".
This should be configurable via autoinstall if this change is undesired.

curtin: desktop grub.replace_linux_default False

---

apt-deps.txt
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/refresh.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/controllers/tests/test_refresh.py

When the request to `v2/systems/enhanced-secureboot-desktop` (or equivalent) fails, Subiquity did not capture the reason. This makes it difficult to understand why this call sometimes fails. We now log the response text to understand better what's going on.
LP:#2061757
Also did the same change for the call to `v2/snaps/ubuntu-desktop-provision` intended to refresh the snap ; although we already know that sending two successive requests will return 409. LP:#2061756

storage: log snapd response text when v2/systems/{system} or v2/snaps/{snap} fails

---

subiquity/client/controllers/mirror.py
subiquity/common/types.py
subiquity/server/controllers/mirror.py
subiquity/ui/views/mirror.py

Client / TUI change
-----------
In the mirror screen, if the test fails and the user decides to ignore the failure, we used to continue the installation normally ; which in most scenarios resulted in an error at a later stage of the installation.
Instead, we now revert to an installation without network (i.e., only packages from the pool are considered for installation) if the user decides to ignore the failure.
Current design:
Proposed design:
<details>
<summary>Previously proposed design</summary>
</details>
Note that the behavior hasn't changed if the user decides to skip the test _while it is running,_ 
Backend change
------------------
The /mirror GET and POST endpoints now include a boolean field named `use_during_installation`.
* if set to `True`, the mirror information will be …

mirror: if the mirror test fails, suggest an offline install

---

snapcraft.yaml

```
$ git whatchanged e4c7d7186c59ade359652db5accb6cb7156df499..c66faffeea657c70374479d62fce32965ff7ac31 --oneline
c66faffe (HEAD -> master, origin/master, origin/HEAD) util: fix lack of string interpolation when raising TiemoutError
:100644 100644 d9b7962b a10f1bfc M      curtin/util.py
```
* canonical/curtin@c66faffeea657c70374479d62fce32965ff7ac31

snapcraft: bump curtin rev for ZFS string interpolation fix

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

If block probing times out, we rerun it with the restricted set of probes. Sadly, the restricted set does not include "nvme" so we do not enumerate NVMe controllers. This leads to the following error if NVMe storage devices are present:
```python
File "subiquity/models/filesystem.py", line 1492, in reset
self.process_probe_data()
File "subiquity/models/filesystem.py", line 1512, in process_probe_data
self._orig_config = storage_config.extract_storage_config(self._probe_data)[
File "/site-packages/curtin/storage_config.py", line 1420, in extract_storage_config
tree = get_config_tree(cfg.get('id'), final_config)
File "/site-packages/curtin/storage_config.py", line 313, in get_config_tree
for dep in find_item_dependencies(item, sconfig):
File "/site-packages/curtin/storage_config.py", line …
```

filesystem: probe NVMe controllers when running the restricted probe

---

subiquity/common/filesystem/manipulator.py
subiquity/server/controllers/tests/test_filesystem.py

Under some plymouth configs, cryptsetup shows warnings on boot for underspecified cryptoswap options.  This makes the warnings go away, but we've hardcoded some options that may change in the future.
LP:#2063252

filesystem: swap options

---

.pre-commit-config.yaml

With "pass_filenames: True" (the default) the spell check entry will be invoked as "make -C doc spelling file1 file2 ..." which will cause the default Make target to be run for the specified files, leading to errors like:
. .sphinx/venv/bin/activate; sphinx-build -M doc/some_file "." "_build" Running Sphinx v7.3.7
Sphinx error:
Builder name doc/some_file not registered or available through entry point
Since the spelling target will check all files, we can suppress sending any filenames.

pre-commit: don't pass file names to spell check

---

subiquity/common/serialize.py
subiquity/common/tests/test_serialization.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapdapi.py

subiquity.common.serialize: add a way to have a "non-exhaustive" enum

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

In python, bool is a subclass of int so we can't use isinstance to check if the user specified a size for the reset partition. This causes autoinstall with "reset-partition: True" and "reset-partition-only: true" to crash the installer. (LP: #2061042).
I'm not too sure how useful the following autoinstall config is:
```yaml
autoinstall:
version: 1
storage:
layout:
name: direct
reset-partition: true
reset-partition-only: true
```
but this will cause subiquity to report the following:
`2024-04-12 22:16:10,913 INFO subiquity.server.controllers.filesystem:1463 autoinstall: will install reset partition of size 1`
and then crash during rsync.

filesystem: reset-partition size bug

---

subiquity/models/network.py
subiquity/models/tests/test_network.py

In commit 9ecc4060b (PR #1911), we changed the permissions of the written netplan config files to be stricter but still retained the logic to separate out the wifi information. Since these both are likely to contain secrets and also have the same permissions, we can keep the config merged.

network: drop logic to split out wifi config

---

subiquity/server/server.py
subiquity/server/tests/test_server.py

We currently don't have plans to do anything with the _data_ of the keys that fail to validate by cloud-init; and trying to access this data has the potential to crash the installer if it doesn't exist, at least at the top level (LP:#2062988).

cc-extract: don't unnecessarily access data

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/identity.py
subiquity/server/controllers/source.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/controllers/tests/test_identity.py
subiquity/server/controllers/tests/test_source.py

Moves the logic for checking if user-data or identity section is provided (on server) in the autoinstall config to the load_autoinstall_data function. Without this change, the exception thrown in apply_autoinstall_config won't halt the installer until
the postinstall steps (LP: 2060547).
The change is ready but I am keeping this as a draft PR until I can test this on Desktop.

identity: fail on missing section sooner

---

examples/snaps/v2-systems.json
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapdapi.py

Rather than always assuming it has to be mounted in from the layer to be installed (snapd will now populate the seed in the target system when its install API is called if it is empty).

allow system definition to be in live layer

---

examples/answers/uc24.yaml
examples/snaps/v2-systems-20240314.json
examples/sources/uc24.yaml
scripts/runtests.sh
subiquity/models/source.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/install.py
subiquity/server/controllers/source.py

The main thing here is to add support for sources that do not require subiquity to copy anything to the target system (snapd's install API takes care of putting the needed bits in place for core).
Working on this I realised that the handling of the 'size' field is a bit incoherent between classic and core boot classic (and now core). That can be cleaned up independently though!

add ability to install uc20+ systems

---

subiquity/models/subiquity.py
subiquity/models/tests/test_subiquity.py

Ensure datasource_list configuration from subiquity is a single line: datasource_list: [None] to support ds-identify limitation in parsing single-line datasource_list values.
cloud-init's ds-identify doesn't actually support multi-line YAML and never has.
We can see this behavior in /run/cloud-init/ds-identify.log which opts to use a default datsource_list and logs:
/etcloud/cloud.cfg.d/99-installer.cfg set datasource_list:
no datasource_list found, using default: ....
This issue doesn't affect subiquity in practice because it also places /etc/cloud/ds-identify.cfg containing `policy: enabled`. Which means cloud-init will be enabled regardless of whether ds-identify finds a valid datasource.
We see this in /run/cloud-init/ds-identify.log with the following logs:
```
DSNAME=
... …
```

fix: cloud-init datasource_list must be one-line for ds-identify

---

subiquity/server/geoip.py
subiquity/server/tests/test_geoip.py

After a recent update of geoip.ubuntu.com/lookup, the value of the `<CountryCode3>` tag is now hardcoded to `Unknown`. The `<AreaCode>` tag also has a slightly different meaning but this should not affect Subiquity in any way.
Update the test data accordingly.

geoip: update test data following change in geoip.ubuntu.com/lookup

---

subiquity/tests/test_timezonecontroller.py

FIxes testrunner when the dbus connection isn't available.  Encountered this scenario in a chroot where systemd was present.

timezone: mock a timedatectl invocation

---

doc/reference/autoinstall-reference.rst
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py

Add unit tests for existing functionality (some overlap with `TestAutoInstallConfig` but some is new)
Permit match specs to be done as a list of match rules.
Refactor `disk_for_match` as well to make it simpler to follow.

List of matchers

---

subiquity/server/server.py
subiquity/server/tests/test_server.py

Make sure we catch autoinstall key name aliases so we don't incorrectly warn (or eventually error) on actually correct key names (LP:#2068603).

ai-filter: be aware of autoinstall_key_alias

---

subiquity/client/client.py
subiquity/cmd/server.py
subiquity/common/api/recoverable_error.py
subiquity/common/api/server.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/server.py
subiquity/tests/api/test_api.py

Today, when a client sends a POST request to /storage/v2/ endpoints, if the data is inconsistent with the current state of the model, the Subiquity server process creates an error report and returns with HTTP status 500.
This is what makes the desktop installer display so many crash dialogs. We would want to a way to:
* display a user-friendly error in a dialog of the UI
* avoid creating a crash report every time
This PR allow to configure Subiquity in such a way that, in case of a user-error in /storage/v2:
* the error is sent back to the client with a 422 HTTP status (Unprocessable Content).
* no crash report is created
Here's the code we could use when consuming /storage/v2/add_boot_partition
```python
try:
await self.endpoint.v2.add_boot_partition.POST(disk.id)
except …
```

Add a way to forward user errors to the client when consuming /storage/v2 POST endpoints

---

doc/reference/ubuntu-image.rst

On several occasions recently, users failed to build images with ubuntu-image because it is not made clear the tool must be run as root or with sudo. Clarify this in the doc.
I added this as a `Note` but a `Warning` or something else might be more appropriate/visible.

doc: add a note about running ubuntu-image as root or with sudo

---

NETBOOT_TESTS.md

Publicly documenting my workflow for leveraging QEMU's built in tftp server functionality to perform much faster iteration with netboot testing. This practically emulates the ISO tracker instructions but allows for much faster downloads (in the VM) and testing with modified ISOs.
I put this in a separate file from the other testing instructions so it wouldn't blow up the size. I wonder though if we should make some sort of `test_instructions` directory, sort of like the `test_data` directory, for manual instructions like this.

Add instructions for netboot with QEMU

---

subiquity/common/types.py
subiquity/server/controllers/cmdlist.py
subiquity/server/controllers/install.py
subiquity/server/controllers/shutdown.py
subiquity/ui/views/installprogress.py
system_setup/server/controllers/configure.py

This is a cherry pick of patches from https://github.com/canonical/subiquity/pull/2013
Essentially, this introduces a new state "LATE_COMMANDS" before moving to "DONE" ; so that a reboot is not performed while late commands are still executing.
It also removes the ability to cancel the unattended-upgrades step. We can choose not to include this change if needed.

Merge late-commands status fix to ubuntu/noble

---

subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/spec.py
subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py

Storage "specs" are deprecated but they exist today and it is difficult to know what variables are expected to be present. By using typing.TypedDict, we can make it more explicit what keys are expected and what types.
Running the type checker after the change revealed the following error so I added a FIXME at first (and finally removed the "size" key)
```
subiquity/server/controllers/filesystem.py:1259: error: Extra key "size" for TypedDict "FileSystemSpec"  [typeddict-unknown-key]
```

Use TypedDict-s for storage specs

---

snapcraft.yaml
subiquity/cmd/server.py
subiquity/common/apidef.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquitycore/prober.py

Using the new probert-firmware, we now check if the firmware happens to be EDK II built using the timberland-sig tree. Of course, this won't be enough going forward because not all firmware that support NVMe/TCP booting will be EDK II ; but it should be enough for the PoC with EDK2.
Alternatively, one can supply the --[no-]supports-nvme-tcp-booting to act as if the firmware did/did not support NVMe/TCP booting.
Depends on canonical/probert#149

storage: use probert to determine if firmware supports NVMe/TCP booting

---

subiquity/client/controllers/filesystem.py
subiquity/common/filesystem/boot.py
subiquity/common/filesystem/tests/test_boot.py
subiquity/models/filesystem.py
subiquity/models/subiquity.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/server.py
subiquity/ui/views/filesystem/filesystem.py

Currently, when installing to a NVMe/TCP drive, the bootfs and ESP must be placed on local storage. When the firmware supports NVMe/TCP booting though, we should drop this restriction.

NVMe/TCP - disable bootfs & ESP restrictions if NVMe/TCP booting is supported

---

.pre-commit-config.yaml
doc/reference/autoinstall-reference.rst
scripts/quick-test-this-branch.sh
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py

* cherry-picked 129623c from #1982  - make it easier to test Desktop changes
* cherry-picked b56ea45 from #1989 - merge fix for doc spelling checks
* cherry-picked 094b8eb..70970b3 from #2004 - merge the feature to support list of matchers

Noble matchers

---

snapcraft.yaml

Obtain a newer version of curtin for fixes for LP:#2061073, which involve a fix for a failed sysfs read after a data race with the kernel.
(cherry picked from commit ed0eb4c32580e943eac81eeb2e77ab470ae01941)
Merging this picks up additional changes to curtin (c66faff..7fbc96a):
* support for removing kernels (unused on this branch as Subiquity does not yet have the matching config opt-in)
* AzureLinux support
* changes related to test runs on Noble that don't affect the curtin runtime
* a readme update

merge "snapcraft: rev curtin for wipefs fix" for noble

---

scripts/inject-probe-data.py

The script can be used to inject a ProbeData.txt file into an existing machine-config file.
By default, it will:
* read the storage probe data from a file named ProbeData.txt in the current directory
* read the machine-config from examples/machines/simple.json
* write the resulting machine-config to stdout
The path to ProbeData.txt can be specified using the --storage-probe-data option.
The patch to the machine-config can be specified using the --machine-config option.
The --overwrite option can be passed to overwrite the original machine-config.
examples:
```
$ scripts/inject-probe-data.py \
--storage-probe-data ProbeData.txt \
--machine-config examples/machines/virtio.json
--overwrite
```
```
$ scripts/inject-probe-data.txt > simple-with-injected-storage.txt
```

scripts: add script to inject ProbeData.txt into existing machine-config

---

subiquity/server/controllers/kernel.py

When attempting an OEM kernel install, the ensure_no_kernel_conflict() check fails. explicitly_requested has been set for stock ISOs, but explicitly_requested was only intended for autoinstall cases.

kernel: fix explicitly_requested for default ISOs

---

subiquity/common/filesystem/boot.py
subiquity/common/filesystem/tests/test_boot.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

If a disk has already reached its limit of (primary) partitions, suggesting a use-gap scenario can only lead to failures. In the same vein, if a disk only has room for one more partition but we also need to add an ESP, the scenario would fail to apply too.
We now try to prevent Subiquity from suggesting such, bad, use-gap scenarios ; by guessing the number of primary partitions needed ; and comparing it with the limit.
Although it isn't a perfect solution (see below), this change should hopefully address the most common problems.
What makes it difficult to properly suggest scenarios is that we do not have all the cards in hand with the current API. For instance, the user can choose to add a recovery partition, which of course influences the number of partitions required. Sadly, we don't …

storage: don't suggest use-gap if we can't fit more partitions

---

doc/index.rst

Per https://discourse.ubuntu.com/t/supporting-users/20: "The Ubuntu Discourse is not a space for technical support"

Drop reference to discourse

---

subiquity/cloudinit.py
subiquity/server/server.py
subiquity/tests/test_cloudinit.py

With the goal of removing cloud-init from the subiquity snap, there are two simple utility functions we import from cloudinit that we can very quickly reimplement:
safeyaml.dumps is a simple wrapper around yaml.dump with safe defaults. We only call it in one place, so I've opted to just replace the safeyaml.dumps call with the equivalent yaml.dump call.
rand_user_password is an ascii password generator. I just copied over the implementation and added some tests.

Remove simple cloudinit utilies

---

subiquity/common/filesystem/boot.py
subiquity/common/filesystem/tests/test_boot.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

This is backport of  https://github.com/canonical/subiquity/pull/2031

Noble - do not suggest use-gap scenarios with invalid number of partitions

---

subiquity/client/client.py
subiquity/ui/views/error.py
subiquity/ui/views/help.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/welcome.py
subiquitycore/tui.py

If the `redraw_screen` coroutine was called while a debug shell was opened (or more rarely during the Subiquity shutdown sequence) urwid would fail with:
```
AssertionError(self._started).
```
We now ensure that we skip the redraw in that scenario. The screen gets now redrawn after the debug shell is closed anyway.
Also, while making the `debug_shell` function a coroutine function, I forgot to update some of the code that invokes it ; resulting in various `RuntimeWarning: coroutine 'SubiquityClient.debug_shell' was never awaited` errors. That should be fixed now.

Fixes related to debug shell in non-async context

---

subiquity/server/mounter.py

In dry run mode we copy the apt config from the running system into the "target". Some files associated with Ubuntu Pro are not readable to regular users and they aren't required to get some kind of working config in the target so skip them.

Fix dry-run mode with Pro enabled.

---

snapcraft.yaml
subiquity/models/kernel.py
subiquity/models/tests/test_kernel.py
subiquity/server/controllers/install.py
subiquity/server/controllers/oem.py

Fixes the problem of ending up with 2 kernels installed that can be seen on the OEM codepath if the kernel is preinstalled in the source image.  Works by telling curtin what to remove, since we can get the preinstalled kernel before we start installing the OEM one.
Requires ~~https://code.launchpad.net/~dbungert/curtin/+git/curtin/+merge/469886~~ (meged)
Fixes other unrelated issues
* fix specification of the oem kernel package name - was unused but it should still be the correct value
* fix a corner case where if OEM metapackage installation is requested and a kernel is requested in autoinstall and they match, don't fail that case
* Update the exception where there is an oem/kernel autoinstall conflict to AutoinstallError

No double kernel

---

subiquity/ui/views/filesystem/guided.py

When no disk are discovered by the storage probing operation, Subiquity used to show a screen that would not allow the user to go back or do anything useful. The screen states something along the lines of "no disks were detected, the installation will not be impossible".
Unfortunately, this means that devices that have been discovered lately cannot be used without restarting the installer. Such devices would include devices that have been hot-plugged (which is rather uncommon on Ubuntu Server) and network storage devices such as NVMe/TCP drives.
Instead of preventing the user to go back, we now show a "Back" button, allowing them to re-enter the storage screen with newly probed disks. We also add a "Refresh" button, which essentially does the does the same as re-entering the screen …

storage: add a refresh and back buttons when no disk are discovered

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

filesystem: arbitrary disk select more consistent
If two disks of the same size went to the disk matchers with the default
"largest" match, the one we would choose would be based on whatever
order in python they ended up, and across installs this means that we
could select arbitrarily among disks of a matching size.
Add sort criteria based on various unique identifiers.  Make it work for
other disk-like devices, though the main target is disks and raids
because that's what can go to the matcher system.

predictably arbitrary disk selection

---

doc/reference/autoinstall-reference.rst

Adds some autoinstall examples for the {early,late,command}-controller references. 
I suppose: 
```yaml
early-commands:
- while [ ! -f /run/finish ]; do sleep 1; done
```
really only makes sense if you already know how to setup ssh access to the live environment with cloud-config, but I find it super useful and worth documenting.

Autoinstall reference for command controllers

---

subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/spec.py
subiquity/models/filesystem.py

When using the text-installer with NVMe/TCP, selecting a NVMe drive in the guided page results in the absence of _netdev option for the filesystems. This makes curtin unaware that we want a NVMe/TCP setup and therefore eventually prevents booting.
~~Ensure _netdev is properly set in this scenario.~~
~~Going forward, we should set this option in every scenarios where we create a filesystem on remote storage. But for now, let's keep things simple.~~
~~Marking as a draft because I want to experiment with encryption and LVM~~

guided: set _netdev more consistently (including when doing guided)

---

snapcraft.yaml
subiquity/cmd/server.py
subiquity/cmd/tui.py

The APPORT_DATA_DIR variable must be set before the apport Python module is imported. This was no longer true potentially because of this import:
from subiquity.server.controllers.filesystem import set_user_error_reportable
The result was:
```
ERROR: hook /usr/share/apport/general-hooks/ubuntu.py crashed
File "/snap/subiquity/5988/usr/lib/python3/lib/python3/dist-packages/apport/report.py", line 228, in _run_hook
symb['add_info'](report, ui)
File "/usr/share/apport/general-hook/ubuntu.py", line 34, in add_info
_add_release_info(report)
File "/usr/share/apport/general-hooks/ubuntu.py", line 472, in _add_release_info
report.add_tags([release_codename])
AttributeError: 'Report' object has no attribute 'add_tags'.
```
Instead of trying to call …

apport: set the APPORT_DATA_DIR variable in snap yaml definition

---

doc/.custom_wordlist.txt
doc/reference/autoinstall-reference.rst

Add instructions for using TPM-backed encryption to the docs.
Reference: https://github.com/canonical/subiquity/releases#:~:text=TPMFDE%20can%20be%20triggered%20with%20autoinstall%3A
Additionally, it may be prudent to resolve [2058147](https://bugs.launchpad.net/subiquity/+bug/2058147) as it currently blocks usage of these instructions on some devices.

Add TPM-backed encryption instructions

---

doc/reference/autoinstall-reference.rst

Add example snippets for locale, timezone and keyboard.
I'm not actually sure about all the details of the behaviour of the timezone key -- like what does `timezone: ""` do??

Autoinstall snippets

---

subiquity/client/client.py
subiquity/common/apidef.py
subiquity/common/errorreport.py
subiquity/server/controllers/integrity.py
subiquity/server/server.py
subiquity/ui/views/error.py

1. On the development branch, when showing a crash dialog early (e.g., after an early-command fails), the installer would often raise an exception because the report is not yet loaded on the client side ; although it has finished generating on the server side. See LP:#2076914 
-> Fixed by showing the "Loading report..." animation in this scenario
2.  When showing a crash dialog early, the md5check result is not shown because the Integrity controller:
a. is not yet started
b. does not respond to GET requests until all controllers are started
-> Fixed by starting the Integrity controller earlier ; and allowing it to respond to GET requests before all controllers have started. LP:#2076997
3. If the result of the MD5 check was not yet available by the time the crash report was shown, the …

Various fixes for error reports

---

subiquity/common/apidef.py

* Cherry pick 41abc3576ebbf8f0753b7f98bb5c3bac553bdcc8 from https://github.com/canonical/subiquity/pull/2056
Other changes from the mentioned pull request are a bit more involved but this specific change seems pretty harmless.
It prevents the UI from getting stuck if the user opens the [Help] menu when a crash report is shown very early on.

Noble / meta: respond to ssh_info queries early

---

doc/reference/autoinstall-reference.rst

General formatting updates, add example sections for each sub-key, and add links to advanced usage examples in curtin. 
Also, because I think the reference here should focus on the parts where Subiquity and Curtin's apt sections differ and not repeating Curtin doc of the section, I removed the "add a PPA" example. I do think it's a good example though, so I opened a PR [1] in Curtin to add it to the common snippet's section.
[1] https://code.launchpad.net/~cpete/curtin/+git/curtin/+merge/471552

doc: update autoinstall reference's apt section

---

subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/install.py

People have reported issues involving non exported zpools at the end of Ubuntu installations. Diagnosing such issues is tricky because the `zpool export` commands have to run after the target is unmounted. And once the target is unmounted, logs can no longer be copied over to the target so bug reports don't include traces of potential `zpool export` failures (or failures to unmount target).
Instead of relying on Subiquity's _pre_shutdown hook, we now make use of systemd-shutdown to export the zpools. The chance of successfully exporting the zpools is expected to be higher since it will happen later in the shutdown sequence ; after more mounts have been detached.
This is an attempt to fix LP:#2073772 but since I never reproduced the issue, I can't tell if that would actually fix it.

storage: lean on systemd-shutdown to export zpools on shutdown

---

console_conf/controllers/identity.py
debian/console-conf-serial.conf
debian/console-conf.conf
debian/console-conf.console-conf@.service
debian/console-conf.serial-console-conf@.service
debian/rules
debian/serial-console-generator
subiquitycore/utils.py

Having `getty@.service` and `console-conf@.service` starting each others seem to generate errors on shut down.
```
[  115.522870] systemctl[1011]: Got message type=error sender=org.freedesktop.systemd1 destination=n/a path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=org.freedesktop.systemd1.TransactionIsDestructive error-message=Transaction for getty@tty1.service/star
[  115.524325] systemctl[1011]: t is destructive (systemd-poweroff.service has 'start' job queued, but 'stop' is included in transaction).
[  115.525067] systemctl[1011]: Failed to start getty@tty1.service: Transaction for getty@tty1.service/start is destructive (systemd-poweroff.service has 'start' job queued, but 'stop' is included in transaction).
```
Instead we should just have both …

Simplify systemd configuration for console-conf

---

doc/.wordlist.txt
doc/howto/autoinstall-validation.rst
doc/howto/index.rst
doc/reference/autoinstall-reference.rst
doc/reference/autoinstall-schema.rst
doc/tutorial/providing-autoinstall.rst
scripts/runtests.sh
scripts/validate-autoinstall-user-data.py

./scripts/validate-autoinstall-user-data is used by the integration tests to verify the written user data is correct, but we can additionally advertise this script as something for users to pre-validate their autoinstall data. 
Changes include some refactoring and trying to catch some likely common mistakes.
Todo:
- ~~[ ] Tests~~

Update validate-autoinstall-user-data script

---

setup.py
snapcraft.yaml
subiquity/cloudinit.py
subiquity/server/server.py
subiquity/tests/test_cloudinit.py
subiquitycore/tests/test_utils.py
subiquitycore/utils.py
system_scripts/subiquity-legacy-cloud-init-extract

~~Requires #2026. New changes for this PR are the last four commits.~~ #2026 now part of main. All commits are for this PR.
I pulled out the `stages.Init()` path from the server code and moved it to a helper script in system_scripts. The idea is that we can call this script and parse the output from it for the same information. It currently prints yaml to stdout, which seems robust enough for the kind of data it returns.
I tested this with the Focal release ISO, the 20.04.1 ISO, and the 22.04.1 ISO, all of which would rely on this code path. I tested by:
- passing no cloud-config
- passing cloud-config with autoinstall
- passing cloud-config without autoinstall
- ensuring the ssh login information was correct on the help screen
All scenarios worked as expected.

Refactor stages.Init() code path

---

scripts/test-in-lxd.sh

I can never remember what arguments test-in-lxd takes. Make it display an usage when called without arguments.

test-in-lxd: add usage when not enough args are supplied

---

console_conf/ui/views/chooser.py
subiquity/ui/views/error.py
subiquity/ui/views/filesystem/compound.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/ssh.py
subiquity/ui/views/zdev.py
subiquitycore/controllers/network.py
subiquitycore/ui/actionmenu.py
subiquitycore/ui/container.py
subiquitycore/ui/selector.py
subiquitycore/ui/views/network.py

On oracular, this PR makes `make unit` produce 59 warnings instead of 146. The remaining warnings (emitted multiple times) are:
*  DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
*  /usr/lib/python3/dist-packages/bson/__init__.py:116: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
-> should be addressed with https://launchpad.net/ubuntu/+source/pymongo/4.7.3-1 (won't be addressed for core24 probably though)
*   /usr/lib/python3/dist-packages/cloudinit/config/schema.py:554: DeprecationWarning: Passing a schema to Validator.iter_errors is deprecated and will be removed in a …

Fix some deprecation warnings on core24

---

subiquity/server/apt.py

`setup_overlay()` expects a list of lower directories. That said, we have one invocation in dry-run mode where we pass it a path (which is a string) directly instead of wrapping the path in a list with one element.
The dry-run implementation of `setup_overlay()` accesses the first element of the list using `lowers[0]`, and expects a path out of it. But when `lowers` is a string, `lowers[0]` returns the first character of string, which usually is `"/"` and therefore corresponds to a valid path.
It makes the code accidentally work, but use a path that is not the one we expected.

apt: fix invocation of setup_overlay in dry-run mode

---

bin/subiquity-server
bin/subiquity-service
scripts/management-script
snap/hooks/configure
snapcraft.yaml
subiquity/cmd/server.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Subiquity now supports two new options:
* `--no-block-probing-timeout` to disable the block-probing timeout completely
* `--block-probing-timeout <seconds>` to set the timeout to a specific value
In addition, we now make the subiquity snap configurable so that this CLI options can be used without modifying the snap.
To disable the timeout:
```bash
snap set subiquity block-probing-timeout=no
```
To set the timeout to a different value:
```bash
snap set subiquity block-probing-timeout=180
```
To reset the timeout to the default value:
```bash
snap unset subiquity block-probing-timeout
```
Based on the current snap configuration, the wrapper script (e.g., bin/subiquity-server) will invoke subiquity either with the `--no-block-probing-timeout` option, the `--block-probing-timeout <seconds>` …

Add way for users to configure block-probing timeout

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Checking for known-good firmware models/versions is one way to determine if the system supports NVMe/TCP booting. That said, if a NBFT is present on the system, it is a much stronger hint that NVMe/TCP booting will be possible.
We can't completely replace the mechanism because sometimes, the NBFT will not be there during installation ; even though the system can boot using NVMe/TCP.

In the presence of a NBFT, assume the firmware supports NVMe/TCP booting

---

subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/install.py
subiquity/server/controllers/tests/test_filesystem.py

storage: export zpools unconditionally
In the _pre_shutdown function, we used to invoke `zpool export -a` if we found the presence of a zpool in the storage model.
That being said, zpools can be implicitly declared by users using {"type": "format", "fstype": "zfsroot"} in the curtin actions. This is valid curtin configuration and unfortunately causes Subiquity to think that there is no zpool.
When that happened, Subiquity did not invoke `zpool export -a` and therefore the target system couldn't boot without a call to `zpool import -f`.
We now do the call to `zpool export -a` unconditionally. Running this command when there is no zpool is a noop so it should not be a problem.
In theory there is a risk that we could export a zpool that was not meant for exporting. However, that would …

Unconditionally run `zpool export -a` / revert systemd-shutdown implementation

---

doc/.custom_wordlist.txt
doc/reference/ubuntu-image.rst

Follow up to #1929. Minor fixes, updates, and additions to the `ubuntu-image` reference doc.

ubuntu-image docs fixes & updates

---

doc/.sphinx/requirements.txt
doc/custom_conf.py

Quick update:
- Change to `canonical-sphinx-extensions` (new name); also allows latest Sphinx to be used.
- Update intersphinx URL for cloud-init docs.

docs: Update Sphinx extensions and RTD config.

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

We recently made the call to `zpool export -a` unconditional to account for "advanced" autoinstall scenarios. However, the zpool command is not always present in the live installer environment ; and it results in a Subiquity crash if the command fails to execute. Today, zpool (provided by zfsutils-linux) is dynamically installed in the live environment by curtin when it handles a ZFS installation.
Let's make sure we don't crash if zpool is not available when shutting down. It just means we're not using ZFS.

Only execute `zpool export -a` if zpool is available

---

scripts/kvm-test.py

Ensure that the disks used for installation are passed to kvm first and not the disk with cloud-config/autoinstall data. Sometimes curtin will put paths to disk in the fstab like:
/dev/disk/by-path/pci-000n-xxxx/by-uuid/UUID
and when we reboot without the cloud-config disk the path to the install disk will change since the number of pci devices connected to the machine has technically changed. We can make this a little more stable by letting the cloud-config drive be the last drive attached.

kvm-test: set cloud-config disk after real disks

---

subiquity/ui/views/installprogress.py
subiquity/ui/views/tests/test_installprogress.py

The ProgressView.other_event function splits messages on the ":" character to get the context type and the message from journal messages. This code will crash if the message has more than one ":" character. When passing cloud-config with invalid top level keys, subiquity will check these keys and report on the journal with a message: "cloud-init schema validation failure for: <key1> [, <key2>, ...]", which was causing the UI to crash repeatedly.
[LP: #2080918](https://pad.lv/2080918)

ui: fix journal parsing in ProgressView

---

setup.py
snapcraft.yaml
subiquity/cloudinit.py
subiquity/cmd/server.py
subiquity/models/subiquity.py
subiquity/models/tests/test_subiquity.py
subiquity/server/controllers/tests/test_userdata.py
subiquity/server/server.py
subiquity/server/tests/test_server.py
subiquity/tests/test_cloudinit.py
system_scripts/subiquity-legacy-cloud-init-validate

Slightly more changes for one PR than I'd like but everything sort of fell together:
- Extract cloud-init schema validation to a new system_script `subiquity-legacy-cloud-init-validate`. This is called "legacy" because, in the future, we likely want to rely on the cloud-init CLI directly to do schema validation, but there isn't a pressing need to rely on it now. For now, all releases will rely on the "legacy" script.
- Rename the old `validate_cloud_init_schema` function to `validate_cloud_init_top_level_keys` (along with some other function and type renaming). The function wasn't really validating the whole cloud-init schema. It's really just parsing the output for any top-level keys that failed to validate. 
- Skip the top-level key validation during autoinstall extraction in …

Replace cloud-init validation with external script

---

snapcraft.yaml

Requires #2079. With those changes, we can safely unstage cloud-init from the snap. I ran test installs on jammy, focal, noble, and oracular injected with a snap with #2079's changes, as well as unstaging cloud-init, and ran into no problems.

snapcraft.yaml: unstage cloud-init

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Autoinstall directives allow to specify match directives when using guided `use_gap` mode:
```yaml
storage:
layout:
name: direct
mode: use_gap
match:
install-media: true
```
However, match directives are currently ignored ; unlike when using the `reformat_disk` mode.
Make sure they are honored.
LP:#2080608

Honor match directives when installing in a gap using layout.mode: use_gap

---

snapcraft.yaml
subiquity/models/kernel.py
subiquity/models/tests/test_kernel.py

Incorporate changes from https://code.launchpad.net/~dbungert/curtin/+git/curtin/+merge/473473

kernel: migrate to `remove: existing`

---

snapcraft.yaml

This is to pick up the change from https://code.launchpad.net/~ogayot/curtin/+git/curtin/+merge/473058 , fixing two bugs:
* dracut was getting removed when installing the kernel
* a call to update-initramfs was attempted even if initramfs-tools was replaced with dracut
~~However, as it stands currently, it also brings in the kernel's `remove_existing` vs `remove: existing` change (but only the curtin side of the change). Therefore, this PR depends on #2086 ; and I'm marking it as a draft. I'll rebase once the other PR is merged.~~ [EDIT: rebased on top of main]
LP:#2073125

snapcraft: rev to fix dracut removal and call to missing update-initramfs

---

.github/workflows/snap.yaml
snapcraft.yaml

This is to pick up this fix:
canonical/curtin@cf66592a13481c3109f357891be09a2dbaf4830c ([curtin MP](https://code.launchpad.net/~ogayot/curtin/+git/curtin/+merge/473583)) to address LP:#2081256
Also includes a fix for the CI issue.

snapcraft: rev curtin to ignore new by-path/.../by-uuid entries

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

In https://github.com/canonical/subiquity/pull/2031, I added code to ensure that we only suggest "use-gap" scenarios if we have enough room for primary partitions.
This is basically a follow-up where we do the same for "target-resize" scenarios.
Same as in the other PR, there are some limitations:
* recovery partition is not accounted for
* only the requirements for the DIRECT capability are accounted for.
LP:#2081724

Don't suggest target-resize scenarios if we don't have room for partitions

---

subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/tests/test_gaps.py

The parts_and_gaps function returned no partition nor gap when the disk itself has (or had) a file-system signature. This is to make sure we don't partition a disk that is already used unpartioned.
However, when we are operating on an existing partition of a disk, we should not pretend that the underlying disk has no partition ; even if the disk itself has a FS signature. This leads to a common issue when doing GuidedTargetReformat:
```python
File "subiquity/common/api/server.py", line 164, in handler
File "subiquity/server/controllers/filesystem.py", line 1184, in v2_guided_POST
await self.guided(data)
File "subiquity/server/controllers/filesystem.py", line 726, in guided
gap = self.start_guided(choice.target, disk) …
```

storage: when handling a partition, ignore any FS at the disk level

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

When reformatting a disk that has in-use (i.e., mounted) partitions, we do a "partial" reformat, which means we attempt to delete all the partitions that are *not* in use.
Unfortunately, the implementation was not correct. While iterating over the partitions, calling delete_partition affects the iterator. As a consequence, some partitions that should have been removed end up preserved.
Fixed by iterating over a copy of the container.
LP:#2083322

storage: fix partial reformat not removing all candidate partitions

---

doc/.custom_wordlist.txt
doc/.wordlist.txt

The intention of .wordlist.txt is to match the general wordlist, so make future merges easier by moving custom words to the intended custom_wordlist location.

doc: move custom words to custom_wordlist

---

subiquity/server/controllers/filesystem.py

It seems that we have a strange behavior when
/storage/v2/add_boot_partition is called on a disk different from the disk partitioned for installation. However, we did not log the disk ID so post-mortem analysis is very hard.

storage: log disk-id in POST /storage/v2/add_boot_partition

---

subiquity/server/controllers/filesystem.py

It seems that we have a strange behavior when
/storage/v2/add_boot_partition is called on a disk different from the disk partitioned for installation. However, we did not log the disk ID so post-mortem analysis is very hard.
(cherry picked from commit de5356b15247cebe142e4179aa1a41a941b8b6b2)
CC: @d-loose

Oracular / storage: log disk-id in POST /storage/v2/add_boot_partition

---

doc/custom_conf.py
doc/reference/autoinstall-reference.rst

Update the place holder text in the `kernel-crash-dumps` configuration reference section to link to the kernel crash dumps section of the ubuntu server documentation.

Update kdump cross reference

---

examples/answers/bridge.yaml
examples/sources/bridge.yaml
scripts/runtests.sh
subiquity/models/filesystem.py
subiquity/models/source.py
subiquity/models/tests/test_source.py
subiquity/server/controllers/drivers.py
subiquity/server/controllers/install.py
subiquity/server/controllers/kernel.py
subiquity/server/controllers/source.py
subiquity/server/controllers/tests/test_kernel.py
subiquity/server/types.py

This needs a lot more commentary and tests but its the end of my week and I think the logic is basically correct and I welcome any comments you have before I get back to it on Monday.

support falling back to a bridge kernel

---

doc/.custom_wordlist.txt
doc/custom_conf.py
doc/howto/index.rst
doc/howto/ubuntu-image-classic-examples.rst

A how-to article with examples of `ubuntu-image` use.
Fixes [FR-6785](https://warthogs.atlassian.net/browse/FR-6785)
[FR-6785]: https://warthogs.atlassian.net/browse/FR-6785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add CLI examples for ubuntu-image

---

scripts/kvm-test.py

When running `kvm-test` with `--install`, we currently have two options related to the target disk:
* Abort if the target already exists, This is the default behavior.
* If the `--overwrite` option (or `-o`) is passed, we instead recreate the target image from scratch.
This makes us unable to supply an already partitioned disk to kvm-test, which is a bit of a shame considering the use-cases we have currently.
This change adds 3 new options (well, only one is truly new):
* `--preserve-target` which is an explicit way to abort if the target image already exists (this is the default behavior)
* `--recreate-target` which mimics what `-o` / `--overwrite` does.
* `--reuse-target` which is the new one. When the option is supplied, we will reuse the disk without recreating it (if it already …

kvm-test: add the option to "overwrite" an existing installation without recreating the disk from scratch

---

subiquity/cloudinit.py
subiquity/tests/test_cloudinit.py

In the future, cloud-init will be available in a more minimal
`cloud-init-base` package, which is expected to provide the
functionality we expect.  Version check that one, if present, along with
the existing `cloud-init` package.

cloud-init: check for cloud-init-base package also

---

snapcraft.yaml

Subiquity relies on the more_itertools Python module. However, python3-more-itertools was not listed as a staged package in snnapcraft.yaml.
When running Subiquity on core24, this leads to a ModuleNotFoundError. For earlier core versions, python3-more-itertools was pulled as a transitive dependency so it was working ok.

snapcraft: explicitly pull python3-more-itertools for core24

---

apt-deps.txt
snapcraft.yaml
subiquitycore/tests/test_utils.py
subiquitycore/utils.py

~~In python3.13, the crypt submodule will be removed from the standard library. This won't affect snap builds until core26, but makes dryrun testing difficult. This PR introduces some logic to shell out to perl to compute the hash in dry-run mode only.~~
Replace `crypt` module usage with the `passlib` module, which is provided by the  `python3-passlib` package. The package is already in Main and doesn't appear to have any open CVEs. This will fix the issue when trying to import the `crypt` module in python3.13 or later, where it was finally removed.

Replace crypt module with passlib

---

scripts/kvm-test.py

Follow up to #2108 to also replace the usage of `crypt` in kvm-test with `passlib`.
This means kvm-test will require the `python3-passlib` package. I omitted the changes to `apt-deps.txt` in this PR since we'll take care of that in the other one.

kvm-test: replace crypt with passlib

---

scripts/kvm-test.py

kvm-test now supports `--disk-interface scsi-multipath` ; which basically creates two paths to a single disk image. When booting the installer, multipathd is expected to react accordingly and we should expect a `/dev/mapper/mpatha` device.
Tooling would be good to test scenarios where we have problems with multipath but it is already a start.
NOTE: the `boot` function does not currently honor the `--disk-interface` option (nor the `--no-disk` option). It probably should but I didn't want to fix it as part of this PR.

Add kvm-test support for multipath drives

---

bin/console-conf-check-error
bin/console-conf-wrapper
debian/console-conf-serial.conf
debian/console-conf.conf
debian/console-conf.console-conf@.service
debian/console-conf.install
debian/console-conf.serial-console-conf@.service
debian/rules
setup.py

When a password for a user is set, then we should use getty rather than console-conf. Unit conditions did not work along conflicts, because conflicts are resolved during loading of systemd, and conditions are resolved right before executing the unit.
Instead we always use console-conf. If we find that we should have switched to getty, then we return a special value that is marked as not restarting (we always restart otherwise). An ExecStopPost also matches that exit status to start getty (the default job mode is "replace", which means the conflict will also kick console-conf out).

Fix switching back from console-conf to getty

---

debian/console-conf.console-conf@.service

Something got lost in patch #2111. This fixes starting login on VT when console-conf got disabled.

console-conf@.service: Remove left over conditions

---

scripts/mirror-checker.py

Introduce a small script to generate a schroot for testing country mirror health. I generally found this approach just as reliable to reproduce mirror issues and has been faster than firing up a whole VM to test.

scripts: mirror-checker

---

scripts/mount-layered-fs

Add a helper script to mount a layered squashfs, as is used on the Ubuntu ISOs.

scripts: add mount-layered-fs

---

apt-deps.txt
scripts/mirror-checker.py

An update to the mirror checker script to add a command for checking all of the country mirrors. The `check-all` command takes all known country codes and then calculates the actual mirrors to test based on DNS records. The script will print out the DNS information for each attempted mirror (i.e., `cc.archive.ubuntu.com`), the calculated real mirrors, and a table with the status of each mirror. It will also save the results of each mirror check in the single mirror check mode style (which is now available under the `check` command), which can be specified with the `-o` flag.
By default it will omit reporting information about mirrors which don't exist (i.e., fallback to `archive.ubuntu.com`) but can be instructed to provide it with the `--all` flag.  
Some examples of the output: …

scripts: mirror-checker check all mirrors

---

doc/reference/autoinstall-reference.rst

This bug was reported at:
https://bugs.launchpad.net/subiquity/+bug/2088366

doc: fix use of "flavour" (GB spelling) in examples instead of "flavor"

---

subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/tests/test_gaps.py
subiquity/common/types/storage.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Steps to try with the TUI + curl:
1. apply this patch
```diff
diff --git a/Makefile b/Makefile
index 87e666ab..5bb0e0de 100644
--- a/Makefile
+++ b/Makefile
@@ -6,9 +6,9 @@ PYTHONSRC=$(NAME)
PYTHONPATH=$(shell pwd):$(shell pwd)/probert:$(shell pwd)/curtin
PROBERTDIR=./probert
PROBERT_REPO=https://github.com/canonical/probert
-DRYRUN?=--dry-run --bootloader uefi --machine-config examples/machines/simple.json \
+DRYRUN?=--dry-run --bootloader uefi --machine-config examples/machines/threebuntu-on-msdos.json \
--source-catalog examples/sources/install.yaml \
-       --postinst-hooks-dir examples/postinst.d/
+       --postinst-hooks-dir examples/postinst.d/ --storage-version=2
export PYTHONPATH
CWD := $(shell pwd)
```
2. run `make dryrun`
3. navigate to the guided screen
4. list the guided …

Add "Erase and Install" support

---

Makefile
subiquity/client/controllers/filesystem.py
subiquity/cmd/tui.py
subiquity/ui/views/filesystem/guided.py

The TUI gained a new CLI option (i.e., --debug-sv2-guided) causing the normal guided storage view to be replaced by a debugging view.
The debugging view is blunt but offers at least some support for all v2 guided scenarios (target reformat, use_gap, resize, erase & install, ...) which the normal view lacks support for.
The list of scenarios is taken straight from what the API returns. There is no filtering (capabilities are basically ignored) and currently no customization is possible (e.g., resizing always takes the recommended size).
Nevertheless, this new view could be very helpful to reproduce storage bugs that occurred on the desktop installer.
Also, the makefile now has a `dryrun-debug-sv2` target that runs subiquity in dry-run mode with the relevant options to make the new …

storage: add debugging TUI view to debug storage v2 guided scenarios

---

subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/tests/test_gaps.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

A bunch of bug fixes for noble in no particular order. There are a few cosmetic patches in the batch.
* Arbitrary disk selection more consistent
* originally part of https://github.com/canonical/subiquity/pull/2050
* LP:#2080608 Honor matches in use-gap autoinstall mode
* originally part of https://github.com/canonical/subiquity/pull/2083
* LP:#2081738 Fix crash when formatting a disk that has partitions + a filesystem signature
* originally part of https://github.com/canonical/subiquity/pull/2092
* LP:#2081724 Don't suggest target-resize if there is no more room for primary partitions
* originally part of #2090

Noble merge 2025 01 08

---

scripts/kvm-test.py

Several fixes to swtpm integration allowing TPMFDE test automation, including having TPM state persist across VM boots, allowing multiple VMs with TPM to run in parallel, and an apparmor integration workaround.
Sample command line
```
./scripts/kvm-test.py -r24.04.1-desktop --install -o -b --boot --profile desktop --with-tpm2
```

Kvm test swtpm

---

subiquity/server/controllers/tests/test_identity.py
subiquity/server/controllers/tests/test_userdata.py

A couple of small fixes to some test code:
- Remove an unnecessary usage of the SoureController in the IdentityController tests
- Update the UserdataController tests so they are testing the expected behavior. Default usage of a mock object for the `base_app` attribute was hiding a failing test.

Small test cleanup for Identity and Userdata controllers

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

If os-prober reports that Ubuntu is installed on e.g., sda4 (i.e., partition 4 of disk sda), then we should make that info available in the API.
However, if we remove sda4 and then create another partition with number 4, we should not assume that it contains anything of value.
This is only a partial fix for LP:#2091172
One easy way to recreate the situation is to use threebuntu-on-msdos.json and then:
* run `make dryrun-debug-sv2`
* navigate to the partitioning screen and select "Install to disk-sda after wiping it"
* in another terminal, query /storage/v2 and look at the result. Before the patch it would show that the newly created ESP has an OS installed:
```json
"partitions": [
{
"size": 1127219200,
"number": 1,
"preserve": false,
"wipe": "superblock",
"annotations": [
"new",
"primary …
```

Only associate os information to existing partitions

---

examples/answers/core-desktop.yaml
subiquity/client/client.py
subiquity/client/controllers/source.py
subiquity/client/controllers/tests/test_source.py
subiquity/client/tests/test_client.py
subiquity/server/server.py
subiquity/tests/api/test_api.py

Part 2 of 2 for adding support for a "core" variant from #2127. 
This PR:
- Adds "core" as a supported variant in the server.
- Registers a list of controllers (and therefore, screens) to use for the "core" variant in the TUI (Language/Welcome, Keyboard, Refresh, Network, Disk).
- Adds some logic to the client's `SourceController` to auto-configure this section if (1) there is only one source to choose from **and** (2) that source type doesn't have the option of installing drivers, thus skipping this screen since there aren't really any questions to ask. 
- Removes some sections from the ubuntu-core answers tests since it had information about additional screens in it. If these screens come up, we want it to block and fail the test.

 Introduce support for "core" variant in TUI

---

subiquity/server/controller.py
subiquity/server/controllers/source.py
subiquity/server/controllers/tests/test_source.py
subiquity/server/server.py
subiquity/server/tests/test_controller.py
subiquity/server/tests/test_server.py
subiquity/tests/api/test_api.py

Part 1 of 2 for adding support for a "core" variant from #2127.
This PR introduces 1 behavior change and 1 bug fix surrounding variant handling, and 1 function signature fix for a semi-related function in the `SubiquityController` class.
- Behavior change: On startup, the server's variant will be set to the variant of the selected source in the catalog. Previously, the source controller would pick the first entry in the source catalog but not update the variant for the server. 
- Bug fix: Fixes a bug where configuring the source controller only updates the SubiquitModel (`app.base_model`) and not the server's notion of the variant (`app.variant`). Now selecting a new source will update both.
- Minor fix: Update `SubiquityController.interactive` to return `False` instead of `None` for …

Update variant handling in SubiquityServer

---

subiquity/models/filesystem.py

If the installation media is a RAID (this is a mostly a OEM use-case), using `{"install-media": true}` as a disk matcher fails to find the expected RAID device.
This is because in the previous implementation, only `Disk` objects could have `_has_in_use_partitions=True`.
We now also set `_has_in_use_partitions=True` on involved `Raid` objects.
In theory, this means that for a given RAID, the matcher can return one `Raid` object + N * `Disk` objects.
In practice though, we only use disk matchers on "potential boot disks". This should exclude from the equation `Disk` objects that are part of a `Raid`. So we can reliably expect a single match.
LP:#2094966

storage: also allow raid devices to match install-media: true

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

If there are at least two disks and one of them is missing any metadata used
during sorting installer will crash. Issue can be reproduced using already
available machine .json file: examples/machines/existing-partitions.json
in which /dev/vda does not have serial value.
This patch makes sure that all values used in sorting are initialized
2025-01-21 15:41:33,340 ERROR root:38 finish: subiquity/apply_autoinstall_config: FAIL: '<' not supported between instances of 'str' and 'NoneType'
2025-01-21 15:41:33,340 ERROR subiquity.server.server:503 top level error
File "/home/rmalz/repos/subiquity/subiquity/server/server.py", line 1021, in start
await self.apply_autoinstall_config()
File "/home/rmalz/repos/subiquity/subiquitycore/context.py", line 165, in …

filesystem: handle sorting disks without required metadata

---

subiquity/common/filesystem/manipulator.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

This is another option to address the issue with partition renumbering. Instead of completely hiding a erase-and-install scenario just because renumbering is a problem, we disable it for erase-and-install scenarios only.
The (possibly weak) assumption is that because we are erasing one partition and installing a new system **at the same place**, we will never end up with less logical partitions that we had before (and therefore we can avoid renumbering).
This makes it possible to do erase-and-install on a logical partition that is not at the end (e.g., p5 on threebuntu-on-msdos.json).

Erase install - disable renumbering instead of excluding scenarios

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

* cherry-picked fbf6de2 from #2143

noble - filesystem: handle sorting disks without required metadata

---

subiquity/server/controllers/kernel.py
subiquity/server/controllers/tests/test_kernel.py

Fix an install hang that is reproducible today on main branch (oracular and earlier not affected) when supplying a kernel to install via autoinstall.

kernel: fix install hang with autoinstall + kernel

---

bin/console-conf-check-error
debian/console-conf.console-conf@.service
debian/console-conf.serial-console-conf@.service

Upstreaming of https://github.com/canonical/core-base/pull/296
This does not affect behavior apart from systemctl not showing the service in red.

console-conf@.service: do not exit as error when preventing restart

---

subiquity/models/source.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/source.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapd/system_getter.py
subiquitycore/async_helpers.py
subiquitycore/tests/test_async_helpers.py

**Initial problem** 
The `SystemGetter.get` method essentially does 3 important things:
* it mounts stuff in `/var/lib/snapd/seed`
* it queries snapd (and expect it to read contents from `/var/lib/snapd/seed`)
* it then tries to cleanup by unmounting what it previously mounted
Unfortunately, if we cancel this task in the middle, especially while it is querying snapd, the cleanup code will fail to unmount things because snapd is still using `/var/lib/snapd/seed` (cancelling the query does not mean that snapd will immediately release the resources - or even stop processing the query). Typically this results in a failure to unmount pc-kernel.snap with EBUSY.
```
umount: /var/lib/snapd/seed/snaps/pc-kernel_2010.snap: target is busy.
```
Effectively, if `SystemGetter.get` gets cancelled, we …

Fix the pc-kernel issue

---

doc/howto/configure-storage.rst
doc/index.rst
doc/tutorial/providing-autoinstall.rst
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/mounter.py

* cherry-pick 97c5990c88bd86cc3582e79f6ef4380b5177ab30 from https://github.com/canonical/subiquity/pull/2046
* only affects dry-run
* cherry-pick 133dcc7 from https://github.com/canonical/subiquity/pull/2138
* Fix for LP:#2095159
* cherry-pick 07fb317..7c0037c from https://github.com/canonical/subiquity/pull/2135
* Partial fix for LP:#2091172
* cherry-pick 26e0bfd590528a585b1468e2b2cb2a34e6324eb5 from https://github.com/canonical/subiquity/pull/2094
* Fix for LP:#2083322
* cherry-pick 29064316230fe880594a3bc258360b451507c911 from #2077
* Fix for LP:#2073772
* also cherry-pick 7a020ff88bf93c6d194a8b932797960259c99fb6 from #2080 to address a regression in the previous fix.
* cherry-pick ad92d7aa54640bb03eb3680db53cfb148f655fc4 from #2118 
* cherry-pick …

Noble merge 2025 01 27

---

subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/tests/test_manipulator.py

If we are wiping a partition, don't bother checking if the filesystem that was on it supports resizing. The filesystem is going to be erased anyway. The new filesystem (if any) will be created using mkfs.* so there is no need for resize support.
LP:#2096799

storage: always accept to resize a partition that is being wiped

---

subiquity/server/controllers/tests/test_filesystem.py

test_guided_zfs_luks_keystore() causes a file named zpool-key-foo to be created, clean that up.

storage: fix zpool-key-foo cruft from unit tests

---

doc/.custom_wordlist.txt
doc/reference/autoinstall-reference.rst
subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/tests/test_manipulator.py
subiquity/common/types/storage.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/ui/views/filesystem/delete.py

When reformatting a disk using the following call:
```python
manipulator.reformat(disk, ptable="something")
```
The ptable parameter would only appear to be honored if the disk did not contain any partition. This happened because the `reformat()` function sets the ptable of the disk first and then starts removing partitions using `delete_partition()` in a loop.
However, `delete_partition()` has a mechanism to reset the partition table to `None` when it is invoked on the last partition of a disk.
Therefore, the disk ended up with `None` as the partition table (ignoring the ptable value) if the disk contained any partition.
Fixed by moving the assignment of `disk.ptable` after removing partitions. Arguably, it is a mistake to change the partition table value before removing the partitions …

storage: fix use of ptable parameter when calling reformat

---

subiquity/common/filesystem/actions.py
subiquity/common/filesystem/boot.py
subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/labels.py
subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/tests/test_gaps.py
subiquity/common/filesystem/tests/test_labels.py
subiquity/common/filesystem/tests/test_manipulator.py
subiquity/common/types/storage.py
subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

This PR allows Subiquity to work with partition tables that are marked "unsupported". In the presence of such disk, Subiquity used to crash, either in the UI, or when generating guided scenarios.
**TODO**
Locally, I have been using probe-data from LP:#2065516 but it requires curtin patches to mark the ptable from the dynamic disk as "unsupported". Otherwise, it still crashes. See https://code.launchpad.net/~ogayot/curtin/+git/curtin/+merge/480694
Disks that have an unsupported partition table will now be marked `"requires_reformat": true` in the /storage/v2 endpoint:
```json
"disks": [
{
"id": "disk-sda",
"label": "TOSHIBA_HDWD110_999E6AZFS",
"type": "local disk",
"size": 1000204886016,
"usage_labels": [
"unsupported partition table"
],
"partitions": [
[...]
]
"ptable": "unsupported", …
```

Don't crash and allow reformat of a disk with unsupported partition table

---

scripts/kvm-test.py

If the guest supports it (plucky does but noble does not), we can simulate IMSM RAID devices by using one (or more) SCSI disks.
In the guest, you can create an IMSM RAID 0 using:
```bash
IMSM_NO_PLATFORM=1 mdadm --create /dev/md/imsm0 -n 1 --metadata=imsm /dev/sda
IMSM_NO_PLATFORM=1 mdadm --create /dev/md/raid0_1 -n 1 --level 0 /dev/md/imsm0
```
We already supported SCSI disks but only for multipathing.
RAID 1 is also possible but we need to add support for multiple disks (see https://github.com/canonical/subiquity/pull/1523)
```bash
IMSM_NO_PLATFORM=1 mdadm --create /dev/md/imsm0 -n 2 --metadata=imsm /dev/sda /dev/sdb
IMSM_NO_PLATFORM=1 mdadm --create /dev/md/raid1_1 -n 2 --level 1 /dev/md/imsm0
```

kvm-test: add support for SCSI disk without multipathing (useful for IMSM)

---

subiquitycore/ui/container.py

urwid added support in Pile() objects for widgets with fixed sizing. However, this caused big performance issues for us. Going up and down in the the guided storage screen is > 30 times slower now.
Maybe there is something smart to do ; but in the meantime, let's "revert" the upstream urwid change in our own Pile() implementation.
LP:#2089681
https://github.com/urwid/urwid/pull/733

pile: work around perf regression when moving to urwid from core24

---

snapcraft.yaml

* canonical/curtin@05217835 Merge remote-tracking branch 'ogayot/raid+multipath-drop-legacy'
* canonical/curtin@d7160fab Merge remote-tracking branch 'ogayot/raid+ptable'
* canonical/curtin@5c54e88e storage-config: parse ptable field for RAID if specified
* canonical/curtin@ee2d6f67 storage-config: factorize detection of the partition layout
* canonical/curtin@5dfa84cf block: drop legacy multipath detection mechanism
* canonical/curtin@c54851d4 storage_config.py: fix missing uuid entry for RAID partitions

snapcraft: bump curtin revision to pickup RAID fixes

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/install.py
subiquity/server/controllers/tests/test_install.py
subiquity/server/snapd/types.py

~~Prerequisite PR: https://github.com/canonical/subiquity/pull/2166~~
install: handle nvidia driver version != component version
Often (always?) the `ubuntu-drivers list --recommended` version is going
to be newer than what's actually available as a pc-kernel component.
Handle that version mismatch.

components: fix version matching

---

snapcraft.yaml
subiquity/common/filesystem/labels.py
subiquity/common/filesystem/tests/test_labels.py
subiquity/common/types/storage.py
subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/tests/api/test_api.py

This leans on https://code.launchpad.net/~ogayot/curtin/+git/curtin/+merge/481790 which has been merged.
* Partition(number=1, name=None)
* Partition(number=2, name="Microsoft Reserved Partition")
```
GET /storage/v2
[...]
{
[...]
"number": 1,
"name": "Basic data partition",
"$type": "Partition"
},
{
[...]
"number": 2,
"name": "Microsoft Reserved Partition",
"$type": "Partition"
},
```
This is a read-only property, the API will reject modifications of the partition name:
```
POST /storage/v2/edit_partition
> {..., "partition": {"number": 1, ...}}
```
-> OK (not trying to change the name)
<br>
```    
POST /storage/v2/edit_partition
> {..., "partition": {"number": 2, ...}}
```
-> OK (not trying to change the name)
<br>
```
POST /storage/v2/edit_partition
> {..., "partition": {"number": 1, …
```

Add read-only access to GPT partition name to /storage/v2 API

---

snapcraft.yaml

Curtin now requires python3-packaging to be installed to work properly. See https://code.launchpad.net/~sjg1/curtin/+git/curtin/+merge/480712
Add that package to the snap.

snapcraft: add python3-packaging in the snap to satisfy curtin

---

snapcraft.yaml

Full commit log:
* canonical/curtin@b6eb1113 nvme-o-tcp: add function to adapt netplan config for dracut
* canonical/curtin@161d1767 nvme-o-tcp: add function to iterate over NVME TCP controllers
* canonical/curtin@4a0f9568 block: fix string interpolation when building RuntimeError

snapcraft: bump curtin revision for nvme-o-tcp fix (netplan + dracut)

---

subiquity/common/types/storage.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapd/types.py

* Pass pin / passphrase info along, if supplied in GuidedChoiceV2.
* Fix pin / passphrase validation, which should consider both CORE_BOOT_{,PREFER_}ENCRYPTED.
* Fix use_tpm check to also consider both CORE_BOOT_{,PREFER_}ENCRYPTED.

pin/pass: volume auth, plus capability related fixes

---

examples/autoinstall/core-installer.yaml
examples/snaps/v2-systems-ubuntu-core-24-amd64.json
examples/snaps/v2-systems.json
examples/sources/core-installer.yaml
scripts/runtests.sh
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapd/types.py

The snapd API expects that by specifying a value for `optional_install` on a request to `/v2/systems/` you only want those items installed. Existing logic to support only installing particular components meant that no optional snaps were installed. Update the logic in `finish_install` to always install all of the optional snaps available for the model.
I found the behavior surrounding `optional_install` on the snapd API a little confusing so I added some extra comments surrounding the type definitions in subiquity to document the expected behavior.

filesystem: install all optional snaps

---

snapcraft.yaml

snapcraft: rev curtin for kernel postinstall handling
canonical/curtin@ce8d0666 curthooks: reconfigure kernel after initrd generated
canonical/curtin@1343ac92 curthooks: move zipl invocation after update-initramfs
canonical/curtin@ab45bb24 curthooks: minor extlinux test cleanup prior to zipl mocking
canonical/curtin@1667812b unittests: remove usage of imp module

snapcraft: rev curtin for kernel postinstall handling

---

subiquity/server/server.py
subiquity/server/snapd/api.py

If `subiquity-log-snapd` is found on the kernel command line, log snapd responses to /tmp.  Off by default.

Log snapd responses

---

snapcraft.yaml
subiquity/cmd/server.py
subiquitycore/controllers/network.py
subiquitycore/prober.py
subiquitycore/ssh.py

Since the desktop installer does not rely on the WLAN listener, we expect the ubuntu-desktop-bootstrap snap to run subiquity with `--no-wlan-listener` (CC: @d-loose).
This should be a good way to avoid running into Python crashes, such as LP:#2071620 until we get them addressed.

Add CL arg to disable the WLAN listener

---

subiquity/server/controllers/tests/test_zdev.py
subiquity/server/controllers/zdev.py

During real installs on s390x, passing a `zdevs` autoinstall section with content leads to the following error:
`ZdevController' object has no attribute 'zdevinfos'`
This happens because the `zdevinfos` variable is only defined when running in dry-run mode, but the tests did not catch that.
The variable is now renamed `dr_zdevinfos` (dr stands for "dry-run") to make it more obvious.
When the list of `zdevinfos` is needed, we now call `lszdev` to populate it. On some hardware, calling `lszdev` takes seconds so we do not invoke it in the initializer of the controller. Instead we delay its use until we know for sure we need it.
We also use an `async` version of `lszdev` so that we don't block the whole event loop when it is running.
LP:#2104267

Fix crash for automated installs with zdevs

---

snapcraft.yaml

Full commit log:
* canonical/probert@2e5ec81 Merge pull request canonical/probert#156 from ogayot/fix-warnings
* canonical/probert@8f4853a _rtnetlinkmodule: fix warnings when converting between pointer types
* canonical/probert@2ba8f37 _nl80211: fix warning for signed / unsigned pointer conversions
* canonical/probert@c3394ad Merge pull request canonical/probert#154 from canonical/libnl-fixes
* canonical/probert@7b8ecb3 Merge pull request canonical/probert#152 from ogayot/missing-ssid-ie
* canonical/probert@811a709 network: filter out link_change events for AF_INET6
* canonical/probert@c68742b _rtnetlinkmodule: filter out link objects having family=AF_INET6
* canonical/probert@204775d Merge pull request canonical/probert#153 from ogayot/ie-with-long-length
* canonical/probert@dafe191 …

snapcraft: pickup probert fixes for network

---

subiquity/models/subiquity.py

Curtin knows to carry forth kernel command line after ---.  We set replace_linux_default=False in subiquity with the goal of having `quiet splash` be in the default grub config, but `--- quiet splash` is already specified in the ISO grub config.
This matters because on arm64 we need more parameters, so we want those to flow through to the default grub config on the target system.
LP:#2104310

models: we don't need curtin's grub replace_linux_default=False

---

snapcraft.yaml
subiquity/cmd/server.py
subiquitycore/controllers/network.py
subiquitycore/prober.py
subiquitycore/ssh.py

Backport to noble of probert network fixes (and the ability to disable use of nl80211 C module for desktop)
* canonical/probert@ee45ec6 Merge pull request canonical/probert#158 from ogayot/noble-network-fixes
* canonical/probert@13e6f51 _nl80211: fix warning for signed / unsigned pointer conversions
* canonical/probert@9be3763 network: handle missing SSID information element
* canonical/probert@4982a00 nl80211: handle information elements with length > 0x7F
* canonical/probert@fd1124d network: only try to load _nl80211 if required
* canonical/probert@4adbbe8 network: instantiate the WLAN listener earlier
* canonical/probert@035eb25 network: make the wlan_listener support optional
Also cherry-picks eca1827b1f43b7ee9db81588b7ef6ab6e2581df4 network: add command line arg to control the …

Noble probert network fixes

---

subiquity/ui/views/filesystem/compound.py

When creating or editing an LVM or MD container, the list of potential devices is shown. Unfortunately, when one of the devices has an overly long label (> 50 chars), all of the devices became invisible, making it challenging to create a RAID / LVM properly.
Ensure, the list of devices is now visible no matter the length of labels.
The actual fix is the `can_shrink=True` property. But we can also clip the name of the device using `wrap="ellipsis"` if we want a cleaner (but less detailed) output.
LP:#2045688
**Current behavior when a device has a long label:**
**New behavior with the `wrap="ellipsis"`**
**Alternative new behavior without the `wrap="ellipsis"`**

storage: fix display of potential devices for MD or LVM

---

subiquity/server/apt.py

In testing against a country mirror, apt-get update may fail with:
File has unexpected size (x != y). Mirror sync in progress?
On inspection, we found that the copy of /var/lib/apt/lists was in a bad state and that further apt-get update invocation would not correct it.
By removing this cached information, we have to download more from the mirror (not great), but the result should be more robust.
LP:#2105480

apt: remove /var/lib/apt/lists from apt runs

---

snapcraft.yaml

* curtin/subiquity@aa2f5dd03
LP:#2107381

plucky: snapcraft: bump curtin to pickup the ZFS keystore size fix

---

snapcraft.yaml

Full changelog
* canonical/curtin@148b02f5f4027ca508727110604e376f325a1078 (MP ~~currently~~ merged at https://code.launchpad.net/~ogayot/curtin/+git/curtin/+merge/484500)
* canonical/curtin@3a123215 several: fix flake re unassigned globals
* canonical/curtin@ade5432d apt_config: attempt to clean cloud-init-base
* canonical/curtin@207b0bb8 control: build-dep on python3-packaging
* canonical/curtin@8ddb9598 curthooks: rename kernel event
* canonical/curtin@84096412 curthooks: rely on reconfiguring kernel to create initramfs

Update curtin Apr 15th 2025

---

subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/filesystem/tests/test_guided.py

Ever since we introduced support for booting from a recovery partition, storage v2 has been advertising "partial" guided reformat scenarios (without making a clear distinction from a normal reformat scenario).
However, only the /storage/v2 API supports partial reformats.
For the TUI, which uses storage v1, a partial reformat is not possible, so we should not offer the installation media as a potential target to reformat, even though the storage v2 API advertises it.
**Before**
**After**
LP:#2106499

storage: prevent using the install media in the guided TUI

---

subiquity/server/controllers/shutdown.py

This uses a backwards compatible argument for calling shutdown/reboot as simply using --check-inhibitors will not work for any system using systemd <257
Regression introduced by https://github.com/canonical/subiquity/pull/2182
Relevant systemd code for the given argument:
https://github.com/systemd/systemd/blob/caecff5fa2ebc4ad7470aebd564cf7c1a705f184/src/systemctl/systemctl.c#L484
https://github.com/systemd/systemd/blob/caecff5fa2ebc4ad7470aebd564cf7c1a705f184/src/systemctl/systemctl.c#L280
https://github.com/systemd/systemd/blob/caecff5fa2ebc4ad7470aebd564cf7c1a705f184/src/systemctl/systemctl.c#L849
Discussion:
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2092438?comments=all

Shutdown should use a backwards compatible argument for ignoring inhibitors

---

snapcraft.yaml

This includes the curtin changes from https://code.launchpad.net/~mwhudson/curtin/+git/curtin/+merge/482870 along with the continued work on extlinux at https://code.launchpad.net/~sjg1/curtin/+git/curtin/+merge/484176 (not yet sufficient to enable extlinux installs).

snapcraft: rev for extlinux / update-initramfs changes

---

subiquity/common/apidef.py
subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

This introduces a new endpoint meant to be used by the desktop installer at the end of an installation in the TPM/FDE flow when requesting a recovery key.
* GET /v2/storage/core_boot_recovery_key
For now, the returned key is not usable, but in the future we will get it from snapd instead - which will associate it to the encrypted device.
The endpoint can only be used after marking the storage model as configured (i.e., after confirming the summary of changes in the desktop installer).
Cc: @d-loose

Add stub endpoint to get TPM/FDE recovery key

---

subiquity/models/snaplist.py

`update_snap` doesn't exist; this PR calls the existing `update` (which was used to replace snap.update by the commit linked below).
Commit that introduced the typo: https://github.com/canonical/subiquity/commit/e43e3cca1493679e7e3cbd69ffb97b49ee4659ea (CC @mwhudson)
Relevant launchpad bug: https://bugs.launchpad.net/subiquity/+bug/2067253
I didn't test this change, at least not yet.
LP: #2067253

Fix bug/typo in snaplist.py

---

subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/install.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapd/api.py
subiquity/server/snapd/types.py
subiquitycore/snapd.py

Instead of generating a fake recovery key for core boot installations, we now lean on a new feature from snapd to fetch an actual recovery key.
The main problem I ran into is that the Subiquity defines the return type of `/v2/systems/{system-label}` as a `ChangeID`. But this is only correct if the endpoint returns an async response. Depending on the content of the request, the response is sync or async.
I have tried to add support for `Union[str, SystemActionResponse]` as a return type but with no success for now. In the meantime, I introduced a workaround to use an alternative snapd API definition.
~~Marking as a draft since this depends on canonical/snapd#15503~~

Fetch core boot recovery key from snapd

---

subiquity/ui/views/tests/test_installprogress.py

When running the unit tests, the following warnings are raised:
```
subiquity/ui/views/tests/test_installprogress.py::IdentityViewTests::test_event_other_formatting
subiquity/ui/views/installprogress.py:69: PileWarning: <MagicMock name='Text()' id='136247309836912'> is not a Widget
self.event_pile = Pile(event_body)
subiquity/ui/views/tests/test_installprogress.py::IdentityViewTests::test_event_other_robust_splitting
subiquity/ui/views/installprogress.py:69: PileWarning: <MagicMock name='Text()' id='136247310463200'> is not a Widget
self.event_pile = Pile(event_body)
subiquity/ui/views/tests/test_installprogress.py::IdentityViewTests::test_event_other_robust_splitting
subiquitycore/ui/container.py:368: ColumnsWarning: <MagicMock name='Text()' id='136247310463200'> is not a Widget …
```

identity: fix warnings when running unit tests

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/install.py
subiquity/server/controllers/tests/test_filesystem.py

When calling `/v2/systems/{label}` with `action="generate-recovery-key"`, a recovery key is created with an expire duration of 5 minutes (defined in snapd).
Snapd expects that the `/v2/systems/{label}` with `action="finish-install"` gets called before the key expires.
In case the installer doesn't, we end up with:
```
File "subiquity/server/snapd/api.py", line 142, in post_and_wait
raise aiohttp.ClientError(result.err)
aiohttp.client_exceptions.ClientError: cannot perform the following tasks:
- Finish setup of run system for "enhanced-secureboot-desktop" (recovery key has expired)
```
We now move the "generate-recovery-key" step just before the "finish-install" step. This should drastically lower the window for key expiration.
The drawback is that subiquity's …

storage: generate the recovery later, so it doesn't expire

---

examples/snaps/v2-snaps-snapd.json
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/server.py
subiquity/server/snapd/info.py
subiquity/server/snapd/test/test_info.py
subiquity/tests/api/test_api.py

This is to disable TPM/FDE if the snapd version in the live environment is too old. This will typically happen when refreshing the installer from an older ISO.
This will not prevent the installer from offering features (e.g., recovery key) that are not properly understood by the snapd version that is getting installed on the target system (i.e, the snapd from the squashfs).
Adding more stuff inside _examine_systems() broke some API tests, making it clear that we have race conditions to watch for.  One way to make it obvious is to apply the following patch:
```diff
--- a/subiquity/server/controllers/filesystem.py
+++ b/subiquity/server/controllers/filesystem.py
@@ -468,6 +468,7 @@ class FilesystemController(SubiquityController, FilesystemManipulator):
async def _examine_systems(self): …
```

Disable TPM/FDE if snapd is too old

---

subiquitycore/snapd.py

When POSTing to Snapd, we send it JSON data. Previously, we did not specify a Content-Type header, which is fine with snapd. We now rely on requests to set the Content-Type header appropriately (i.e., to application/json).
When debugging, it makes it easier to work with captured data. It also makes it easier to implement a mock version of snapd with flask.

snapd: set Content-Type header appropriately when POSTing to snapd

---

subiquity/common/api/client.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapd/api.py
subiquity/server/snapd/types.py
subiquitycore/snapd.py
subiquitycore/tests/test_snapd.py

The `/v2/systems/{label}` action="check-passphrase|check-pin" endpoint doesn't return `{"type": "sync"}` on error, it returns `{"type": "error"}` instead. This code path in Subiquity was untested and there were several issues with it:
* The `make_request` context manager yields a `_FakeError` instance, but then could yield `_FakeResponse` subsequently. This caused a:
```python
RuntimeError: "generator didn't stop"
```
* The caller or `_FakeError` didn't provide the data argument that the initializer expected.
* If `raise_for_status` is False, then `_FakeError`.json gets called, but the method didn't exist.
I also adapted the dry-run implementation so that it returns `{"type": "error"}`
Last, it turned out during testing that snapd 2.68 returns `min-entropy-bits` as an integer and …

Entropy fix when response is {"type": "error"} (and fix entropy expected type)

---

subiquity/server/controllers/oem.py

This is a port to noble of #2230.
> On certified devices, when we are offline and the OEM metapackage declares that it should be used with the OEM kernel (i.e., Ubuntu-Oem-Kernel-Flavour: oem), we store the name of the kernel package to install in the kernel model.
> 
> However, the flavor_to_pkgname() function was used incorrectly. We were meant to give it the name of a flavor (e.g., oem, generic, ...) but instead we gave it the name of the OEM metapackage.
> 
> As a consequence, we ended up trying to install kernel package with names such as "linux-oem-somerville-treckoo-meta-24.04". Instead it should have been "linux-oem-24.04".
LP:#2114780
(cherry picked from commit 0c997768bc4a0a94ef123298d37fe953d6499976)

[Noble]: oem: fix kernel metapackage name for OEM kernel

---

subiquity/common/apidef.py
subiquity/common/types/storage.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapd/types.py
subiquitycore/snapd.py
subiquitycore/tests/test_snapd.py

This PR is now based on #2221 and adapts the `/storage/v2/calculate_entropy` endpoint to the current entropy rework in snapd (> 2.70) (see https://github.com/canonical/snapd/pull/15607)
* The entropy values are expressed as integers, not floats
* We provide access to the `optimal-entropy-bits` field
* Successful entropy-checks return a non-null response with entropy information.
* We provide access to the failure-reasons and a success boolean.
<details>
<summary>Original description (before split):</summary>
Up to 925caabec4fe61562353adbbc5fe5ebc2b02fd5c, this is basically a rework of https://github.com/canonical/subiquity/pull/2181 where the implementation is based on what snapd 2.68 offers.
In subsequent commits though, we lean on future snapd work or work that isn't yet part of …

Entropy calculation against newer snapd (2.71)

---

subiquity/common/serialize.py
subiquity/common/tests/test_serialization.py

This makes is possible to use `typing.Union[int, str]`, `typing.Union[bool, float, int, None]`, etc when serializing / deserializing data exchanged with APIs.

Serializer: add support for unions of basic types

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Subiquity does not support changing the name of a GPT partition. However, Subiquity intends to support preserving the name if it is already set. To do so, the user has in theory two ways:
* they can set the "name" field of the /storage/v2/edit_partition request to the original name
* they can omit the "name" field from the /storage/v2/edit_partition request
Unfortunately, both options were broken. When trying each, Subiquity would fail with the following error:
```
ValueError: edit_partition does not support changing partition name
```
Indeed, there was a flow when comparing the original name and the new name.
The Partition API object has a "name" field which corresponds to the (GPT) partition name. But in the Partition model object, the "name" field is different. It is inherited from …

storage: fix inability to edit a partition having a GPT name

---

subiquity/common/apidef.py
subiquity/common/types/storage.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/snapd/types.py

This introduces a new endpoint:
```
GET /storage/v2/core_boot_encryption_features
```
e.g.:
```sh
curl --unix-socket /run/subiquity/socket http://a/storage/v2/core_boot_encryption_features
["PASSPHRASE_AUTH"]
curl --unix-socket /run/subiquity/socket http://a/storage/v2/core_boot_encryption_features
["PASSPHRASE_AUTH", "PIN_AUTH"]
```
Which returns a list of encryption "features" supported by a TPM/FDE variation.
When booting a TPM/FDE system, different authentication methods are supported.
NOTE: This change was originally part of a larger change that included a rework of how we handle variations info.

storage: add endpoint to check if the TPM key can be encrypted

---

subiquity/common/api/recoverable_error.py
subiquity/common/api/server.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py
subiquity/server/server.py

This PR comes with 3 main changes:
* changed the way to configure whether StorageRecoverableError should produce crash reports. The main drawback of the previous implementation (using type aliasing) is that inheriting from StorageRecoverableError is resolved at class creation time, not instance creation time.
* use subclasses of StorageRecoverableErrors to categorize storage errors
* added title and error code to RecoverableError. This is a step towards implementing RFC9457 (Problem Details for HTTP APIs) or something somehow similar to RFC9457.

Make relevant filesystem controller errors "user errors" and categorize them

---

Makefile
apt-deps.txt
scripts/slimy-update-snap.sh
snapcraft.yaml

Now that canonical/probert#160 has landed, we can use the new probert-network implemented only in python.
FFe was approved https://bugs.launchpad.net/subiquity/+bug/2121429

snapcraft: build with new python-only probert-network

---

console_conf/cmd/tui.py

In patch dfea4471363c0904b784fb0e78b5d1b30085e27e, we ensured warnings are captured by the logging system in subiquity so that they don't show up over the UI, rendering it barely usable.
However, only the warnings emitted when running subiquity (client & server) were captured. The warnings emitted by console-conf were not affected by that change. Therefore, they could still show up and "break" the UI.
Fixed by capturing the warnings as well for console-conf.
LP:#2121857
NOTE: to test this on main, one also needs https://github.com/canonical/subiquity/pull/2252

console-conf: capture warnings emitted using warnings.warn()

---

apt-deps.txt
subiquity/server/apt.py
subiquity/server/controllers/shutdown.py

`cp -T` in rust-coreutils has partial support for directory handling, but not a case that subiquity uses, where a directory is being copied and the destination version of that directory is currently absent.
When rust-coreutils cp supports this usage of -T I suggest reverting this commit.
LP:#2122363

several: use rsync over cp -T

---

subiquitycore/netplan.py

If multiple sections match a given interface name (i.e., ens3 here), netplan (or the backend really) will honor the first matching section ordered by section name.
```yaml
ethernets:
cc:
match: {name: ens3}
addresses: [2.2.2.2/24]
bb:
match: {name: ens3}
addresses: [1.1.1.1/24]
aa:
match: {name: lo}
addresses: [127.0.0.1/8]
ens3:
addresses: [3.3.3.3/24]
```
In this scenario, that would be "bb" because it matches the interface name and "bb" comes before "ens3" in lexical order.
Previously, Subiquity would honor the first matching section (i.e., cc). This would result in `netplan apply` to honor "bb" but subiquity to apply "cc" when reaching the network screen.
Fixed by making Subiquity behave more like netplan. We now sort by section name when determining the right configuration to apply. …

Behave more like netplan when multiple configs match the same interface

---

subiquitycore/models/network.py

network: fix network loss if Wi-Fi IP configured before AP settings
From a netplan standpoint, it is invalid to declare a Wi-Fi configuration without defining the access points settings.
And if a user of Subquity decides to configure the Wi-Fi IP settings before the "Wi-Fi" (i.e., AP) settings, the *intermediate* netplan configuration produced becomes invalid. As soon as the user validates the IP settings, the network is lost immediately (for all interfaces).
The logs show that "netplan apply" fails with:
```
Error in network definition: {iface}: No access points defined
```
Furthermore, if using console-conf instead of Subiquity, the exception is uncaught and terminates the console-conf process.
Fixed by not producing the netplan configuration when a Wi-Fi device is incompletely …

network: fix network loss if Wi-Fi IP configured before AP settings
