subiquitycore/models/network.py
See https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1623756
=> Do not write any config for a wlan device that has not been given a ESSID

console_conf/ui/views/identity.py, console_conf/ui/views/login.py
Otherwish if you reboot while still on the final screen you end up in
console-conf again.
=> Mark firstboot complete as soon as we've called create-user

console_conf/controllers/identity.py
This is https://github.com/CanonicalLtd/subiquity/pull/168 rebased against master and with a little refactoring from me.
=> skip the "enter your email address" view if the device is already owned

subiquitycore/models/network.py
See https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1634540
=> render gateway4/gateway6 in network config

subiquitycore/models/network.py, subiquitycore/ui/views/network_configure_ipv4_interface.py
This depends on netplan changes that pitti is frantically hacking up right now so there's a chance the two bits won't line up. But I think it should be OK.
=> add UI for entering nameservers

bin/console-conf-tui, subiquitycore/controllers/network.py
The setting of umask was breaking configuring wifi :(
=> remove setting of umask, redact wifi password from log file

subiquitycore/controllers/network.py, subiquitycore/signals.py
Two of these were properly stupid :(
LP: #1636421 (again)
=> make properly sure that the wifi password does not get logged

Makefile, console_conf/controllers/identity.py, console_conf/ui/views/login.py, debian/changelog, installer/geninstaller, requirements.txt, subiquitycore/controllers/network.py, subiquitycore/models/network.py, subiquitycore/prober.py, subiquitycore/ui/views/__init__.py, subiquitycore/ui/views/network.py, subiquitycore/ui/views/network_configure_interface.py, subiquitycore/ui/views/network_configure_ipv4_interface.py, subiquitycore/ui/views/network_configure_wlan_interface.py, subiquitycore/ui/views/network_default_route.py
Each of the commits in this PR could be it's own PR but github doesn't handle that sort of thing very well. Let me know if you want me to split it up for review.
6d7877f depends on https://github.com/CanonicalLtd/probert/pull/32
Please do try this out. I've had everything working at some point but I have refactored a little since then and it's possible I've broken something.
=> live updating of network model

console_conf/controllers/identity.py
for https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1643930
=> rewrite login-details.txt a bit

installer/README.md, installer/geninstaller
some fixes to geninstaller to run cleanly in a chroot and not leave broken mounts / kpartx mappings around.
=> Geninstaller cleanup

Makefile, debian/control, installer/geninstaller, requirements.txt, subiquity/controllers/installprogress.py, subiquity/ui/views/identity.py, subiquity/ui/views/installprogress.py, subiquitycore/controller.py, subiquitycore/controllers/network.py, subiquitycore/core.py, subiquitycore/utils.py
Half of this addresses https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1654390 which is complaining about the UI of the final installprogress screen. The other half is rewriting the logic of the installprogress controller (and as a bonus, killing off a dependency).
=> clean up installprogress controller and view

bin/subiquity-debug, debian/rules, debian/subiquity-tty1.conf, debian/subiquity-ttyN.conf, debian/subiquity.conf, debian/subiquity.install, debian/subiquity.subiquity-debug@.service, debian/subiquity.subiquity.service
for https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1654085
=> rearrange systemd stuff to only run subiquity on tty1

subiquity/ui/views/filesystem/add_partition.py, subiquitycore/ui/interactive.py
Here's me playing with the new feature https://asciinema.org/a/0pveykhykc6hncidesxyc0md5
It needs some other "common mount points", please suggest away.
=> recommend some common mount points per spec

subiquity/models/filesystem.py, subiquity/ui/views/filesystem/add_partition.py, subiquitycore/ui/interactive.py
See https://asciinema.org/a/98q279mo3w6tvxdg2mb6kh41v for a demo
=> disable mount point widget if partition format should not be mounted

console_conf/ui/views/identity.py, console_conf/ui/views/login.py, console_conf/ui/views/welcome.py, subiquity/ui/views/bcache.py, subiquity/ui/views/ceph.py, subiquity/ui/views/filesystem/add_format.py, subiquity/ui/views/filesystem/add_partition.py, subiquity/ui/views/filesystem/disk_info.py, subiquity/ui/views/filesystem/disk_partition.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/identity.py, subiquity/ui/views/installpath.py, subiquity/ui/views/installprogress.py, subiquity/ui/views/iscsi.py, subiquity/ui/views/lvm.py, subiquity/ui/views/raid.py, subiquity/ui/views/welcome.py, subiquitycore/ui/dummy.py, subiquitycore/ui/error.py, subiquitycore/ui/utils.py, subiquitycore/ui/views/login.py, subiquitycore/ui/views/network.py, subiquitycore/ui/views/network_bond_interfaces.py, subiquitycore/ui/views/network_configure_interface.py, subiquitycore/ui/views/network_configure_manual_interface.py, subiquitycore/ui/views/network_configure_wlan_interface.py, subiquitycore/ui/views/network_default_route.py
=> make Color.button etc apply the corresponding focus map

subiquity/ui/views/filesystem/add_partition.py, subiquitycore/ui/views/network_configure_manual_interface.py
This takes the machinery I developed for the last branch and applies it to the manual network configuration view. It's still a bit verbose (the logic for disabling the done button when there is an error is entirely duplicated) but one thing at a time.
=> more immediate validation for manual network view

subiquitycore/ui/form.py, subiquitycore/ui/views/network_configure_wlan_interface.py
I noticed testing something else that wpa_supplicate refuses to use a short password, so we should refuse to give it one. Also the wifi config view was the first complex urwid code I wrote and I'm better at it now.
=> validate wifi password to be between 8 and 63 chars

subiquity/ui/views/filesystem/filesystem.py
I looks like this:
thoughts on wording or formatting welcomed.
=> confirm before writing data to disks

console_conf/ui/views/identity.py, subiquity/controllers/filesystem.py, subiquity/ui/views/filesystem/add_format.py, subiquity/ui/views/filesystem/add_partition.py, subiquity/ui/views/filesystem/disk_info.py, subiquity/ui/views/filesystem/disk_partition.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/identity.py, subiquity/ui/views/installpath.py, subiquitycore/controller.py, subiquitycore/controllers/network.py, subiquitycore/ui/interactive.py, subiquitycore/ui/views/network.py, subiquitycore/ui/views/network_bond_interfaces.py, subiquitycore/ui/views/network_configure_interface.py, subiquitycore/ui/views/network_configure_manual_interface.py, subiquitycore/ui/views/network_configure_wlan_interface.py, subiquitycore/ui/views/network_default_route.py, subiquitycore/view.py
Previously I'd done this kind of half-done way of stacking views and having the escape key pop from the stack. But it didn't work right, so rip it all out and be a bit more mechanical about it all.
=> more straightforward handling of escape key

subiquity/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/add_partition.py, subiquity/ui/views/filesystem/disk_partition.py, subiquity/ui/views/filesystem/filesystem.py
This is my effort at making a UI for the filesystem pages that (a) refers to disks by id (b) works in 80 characters-wide displays.
I really don't want to merge this without feedback, but what's the best way of getting feedback? Make a custom image and send it to the design team?
=> refer to disks in the UI by id not path

subiquitycore/ui/interactive.py, subiquitycore/ui/selector.py
I wanted this so I can enable/disable options after creating the widget.
=> move Selector widget to its own file and create a class for its Options

Makefile, README.md
Main changes: 1) mention console-conf at all in the README, 2) mention that bugs should be file on Launchpad
=> update readme and makefile a bit

subiquity/ui/views/filesystem/filesystem.py
the only worthwhile bit of my first reporting branch :-)
=> make it clear that selecting continue in the fs screen starts the installation

subiquity/ui/views/filesystem/disk_info.py, subiquity/ui/views/filesystem/disk_partition.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/guided.py, subiquity/ui/views/filesystem/partition.py, subiquity/ui/views/identity.py, subiquity/ui/views/installprogress.py, subiquitycore/ui/form.py, subiquitycore/ui/utils.py, subiquitycore/ui/views/network.py, subiquitycore/ui/views/network_configure_interface.py, subiquitycore/ui/views/network_configure_manual_interface.py, subiquitycore/ui/views/network_configure_wlan_interface.py
=> add and use a helper to make a pile of buttons the right width

console_conf/controllers/identity.py, subiquity/controllers/filesystem.py, subiquity/controllers/identity.py, subiquity/controllers/installpath.py, subiquity/controllers/installprogress.py, subiquity/core.py, subiquity/ui/views/welcome.py, subiquitycore/controllers/network.py, subiquitycore/core.py, subiquitycore/ui/anchors.py, subiquitycore/ui/frame.py
Also make its progress more automatic.
=> change the progress bar to show x / y rather than a %age

po/ca.po, po/hu.po, po/lv.po, subiquity/models/welcome.py
Import lp translations and enable them
=> More locales

subiquitycore/controllers/network.py
I have a more complicated networking change brewing which doesn't quite work and these are bugs I found while debugging that.
=> misc networking fixes

subiquity/core.py
=> Drop Installpath controller, whilst it's single option.

subiquity/models/filesystem.py
instead, filter out devices with devpath /devices/virtual/...
Please review skeptically, I'm not really sure what this code is trying to do. Ping @raharper too!
=> do not filter block devices by major

subiquity/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/partition.py
This makes installing in UEFI mode work. Will merge in a bit, gotta run right now.
=> fix uefi installs

subiquity/palette.py, subiquitycore/core.py
Switch to vt2 and running e.g. ls was very confusing without this...
=> do not overwrite the top 8 colors of the palette with black

snapcraft.yaml, subiquity/curtin.py
It's not pretty but it does work!
For https://bugs.launchpad.net/subiquity/+bug/1722574
=> add user to the correct set of default groups

subiquitycore/ui/views/network_configure_interface.py
I'm waiting on design for a proper go at this but this is probably a sufficient temporary improvement.
"Video" at https://asciinema.org/a/kmUqrUOGDVDRfdo91GV5abU5J
=> clunky way of indicating which network config method is active

subiquity/ui/views/welcome.py
now that we have actual translations, this screen actually makes sense and we
can remove the stuffy "(More language choices will appear in time)" text
=> remove disclaimer from welcome screen

subiquity/palette.py, subiquity/ui/views/filesystem/disk_partition.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/installprogress.py, subiquitycore/controllers/network.py, subiquitycore/ui/container.py, subiquitycore/ui/views/network.py, subiquitycore/ui/views/network_configure_interface.py
This adds scrollbars to all the scrollable areas (they only appear when needed).
I haven't thought very hard about the appearance of the scrollbars but I think they're OK.
https://asciinema.org/a/CijkRdQjjpjaz6SQ1TyMd5uPY
=> add scrollbars to listboxes

bin/subiquity-tui, examples/answers.yaml, subiquity/controllers/filesystem.py, subiquity/controllers/identity.py, subiquity/controllers/installprogress.py, subiquity/controllers/welcome.py, subiquitycore/controller.py, subiquitycore/controllers/network.py, subiquitycore/core.py
This allows you to pass a yaml file to --answers and have it provide enough information for a hands off install with the default options.
=> simple non interactive mode

subiquity/core.py, subiquity/palette.py, subiquitycore/core.py
Replace some incomprehensible garbage with slightly better factored incomprehensible garbage.
=> refactor color / palette setup

subiquity/palette.py, subiquity/ui/views/filesystem/guided.py, subiquity/ui/views/welcome.py, subiquitycore/ui/buttons.py
https://asciinema.org/a/A0jnRyc0g0ksNl4LSoL1YQK0I
=> implement new color scheme from design

subiquity/ui/views/filesystem/guided.py
For https://bugs.launchpad.net/subiquity/+bug/1750054
=> use better wording on guided screen

.travis.yml, scripts/runtests.sh, scripts/test-in-lxd.sh
other work requires having systemd running
=> move to running tests in lxd rather than docker

bin/console-conf-tui, console_conf/controllers/identity.py, console_conf/core.py, console_conf/models/console_conf.py, console_conf/palette.py, console_conf/ui/views/identity.py, console_conf/ui/views/login.py, console_conf/ui/views/welcome.py, subiquitycore/models/identity.py
This makes console-conf work again, at least in dry run mode. It wasn't as bad as I feared.
=> Resurrect console conf

subiquity/controllers/keyboard.py, subiquity/models/keyboard.py, subiquity/ui/spinner.py, subiquity/ui/views/installprogress.py, subiquity/ui/views/keyboard.py, subiquitycore/view.py
needs testing in a vm but in the mean time: https://asciinema.org/a/MBWfJvicE8T2L1ynDgeMeLhD4
=> keyboard fixes: show dialog while applying, re-setup shift tab afterwards

subiquity/models/filesystem.py, subiquity/models/subiquity.py
https://bugs.launchpad.net/subiquity/+bug/1750657
=> prevent creation of a swapfile when / is btrfs

subiquity/ui/views/identity.py, subiquitycore/ui/form.py, subiquitycore/ui/views/network_configure_manual_interface.py
Just a couple of simple things.
=> address feedback from sprint

subiquity/models/filesystem.py, subiquity/models/subiquity.py
and also suppress the swapfile if there is an explicit swap partition.
for https://bugs.launchpad.net/subiquity/+bug/1757319
=> adjust curtin config so swap partitions are actually used

subiquity/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/disk_partition.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/guided.py, subiquity/ui/views/filesystem/partition.py, subiquity/ui/views/filesystem/tests/test_partition.py
also remove it from the curtin config.
mostly deleting code which is nice!
=> remove ability to supply partition number from the UI

subiquity/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/disk_partition.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/partition.py
https://asciinema.org/a/pLJ95ajEDPsOEJQrZVQp3cVbv
Not sure about the UI for moving the boot partitions between drives but can't think of anything much better...
=> address confusion around the boot partition

subiquity/models/subiquity.py
=> ask cloud-init to configure the locale of the installed system

po/ast.po, po/ca.po, po/de.po, po/el.po, po/es.po, po/fr.po, po/hr.po, po/lv.po, po/pl.po, po/ru.po, subiquity/models/locale.py
@xnox can you take a look?
There are also French, Spanish, Croatian and Asturian translations in here, I guess we should enable those too?
=> update translations from lp, enable some new ones

subiquity/ui/views/identity.py
for https://bugs.launchpad.net/subiquity/+bug/1760140
=> handle the separate validation requirements for launchpad and github usernames

examples/answers.yaml, subiquity/controllers/__init__.py, subiquity/controllers/proxy.py, subiquity/models/proxy.py, subiquity/models/subiquity.py, subiquity/ui/views/installpath.py, subiquity/ui/views/proxy.py, subiquitycore/ui/form.py
very simple, not tested in a VM yet
=> proxy support

subiquitycore/ui/container.py
https://asciinema.org/a/9JRs04vMkpI4ce2f2zpcwhqAV
=> change scrollbar color if focused

subiquity/models/subiquity.py
for https://bugs.launchpad.net/subiquity/+bug/1764168
=> prevent cloud-init from resizing the rootfs into any space

po/POTFILES.in, subiquity/controllers/keyboard.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/guided.py, subiquity/ui/views/identity.py, subiquity/ui/views/installprogress.py, subiquity/ui/views/keyboard.py, subiquitycore/controllers/network.py, subiquitycore/i18n.py, subiquitycore/ui/form.py
The behaviour of _("") surprised me...
=> updates to make subiquity more translatable

subiquity/controllers/installprogress.py, subiquity/controllers/keyboard.py, subiquitycore/controller.py, subiquitycore/controllers/network.py, subiquitycore/core.py
I'm going to be doing a lot more stuff in the background soon (fetching snap lists, container stuff) so I'm going to make some tweaks ahead of time.
=> run_in_bg tweaks

.travis.yml, console_conf/controllers/identity.py, subiquity/controllers/installprogress.py, subiquitycore/controllers/network.py, subiquitycore/utils.py
Just add logging and change some defaults.
=> make the wrapper we have around subprocess functions thinner

examples/answers.yaml, subiquity/controllers/identity.py, subiquity/models/subiquity.py, subiquity/ui/views/identity.py, subiquitycore/models/identity.py
Turns out ssh-import-id sucks wrt error handling but oh well. Video: https://asciinema.org/a/94Dp49Pm5SbfRohOFGQbXlonH
=> have subiquity fetch ssh keys rather than cloud-init

subiquity/controllers/proxy.py, subiquity/models/proxy.py, subiquity/models/subiquity.py
also emit a signal when proxy config is set
=> configure proxy for apt and snapd in installed system 

subiquitycore/controllers/network.py, subiquitycore/tasksequence.py, subiquitycore/ui/views/network.py
I want to reuse it in my containerizing branch.
Improve API and docs a bit while I am looking at it.
=> move TaskSequence somewhere more generic

.travis.yml, Makefile, scripts/installdeps.sh, scripts/runtests.sh, scripts/test-in-lxd.sh
There would be something to be said for running the linting in a different "stage" I think but my limited fiddling couldn't get that to work, so I think this will do for now.
=> update travis jobs: test on cosmic, run make lint

subiquity/controllers/filesystem.py, subiquity/ui/views/__init__.py, subiquity/ui/views/filesystem/__init__.py
Tests are not fixed, just to QA the branch
=> Remove useless imports

Makefile, subiquity/__main__.py
Add a main to subiquity so that you can run subiquity with:
python3 -m subiquity
Adjust Makefile to use that.
=> Add main to subiquity, and use it frm make ui-view.

examples/answers.yaml, subiquity/controllers/__init__.py, subiquity/controllers/mirror.py, subiquity/core.py, subiquity/models/mirror.py, subiquity/models/subiquity.py, subiquity/ui/views/mirror.py
This very simply adds a mirror panel to subiquity.
Nothing intelligent at all.  Just defaults to filling with
http://archive.ubuntu.com/ubuntu/ and lets user fill it in.
=> Add a mirror panel.

console_conf/palette.py, subiquity/palette.py, subiquitycore/ui/container.py
in response to design feedback
https://asciinema.org/a/UbUeug9qPbrA6QPXbrQF5588S
also pretty up its implementation a bit while I am here
=> make scrollbar less intrusive

subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/snaplist.py, subiquitycore/ui/form.py, subiquitycore/ui/table.py
Make a separate listbox vs pile table class, allow columns to take all available space, fix an off-by-one error, fix binding more than two tables, build forms out of tables.
=> Table tweaks

subiquity/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/raid.py, subiquitycore/ui/form.py
A few fairly small changes to how the filesystem view works.
=> filesystem tweaks

examples/answers-raid.yaml, subiquity/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/ui/mount.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/partition.py, subiquity/ui/views/filesystem/raid.py, subiquity/ui/views/filesystem/tests/test_filesystem.py
Some attempts to avoid unbootable things, and even trying to give the user some hints what to do to progress.
=> add some raid/not physical disk checks

snapcraft.yaml, subiquitycore/models/network.py
using support i just added to probert
=> read vlan config from netlink

reserved-usernames, snapcraft.yaml, subiquity/ui/views/identity.py
=> do not let the user choose a reserved username

examples/answers-bond.yaml, subiquity/controllers/filesystem.py, subiquitycore/controller.py, subiquitycore/controllers/network.py, subiquitycore/models/network.py, subiquitycore/netplan.py, subiquitycore/ui/table.py, subiquitycore/ui/views/network.py, subiquitycore/ui/views/network_configure_manual_interface.py, subiquitycore/ui/views/tests/test_network_configure_manual_interface.py
Mostly making virtual interfaces work a bit more like the other bits.
=> refactor network model

bin/subiquity-service, snapcraft.yaml, subiquity/cmd/tui.py, subiquity/controllers/installprogress.py
Just about every detail of this was excruciating, but it does work now.
=> include curtin in snap

subiquity/controllers/installprogress.py, subiquity/models/subiquity.py
And clean itself up afterwards.
With this and recent seed changes, I think offline installs become possible.
=> configure curtin to be able to install packages from pool during installation

examples/answers-bond.yaml, examples/answers-guided-lvm.yaml, examples/answers-lvm.yaml, examples/answers-raid-lvm.yaml, examples/answers-raid.yaml, examples/answers-swap.yaml, snapcraft.yaml, subiquity/controllers/__init__.py, subiquity/controllers/identity.py, subiquity/controllers/installprogress.py, subiquity/controllers/ssh.py, subiquity/core.py, subiquity/models/ssh.py, subiquity/models/subiquity.py, subiquity/ui/views/identity.py, subiquity/ui/views/snaplist.py, subiquity/ui/views/ssh.py, subiquity/ui/views/tests/test_identity.py, subiquitycore/models/identity.py, subiquitycore/ui/form.py, subiquitycore/ui/width.py
The diff is scary but a lot of that is code moving around.
Demo: https://asciinema.org/a/sFNXS96PxN3IFpBdNxABP3yoC
=> ask the user if they want to install ssh during the install 

subiquity/ui/mount.py, subiquity/ui/views/filesystem/compound.py, subiquity/ui/views/filesystem/partition.py, subiquity/ui/views/filesystem/raid.py, subiquity/ui/views/filesystem/tests/test_partition.py, subiquity/ui/views/filesystem/tests/test_raid.py
Fix a couple of crash bugs reported on Launchpad and a few other things I noticed while I was working on those.
=> crash and other fixes for filesystem views

scripts/installdeps.sh, scripts/replay-curtin-log.py, scripts/runtests.sh, subiquity/controllers/installprogress.py, subiquity/models/keyboard.py, subiquitycore/controller.py, subiquitycore/controllers/network.py, subiquitycore/core.py
This takes scripts/runtest.sh from 80 s to 20 s on my system.
=>  make sure all delays during replaying answers repsect SUBIQUITY_REPLAY_TIMESCALE

examples/answers-lvm-dmcrypt.yaml, scripts/runtests.sh, subiquity/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/lvm.py, subiquity/ui/views/identity.py
* rendering the curtin config is kind of hackish
* the passphrase ends up in the log file a few times, need to fix that
=> add encrypted LVM support

subiquity/controllers/snaplist.py, subiquitycore/core.py
will need this for the refresh screen if there is no update
=> add a way for a controller to be skipped

subiquity/controllers/installpath.py, subiquity/controllers/mirror.py, subiquity/controllers/proxy.py, subiquity/controllers/welcome.py, subiquitycore/controller.py, subiquitycore/core.py
so we can return the point where the user left off on update
This is a bit more subtle I guess, will leave the PR around for a while in case anyone wants to look :)
=> add a more systematic way for controllers to record their state

subiquity/models/keyboard.py, subiquity/ui/views/keyboard.py
saves a second or so for the US keyboard user
=> do not run setupcon if the keyboard setup has not changed

subiquity/ui/views/ssh.py
just because it feels like I haven't achieved much today :)
=> relax constraint that launchpad usernames must be >1 character long

subiquity/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/partition.py
Bootloader fails to install on POWER because there is no prep partition.
Ensure we create one.
Not sure how this works at all, in neither subiquity or curtin. But it seems like curtin should know what to do with a 'prep' flag partition. I guess it's worth a try.
=> Attempt to add a PReP partition.

scripts/inject-subiquity-snap.sh, subiquity/ui/views/snaplist.py
=> use yaml.safe_load instead of yaml.load

examples/snaps/v2-changes-8/0000.json, subiquity/controllers/refresh.py, subiquity/snapd.py
also support passing subquity-channel= on the kernel command line
=> customize where subiquity refreshes from

subiquity/ui/views/filesystem/filesystem.py
before: https://asciinema.org/a/JYqviJjWssSVg7xbhnGxNETv1
after: https://asciinema.org/a/85S7QuU5ymz2lvQfF8HrUCj52
=> show table heading on filesystem view initial load

subiquity/models/filesystem.py
Allow a compound device (i.e. VG or raid) to be deleted if none of its
partitions are mounted or part of another device.
This makes it a lot easier to remove existing devices that probing for
existing partitions / compound devices can find.
=> Relax constraints on what can be deleted slightly

subiquitycore/controllers/network.py, subiquitycore/core.py
* add a bit more logging
* wait for initial network apply to finish before moving on from
network screen
=> trying to debug edge ci failures

subiquity/models/subiquity.py
rather than doing it via cloud-init, which gets reapplied on each boot.
also set up /etc/hosts as the other installers do it.
=> configure hostname directly

bin/subiquity-configure-apt
For https://bugs.launchpad.net/subiquity/+bug/1824173
=> do not use apt proxy during no-network install

subiquity/controllers/filesystem.py
Currently changes to the encryption / passphrase of a vg aren't saved, oops.
=> fix editing encrypted/passphrase of vg

examples/snaps/v2-find-select=refresh.json, examples/snaps/v2-snaps-subiquity.json, subiquity/controllers/refresh.py, subiquity/ui/views/refresh.py
https://asciinema.org/a/ZwsCBvgEXN3QMVwkwPQ06mnck
=> show subiquity versions in upgrade screen

subiquity/controllers/snaplist.py
otherwise postinstall steps never run!
=> emit snap-config-done signal when skipping snap list

subiquity/models/subiquity.py
cloud-init may end up writing them too late
=> write hostname/hosts/machine-id earlier

subiquity/controllers/installprogress.py
the bionic edge tests are failing and this might help explain why (they work on my machine...)
=> add some logging to _step_done

subiquity/controllers/ssh.py
=> SSHController: the keyword to install openssh-server is install_server

DESIGN.md
probably best to get some of this stuff out of my head.
=> start a design document

subiquity/models/subiquity.py
for https://bugs.launchpad.net/bugs/1825576
=> copy /cdrom/.disk/info to /var/log/installer/media-info

subiquity/ui/views/filesystem/lvm.py, subiquity/ui/views/filesystem/tests/test_lvm.py
I wrote this for another branch then realized it was not of any use for
testing that branch but still worth having
=> add simple lvm view tests

subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/partition.py
https://bugs.launchpad.net/subiquity/+bug/1828661
=> fix some bugs in editing and displaying swap partitions/devices

subiquity/controllers/filesystem.py, subiquity/models/filesystem.py
With bonus mostly cosmetic shuffling.
=> canonicalize ptable, size, raidlevel values for filesystem actions

subiquity/models/filesystem.py
Some stuff I did doing reusing existing partitions that does not depend on anything in that branch.
=> filesystem model tweaks

subiquity/controllers/tests/test_filesystem.py, subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py
Fix a bug on ppc64el this found.
=> add a tonne of tests for when various device actions are permitted

examples/answers-lvm-dmcrypt.yaml, examples/answers-lvm.yaml, subiquity/controllers/filesystem.py
And similar for RAID. Fix a couple of the answers files that got this
wrong and only worked by chance.
=> when assembling vg from answers, check devices are ok_for_lvm_vg

subiquity/controllers/filesystem.py
@raharper is any reason to favour on of "wipe: superbloc" or "wipe: superblock-recursive" over the other?
=> always wipe a disk when clearing its partition table

subiquity/ui/views/filesystem/compound.py
Just a fairly minor thing I noticed playing around.
=> relax "don't put all disks in a RAID" check for existing partition tables

requirements.txt, snapcraft.yaml
Oops we were a bit behind here!
=> update to probert tip to get multipath, lvm, raid fixes

subiquity/ui/views/filesystem/partition.py, subiquity/ui/views/filesystem/tests/test_partition.py
As reported in https://bugs.launchpad.net/subiquity/+bug/1837101.
There were two copies of some slighlty fiddly code and one had an extra line. Folded
both into a single function.
=> fix editing format of device with unusual filesystem

requirements.txt, subiquity/ui/mount.py, subiquity/ui/views/filesystem/partition.py, subiquity/ui/views/filesystem/tests/test_partition.py, subiquitycore/ui/form.py, subiquitycore/ui/selector.py
For https://bugs.launchpad.net/subiquity/+bug/1837219.
https://asciinema.org/a/z3jEPlzk5BJJyQZTUziPJV0Pk
=> Warn on suspicious filesystem reuse

subiquity/ui/views/filesystem/partition.py, subiquity/ui/views/filesystem/tests/test_partition.py
for https://bugs.launchpad.net/subiquity/+bug/1837820
=> fixes for editing existing ESPs

.travis.yml, subiquity/models/keyboard.py, subiquity/models/tests/test_keyboard.py
for https://bugs.launchpad.net/subiquity/+bug/1838126
=> write the new, not old, keyboard setting to the config file :/

console_conf/cmd/tui.py, console_conf/controllers/identity.py, console_conf/controllers/welcome.py, console_conf/models/console_conf.py, console_conf/models/identity.py, console_conf/ui/views/identity.py, console_conf/ui/views/login.py, console_conf/ui/views/welcome.py, subiquity/models/identity.py, subiquity/models/subiquity.py, subiquity/ui/views/tests/test_identity.py, subiquitycore/models/__init__.py, subiquitycore/models/network.py, subiquitycore/ui/form.py
At least with these patches, I can complete console-conf in dry-run mode.
Still need to test / fix, actual store code paths (success & failure).
Make pages pretty and consistent.
Add automated tests, as otherwise this will keep on breaking.
=> Unbreak console conf

console_conf/controllers/identity.py
Port to use prober API, stop using removed APIs.
This supposedly fixes core20 boot.
=> consoleconf: Fixup write_login_details_standalone

subiquity/models/identity.py, subiquity/ui/views/identity.py
for https://bugs.launchpad.net/subiquity/+bug/1786381
=> allow real name to be empty

console_conf/controllers/identity.py, console_conf/models/console_conf.py, subiquity/controllers/filesystem.py, subiquity/controllers/identity.py, subiquity/controllers/installprogress.py, subiquity/controllers/keyboard.py, subiquity/controllers/mirror.py, subiquity/controllers/proxy.py, subiquity/controllers/refresh.py, subiquity/controllers/snaplist.py, subiquity/controllers/ssh.py, subiquity/controllers/tests/test_filesystem.py, subiquity/controllers/welcome.py, subiquity/controllers/zdev.py, subiquity/core.py, subiquity/models/keyboard.py, subiquity/ui/views/keyboard.py, subiquitycore/controller.py, subiquitycore/controllers/network.py, subiquitycore/core.py, subiquitycore/view.py
Get rid of that 'common' dictionary that had just a bag of stuff in it.
No change in behaviour (hopefully!)
=> clean up how data is passed around at the centre of subiquity

console_conf/controllers/identity.py, subiquity/controllers/filesystem.py, subiquity/controllers/ssh.py, subiquitycore/controllers/network.py, subiquitycore/ui/frame.py
Current plans involve putting a focusable widget (a help button) in the
footer, and Pile's behaviour is much more what we want than Frame for
this.
=> Make the outermost widget an instance of Pile rather than Frame

subiquitycore/core.py
Notices this while debugging something entirely different.
=> fix fd leak in run_in_bg

subiquity/controllers/installprogress.py
for https://bugs.launchpad.net/subiquity/+bug/1838520
=> make sure unattended-upgrades always runs

subiquity/controllers/installprogress.py
also rejig uu running code to run as much of it as possible in dry-run
mode.
=> fix writing unattended-upgrades configuration

subiquitycore/core.py
This will be used for the drop to shell functionality and also to allow
viewing an error report before we submit it to daisy.
It is almost but not quite surprisingly easy (I added a long-ish comment
about the difficulties).
=> add a way to suspend the subiquity UI and run some other command

console_conf/controllers/identity.py, console_conf/controllers/welcome.py, subiquity/controllers/filesystem.py, subiquity/controllers/identity.py, subiquity/controllers/installprogress.py, subiquity/controllers/keyboard.py, subiquity/controllers/mirror.py, subiquity/controllers/proxy.py, subiquity/controllers/refresh.py, subiquity/controllers/snaplist.py, subiquity/controllers/ssh.py, subiquity/controllers/welcome.py, subiquity/controllers/zdev.py, subiquitycore/controller.py, subiquitycore/controllers/network.py, subiquitycore/core.py
Nothing very deep here. Rename BaseController.default to BaseController.start_ui.
=> refactor some controller stuff

subiquitycore/ui/stretchy.py, subiquitycore/view.py
Also add overridable opened/closed hooks.
=> move stretchy signals from overlay to stretchy itself

console_conf/cmd/tui.py, subiquity/cmd/tui.py, subiquity/controllers/filesystem.py, subiquity/controllers/installprogress.py, subiquity/controllers/refresh.py, subiquity/controllers/ssh.py, subiquity/controllers/welcome.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/compound.py, subiquity/ui/views/filesystem/disk_info.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/guided.py, subiquity/ui/views/filesystem/raid.py, subiquity/ui/views/keyboard.py, subiquity/ui/views/proxy.py, subiquity/ui/views/snaplist.py, subiquity/ui/views/welcome.py, subiquity/ui/views/zdev.py, subiquitycore/core.py, subiquitycore/log.py, subiquitycore/netplan.py, subiquitycore/prober.py, subiquitycore/signals.py, subiquitycore/tasksequence.py, subiquitycore/ui/table.py, subiquitycore/ui/views/network.py, subiquitycore/ui/views/network_configure_manual_interface.py, subiquitycore/utils.py
And a few other things I couldn't resist as I was looking around.
I think my opinion is generally coming around to the view that each "significant" user action (obviously a bit vague, but I mean something like opening or closing a dialog, switching screen but definitely not just typing in a text field or moving focus around) should result in one log message. Not there yet, there are definitely some redundant log lines and I do wonder if we should make more of a distinction between debug and info and create a subiquity-info.log as well. But this is still better, I think.
=> clean up logging a touch

subiquitycore/core.py
Not sure how I didn't notice this when implementing it for the first
time but well. This is all fairly confusing.
=> fix run_command_in_foreground to disconnect from stdin while in background

subiquity/cmd/tui.py, subiquitycore/core.py
This makes s390x ASCII installer look extra nice!
=> Add ASCII mode

subiquitycore/core.py
Without custom colors, white on colored backgrounds is hard to read. Thus in ascii mode, use more contrasting colors from the pallete (ie. black on colored).
Also add one more substitution to use box drawing characters in the scrollbar.
This fixes https://bugs.launchpad.net/subiquity/+bug/1847072
=> Asciify color pallete

subiquity/models/filesystem.py
LP: #1848533
https://bugs.launchpad.net/subiquity/+bug/1848533
=> WWN is confusing, for non-multipathed (but multipath capable) drives.

subiquity/controllers/filesystem.py, subiquity/core.py, subiquitycore/core.py
This is actually pretty easy! I am a bit worried about the amount of log spam that will result from this, maybe it won't be too bad in practice.
=> reprobe block devices on udev events

snapcraft.yaml, subiquity/cmd/tui.py, subiquity/controllers/error.py, subiquity/controllers/filesystem.py, subiquity/controllers/installprogress.py, subiquity/controllers/refresh.py, subiquity/core.py, subiquitycore/core.py
This doesn't have any of the nice UI we designed for presenting and uploading crash reports, but it should still be useful. Please ask if anything doesn't make sense, some of the mysterious things might become clearer when I add the UI code but quite possibly some of it is redundant now.
=> generate crash reports

subiquitycore/prober.py
A recent branch carefully called Prober.get_storage() whenever a udev
block device event was seen. But Prober.get_storage() cached the results
from probert rendering that useless. Rip the caching and some other
complexity out of the prober class.
=> stop caching probed storage data

subiquity/controllers/filesystem.py
The installer now lets you restart after an install failure, but unless
we do something like this, the target system still being mounted will
make life confusing.
It's more robust to be defensive and try to unmount at startup rather
than trying to unmount before restarting.
=> if /target exists, run curtin umount /target before first disk probe

scripts/installdeps.sh, scripts/replay-curtin-log.py, snapcraft.yaml, subiquity/controllers/error.py, subiquity/controllers/installprogress.py, subiquity/core.py, subiquity/ui/views/error.py
Probably not really ready but might be interesting to play with. Will make a video tomorrow :)
=> enable sending reports to daisy

subiquitycore/core.py
the symptom of the bug fixed is that exceptions that crash the process
do not get reported sensibly.
=> get a fix from upstream urwid

console_conf/controllers/identity.py, subiquity/controllers/__init__.py, subiquity/controllers/error.py, subiquity/core.py, subiquity/ui/views/error.py, subiquity/ui/views/help.py, subiquitycore/controller.py, subiquitycore/core.py
The duplication between next_screen and prev_screen has bugged me for ages!
=> refactor how controllers are stored

subiquity/ui/views/snaplist.py
In urwid design language () are radio buttons, and [] are checkboxes.
=> Switch snaplist checkbox from () to []

subiquity/cmd/tui.py, subiquity/controllers/error.py, subiquity/controllers/filesystem.py, subiquity/core.py, subiquitycore/core.py, subiquitycore/log.py
Things I wish were in the error reports I'm looking at now.
=> More error report things

subiquitycore/ui/form.py
Somewhat cleaned up version of the hacks I was creating for @xnox's new-disk-ux branch.
=> Form tweaks

DESIGN.md, subiquity/controllers/installprogress.py, subiquitycore/utils.py
=> asyncioify installation

subiquity/controllers/error.py, subiquity/controllers/refresh.py, subiquity/controllers/snaplist.py, subiquitycore/controller.py, subiquitycore/core.py
there will be a bunch of these coming for autoinstall
=> add a class for controllers with no ui

subiquitycore/controller.py, subiquitycore/core.py
a snap update was offered the second time even if it had been
offered already
=> fix RepeatedController

subiquity/ui/views/keyboard.py, subiquitycore/ui/selector.py
Will use this on the guided disk selection view
=> allow Selector to have non-text entries

subiquity/controllers/refresh.py, subiquity/ui/views/refresh.py, subiquitycore/async_helpers.py
Includes a slightly obscure fix for SingleInstanceTask. The interface between the sync and async worlds is a bit grotty :/
=> make the refresh view code use asyncio apis

subiquity/controllers/__init__.py, subiquity/controllers/filesystem.py, subiquity/controllers/identity.py, subiquity/controllers/installprogress.py, subiquity/controllers/keyboard.py, subiquity/controllers/mirror.py, subiquity/controllers/network.py, subiquity/controllers/proxy.py, subiquity/controllers/snaplist.py, subiquity/controllers/ssh.py, subiquity/controllers/welcome.py, subiquity/models/subiquity.py, subiquity/models/tests/test_keyboard.py, subiquity/models/tests/test_subiquity.py, subiquitycore/controller.py, subiquitycore/controllers/network.py
One of the two remaining non-UI uses of urwid signals bites the dust
=> stop using urwid signals to coordinate installation

subiquity/controllers/__init__.py, subiquity/controllers/error.py, subiquity/controllers/filesystem.py, subiquity/controllers/installprogress.py, subiquity/controllers/mirror.py, subiquity/controllers/refresh.py, subiquity/controllers/reporting.py, subiquity/controllers/snaplist.py, subiquity/controllers/ssh.py, subiquity/controllers/tests/test_filesystem.py, subiquity/core.py, subiquitycore/context.py, subiquitycore/controller.py, subiquitycore/controllers/network.py, subiquitycore/core.py, subiquitycore/ui/stretchy.py, subiquitycore/ui/views/network.py
autoinstalls will need to report their progress in a somewhat structured way. This branch hooks into curtin's reporting machinery to do this. 
The commit history is a mess, the diff is inflated by moving code into with blocks and there are some awful hacks around the formatting and level of log messages (and too much is still at INFO) but... I think this approach has legs.
=>  structured reporting

subiquity/controller.py, subiquity/controllers/error.py, subiquity/controllers/filesystem.py, subiquity/controllers/identity.py, subiquity/controllers/installprogress.py, subiquity/controllers/keyboard.py, subiquity/controllers/mirror.py, subiquity/controllers/proxy.py, subiquity/controllers/refresh.py, subiquity/controllers/reporting.py, subiquity/controllers/snaplist.py, subiquity/controllers/ssh.py, subiquity/controllers/welcome.py, subiquity/controllers/zdev.py, subiquitycore/controller.py
There is going to be a chunk of subiquity specific functionality coming
for autoinstalls, this gives us somewhere to put it.
=> make all subiquity controllers used inherit from SubiquityController

subiquity/controller.py, subiquity/controllers/__init__.py, subiquitycore/core.py
* add a way to load just one controller
* fetch the RepeatedController class from a projet specific location
neither used yet, but soon
=> tweak ControllerSet

subiquity/controllers/welcome.py
unless LANG happened to match a supported language exactly, the last language
(currently Ukranian) would be selected by default
=> fix initial highlight on the welcome screen

subiquity/controllers/filesystem.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/guided.py
ping @xnox 
The only problem I have with this is that it looks pretty cluttered in 80x24. Unclear how much we should worry about that.
=> add guided luks options

snapcraft.yaml, subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/partition.py, subiquity/ui/views/filesystem/tests/test_filesystem.py
Stops trying to reformat dasd drives as gpt. Also displays a hint as to which partition type is being created.
=> vtoc support

subiquity/models/filesystem.py
also show extended/logical partitoin state in ui
=> do not count extended partition as using space

subiquity/controllers/refresh.py, subiquity/core.py, subiquity/ui/views/error.py
so that we restart even if systemd does not do it for us
=> restart subiquity when snap refresh completes

README.md
Now with the correct link to the localization itself and the updated string.
=> Added localization link to the README

subiquity/controllers/installprogress.py, subiquitycore/core.py
=> Release tweaks

examples/answers-bond.yaml, subiquity/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/guided.py, subiquitycore/controllers/network.py, subiquitycore/ui/views/network.py
I went through the error tracker since we promoted 20.03.1 to stable and fixed the common things that had obvious causes. Hope to release 20.03.2 pretty soon after this lands.
=> 20.03.1 oopsies

snapcraft.yaml, subiquity/cmd/tui.py, subiquity/core.py
I guess I'd like to know if any of the cloud-init developers think this is insane...
=> wait for cloud init & extract autoinstall config

Makefile, examples/autoinstall-invalid.yaml, subiquity/cmd/schema.py, subiquity/controller.py, subiquity/controllers/cmdlist.py, subiquity/controllers/error.py, subiquity/controllers/filesystem.py, subiquity/controllers/identity.py, subiquity/controllers/keyboard.py, subiquity/controllers/mirror.py, subiquity/controllers/network.py, subiquity/controllers/proxy.py, subiquity/controllers/refresh.py, subiquity/controllers/reporting.py, subiquity/controllers/snaplist.py, subiquity/controllers/ssh.py, subiquity/controllers/welcome.py, subiquity/core.py
I wrote some documentation about all this: https://wiki.ubuntu.com/FoundationsTeam/AutomatedServerInstalls/ConfigSchema
This also fixes some rough edges around error handling and error-commands are now actually run.
=> validate autoinstall data against a schema

examples/autoinstall-interactive.yaml, subiquity/controllers/snaplist.py, subiquity/models/snaplist.py, subiquity/ui/views/snaplist.py
went through a few versions of this locally, this one is pleasingly
small in delta.
=> handle the 'snaps' section of the autoinstall file

subiquity/controllers/network.py
=> update NetworkModel.has_network when non-interactive

subiquity/controllers/snaplist.py
I wrote something in the schema validation branch but then changed it in
another branch in parallel.
=> fix snaplist schema

console_conf/models/console_conf.py, subiquity/controllers/network.py, subiquity/models/subiquity.py, subiquity/models/tests/test_subiquity.py, subiquitycore/controllers/network.py, subiquitycore/models/network.py
rather than via curtin and then cloud-init
=> write netplan directly to the target

examples/autoinstall-interactive.yaml, examples/autoinstall-invalid.yaml, subiquity/cmd/tui.py, subiquity/controllers/cmdlist.py, subiquity/controllers/error.py, subiquity/controllers/filesystem.py, subiquity/controllers/installprogress.py, subiquity/controllers/refresh.py, subiquity/controllers/welcome.py, subiquity/core.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/installprogress.py
This depends on https://github.com/CanonicalLtd/subiquity/pull/661
=> only run autoinstall once

subiquity/controllers/welcome.py
Do not crash when LANG is unset.
=> subiquity/controllers: fix failure when LANG is unset

snapcraft.yaml
pending hearing whether the curtin change was intended.
=> stage efibootmgr for now

subiquity/controllers/filesystem.py, subiquity/controllers/package.py, subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py
=> implement extensions to curtin storage syntax 

subiquitycore/controllers/network.py, subiquitycore/models/network.py, subiquitycore/netplan.py
For some reason this also involved sitting harder on networkd to stop it doing things while we reconfigure the NICs.
=> avoid deleting virtual devices on every network change

subiquity/controllers/filesystem.py, subiquity/models/filesystem.py
1. allow autoinstall config to control swapfile creation
2. allow a layout to use a match to select the disk to install to
=> two parts of the autoinstall storage spec i forgot about

console_conf/controllers/identity.py
I guess it should be rewritten as a form, instead of this old style view.
=> Fix login view button focus to done

subiquity/controllers/filesystem.py, subiquity/controllers/tests/test_filesystem.py, subiquity/models/tests/test_filesystem.py
For https://bugs.launchpad.net/subiquity/+bug/1872464
=> fix handling of install_devices converting storage autoinstall config

subiquity/ui/views/refresh.py
=> Fix choosing continue before snap refresh has completed

subiquity/models/filesystem.py
hopefully fixing https://bugs.launchpad.net/subiquity/+bug/1861369
=> use curtin.block.partition_kname to calculate partition devpath

snapcraft.yaml
because all the cool kids are switching this week too.
=> Switch to core18

snapcraft.yaml, subiquity/cmd/tui.py
This was harder than it should have been!
=> get apport python package and hooks from focal branch

subiquity/models/filesystem.py
for https://bugs.launchpad.net/subiquity/+bug/1872999
=> always clear grub_install_device when removing a partition etc

subiquity/controllers/filesystem.py
wipe a volume before formatting it, wipe a device that used to be part of a compound device.
=> wipe more devices

subiquity/core.py
this might happen when refreshing
=> do not run early-commands again when installer restarts

examples/answers-lvm-dmcrypt.yaml, examples/answers-lvm.yaml, examples/answers-raid-lvm.yaml, examples/answers-raid.yaml, snapcraft.yaml, subiquity/controllers/filesystem.py, subiquity/controllers/tests/test_filesystem.py, subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/partition.py, subiquity/ui/views/filesystem/tests/test_filesystem.py, subiquity/ui/views/filesystem/tests/test_partition.py
Lots of hacks, not tested for real yet.
=>  ui for resilient boot

snapcraft.yaml
https://git.launchpad.net/~ubuntu-core-dev/curtin/commit/?h=ubuntu-20.04&id=1bf7eb5456531bc42952d9a47861c14e95418396
Is the new commit introduced, and the parent of it, is the previous commit id.
=> Update curtin to a hotfix

subiquity/controllers/filesystem.py, subiquity/controllers/tests/test_filesystem.py, subiquity/ui/views/filesystem/filesystem.py
tested this in bionic and focal vms, seemed to work ok!
After this lands I think we can release to stable again.
=> do not offer resilient boot options pre-focal

DESIGN.md, subiquitycore/ui/anchors.py
for https://bugs.launchpad.net/ubuntu-z-systems/+bug/1874314
=> do not crash in a terminal < 76 columns wide

subiquity/core.py
for https://bugs.launchpad.net/subiquity/+bug/1874052
=> run "stty sane" in a non-interactive install on the serial line

subiquity/controllers/filesystem.py, subiquity/ui/views/filesystem/guided.py
For https://bugs.launchpad.net/subiquity/+bug/1785321
=> have the lv created by the guided lvm option take up 80% of the vg

subiquity/controllers/filesystem.py, subiquity/controllers/installprogress.py, subiquity/controllers/refresh.py, subiquity/core.py, subiquity/lockfile.py, subiquitycore/core.py
This is the fix bit of https://github.com/CanonicalLtd/subiquity/pull/738 before @raharper pushed me to make it better and more complicated
=> do not block probe during install

examples/autoinstall.yaml, scripts/runtests.sh, scripts/validate-yaml.py, subiquity/models/filesystem.py
Fixes two problems: spare_devices should be optional, sizes specified using e.g. "1G" short cuts ended up as floats, not ints
=> raid fixes

subiquity/ui/views/installprogress.py
this is a global overlay now but i forgot to update its code
=> fix install confirmation

scripts/runtests.sh, subiquity/controller.py, subiquity/controllers/cmdlist.py, subiquity/controllers/filesystem.py, subiquity/controllers/identity.py, subiquity/controllers/installprogress.py, subiquity/controllers/keyboard.py, subiquity/controllers/mirror.py, subiquity/controllers/network.py, subiquity/controllers/proxy.py, subiquity/controllers/reboot.py, subiquity/controllers/refresh.py, subiquity/controllers/reporting.py, subiquity/core.py, subiquity/ui/views/installprogress.py, subiquitycore/context.py, subiquitycore/controllers/network.py
i want this to help debug another branch i am working on!
also refactor some of the context handling code to be simpler and more regular
=> make it easier to nest contexts appropriately

examples/autoinstall.yaml, subiquity/controllers/network.py, subiquity/models/network.py, subiquity/models/subiquity.py, subiquitycore/controllers/network.py
=> copy autoinstall netplan to target

subiquity/controllers/cmdlist.py, subiquity/controllers/filesystem.py, subiquity/controllers/identity.py, subiquity/controllers/installprogress.py, subiquity/controllers/network.py, subiquity/controllers/proxy.py, subiquity/controllers/reboot.py, subiquity/controllers/refresh.py, subiquity/controllers/snaplist.py, subiquity/controllers/ssh.py, subiquitycore/context.py, subiquitycore/controllers/network.py
the decorated function must now be called with keyword arguments
=> improve with_context helper a bit, use it more

examples/autoinstall.yaml, scripts/validate-yaml.py, subiquity/models/filesystem.py
https://bugs.launchpad.net/subiquity/+bug/1876874
=> round autoinstall partition sizes using percentages down to a megabyte boundary

subiquity/controllers/cmdlist.py
so one does not have to pass --target to curtin in-target in a
late-command
=> set $TARGET_MOUNT_POINT when running late-commands

subiquity/controllers/mirror.py
I initialized things in the wrong order
=> allow autoinstalls to disable geoip

subiquity/models/subiquity.py
only applicable in the autoinstall case
see https://discourse.ubuntu.com/t/please-test-autoinstalls-for-20-04/15250/99
=> do not set preserve_hostname if there is no hostname set

subiquity/core.py
Signed-off-by: Igor Ryzhov <iryzhov@nfware.com>
=> write version into autoinstall-user-data

subiquitycore/models/network.py, subiquitycore/ui/views/network_configure_wlan_interface.py
WiFi screen was broken since NetDev refactor. Unbreak it.
=> network: fix wifi screen

examples/autoinstall.yaml, scripts/runtests.sh, subiquity/cmd/tui.py
I did this in another branch but now I want it here.
=> call setlocale() and set LC_CTYPE to C.UTF-8 if it fails

subiquity/ui/views/help.py, subiquity/ui/views/tests/test_welcome.py, subiquity/ui/views/welcome.py, subiquitycore/core.py
This is mostly a RFC currently, there's some bad code I want to clean up if we think it's a good idea.
Demo at https://asciinema.org/a/3dDg5jPWCmuBLf5AQtoFWpqyj
=> start in a super basic mode on serial, offer upgrade immediately

subiquity/core.py, subiquity/ui/frame.py, subiquity/ui/views/help.py, subiquity/ui/views/welcome.py
meant to do this before landing my recent branch
=> make it easier to open a help topic

languagelist, scripts/make-language-lists, snapcraft.yaml, subiquity/controllers/welcome.py, subiquity/models/locale.py, subiquity/ui/views/help.py, subiquity/ui/views/tests/test_welcome.py, subiquity/ui/views/welcome.py
Use language names and console-suitability from localechooser with some special cases.
For https://bugs.launchpad.net/subiquity/+bug/1873342
=> make language list at snap build time

subiquity/controllers/refresh.py
I am not sure when I dropped this :(
=> catch errors raised by checking for a snap update

console_conf/controllers/identity.py, console_conf/ui/views/login.py, debian/control, po/POTFILES.in, subiquity/core.py, subiquitycore/snapd.py
=> use snapd apis to check for users

scripts/inject-subiquity-snap.sh
I know a bit more about xorriso now :)
=> clean up the xorriso arguments in inject-subiquity-snap a bit

console_conf/controllers/chooser.py, console_conf/controllers/identity.py, console_conf/controllers/welcome.py, console_conf/core.py, subiquity/controller.py, subiquity/controllers/cmdlist.py, subiquity/controllers/debconf.py, subiquity/controllers/filesystem.py, subiquity/controllers/identity.py, subiquity/controllers/installprogress.py, subiquity/controllers/keyboard.py, subiquity/controllers/mirror.py, subiquity/controllers/network.py, subiquity/controllers/package.py, subiquity/controllers/proxy.py, subiquity/controllers/reboot.py, subiquity/controllers/refresh.py, subiquity/controllers/reporting.py, subiquity/controllers/snaplist.py, subiquity/controllers/ssh.py, subiquity/controllers/userdata.py, subiquity/controllers/welcome.py, subiquity/controllers/zdev.py, subiquity/core.py, subiquitycore/controller.py, subiquitycore/controllers/network.py, subiquitycore/core.py, subiquitycore/tui.py, subiquitycore/tuicontroller.py
The subiquity server process will not have a UI, so we need to start splitting fundamental from UI code.
=> remove all UI code from "core" application object, add tuiapplication

Makefile, requirements.txt, subiquity/common/api/__init__.py, subiquity/common/api/client.py, subiquity/common/api/defs.py, subiquity/common/api/server.py, subiquity/common/api/tests/__init__.py, subiquity/common/api/tests/test_client.py, subiquity/common/api/tests/test_endtoend.py, subiquity/common/api/tests/test_server.py, subiquity/common/serialize.py, subiquitycore/contextlib38.py
Nothing uses this yet, but it might be interesting to review!
=> add api definition and support code for client server split

subiquity/common/types.py, subiquity/controllers/identity.py, subiquity/controllers/mirror.py, subiquity/controllers/proxy.py, subiquity/controllers/ssh.py, subiquity/models/identity.py, subiquity/ui/views/identity.py, subiquity/ui/views/mirror.py, subiquity/ui/views/proxy.py, subiquity/ui/views/ssh.py, subiquity/ui/views/tests/test_identity.py
These are the easiest views to convert.
=> convert proxy, mirror, identity, ssh views to only refer to simple types

subiquity/controller.py, subiquity/core.py, subiquity/models/subiquity.py, subiquity/ui/views/snaplist.py, subiquitycore/tui.py, subiquitycore/ui/utils.py
and some cleanups this enables.
=> allow make_ui to be async

subiquity/common/types.py, subiquity/controllers/filesystem.py, subiquity/controllers/installprogress.py, subiquity/core.py, subiquity/ui/frame.py, subiquity/ui/views/installprogress.py, subiquity/ui/views/tests/test_installprogress.py, subiquitycore/context.py, subiquitycore/controllerset.py
This fixes some warts in how install failures are presented that have been around for a long time :(
=> tidy up interface between progress view and controller

subiquity/common/types.py, subiquity/controllers/refresh.py, subiquity/ui/views/refresh.py
=> make refresh view/controller interface more client/server friendly

console_conf/core.py, examples/answers.yaml, subiquity/cmd/common.py, subiquity/cmd/server.py, subiquity/cmd/tui.py, subiquity/common/apidef.py, subiquity/common/types.py, subiquity/core.py, subiquity/server/controllers/__init__.py, subiquity/server/server.py, subiquitycore/core.py, subiquitycore/log.py
run it automatically in dry-run mode
=> add a minimal server process

subiquity/cmd/tui.py, subiquity/core.py
otherwise, when we start adding server restarts to the mix, it is easy to
end up with multiple server processes running
=> handle automatically run server processes in dry-run mode better

subiquity/controller.py, subiquity/core.py, subiquitycore/core.py, subiquitycore/tui.py
More client / server prep, obviously.
=> refactor startup and state management a bit

subiquity/controllers/installprogress.py, subiquity/controllers/reporting.py, subiquity/core.py, subiquity/journald.py
this means curtin events go through the journal twice, but that has to happen
when client and server get split
=> feed progress view via journal

subiquity/controllers/welcome.py
LP: #1900707
https://bugs.launchpad.net/subiquity/+bug/1900707
=> welcome: fix crash on serial ip addresses

scripts/inject-subiquity-snap.sh
This doesn't work because the quoting goes wrong. But we can probably make something like this work.
=> use -report_el_torito as_mkisofs option of xorriso to find command to repack ISO

console_conf/controllers/identity.py, console_conf/core.py
For https://bugs.launchpad.net/subiquity/+bug/1903050
=> trivial fixes for console_conf breakage

snapcraft.yaml, subiquity/client/client.py, subiquity/client/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/tests/test_filesystem.py, subiquitycore/controllers/network.py
Together with the referenced branches (which should be merged before this branch lands I guess), this should fix all the bugs I know about with dasds.
=> fixes for FBA, unformatted, and passed-via virtio dasds

subiquity/client/client.py, subiquity/common/types.py, subiquity/server/controllers/cmdlist.py, subiquity/server/server.py
This makes the code to print the output from early commands a bit
simpler, and would make the output of error commands visible if anything
actually ran the error commands (coming soon to a PR near you!)
=> have the client unconditionally print whatever comes over one syslog id

subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py
also allow matching on ID_VENDOR
=> check udev data directly when processing match: specs

subiquity/common/types.py, subiquity/models/filesystem.py, subiquity/server/controllers/filesystem.py
so the ptable ends up being correct
I did this once already but apparently accidentally dropped the change before merging
=> pass data about dasds from server to client

subiquity/server/controllers/network.py, subiquitycore/tui.py, subiquitycore/ui/views/network.py, subiquitycore/ui/views/network_configure_manual_interface.py, subiquitycore/ui/views/tests/test_network_configure_manual_interface.py
fixes half of https://bugs.launchpad.net/subiquity/+bug/1912955
=> fix crash when trying to view nic info

languagelist, scripts/make-language-lists
=> scripts: fix make-language-lists for non-languagelist languages

subiquity/journald.py, subiquity/server/controllers/install.py
for https://bugs.launchpad.net/subiquity/+bug/1912957
=> do not stop listening to curtin events when the curtin process exits

Makefile, autoinstall-schema.json, scripts/runtests.sh, subiquity/cmd/schema.py
It seems schema generation was broken during the client/server refactor.
Address that.
Add a test to help enforce the current schema against unintended changes.
=> Schema generation fix and test

subiquity/client/controllers/filesystem.py, subiquity/cmd/schema.py
autoinstall stuff is a strictly server side thing
I should have read the previous PR a little closer :)
=> simplify schema generation

subiquity/common/filesystem.py, subiquity/ui/views/filesystem/lvm.py
for https://bugs.launchpad.net/bugs/1905412
=> do not try to reuse a name of an existing vg in guided_lvm

subiquity/common/errorreport.py
=> fix submitting error reports

subiquity/client/client.py, subiquity/client/controllers/welcome.py, subiquity/common/apidef.py, subiquity/common/types.py, subiquity/server/server.py, subiquity/ui/views/help.py, subiquity/ui/views/welcome.py, subiquitycore/ssh.py
We used to have cloud-init do this but it hides the password better now.
=> have subiquity set password for installer user in live session

subiquity/client/client.py, subiquitycore/tui.py
This fixes a problem where you drop to a shell and refresh subiquity
from that shell -- the client tries to restart but it is running in the
background and so crashes trying to modify the terminal settings. So
this kills the subprocess before restarting. This required the extremely
angry PR I sent before: forcefully killing the subprocess also crashes
the client before restart in a similar way.
=> kill any foreground subprocess before restarting

subiquity/client/controllers/welcome.py, subiquity/cmd/server.py, subiquity/models/subiquity.py, subiquity/server/server.py
No particular reason to sneak this in before release, but otoh it should be pretty harmless.
=> remove some dead code

subiquity/models/subiquity.py
debugging Launchpad bug 1926616 would have been much easier if this was
working!
=> fix logging unconfigured models

subiquity/server/controllers/network.py
https://bugs.launchpad.net/subiquity/+bug/1926132
=> fix crash on network apply failure

Makefile
Skip a recursive make step and simplify a bit.
Add dryrun-server.
Also an unrelated whitespace fix.
=> Rearrange makefile targets

subiquity/client/controllers/network.py, subiquity/common/apidef.py, subiquity/server/controllers/network.py
nothing will call these yet because we are still hiding wlan nics in the
model but its all simple enough
=> add wlan-related methods to API

po/POTFILES.in, subiquity/common/filesystem/actions.py, subiquity/common/filesystem/boot.py, subiquity/common/filesystem/labels.py, subiquity/common/filesystem/manipulator.py, subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py, subiquity/server/controllers/filesystem.py, subiquity/ui/views/filesystem/filesystem.py, subiquity/ui/views/filesystem/partition.py
This is the stuff that will need to change to support putting ESPs on VROC raid volumes.
=> make booting related queries singledispatch methods

subiquity/models/network.py
Perhaps a bit trivial for a PR to itself but oh well.
=> write any wifi config to a file only readable by root

examples/mwhudson.json, subiquity/client/controllers/network.py, subiquity/common/apidef.py, subiquity/common/types.py, subiquity/models/network.py, subiquity/server/controllers/install.py, subiquity/server/controllers/network.py, subiquitycore/models/network.py, subiquitycore/ui/views/network.py
This should (together with seed changes) should be enough to support wifi in subiquity. Haven't tested it yet though!
=> install wpasupplicant when a wifi nic is seen

po/ast.po, po/be.po, po/bo.po, po/ca.po, po/cs.po, po/de.po, po/el.po, po/en_GB.po, po/en_US.po, po/es.po, po/fi.po, po/fr.po, po/he.po, po/hr.po, po/hu.po, po/id.po, po/kab.po, po/lt.po, po/lv.po, po/nb.po, po/nl.po, po/oc.po, po/pl.po, po/ru.po, po/sr.po, po/sv.po, po/uk.po, po/zh_CN.po, subiquity/ui/views/ssh.py
=> Correct spelling of GitHub

scripts/installdeps.sh
to work around bug #1925745 in apt until it is SRUed.
=> install packages with -o APT::Get::Always-Include-Phased-Updates=true

subiquity/models/filesystem.py, subiquity/server/controllers/filesystem.py
so I can adapt a call to not require changes when imsm volumes become
possible boot devices
=> make two FilesystemModel helper methods slightly more general

subiquity/models/filesystem.py
for https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1933711
=> allow a mount action to not have a device

scripts/runtests.sh, scripts/validate-yaml.py
an ESP can be on a RAID now. Also always run the integration tests in UEFI mode.
=> fix "make check" on uefi systems

subiquity/common/filesystem/manipulator.py
found this by mistake by accident when trying to test something else...
=> fix adding a partition to an existing raid

scripts/slimy-update-snap.sh, scripts/update-part.py
Also tweak scripts/update-part.py to work better when switching
repositories.
=> have slimy-update-snap.sh update curtin in the snap too

Makefile, scripts/installdeps.sh, scripts/runtests.sh, subiquity/common/apidef.py, subiquity/server/controllers/filesystem.py
* Adds bitlocker info query API
* Adds first API test to runtests for above
=> Add /storage/has_bitlocker convenience API

subiquity/common/types.py, system_setup/client/controllers/wslconfadvanced.py, system_setup/models/wslconfadvanced.py
This fixes the TODO 1 for the WSL OOBE
1. Remove duplicated fields between `wslconfadvanced` and `wslconfbase`.
=> DE-97 - system_setup: reduce WSLConfigurationAdvanced size

subiquity/models/network.py, subiquity/models/ssh.py, subiquity/models/subiquity.py, subiquity/server/controllers/install.py, subiquity/server/server.py
Deciding which packages to install for language in a desktop build isn't totally trivial, so lets make it possible to have it done by an async method.
=> generalize how models can ask for pcakges to be installed in the target

subiquity/models/subiquity.py, subiquity/models/tests/test_subiquity.py, subiquity/server/controller.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/identity.py, subiquity/server/controllers/keyboard.py, subiquity/server/controllers/locale.py, subiquity/server/controllers/mirror.py, subiquity/server/controllers/network.py, subiquity/server/controllers/proxy.py, subiquity/server/controllers/snaplist.py, subiquity/server/controllers/source.py, subiquity/server/controllers/ssh.py, subiquity/server/controllers/timezone.py, subiquity/server/server.py, subiquity/server/types.py, system_setup/models/system_setup.py, system_setup/server/controllers/wslconfadvanced.py, system_setup/server/controllers/wslconfbase.py, system_setup/server/server.py
I'm not _sure_ the change to make configured async is necessary but it probably makes things more flexible...
=> Have SubiquityController.configured broadcast rather than set an event

subiquity/client/client.py, subiquity/cmd/tui.py, subiquity/common/types.py, subiquity/server/server.py, system_setup/cmd/tui.py
and check this in client when getting status over api fails
=> write server state to disk when it is updated

system_setup/common/wsl_utils.py, system_setup/server/controllers/__init__.py, system_setup/server/controllers/configure.py, system_setup/server/controllers/locale.py, system_setup/server/controllers/shutdown.py, system_setup/server/controllers/wslconfadvanced.py, system_setup/server/controllers/wslconfbase.py, system_setup/server/server.py
This fixes "Locale/Base/Advanced models should be initialized with current values on the system."
=> DE-100 - Locale/Base/Advanced models initialization

subiquity/models/locale.py, subiquity/models/source.py, subiquity/models/subiquity.py, subiquity/server/controllers/locale.py, subiquitycore/utils.py, system_setup/models/system_setup.py
This branch does two main things:
1. it installs language support packages in desktop installs
2. it does not configure a locale for a minimal server install
=> improve locale support

subiquity/tests/api/test_api.py
This is part of a changeset intended to have the API tests run in
parallel.  I don't consider this ideal - I still see failures when
running tests in parallel - but am providing it now with the intent of
helping people who are seeing api test flakiness even when those tests
are run serially.
* check for socket existence on startup
* lengthen timeouts on shutdown
=> test/api: make less flaky

scripts/kvm-test.py
Updated version of the kvm-test script shown previously.
=> scripts: add kvm-test

scripts/kvm-test.py
The script is great but I found I needed to make a few changes.
=> kvm-test: assorted updates

subiquity/models/subiquity.py, subiquity/models/tests/test_subiquity.py, subiquity/server/controllers/install.py, subiquity/server/curtin.py, subiquity/server/runner.py, subiquity/server/server.py
More shuffling of code around. I will start doing something interesting with this next, I promise :)
=> refactor curtin invocation some more

autoinstall-schema.json, subiquity/common/apidef.py, subiquity/models/mirror.py, subiquity/models/tests/test_mirror.py, subiquity/server/apt.py, subiquity/server/controllers/mirror.py, subiquity/server/controllers/tests/test_mirror.py, subiquity/server/server.py, subiquity/tests/api/test_api.py
Add API, and document for autoinstall, the ability to pass in components to
disable in apt.
=> apt: disable_components

subiquity/server/controllers/install.py
this makes the apt configuration appear in the progress view in the
client
=> pass install context to configure_apt method

subiquity/server/controllers/install.py
=> pass -t /target to the system-install command

Makefile, subiquity/common/snap.py, subiquity/common/tests/test_snap.py
Hello,
Just some minor fixes to cleanup the Makefile and remove typos from my recent PR.
Nothing serious, nothing urgent.
Thanks,
Olivier
=> Minor fixes in Makefile and tests

scripts/kvm-test.py
* better command execution
* various build arguments imply --build, so one can do just '-q' where
one would have to previously '--build -q'
=> kvm-test: cleanups

autoinstall-schema.json, examples/autoinstall.yaml, scripts/runtests.sh, subiquity/server/controllers/ubuntu_advantage.py
Hello,
This PR adds support for Ubuntu Advantage token when running Subiquity with `--autoinstall`.
Also added a dummy token in the integration tests.
Thanks,
Olivier
refs FR-1652
=> Add support for ubuntu-advantage with autoinstall

subiquity/server/controllers/filesystem.py
For https://bugs.launchpad.net/bugs/1954848
=> do not accept probert results after user has submitted a filesystem config

subiquity/server/controllers/mirror.py
=> initialize MirrorController.configure_once to False

subiquity/models/subiquity.py
When running an autoinstallation with only “network” as an interactive section, the installation hanged after the following steps:
```
finalizing installation
running 'curtin hook'
curtin command hook
executing late commands
```
where in normal conditions, the next step is:
```
final system configuration
```
Also, querying the meta/status endpoint at this point shows that the app is in POST_WAIT state.
Rationale:
* the network model is declared as both an “install” model and a “postinstall” model (it is the only one we have AFAIK)
* when calling `.configured()` for a given model, we only trigger /at max/ one event. Either:
* `install_event` (if the model is an “install” model - and it is the last one configured)
* `postinstall_event` (if the model is a “postinstall” model but not an …
=> Fix hanging when network is the last postinst model configured

subiquity/ui/views/refresh.py
Per LP: #1962025, the update screen can get stuck in test automation.
Cancel the task waiting to see if there is an update, which makes sense
more broadly anyhow in that if a regular UI user has declined the
update then the check task is no longer helpful.
=> refresh: cancel the task waiting on update

subiquity/server/server.py
=> catch the correct exception when waiting for cloud-init

subiquity/common/filesystem/gaps.py, subiquity/common/filesystem/labels.py, subiquity/common/filesystem/manipulator.py, subiquity/common/filesystem/tests/test_actions.py, subiquity/common/filesystem/tests/test_gaps.py, subiquity/common/filesystem/tests/test_manipulator.py, subiquity/common/types.py, subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py, subiquity/server/controllers/filesystem.py, subiquity/tests/api/test_api.py, subiquity/ui/views/filesystem/tests/test_filesystem.py, subiquity/ui/views/filesystem/tests/test_partition.py
* use alignment data to help place partitions & gaps
* parts & gaps will report gaps if there are preexisting partitions
=> filesystem: show offset in gap & partition

subiquity/tests/api/test_api.py
With this, the API tests are currently storage-version=2 clean.
Also some minor cleanup of the v2_flow test.
=> api test: fix flow test for v2 storage actions

subiquity/server/server.py, subiquity/server/tests/test_server.py
=> autoinstall: allow cloud source to override iso source

snapcraft.yaml, subiquity/cmd/server.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py, subiquitycore/prober.py, subiquitycore/tests/test_prober.py
* add command line arg for using os-prober
* use probe_types to pass message along
=> probert: use os-prober only if asked

subiquity/common/filesystem/boot.py, subiquity/common/filesystem/manipulator.py, subiquity/common/filesystem/tests/test_manipulator.py, subiquity/tests/api/test_api.py
This is all a bit crazy but it think it will make the conversion of this logic to the v2 partitioning world a lot more self-contained.
=> Combine "can this be" and "make this a" boot disk logic

examples/answers-system-setup-reconf.yaml, system_setup/client/controllers/wslconfadvanced.py, system_setup/server/controllers/configure.py, system_setup/tests/golden/answers-reconf/wsl.conf, system_setup/ui/views/wslconfadvanced.py
Removed systemd from the UI. However it can still be enabled manually from wsl.conf.
=> Wsl remove systemd

subiquity/common/filesystem/gaps.py, subiquity/common/filesystem/manipulator.py, subiquity/common/filesystem/tests/test_gaps.py, subiquity/models/filesystem.py, subiquity/ui/views/filesystem/partition.py
Also correct the max_size in the partition stretchy.
=> keep partition offsets up to date as they are deleted and resized

subiquity/server/geoip.py, subiquity/server/tests/test_geoip.py
This reverts commit ebdf1db63619424d06f7597f0c358e72cae4eedc.
Jammy merge of #1278
LP: #1969393
=> Revert "Move to aiohttp for GeoIP requests"

apt-deps.txt, subiquity/common/filesystem/boot.py, subiquity/common/filesystem/tests/test_manipulator.py
Turns out I had half of this sitting around in a branch I'd forgotten about.
=> make "can this be a boot partition" use v2 capabilities

snapcraft.yaml, subiquity/common/apidef.py, subiquity/common/filesystem/labels.py, subiquity/common/filesystem/manipulator.py, subiquity/common/filesystem/tests/test_manipulator.py, subiquity/common/types.py, subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py, subiquity/server/controllers/filesystem.py, subiquity/tests/api/test_api.py
Allow resize by way of storage/v2/edit_partition
=> Enable resize

subiquity/common/filesystem/labels.py
Cooking this up took no time, cooking up a machine config that lets me see what it looks like is something I don't have time for now :)
=> indent logical partitions and gaps in extended partitions

snapcraft.yaml
Merged MP on curtin side: https://code.launchpad.net/~ogayot/curtin/+git/curtin/+merge/420651
=> curtin: pickup fix for HTTP proxy settings being discarded

snapcraft.yaml
Updated curtin for proxy fix
Update probert for raid fix
=> server/jammy: merge two fixes

subiquity/common/filesystem/boot.py
The Gap object created in boot plans had size == 0, which can cause
problems if create_partition() actually looks at this size.
=> boot: update plans to use a better Gap

subiquity/common/filesystem/gaps.py, subiquity/common/filesystem/tests/test_gaps.py, subiquity/models/tests/test_filesystem.py
Add gap.split() and gaps.at_offset().
=> gap: several utilities

subiquity/common/filesystem/gaps.py, subiquity/common/filesystem/tests/test_gaps.py
Also an unrelated Exception tweak.
=> gaps: allow largest_gap to accept a list

subiquity/common/filesystem/manipulator.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py
Marked draft as this needs a bit more testing before I would be comfortable merging.
=> filesystem: autoinstall support use_gap mode

subiquity/client/controllers/ubuntu_pro.py, subiquity/ui/views/ubuntu_pro.py
ubuntu-pro: don't assume an overlay is present in show_* functions
show_* functions from the UbuntuProView object always assumed that the loading overlay was present. When called, they would therefore attempt to close the overlay. This results in a crash if no overlay is present.
With the current design, it is fine because we never call the show_* functions without an overlay being present.
However, with new design of Ubuntu Pro, sometimes the show_* functions will be called without an overlay.
We now delegate the responsibility of removing the overlay by using a callback system.
=> ubuntu-pro: don't assume an overlay is present in show_* functions

subiquity/server/server.py, subiquity/server/tests/test_server.py
The documentation specifies that we shall copy the autoinstall file to
/autoinstall.yaml, regardless of how we obtained the info.
This appears redundant with the reload location, so phase that out.
=> autoinstall: fix where ai file is copied

snapcraft.yaml, subiquity/client/client.py, subiquity/server/controllers/refresh.py
Otherwise the refresh awareness blocks refresh when you are connected
via SSH.
=> Pass ignore-running: true when refreshing ourself

.github/workflows/build.yaml, snapcraft.yaml
Cherry-pick: db95d2f
Also cherry-pick 5bd940c for CI.
=> snapcraft: set contact field

subiquity/common/filesystem/actions.py, subiquity/common/filesystem/gaps.py, subiquity/common/filesystem/labels.py, subiquity/common/filesystem/tests/test_gaps.py, subiquity/common/types.py, subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/tests/api/test_api.py
* stricter numbering of logical partitions
* catch overallocation of primary part numbers for msdos/vtoc
* some unit test improvements
=> filesystem: logical part numbering and related

subiquity/server/controllers/keyboard.py
This is a partial fix to canonical/ubuntu-desktop-installer#832. The last missing piece is to set the `DISPLAY` environment variable but this can be done in the Subiquity startup script in UDI: https://github.com/canonical/ubuntu-desktop-installer/pull/1021.
=> Run setxkbmap as the ubuntu user

scripts/yaml-normalize.py, snapcraft.yaml
Normalized yaml is nice for subsequent programmatic changes.
=> Yaml normalize

subiquity/client/controllers/ubuntu_pro.py
Cherry-pick https://github.com/canonical/subiquity/pull/1414 to ubuntu/kinetic.
=> Cherry-pick to kinetic: ubuntu-pro: fixed model not being marked configured on LTS

subiquity/models/subiquity.py, subiquity/server/apt.py, subiquity/server/controllers/install.py, subiquity/server/controllers/tests/test_install.py
Prep work for fde installs being ... different.
Not sure if this is the right final form but it's probably a step in the right direction.
=> refactor CurtinInstallStep a bit

subiquitycore/ui/form.py
=> Defaults help text style to gray (kinetic)

subiquitycore/controllers/network.py, subiquitycore/models/network.py, subiquitycore/models/tests/test_network.py
Cherry-pick 9e0a90fc229fe707035a95d65645b3ef04d2945f
LP: #1983265
=> network: use routes instead of gateway directives (kinetic)

subiquity/server/controllers/mirror.py
The mirror controller is responsible from creating the APT configuration once its associated model is marked configured. However, the APT configuration is also dependent on the source model being marked configured.
When subiquity is used for the server installer, the client immediately sends a POST /a/meta/client_variant request. This ends up marking the source model as configured (even though I think it should not - and the default value does not make much sense). So we never end up in a scenario where the mirror model is marked configured before the source model.
When Subiquity is used by a different client, such as the ubuntu-desktop-installer, it is possible that we mark the mirror model configured first. This ends up crashing the installer.
Fixed by adding a dependency on the source …
=> mirror: only start configuring APT once source & mirror are configured

subiquity/server/controllers/kernel.py, subiquity/server/controllers/tests/test_kernel.py
Marking draft due to ongoing crashes related to /cdrom.
=> kernel: fix autoinstall and run file

subiquity/common/serialize.py, subiquity/common/tests/test_serialization.py
I want to start using attrs objects when talking to the snapd API. This requires a bit more flexibility in the serialization code.
=> serialization enhancements in preparation for talking to snapd api

scripts/runtests.sh
The second `trap ... EXIT` registration meant that the first one, the one repsonsible for providing a clear PASS / FAIL at the end, was not being shown.
=> runtests: ensure message shown at end

scripts/kvm-test.py
The `--cloud-config` option now replaces the old `--autoinstall-file` option.
The use of `--autoinstall-file` always made kvm-test pass the `autoinstall` argument to the kernel command line. With the `--cloud-config` option, we now determine if the `autoinstall` argument is needed by reading the cloud config and checking if an autoinstall section is present.
The two new options `--force-autoinstall` and `--force-no-autoinstall` can be used to override this behaviour.
The `--autoinstall` option is also dropped. If we want to use the default, hardcoded cloud-config, one can use `--cloud-config-default`.
Example of an useful snippet that can be used to debug an installation with more ease:
```yaml
#cloud-config
users:
- default
- name: root
ssh_import_id: lp:ogayot
```
=> kvm-test: allow to specify a cloud-init file not meant for autoinstall

reserved-usernames, snapcraft.yaml, subiquity/common/filesystem/gaps.py, subiquity/common/filesystem/tests/test_gaps.py, subiquity/models/tests/test_filesystem.py, subiquity/server/controllers/kernel.py, subiquity/server/controllers/mirror.py, subiquity/server/controllers/snaplist.py, subiquity/server/controllers/tests/test_kernel.py, subiquity/server/controllers/tests/test_snaplist.py
* cherry-picked c063717..aff9ed0a from #1430 for LP: #[1987341](http://pad.lv/1987341)
* cherry-picked ecb6cb6 from #1418 for LP: #[1988407](http://pad.lv/1988407)
* cherry-picked 83a7aff from #1425
* cherry-picked b9f9aee from #1419 for LP: #[1980584](http://pad.lv/1980584)
* cherry-picked 5c636ac..9d5ae67 from #1426 for LP: #[1989193](http://pad.lv/1989193) and LP: #[1989198](http://pad.lv/1989198)
* cherry-picked 884f296 from #1428 for LP: #[1989353](http://pad.lv/1989353)
=> Kinetic merge 2022-09-28

subiquity/common/api/defs.py, subiquity/common/api/tests/test_client.py, subiquity/common/apidef.py, subiquity/common/serialize.py, subiquity/common/tests/test_serialization.py, subiquity/common/types.py, subiquity/server/controllers/refresh.py, subiquity/server/server.py, subiquity/server/snapdapi.py, subiquity/ui/views/refresh.py, subiquitycore/snapd.py
Some bits of this should probably be split off and maybe a little rebasing should be done but I'm interested in what you think about this.
=> create and use a more richly typed snapd api

subiquity/common/apidef.py, subiquity/common/types.py, subiquity/server/controllers/refresh.py, subiquity/server/server.py, subiquity/server/snapdapi.py, subiquity/ui/views/refresh.py, subiquitycore/snapd.py
Turns out it was only a minor problem. This has been vmtested (with an asserted and unasserted subiquity snap)
=> rich snapdapi again

snapcraft.yaml
=> curtin: rev for flash-kernel fix

subiquity/server/apt.py, subiquity/server/controllers/drivers.py
Sometimes, unmounting the overlay used by ubuntu-drivers fails with EBUSY. Heinrich witnessed it on riscv64 but Dan also reproduced it on amd64. The root cause is not clear but the most obvious reason would be that a process is still running with its CWD set to the overlay. It could be due to:
* ubuntu-drivers spawning a subprocess that had not exited when the main process exited
*  `subprocess` unblocking before calling wait on the child process (seems unlikely)
* the lack of guarantee that all resources are freed released after a process exits?
* an issue with `umount` itself - as pointed out in the manpage:
>       Note that a filesystem cannot be unmounted when it is 'busy' - for example,
>       when there are open files on it, or when some process has its working
>       directory …
=> drivers: make overlay unmount error not fatal

subiquity/server/apt.py, subiquity/server/mounter.py, subiquity/server/tests/test_apt.py, subiquity/server/tests/test_mounter.py
I want this for some FDE bits. I gave it a vm test successfully, score one for the unit and integration tests which certainly found plenty of bugs :)
=> extract mount handling bits out of AptConfigurer

subiquity/client/client.py, subiquity/client/controllers/filesystem.py, subiquity/client/controllers/network.py, subiquity/client/controllers/progress.py, subiquity/common/errorreport.py, subiquity/server/controllers/cmdlist.py, subiquity/server/controllers/install.py, subiquity/server/controllers/locale.py, subiquity/server/controllers/network.py, subiquity/server/controllers/shutdown.py, subiquity/server/server.py, subiquity/ui/views/error.py, subiquity/ui/views/help.py, subiquity/ui/views/installprogress.py, subiquity/ui/views/keyboard.py, subiquity/ui/views/snaplist.py, subiquity/ui/views/zdev.py, subiquitycore/core.py, subiquitycore/tui.py, subiquitycore/ui/views/network.py, system_setup/client/controllers/summary.py, system_setup/server/controllers/configure.py, system_setup/server/controllers/shutdown.py
=> switch from loop.create_task to asyncio.create_task

examples/tpm-sources.yaml, subiquity/client/client.py
We could definitely make this more elegant. But what do you think?
=> configure controllers tui does not support when installing desktop

subiquity/client/controllers/filesystem.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/server/snapdapi.py
This required a bit of a refactor which lead to rewriting tests as well as adding a new one.
=> reuse an existing partition if possible in apply_system

subiquity/server/controllers/filesystem.py
This adds support for a 'hybrid' layout, which can only be used with a core boot classic system (and no other style can be used).
=> Support for autoinstalling a core boot classic system

subiquity/common/apidef.py, subiquity/common/types.py, subiquity/models/integrity.py, subiquity/models/subiquity.py, subiquity/server/controllers/__init__.py, subiquity/server/controllers/integrity.py, subiquity/server/controllers/tests/test_integrity.py, subiquity/server/server.py, subiquity/ui/views/error.py
* log the results of the md5 check
* if a failure and a crash occurs, mention that in the crash dialog
=> integrity: add md5 check integration

subiquity/models/subiquity.py, subiquity/server/controllers/snaplist.py, subiquity/server/controllers/ssh.py, subiquity/server/types.py
=> document InstallerChannels and add INSTALL_CONFIRMED event

apt-deps.txt, snapcraft.yaml, subiquity/client/controllers/ssh.py, subiquity/common/apidef.py, subiquity/common/filesystem/tests/test_gaps.py, subiquity/common/types.py, subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py, subiquity/server/controllers/ssh.py, subiquity/server/controllers/tests/test_ssh.py, subiquity/ui/views/ssh.py, subiquitycore/ssh.py, subiquitycore/utils.py
* cherry-picked 286b031 from #1459 for LP: #[1927103](http://pad.lv/1927103)
* cherry-picked fcebcac from #1489
* cherry-picked fd3a856..0f4376c from #1490
* cherry-picked 7c3e966 from #1504
* cherry-picked d5182af..73d9ecd from #1433 and 20513cc..c204578 from #1445 to fix issues around using -1 as a partition size to allocate the rest of the disk to that partition (LP: #[1991413](http://pad.lv/1991413), LP: #[1991929](http://pad.lv/1991929), LP: #[1989977](http://pad.lv/1989977))
* update curtin and probert to the latest versions
=> Kinetic merge 2022 12 07

examples/lp1999173-raid1.json, subiquity/models/filesystem.py
This misplaced disk method is called on a raid.  It's viable for any _Device.
=> filesystem: fix raid deletion

apt-deps.txt, setup.py
* Start migration away from distutils
* Declare dependency on gettext
* Needed to get the lunar CI running
=> distutils migration related items

subiquity/ui/views/filesystem/guided.py
=> ui/guided: TPM string tweaks

bin/subiquity-service
* cherry-picked 8dd1495 from #1545
=> kinetic merge: tui: turn off systemd ShowStatus

snapcraft.yaml
* update curtin to pick up a fix for LP: #[2004609](http://pad.lv/2004609), allowing swap partition creation when using storage v1 and MSDOS partition tables
* update probert to pick up a fix for reporting of swap partition sizes
=> Kinetic merge 2023 02 10

subiquity/tests/api/test_api.py
Remove usage of first()/find(), match() is more flexible.
Cleanup a few cases where match wasn't needed.
=> test/api: match cleanup

subiquity/server/controllers/filesystem.py, subiquity/ui/views/filesystem/guided.py
@mwhudson is a reason available in the DISABLED case?
=> More fde strings

subiquity/common/apidef.py, subiquity/models/ad.py, subiquity/server/controllers/ad.py, subiquity/tests/api/test_api.py
As discussed in #1563 two small enhancements are presented:
1. Automatic domain discovery through the network (powered by realmd) and
2. An endpoint to allow clients to know whether AD is supported in the live system.
The current plans require the existance of the realmd package to discover the domain, thus checking whether the required binary is accessible is enough to represent the AD support.
It is expected that clients should GET this endpoint prior to showing the AD configuration page.
=> Active Directory API UX Enhancements

subiquity/server/controllers/source.py
If a specific source ID is set via autoinstall but the source controller is marked interactive, the UI would select the default source (i.e., the first one on the list) instead of the one matching the ID specified.
This happens because the matching between the ID and the sources loaded was done in apply_autoinstall_config ; which is only called in non-interactive scenarios.
By moving this matching in the start coroutine instead, the right source is also selected when the source controller is interactive.
Test-case:
```bash
$ cat autoinstall-user-data-test 
interactive-sections: ["source"]
source:
id: ubuntu-server-minimal
search_drivers: true
version: 1
```
```diff
diff --git a/Makefile b/Makefile
index 209d6ecce..ce0a7e852 100644
--- a/Makefile
+++ b/Makefile
@@ -8,7 +8,7 @@ …
```
=> source: honor source if hinted by autoinstall but interactive

subiquity/server/controllers/filesystem.py
A reasonably common type of bug report is hitting the block probing timeout.  That timeout is at 15 seconds today.  Extend that to 90 seconds, and log the time it takes.
As a performance exercise, it would be good to know where that time is being spent and why it takes 10x longer or more for some people.
=> storage: lengthen and log probing time

.github/workflows/build.yaml, Makefile, bin/subiquity-cmd, bin/subiquity-server, bin/subiquity-service, documentation/autoinstall-reference.md, scripts/slimy-update-snap.sh, snapcraft.yaml, subiquity/common/api/defs.py, subiquity/common/api/server.py, subiquity/common/api/tests/test_server.py, subiquity/common/apidef.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/server/tests/test_runner.py, subiquitycore/async_helpers.py, subiquitycore/core.py, subiquitycore/tests/test_async_helpers.py, subiquitycore/tests/test_utils.py, system_setup/ubuntu-wsl-setup
* cherry-picked fcf329e from #1592
* cherry-picked 91fe266..0a7d4a8 from #1593
* cherry-picked c6530c1 from #1596
* cherry-picked 9b18f45 from #1597
=> Lunar 2023 03 17

subiquity/client/controllers/filesystem.py, subiquity/ui/views/filesystem/filesystem.py
=> filesystem: rename done btn which overrides a meth. of the same name

snapcraft.yaml, subiquity/client/controllers/filesystem.py, subiquity/common/api/server.py, subiquity/server/controllers/ad.py, subiquity/server/controllers/network.py, subiquity/ui/views/filesystem/filesystem.py
* cherry-picked c41934c from #1586
* cherry-picked ec2255b from #1603
* cherry-picked 07db52e from #1601
* cherry-picked e063260 from #1602
* cherry-picked c07d32b from #1606
=> Lunar 2023 03 21

subiquity/common/types.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/tests/api/test_api.py
this is the only non-merge commit that ended up on the short lived canary-23.04 branch
=> move from use_lvm flag on guided fs things to more generic capabilities

console_conf/core.py, console_conf/ui/views/chooser.py, subiquity/server/runner.py, subiquity/ui/views/refresh.py, subiquitycore/utils.py
pyflakes is broken in lunar release currently and if you get python3-flake8 from proposed, we get some new issues.
=> fix "make lint" when run with the new pycodestyle/flake8

subiquity/client/controllers/filesystem.py, subiquity/common/types.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/server/snapdapi.py, subiquity/ui/views/filesystem/guided.py
This actually makes the v1 and v2 guided apis a bit closer, which is nice. This area of the code is not very well tested though!
Needs a rebase but going to stick it up for review / comment anyway.
=> use capabilities on the v1 api

subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py
Will need this in a follow on branch.
=> make FilesystemController.guided_core_boot async and fallout

subiquity/models/locale.py, subiquity/models/tests/test_locale.py, subiquity/server/controllers/locale.py
Move away from localedef to fully set the locale.  The set-locale operation is also generating the locale.
=> locale: switch to localectl set-locale

examples/install-sources-canary.yaml, subiquity/models/source.py, subiquity/models/tests/test_source.py, subiquity/server/controllers/source.py, subiquity/server/controllers/tests/test_source.py
This parses variations but nothing iterates over them or selects a non-arbitrary one yet.
=> parse variations out of the source catalog

scripts/slimy-update-snap.sh
If the target snap is ubuntu-desktop-installer, put subiquity changes in the appropriate location.
=> scripts: update slimy to handle u-d-i

subiquity/common/filesystem/gaps.py, subiquity/common/filesystem/tests/test_gaps.py, subiquity/models/locale.py, subiquity/models/tests/test_locale.py, subiquity/server/controllers/locale.py, subiquity/tests/api/test_api.py
* cherry-picked fb2c6da from #1640
* cherry-picked 0a4134c..5219ecf from #1641 with minor tweak for capabilities changes
=> Lunar 2023 04 11

scripts/slimy-update-snap.sh, snapcraft.yaml, subiquity/cmd/server.py, subiquity/server/controllers/install.py, subiquity/server/controllers/mirror.py, subiquity/server/runner.py, subiquity/tests/api/test_api.py, subiquitycore/utils.py
* cherry-picked b72a539 from #1642
* cherry-picked 8cbb1cf..800a1e9 from #1643
* cherry-picked 8a71b7d from #1646
* cherry-picked fd1fc1c from #1647
* cherry-picked 938f2ffc2432d2c7dbd69cb5503aa256ec63fbda..8298ec17c819510688ab530ae77b5f7196969e37 from #1648
=> Lunar 2023 04 12

subiquity/common/errorreport.py, subiquity/ui/views/filesystem/lvm.py
* cherry-picked dcc66fa from #1532
* cherry-picked c22ad1d..cd03fea from #1651
=> Lunar 2023 04 13

system_setup/server/controllers/configure.py
Currently in lunar we have:
```
2023-04-13 13:20:15,895 DEBUG subiquitycore.utils:96 arun_command called: ['check-language-support', '-d', '/usr/share/language-selector', '-l', 'en_US']
2023-04-13 13:20:15,898 ERROR root:37 finish: subiquity/Configure/configure: FAIL: [Errno 2] No such file or directory: 'check-language-support'
2023-04-13 13:20:15,898 ERROR subiquity.server.server:422 top level error
File "/snap/subiquity/current/lib/python3.10/site-packages/system_setup/server/controllers/shutdown.py", line 47, in _wait_install
await self.app.controllers.Install.install_task
FileNotFoundError: [Errno 2] No such file or directory: 'check-language-support'
2023-04-13 13:20:15,900 ERROR subiquity.server.server:422 top level error
Traceback (most recent …
```
=> [system_setup] Fixed paths for language-related commands

system_setup/server/controllers/configure.py
Subiquity snap doesn't stage language-selector-common nor locales packages.
Attempting to run those commands require respecting the env previously prepared by the caller, as well as fixing the commands paths (or changing the PATH env var in the env preparation step). Since the apt commands were already ran with a fixed path, I'm applying the same principle in here.
Yet, for now, Jammy doesn't ship the l-s-c package seeded, so a condition was preserved to avoid future crashes.
(cherry picked from commit 2e67005403be469b9e36b34168fa638dc68f667b)
=> Fixed paths for lsc and locales commands

snapcraft.yaml, subiquity/common/filesystem/manipulator.py, subiquity/server/apt.py, subiquity/tests/api/test_api.py
* cherry-picked aa6274c38e8c544e9f52419450e0b2b6eabeb87e from #1652
* cherry-picked 3bb74546e27b1d5f57f00b696d61f4750e6822c4 from #1659 
* cherry-picked 55a5ebd42b997bf76200d01013a08e2478522302 from #1661
=> Lunar 2023 04 17

subiquity/common/apidef.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/tests/api/test_api.py
* cherry-pick 2f160ada88711e9aa06e8f6c991cdd4fa980127c...9e4cd77d9d3ac1a8ebc0e9202959a88e385b5bba for #1660
=> Lunar no probert during partitioning

subiquity/server/controllers/filesystem.py
These errors are really errors in how the ISO is constructed, so logging and ignoring seems more appropriate, compared to say encryption being unavailable because the TPM is in lockout mode.
=> log and ignore systems (in the snapd sense) we cannot install

examples/autoinstall-reset-only.yaml, scripts/runtests.sh, scripts/validate-yaml.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/install.py, subiquity/server/controllers/shutdown.py, subiquity/server/controllers/tests/test_filesystem.py
This is not very pretty but it works, and perhaps isn't toooooo bad?
=> support for creating only a reset partition

subiquity/models/filesystem.py
I think this will make something else I am working on easier... maybe... it's a nice cleanup in any case I think.
=> add annotations to storage model objects

subiquity/client/controllers/network.py, subiquity/common/apidef.py, subiquity/common/types.py, subiquity/server/controllers/network.py, subiquity/server/pkghelper.py, subiquity/server/server.py
I need efibootmgr to configure the rp and it is in the pool but not the live session by default.
=> factor out code to install a package from the pool in the live session

subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py
Centralize the swapfile decision in curtin.
=> zfs: no swapfile

subiquity/common/filesystem/labels.py, subiquity/common/filesystem/manipulator.py, subiquity/common/tests/test_types.py, subiquity/common/types.py, subiquity/models/filesystem.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py
Due to lack of action ordering, BIOS boot should be used.
=> Zfs guided

subiquity/models/subiquity.py, subiquity/server/controllers/install.py, subiquity/server/server.py
I can't remember why I wanted this, but something was a bit racy without it.
=> wait for subscribers to run when broadcasting INSTALL_CONFIRMED

apt-deps.txt, examples/autoinstall/reset-only.yaml, subiquity/server/controllers/cmdlist.py, subiquity/server/controllers/install.py, subiquity/server/controllers/tests/test_install.py
It would be good to figure out how to test this automatically (I've tested it by hand and it seems to work)
=> configure reset partition boot

examples/machines/lp-1986676-missing-osprober.json, subiquity/common/filesystem/actions.py, subiquity/common/filesystem/boot.py, subiquity/common/filesystem/labels.py, subiquity/common/types.py, subiquity/models/filesystem.py, subiquity/models/tests/test_filesystem.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/ui/views/filesystem/filesystem.py
Also include the install media in responses to client requests for disks.
=> offer guided options for the install media

examples/answers/core.yaml, examples/sources/core.yaml, scripts/runtests.sh, subiquity/models/oem.py, subiquity/models/subiquity.py, subiquity/server/controllers/install.py, subiquity/server/server.py
Note that it may not be possible to create an fsimage to use as a core
installation source (haven't tried, tbh) but I have upcoming changes to
use a disk image as installation source.
=> support core installs a bit more

subiquity/models/filesystem.py
Some of these are probably not really Optional but well.
=> fix some of the annotations on Disk

subiquity/server/controllers/shutdown.py
The app command runner already knows if we're dry-run or not, so move to that.  This allows us to skip more command runs, in particular `journalctl -b`.  For my current reboot the integration tests run in half the time!
=> shutdown: move to command runner

subiquity/models/keyboard.py, subiquity/server/controllers/install.py, subiquity/server/controllers/keyboard.py
This has been possible since we changed to invoke curtin multiple times but doing it this way means we can not do it when installing core.
=> call setupcon directly in keyboard controller

examples/sources/core.yaml, scripts/runtests.sh, subiquity/common/types.py, subiquity/models/filesystem.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/install.py, subiquity/server/controllers/source.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/server/curtin.py, subiquity/ui/views/filesystem/guided.py, subiquitycore/ui/table.py
I think only a core dd image source will work for now. Probably.
=> add support for 'dd' image sources

scripts/kvm-test.py
This seems to be enough to get a /dev/tpm0 device under the guest.
=> kvm-test: support emulating a TPM 2.0

examples/answers/desktop.yaml, subiquity/server/controllers/install.py
and do not call it when installing core
=> move oem configuration stuff to a separate method

subiquity/ui/views/filesystem/partition.py, subiquity/ui/views/filesystem/tests/test_partition.py, subiquitycore/ui/form.py
This is a cherry pick of #1759 to ubuntu/lunar.
=> 2023-08-09 - Backport manual size fix to ubuntu/lunar

subiquity/common/tests/test_types.py, subiquity/common/types.py, subiquity/server/controllers/filesystem.py, subiquity/tests/api/test_api.py
Show DIRECT first, list CORE_BOOT ones later.
LP: #2033244
=> filesystem: capability flags in a specific order

snapcraft.yaml
Add sources.list in deb822 support.
=> snapcraft: update curtin, +python3-debian

snapcraft.yaml, subiquity/client/controllers/filesystem.py, subiquity/common/apidef.py, subiquity/common/filesystem/manipulator.py, subiquity/common/filesystem/tests/test_labels.py, subiquity/common/types.py, subiquity/models/filesystem.py, subiquity/models/subiquity.py, subiquity/models/tests/test_filesystem.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/install.py, subiquity/ui/views/filesystem/guided.py, subiquity/ui/views/filesystem/lvm.py, subiquity/ui/views/filesystem/tests/test_lvm.py
This is basically working and ready to be reviewed IMO. Some more automated / units tests would be beneficial.
=> Add API and TUI support for LUKS recovery key

snapcraft.yaml
For grub-pc LP: #2033496 fix and recovery key support.
=> snapcraft: rev curtin

snapcraft.yaml, subiquity/client/controllers/filesystem.py, subiquity/models/filesystem.py, subiquity/server/controllers/install.py, subiquity/server/controllers/shutdown.py, subiquity/server/controllers/tests/test_install.py
* cherry-picked 4d24865 from #1796
* cherry-picked cf828ee from #1799
* cherry-picked ea7b683 from #1800
=> Mantic merge 2023-09-19

subiquitycore/snapd.py
While these changes are not supposed to take nearly this long, per LP: #[2034715](https://bugs.launchpad.net/snapd/+bug/2034715) we know that they are, and that some systems will correctly perform the finish_install() step if just given more time.
=> snapd api: wait longer

subiquity/server/apt.py
(cherry picked from commit 91e84c70bacf8f55b5ccced74ca5b4c03e21bd20)
=> apt: fix source.list mode

subiquitycore/log.py
(cherry picked from commit 84bcd5f7c8ca92e6bada3c21c92ad1560a13235c)
=> log: move /var/log/installer back to 0770 root:adm

examples/answers/desktop.yaml, examples/sources/desktop-standard.yaml, examples/sources/desktop.yaml, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py
* cherry-picked f9e2cbf..d482049 from #1832
=> Merge variation bug

subiquity/server/controllers/shutdown.py
(cherry picked from commit 2d7210557bd4a283bd14024d9d481f2395ec2ab3)
=> shutdown: fix perms on /target/var/log/installer

doc/intro-to-autoinstall.rst, doc/reference/autoinstall-reference.rst
Fixes [FR-5630](https://warthogs.atlassian.net/browse/FR-5630)
Two tiny fixes to get rid of build-time errors in docs.
[FR-5630]: https://warthogs.atlassian.net/browse/FR-5630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Docs build errors

doc/index.rst
Fixes [FR-5545](https://warthogs.atlassian.net/browse/FR-5545)
See $subj
[FR-5545]: https://warthogs.atlassian.net/browse/FR-5545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add contact info to docs index page

doc/custom_conf.py
Fixes [FR-5687](https://warthogs.atlassian.net/browse/FR-5687)
Tiny fix to correct the 'Edit this page' link URL.
[FR-5687]: https://warthogs.atlassian.net/browse/FR-5687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix docs path for theme to function

doc/.wordlist.txt, doc/index.rst
* Replace the placeholder intro text w/ a real intro.
* Add links to issue tracker and localisation to the Contribution section.
* Reformat the links.
(Fixes [FR-5719](https://warthogs.atlassian.net/browse/FR-5719))
[FR-5719]: https://warthogs.atlassian.net/browse/FR-5719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update the index page

doc/howto/autoinstall-quickstart-s390x.rst, doc/reference/autoinstall-reference.rst, documentation/autoinstall-quickstart-s390x.md, documentation/autoinstall-quickstart.md, documentation/autoinstall-reference.md, documentation/autoinstall.md
Merge updates on discourse to the locations here, mostly as a method of checking to see if there are updates needed for the RTD version.   The local version here is intended to go away ASAP once the RTD version is live and in use.
=> Merge discourse 2023 10 18

doc/.custom_wordlist.txt, doc/explanation/configure-storage.rst, doc/explanation/index.rst, doc/explanation/operate-server-installer.rst, doc/tutorial/screen-by-screen.rst
* Heading markup made consistent with starter pack
* Proper inline markup used; semantic where possible
* Language scrubbed
(Fixes [FR-5772](https://warthogs.atlassian.net/browse/FR-5772))
[FR-5772]: https://warthogs.atlassian.net/browse/FR-5772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Review explanation docs

doc/tutorial/basic-server-installation.rst, doc/tutorial/index.rst, doc/tutorial/screen-by-screen.rst
* Heading markup made consistent with starter pack
* Proper inline markup used; semantic where possible
* Language scrubbed
(Fixes [FR-5770](https://warthogs.atlassian.net/browse/FR-5770))
[FR-5770]: https://warthogs.atlassian.net/browse/FR-5770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Review and fixes of doc tutorials

subiquity/server/controllers/install.py, subiquity/server/controllers/tests/test_install.py
When an error occurs during the execution of a "$ curtin install" invocation, the associated bug report would be titled:
"install failed crashed with CalledProcessError"
This is not very user friendly and it does not immediately give any insight on:
With the number of reports that we receive these days, I think classifying these reports would make our life a bit easier, and possibly make the users understand better what's going on.
This change adds a wat to detect if a bug report is the result of a "$ curtin install" invocation failing. If it is, subiquity sets the title of the bug report accordingly. Examples:
* "partitioning crashed with CurtinInstallError"
* "extract crashed with CurtinInstallError"
* "curthooks crashed with CurtinInstallError"
=> apport: show name of curtin stage when an error occurs

subiquity/models/network.py, subiquity/models/tests/test_network.py, subiquity/server/controllers/tests/test_network.py
- cherry-picked 9ecc406 from #1911
- Related: LP:#2052524
=> Mantic merge 2024 02 13

console_conf/controllers/tests/test_chooser.py, subiquity/server/tests/test_controller.py
* python 3.12 fix
* fix usage of not_called
=> Fix unittests on Noble

doc/reference/autoinstall-reference.rst
=> doc: fix documentation of match specs for model and vendor

scripts/kvm-test.py
The local disk that `scripts/kvm-test.py` creates unconditionally uses the `virtio` interface. Recently in Subiquity, we did some work more closely related to NVMe drives but kvm-test.py did not support that type of interface.
We now add the possibility to specify the interface using the --disk-interface option. It can only take two options:
* `--disk-interface nvme`
* `--disk-interface virtio`    (the default)
This should allow us to spot regressions (such as in LP:#2056730) with more ease.
=> kvm-test: add --disk-interface option taking either "nvme" or "virtio"

scripts/kvm-test.py
Adds an option to configure the VM to load SecureBoot enabled firmware. SecureBoot is a feature of UEFI, which means --boot (for legacy BIOS boot) is incompatible with this flag. Providing both will result in an error.
This will be useful for testing MOK enrollment behavior, as on reboot you can confirm if you are presented with mokmanager or regular first boot.
=> kvm-test: add --secure-boot option

doc/reference/autoinstall-reference.rst
This PR fixes some minor language a formatting issues that were mostly introduced with #1956.
(Aside from punctuation and other small things, I removed hard line breaks to make it consistent with the rest of the doc.
=> Language and formatting fixes as a follow up to #1956

doc/reference/autoinstall-reference.rst
=> doc: fix indent in reference of codecs.install

subiquity/server/tests/test_apt.py
test_run_apt_config_check currently writes to curdir, update that to a tempdir instead.
`git diff -w` makes this easier to read, it's a two line change ignoring indent changes.
=> apt: fix mountpoint-install-tree test write dir

DESIGN.md
=> DESIGN.md: document what happens to the API when the server restarts

subiquity/server/server.py, subiquity/server/tests/test_server.py
I can confirm the fix works on the stable branch after local testing. For both Desktop and Server, and both BIOS and UEFI boot on each.
=> Cherry-pick fix for Netboot bug LP: #2062988 to ubuntu/noble

scripts/kvm-test.py
So far, for NVMe/TCP, we wanted to run the installer on a VM with at least a small local disk. Going forward, we want to drop this constraint. Add the --no-disk option to kvm-test so that we can run the installer on a VM with no local disk.
=> kvm-test: allow to run installer with no local disk

subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py
(cherry picked from commit 92a47635d8a988b4cc40a9a9d23d396c8c2a51c0 - PR #1978)
=> Noble merge - Probe NVMe controllers when running the restricted probe

doc/howto/autoinstall-quickstart.rst
closes https://github.com/canonical/subiquity/pull/2003
=> Fix wrong indent of another volume install doc

doc/reference/autoinstall-reference.rst
A few quick fixes in the autoinstall reference.
Fixes [FR-8490](https://warthogs.atlassian.net/browse/FR-8490)
[FR-8490]: https://warthogs.atlassian.net/browse/FR-8490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Formatting and lang. fixes

.github/workflows/ci.yaml, scripts/test-in-lxd.sh, subiquity/models/network.py, subiquity/models/tests/test_network.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/identity.py, subiquity/server/controllers/source.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/server/controllers/tests/test_identity.py, subiquity/server/controllers/tests/test_source.py, subiquity/server/server.py, subiquity/server/tests/test_server.py
- cherry-pick 88f8b21633c9643f0d1b66d36c1505496ac44209..68ae5a4cdcfc3e1a41e547c26f0e6fea269278d7 from #1965
- fix for delayed failure when missing identity section 
- cherry-pick 652f73209c862860d219f60aaf742197cc98b56a from #1972
- fix for reset-partition size bug
- cherry-pick 45d0c7ab87f8dea4b0b18b227d6b894794bfa46f from #1994
- combine wifi config written to disk
- cherry-pick 8c26578abd6df81b9993e1fc8ad0afb0b6a45925 from #2008
- fix for autoinstall warning on autoinstall aliases
- cherry-pick f56c2046ea4eb202da9d4a40829baab132ca2932..7db45712d61fc20ac081f608b56f730c12c6b0bf from #2028
- Drop CI for Mantic and add Oracular
=> Noble stable merge 2024-08-06

doc/reference/autoinstall-reference.rst
Also some opportunistic wording improvements on oem and updates, beside the examples
=> reference: examples for oem drivers codecs updates

scripts/quick-test-this-branch.sh
pass extra args to livefs-edit
=> quick-test: custom livefs-edit args

scripts/kvm-test.py
=> kvm-test: fix mkdir call

subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/server/snapd/system_getter.py
=> extract some functionality from FilesystemController

subiquity/common/apidef.py, subiquity/common/serialize.py, subiquity/common/tests/test_serialization.py, subiquity/common/types/storage.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py
Start work on pin/passphrase with TPMFDE with a stub entropy calculation endpoint and some basic API validation.
=> Pin pass stub

subiquity/ui/views/help.py
Originally reported in LP:#2100651
The name of the project wasn't mentioned anywhere in the About page.
=> ui: Mention "Subiquity" in the about page

subiquity/common/filesystem/labels.py, subiquity/common/filesystem/tests/test_labels.py, subiquity/common/types/storage.py, subiquity/models/tests/test_filesystem.py, subiquity/tests/api/test_api.py
Provide information about the effective mount / format / encrypted state for complex devices constructed by guided installs.
Field names may not be final.
=> Provision issue 1001

.github/workflows/ci.yaml, .github/workflows/cla-check.yaml, .github/workflows/snap.yaml, scripts/github-ci-lxd-setup.sh, scripts/test-in-lxd.sh
Originally landed in main in https://github.com/canonical/subiquity/pull/2163
=> Noble: apply CI fixes

subiquity/server/controllers/filesystem.py
In the future I'd like to move the generation of guided scenarios to a separate object. Moving the code to separate functions is a step in the right direction, and makes it easier to find in the code where the reformat scenarios are being generated.
=> storage: move generation of reformat scenarios to a function

subiquity/common/apidef.py, subiquity/common/types/storage.py, subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py, subiquity/server/snapd/types.py, subiquitycore/snapd.py, subiquitycore/tests/test_snapd.py
I went ahead and merged #2220 to `tpmfde` to ensure that ubuntu-desktop-bootstrap can integrate the TPM/FDE changes before it's formally reviewed.
I'd like to get this branch reviewed before merging it back to main.
=> Merge TPM/FDE branch to main

subiquity/server/controllers/filesystem.py, subiquity/server/controllers/tests/test_filesystem.py
Cherry-pick fixes for LP:#2117025 for plucky.
Original PR #2238
=> Plucky: fix rename partition

snapcraft.yaml
=> snapcraft: bump curtin revision for ZFS+encryption on small disk fix

scripts/kvm-test.py
This allows for example to give Wi-Fi support to the guest if the host has a spare USB Wi-Fi adapter.
```bash
$ kvm-test --usb-passthrough $bus $addr
```
Example:
```bash
$ lsusb
[...]
Bus 001 Device 013: ID 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter
[...]
```
```bash
$ kvm-test --usb-passthrough 1 13
```
Note that the current user must have write access to the device in question.
You can give it access temporarily using:
```bash
$ sudo chown [...] /dev/bus/usb/$bus/$addr
```
e.g.:
```bash
$ sudo chown olivier /dev/bus/usb/001/013
```
or more persistently using a udev rule such as:
```udv
SUBSYSTEM=="usb", ATTRS{idVendor}=="...", ATTRS{idProduct}=="...", OWNER="..."
```
=> kvm-test: add USB passthrough support
