subiquitycore/controllers/network.py

Someone sent me a traceback where cancel() was called before .proc was set.  I
don't really understand how this happens, but there's no harm in being careful.

be more careful in BackgroundProcess.cancel

---

subiquitycore/models/network.py
subiquitycore/prober.py
subiquitycore/ui/views/network.py

Depends on https://github.com/CanonicalLtd/probert/pull/26
See https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1623897

Indicate if a wired interface is connected or not

---

bin/console-conf-wrapper

I don't know if this is what we want, but I wanted to play with it so posting it up...

exit console-conf immediately on a managed device

---

bin/console-conf-tui

this would also affect any other files console-conf creates, but afaict
that's only the netplan config which (a) should be private too and (b)
is handled specially anyway

set umask in console-conf-tui to make log files private

---

console_conf/controllers/identity.py
console_conf/controllers/welcome.py
console_conf/core.py
console_conf/ui/views/identity.py
console_conf/ui/views/login.py
console_conf/ui/views/welcome.py
subiquitycore/controller.py
subiquitycore/controllers/identity.py
subiquitycore/controllers/network.py
subiquitycore/controllers/welcome.py
subiquitycore/models/identity.py
subiquitycore/ui/views/identity.py
subiquitycore/ui/views/login.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_bond_interfaces.py
subiquitycore/ui/views/network_configure_interface.py
subiquitycore/ui/views/network_configure_ipv4_interface.py
subiquitycore/ui/views/network_default_route.py
subiquitycore/ui/views/welcome.py
subiquitycore/view.py

subiquity uses urwid's signals in a lot of places where there can only be one possible receiver. In that case, just call the method on the object directly!

remove trivial uses of signals for console-conf

---

debian/changelog
subiquity/ui/views/bcache.py
subiquity/ui/views/filesystem/add_format.py
subiquity/ui/views/filesystem/add_partition.py
subiquity/ui/views/raid.py
subiquitycore/core.py
subiquitycore/ui/interactive.py
subiquitycore/ui/views/network_bond_interfaces.py

This was way way harder than it seemed like it should be, but it seems a lot
nicer to me.
For https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1654387

rewrite Selector to work like an HTML <select> widget

---

console_conf/ui/views/identity.py
console_conf/ui/views/login.py
console_conf/ui/views/welcome.py
subiquity/ui/views/bcache.py
subiquity/ui/views/ceph.py
subiquity/ui/views/filesystem/add_format.py
subiquity/ui/views/filesystem/add_partition.py
subiquity/ui/views/filesystem/disk_info.py
subiquity/ui/views/filesystem/disk_partition.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/identity.py
subiquity/ui/views/installpath.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/iscsi.py
subiquity/ui/views/lvm.py
subiquity/ui/views/raid.py
subiquity/ui/views/welcome.py
subiquitycore/ui/container.py
subiquitycore/ui/frame.py
subiquitycore/ui/interactive.py
subiquitycore/ui/lists.py
subiquitycore/ui/views/login.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_bond_interfaces.py
subiquitycore/ui/views/network_configure_interface.py
subiquitycore/ui/views/network_configure_manual_interface.py
subiquitycore/ui/views/network_configure_wlan_interface.py
subiquitycore/ui/views/network_default_route.py

I know we said this wasn't a priority but I couldn't resist one more crack and actually I was really nearly there. This makes 'tab' and 'shift tab' move to next and previous widgets respectively and cycles around as needed.

implement proper tab cycling

---

subiquity/models/filesystem.py
subiquity/ui/mount.py
subiquity/ui/views/filesystem/add_format.py
subiquity/ui/views/filesystem/add_partition.py
subiquitycore/ui/container.py
subiquitycore/ui/interactive.py
subiquitycore/ui/lists.py

This all started because @raharper noticed that you could enter the same mountpoint twice for different partitions. This is clearly something that should be prevented, but doing it in a tasteful way (and also the validation of the input size) required me to build up a slightly improbable amount of machinery. Oh well it works now:
https://asciinema.org/a/31wn2g453sayriogqyd75ttia
and will be useful to improve the validation of the other (identity, manual network configuration) views tomorrow.

better validation for add partition view

---

subiquity/ui/views/filesystem/add_format.py
subiquity/ui/views/filesystem/add_partition.py
subiquity/ui/views/identity.py
subiquitycore/controllers/network.py
subiquitycore/ui/form.py
subiquitycore/ui/interactive.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_configure_manual_interface.py
subiquitycore/ui/views/network_configure_wlan_interface.py
subiquitycore/view.py

This branch hides the hints we currently give on forms away behind a small button. The idea is that then we can write much longer documentation without worrying about how much screen space we'll take up. You can see me playing with it at https://asciinema.org/a/d24p02yrlz1jrgy96mriviahk
This is a bit of an experiment, I'm not sure if this is better or not.

move help to an overlay

---

bin/console-conf-wrapper
bin/console-conf-write-login-details
console_conf/controllers/identity.py

console-conf-write-login-details would crash if it ran before the system
got an ip address. re-jig things a bit so that it displays an nice message
when there is no ip address but still checks for a new address every 5s until
it finds one.

fix crash on startup with no ip address

---

snapcraft.yaml

This makes the contents of the snap much more reasonable for reasons I don't entirely
understand
There is still a mystery dh_python in the snap but it's less than half the size now.

still use source-type: git even though source: is now .

---

subiquity/palette.py
subiquitycore/core.py

So urwid does not appear to be using terminfo/curses hence our struggles with orange.
However, for improved i18n support I want to use full unicode, Ubuntu Mono fonts, etc. Thus I've looked into running subiquity under fbterm. It usually reports itself as 'linux', but one can set `TERM=fbterm` for better handling by terminfo / detection. So I piggy back onto that, and use fbterm escape codes api to set orange.

Setup orange for fbterm too

---

bin/subiquity-tui
debian/control
debian/subiquity-tools.install
debian/subiquitycore.install
po/POTFILES.in
po/en_US.po
po/ru.po
setup.cfg
setup.py
snapcraft.yaml
subiquity/controllers/filesystem.py
subiquity/controllers/identity.py
subiquity/controllers/installpath.py
subiquity/controllers/installprogress.py
subiquity/controllers/welcome.py
subiquity/models/installpath.py
subiquity/models/welcome.py
subiquity/ui/mount.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/identity.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/welcome.py
subiquitycore/controllers/network.py
subiquitycore/i18n.py
subiquitycore/ui/buttons.py
subiquitycore/ui/interactive.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_configure_interface.py
subiquitycore/ui/views/network_configure_manual_interface.py

One can launch this in a UTF-8 encoding, e.g. LANG=C.UTF-8 switch language to Russian, cancel from the next screen and see that welcome screen has a Russian welcome message, switch to english again, cancel to return to the welcome screen and notice that welcome message is back in English.
So a general way to run subiquity for translation support is then this:
```
unset LANG LANGUAGE LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL
LANG=C.UTF-8 ./bin/subiquity-tui --dry-run
```
Since untranslated strings fallback to messageid which is English, I've also added a quick backdoor to spot untranslated strings / fixed width layout errors. It is called FAKE_TRANSLATE.
```
LANG=C.UTF-8 FAKE_TRANSLATE=1 …
```

Barebones i18n setup.

---

subiquitycore/ui/container.py

this has been requested a few times, turns out to be easy enough.

have enter advance to the next focus item in piles and listboxes

---

Makefile

Running 'make install_deps' will complain with:
Makefile:49: *** missing separator (did you mean TAB instead of 8 spaces?).

Makefile: tabs not spaces.

---

subiquity/core.py
subiquity/palette.py
subiquitycore/core.py
subiquitycore/ui/frame.py

This adds a bit of machinery to allow us to overwrite the first 8 console colors with 24 bit values we choose and make sure that the color used in a xterm are close to those.
It also ensures that our default background color is actually used and tweaks the colors a bit (probably for the worse but it'll be possible to sensibly change those now)

color tweaks

---

bin/console-conf-tui
bin/subiquity-tui
subiquitycore/core.py
subiquitycore/ui/frame.py

You can break things this way but it's also super helpful when hacking on the identity screen's validation to be able to jump straight there...
Mostly PRing this for visibility but reviews welcome too :)

add a way to run console-conf or subiquity with a subset of the screens

---

subiquity/models/filesystem.py

Possibly we should filter a lot more block devices. But the others seem mostly mighty obscure.

filter out floppy and read-only block devices

---

subiquity/ui/views/filesystem/disk_partition.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/filesystem/partition.py
subiquity/ui/views/identity.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/welcome.py
subiquitycore/ui/anchors.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_configure_interface.py
subiquitycore/ui/views/network_configure_manual_interface.py
subiquitycore/ui/views/network_configure_wlan_interface.py

For a couple of branches I have brewing I want (a) to be able to fill the whole area between the header and footer (b) to add scrollbars, which look very strange if all of the just-mentioned area is what is in the list box.
Fixing the former is easy, just remove the default padding but then of course all existing views need the padding re-adding. While I was doing that I switched most views to a standard layout of
1 line of padding
a stretchy listbox containing the bulk of the content
1 line of padding
the done/save/cancel/etc buttons
1 line of padding

reduce default padding, tighten scrollable areas

---

subiquitycore/ui/views/network_configure_interface.py

for https://bugs.launchpad.net/subiquity/+bug/1750050

stop showing >s on network config choices that do not lead to a new screen

---

scripts/replay-curtin-log.py
subiquity/controllers/identity.py
subiquity/controllers/installprogress.py
subiquity/models/subiquity.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/tests/test_installprogress.py
subiquitycore/ui/anchors.py

https://asciinema.org/a/fBAnH8LdWTeEDOYjQg5Umiuz1
This changes the final view to just show the events curtin reports to subiquity by default, with a dose of indentation and a spinner that hopefully conveys a feeling of progress.
It also improves the display of install progress in the footer, simplifies some logic in the installprogress controller and switches to storing curtin output in the journal, because it just makes life easier that way.

do not show full curtin log output by default

---

subiquity/ui/views/keyboard.py
subiquitycore/view.py

This gives a padding of one row above and below the overlay and 3 characters to the left and right: https://asciinema.org/a/rIYPrq81zOY8kgZE9fF5ajriW

add a border to all overlays to make them more readable

---

subiquity/ui/views/identity.py
subiquity/ui/views/keyboard.py
subiquitycore/ui/form.py

This is the only place in subiquity today where we have selectable fields side
by side, which contradicts the goal to be able to navigate subiquity with up,
down and enter keys only. Replace the existing fancy widget with two fields,
one to select the import source and one to enter the username.
Also remove the "Ubuntu SSO" option as that has never worked.
https://asciinema.org/a/bpddtZbxMiGXpQNDbhkZ5omqD

change how ssh import field works

---

subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/partition.py
subiquity/ui/views/identity.py
subiquity/ui/views/installpath.py
subiquity/ui/views/keyboard.py
subiquitycore/ui/container.py
subiquitycore/ui/form.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_configure_manual_interface.py

Before this change, subiquity has lots of ListBoxes that just contain a single
Pile containing all their contents. This is (a) a bit silly (b) make some parts
of the scrolling experience a bit poor, for example urwid tries to scroll all
of a ListBox element into view when it gets focus but this is defeated by
shoving all the elements into a Pile (this causes
https://bugs.launchpad.net/subiquity/+bug/1750058 and a few other strange
bits).
The fix for this is obvious (don't wrap ListBox elements in a Pile) but this
breaks some aspects of tab cycling (when you shift tab back into a listbox you
want the last element of the box to be both selected and scrolled into view,
that sort of thing). Fixing all these bits of broken behaviour required
rewriting the tab cycling implementation to the …

improve scrolling experience

---

console_conf/models/console_conf.py
subiquity/models/subiquity.py
subiquitycore/models/network.py

This is basically the simplest possible thing, we could show wlan interfaces but have them be disabled which might be less confusing but also I don't think I care very much.

do not show wlan interfaces in server installer

---

subiquity/controllers/keyboard.py
subiquity/models/keyboard.py
subiquity/models/subiquity.py
subiquity/ui/views/keyboard.py
subiquitycore/view.py

https://asciinema.org/a/IESGmVIzLec6feUMGfKEgGWZH (although as that's recorded in a gnome-terminal of course you can't see the actual effect of changing the keyboard)
The behaviour is entirely stolen from d-i -- when the user chooses a non-latin keyboard layout, they are prompted to choose a key stroke to swap between a latin layout and the one they chose.
I've tested this in KVM, it seems to work.
I spent a bit too long trying to find a way to be notified by the kernel of layout changes so I could display the current layout somewhere but didn't find anything (presumably it's possible by tracking things in /dev/input but brrr)

handle non-latin keyboard layouts more intelligently

---

subiquity/models/filesystem.py

installing to a disk that has previously been configured with lvm
fails without this

set wipe: superblock on disks

---

subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/keyboard.py
subiquitycore/ui/stretchy.py
subiquitycore/view.py

subiquity master crashes on the filesystem confirmation dialog if the display is too small currently. This is a massively over engineered fix for the problem (which I wrote in my spare time, does that make it better?). See the docstring in the new file for the background.
I cherry-picked mwhudson/scrollbar-focus for these videos:
In a small window where the text needs to scroll: https://asciinema.org/a/WlijVNbmzeSMyqs8axz4zP2af
In a mid-sized window where there is just enough room for the text not to scroll: https://asciinema.org/a/rmF011nLkSOrErgM0ruvy5xFS
In a large windows, showing that the overlay doesn't stretch too much in this situation: https://asciinema.org/a/G0ZQtjzWJiaPS5DCiSDbWojFy

add an overlay that has nicer resizing behaviour

---

subiquitycore/ui/views/network.py

This bug has been here forever! Oh well.

fix rendering of nic info if dhcp failed but has addresses of other family

---

bin/subiquity-tui
subiquitycore/core.py
subiquitycore/testing/view_helpers.py

This lets you set up the UI from the command line to avoid RSI inducing stuff when testing a new, somewhat nested, screen. To test the raid screen I'm working on I can run
```
bin/subiquity-tui --dry-run --machine-config examples/mwhudson.json --screens Filesystem --click Man --click RAID
```
to get straight to the "create RAID device" screen.

add --click, --script arguments to subiquity-tui

---

subiquity/models/locale.py

All translations are include in subiquity/models/locale.py excepting french.

Missing french translation?

---

subiquitycore/core.py

This mostly affects me in dry-run mode.

hack to stop ThreadPoolExecutor blocking exit

---

subiquity/ui/views/identity.py
subiquity/ui/views/installprogress.py
subiquitycore/ui/container.py
subiquitycore/ui/selector.py
subiquitycore/ui/stretchy.py
subiquitycore/ui/views/network.py

for all the usual reasons why composition is better than inheritance,
but in particular because I want to have a listbox that has a scrollbar
but not our custom tab behaviour in another branch. decoration in urwid
is not as transparent as it sometimes seems it should be but luckily
there's only one view that does much with its listbox and it was due
for some cleanup anyway.

convert ScrollBarListBox to decoration rather than subclass

---

Makefile

Just use 'export PYTHONPATH' in the Makefile so that we all targets
have that in their environment.

Makefile: Always put PYTHONPATH into environment

---

.gitignore
fake_deps/probert/network.py
fake_deps/probert/storage.py
fake_deps/systemd/__init__.py
setup.py
subiquity/models/keyboard.py
subiquity/ui/views/filesystem/tests/test_partition.py
subiquity/ui/views/identity.py
subiquity/ui/views/installpath.py
subiquitycore/i18n.py
subiquitycore/lsb_release.py
tox.ini

tox: Support running tests and flake8 in tox.
This puts into place a tox.ini for running unit tests without
a large amount of deps installed into the system. For example,
we did not want to need libnl-route-3-dev or build-essential installed
in the system in order to run unit tests.
In order avoid import errors in the modules due to these missing
dependencies, we have added a 'fake_deps/' directory that provides
mock'd objects of the dependencies that were used.
The only installed packages necessary for this to run should be
tox itself and its dependencies (pip and friends).  From a clean new
container we can then do:
apt-get install tox
git clone ...
tox
Also adjust setup.py to only need the DistUtilsExtra during 'build'
which is not done in tox.

tox: Support running tests and flake8 in tox.

---

setup.py

Package build was broken with my last commit.
This restores functional debuild/dpkg-buildpackage.

setup.py: fix package build.

---

debian/control
debian/subiquity.install

run 'wrap-and-sort' and drop bzr as a build-depends.

debian: minor package cleanups.

---

subiquitycore/controllers/network.py
subiquitycore/file_util.py
subiquitycore/models/network.py
subiquitycore/netplan.py
subiquitycore/tests/__init__.py
subiquitycore/tests/test_netplan.py

When user configures network with subiquity, it's rendered
netplan should be wholly definitive.  So, we remove the other files
that may have config.  This fixes a bug where running in an instance
when running on a system where cloud-init had rendered a 'match' with
'macaddress'.
When writing netplan we keep 'macaddress' match in place but drop
others.  The others may just wildcard from the installer environment,
but macaddress are likely by cloud-init or otherwise intentionally
written.
Also add an atomic write in subiquitycore/file_util and move the
netplan code into subiquitycore/netplan.py, and add some unit test
helpers from cloud-init.

Fix writing of netplan configs

---

subiquity/models/subiquity.py

Subiquity was specifying the partitioning command to curtin like this:
'partitioning_commands': {
'builtin': 'curtin block-meta custom',
},
That is not necessary, because the built-in config from curtin
is to do ['curtin', 'block-meta', 'simple'] which does the right thing
if storage config is provided.
In addition to that, because we specified a string, but curtin
was expecting an array, the log/status message that curtin would report
would show:
running 'c u r t i n  b l o c k' ....
rather than:
running 'curtin block-meta simple'

Do not specify partitioning commands in curtin config.

---

subiquity/cmd/tui.py
subiquity/controllers/installpath.py
subiquity/models/installpath.py
subiquity/models/subiquity.py

This provides the ability to install from a different source
by providing it on the command line.  So we can boot into a system,
and then run:
subiquity --source=/tmp/xenial-server-cloudimg-amd64.squashfs
or
subiquity --source=http://cloud-images.ubuntu.com/.../some.squashfs
And install that image rather than the hard coded paths.

Add support for --source on command line.

---

subiquity/ui/views/snaplist.py
subiquitycore/ui/container.py

urwid doesn't know about the _select_first/last_selectable methods our
containers use to make tab-cycling work so its WidgetWrap doesn't
forward them along. So add a WidgetWrap that does, and use it in the one
place that it matters so far (more coming soon!).

add our own version of WidgetWrap

---

subiquity/ui/views/snaplist.py
subiquitycore/ui/table.py

Depends on https://github.com/CanonicalLtd/subiquity/pull/361
Something a bit like an HTML table, that takes column widths from contents. I've done this in the snap list views (updated here), and the old and new filesystem views (not done here because the new filesystem views are a whole other branch).
It might be a bit over-engineered but it gets a lot of clutter out of the way of the more specific view code.

Add table widget

---

console_conf/controllers/identity.py

Reuse the login_details_tmpl_no_ip template in standalone, use os-release to determine the Ubuntu Core version as we now support both 16 and 18.

console-conf identity: do not hard-code the core version

---

subiquity/controllers/filesystem.py
subiquity/models/filesystem.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/filesystem/partition.py

Looking forward to RAID, it makes more sense to account for the GPT overhead in the calculation of how much space there is for partitions rather than lying about the size of a drive so do that, and rename a property to make its meaning clearer. 
Also re-introduce the filter on too-small devices that I lost refactoring the fs views.

account for GPT overhead in a better place

---

subiquity/ui/mount.py
subiquity/ui/views/filesystem/partition.py
subiquity/ui/views/keyboard.py
subiquitycore/ui/form.py
subiquitycore/ui/selector.py

A few tweaks to the selector widget. "(+) option" becomes "[ option  ▾ ]".
This probably requires a new console font to look good in the vt...

Selector tweaks

---

examples/answers-raid.yaml
subiquity/controllers/filesystem.py
subiquity/models/filesystem.py
subiquity/ui/views/filesystem/delete.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/raid.py

This removes all my clever "can you made this edit to the raid without making some dependent object" code in favour of forbidding edits to devices that are parts of RAIDs (or LVMs, eventually).
It also removes the format/mount options from the create RAID dialog and adds a context menu item to remove a device from a RAID.

Raid simplifications

---

Makefile

Fixes this error:
```
python3 -m subiquity --dry-run --uefi
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/seth/src/canonicalltd/subiquity/subiquity/__main__.py", line 4, in <module>
from subiquity.cmd.tui import main
File "/home/seth/src/canonicalltd/subiquity/subiquity/cmd/tui.py", line 25, in <module>
from subiquitycore.core import ApplicationError
File "/home/seth/src/canonicalltd/subiquity/subiquitycore/core.py", line 29, in <module>
from subiquitycore.prober import Prober, ProberException
File "/home/seth/src/canonicalltd/subiquity/subiquitycore/prober.py", line 18, in <module>
from probert.network import …
```

Add jsonschema dependency

---

scripts/runtests.sh
subiquitycore/controllers/network.py
subiquitycore/models/network.py
subiquitycore/ui/table.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_configure_manual_interface.py
subiquitycore/ui/views/tests/test_network_configure_manual_interface.py

The main change in this is that instead of rebuilding the entire view when a netlink change comes in, make a much smaller change to just update the details of the link that has changed. This has the advantage that e.g. if you have a menu open for a nic when DHCP completes, the menu isn't closed.
There is also a certain amount of random cleaning up and refactoring.

Finer network refreshes

---

subiquitycore/models/network.py

This is a bit ugly but I think it solves the worst of the problems.

mark interfaces that have dhcp enabled but did not get an address as optional

---

debian/console-conf.console-conf@.service
debian/console-conf.serial-console-conf@.service
debian/subiquity.serial-subiquity@.service
debian/subiquity.subiquity-debug@.service
debian/subiquity.subiquity.service

Otherwise we get duplicate information (or wrong information), as by principle console-conf and subiquity handle all login-prompt-related printing. This seemed to be the default in the past? Not sure what changed but being more explicit is always good.

agetty needs an explicit -i to not to display the /etc/issue file

---

debian/console-conf.console-conf@.service
debian/console-conf.serial-console-conf@.service

On core18 the firstboot seeding happens via the core18.start-snapd
service. This service will do the initial start of snapd when the
system is unseeded. This service will wait until the system is
fully seeded.
We cannot run console-conf before that because it uses the "snap"
command which will not be available before the system is seeded.
Once that has landed https://github.com/snapcore/core18/pull/74
can be reverted (in fact the hooks/200-console-conf-after.chroot
file can be removed entirely).

services: run console-conf after core18.start-snapd.service

---

Makefile
bin/console-conf-wrapper
debian/control

Make shellcheck part of "make check" and ensure that
bin/console-conf-wrapper is shellcheck clean.

Makefile,console-conf-wrapper: run shellcheck and fix issues

---

subiquity/ui/views/filesystem/lvm.py
subiquity/ui/views/filesystem/partition.py
subiquity/ui/views/filesystem/raid.py

For https://bugs.launchpad.net/subiquity/+bug/1786556
Got a bit sidetracked by mdadm's hilarious failures when you try to include spaces in the name of the device...

validate raid and vg/lv names

---

scripts/inject-subiquity-snap.sh

This is like copy & paste from debian-cd.

scripts: add s390x support to inject-subiquity-snap

---

subiquity/controllers/filesystem.py
subiquity/models/filesystem.py
subiquity/ui/views/filesystem/compound.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/guided.py

This makes the installer to correctly install on to /dev/vda1, without any grub-bios nonsense.

filesystem: do not create bios-grub partition on s390x.

---

subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/installpath.py
subiquity/ui/views/installprogress.py
subiquitycore/ui/anchors.py
subiquitycore/ui/table.py
subiquitycore/ui/utils.py
subiquitycore/ui/views/network.py

I realized that "Padding.center_79(..., min_width=76)" does what I always wanted: it uses most of the available width when the terminal is 80 columns wide (all but two columns on either side) but only uses 80% of the width when the terminal is wider. I really wanted this for the network and filesystem views but I've changed all views to this because consistency is a nice thing.
Video at https://asciinema.org/a/JYQb2QEQ5oeonnOnXQHbVWwCN

use more of the screen for content when the terminal is narrow

---

subiquity/models/installpath.py
subiquity/ui/views/installpath.py

and only turn it into curtin config when needed. This means its possible
to pre-fill the forms if the user goes back to these screens.

rework installpath model to record what the user entered

---

subiquity/controllers/snaplist.py
subiquity/core.py
subiquity/snapd.py
subiquitycore/controller.py
subiquitycore/controllers/network.py
subiquitycore/core.py

Before the snap refresh stuff, the only thing that talked to the network really was the snap list. I pulled the code to talk to snapd itself out into a separate module already but I didn't pull out the code that tried again when a proxy was configured or the network configuration was changed. So I did that. I also changed things slightly so that the snap list only starts talking to snapd when a default route is noticed -- including the common case where a default route is present at startup (this will make it easier I think to add geoip lookups to suggest a mirror, as well as the snap refresh checks).

reorganize how network/proxy changes are handled

---

bin/subiquity-service

Currently tty1 subiquity is launched via snap run subiquity-service, which setups up expected PATH, and does a keys&font setup.
At the moment serial subiquity does nto go via the subiquity-service, and results in a different environment. Also serial subiquity does not block on seeding snaps, and does a weird loop of trying to start up like 3 times. Since it's not blocking on snapd via "/usr/bin/snap run subiquity.subiquity-service"
Let's try to make subiquity-service script, a unified entry point into subiquity. And make serial-subiquity@.service to use that.
This merge can go in, anytime. Whilst livecd-rootfs change will need to go in, after this commit is promoted to stable. As otherwise the arguments passed to the script will not be processed in serial-subiquity@ case.

Make a unified launcher

---

subiquity/controllers/filesystem.py
subiquity/models/filesystem.py

However, we use the grub_device flag on the disk for UX, but we should
either not have it at all for power, or set it on the partition
(rather than the disk), and I guess we need to make our 'can make
boot' smarter for ppc64le... as in check if the disk has any
partitions marked as prep already... not sure.

PReP partition must be wiped, and the _disk_ should not have grub_device flag

---

subiquitycore/models/network.py
subiquitycore/ui/views/network.py

The visible impact of this is that the addresses for a NIC are now
displayed underneath its name and a long "info line" (i.e. mac / model /
vendor) for a nic no longer distorts its table.
This lays the groundwork for better handling of NICs that fail to dhcp
and things like that.

refactor network view

---

snapcraft.yaml
subiquitycore/controllers/network.py
subiquitycore/models/network.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_configure_manual_interface.py
subiquitycore/ui/views/tests/test_network_configure_manual_interface.py

This changes how the network UI works to:
1. apply changes on every edit
2. mark interfaces that do not autoconfigure as disabled
3. allow progress past the network screen even if there is no network
Demo at https://asciinema.org/a/LIC8SLjYyZRdsl8lp2vukUh94

rework network ui, allow offline progress

---

snapcraft.yaml

probert has a requirements.txt that pins the version to the version
currently in the archive whereas curtin's is unversioned.

take jsonschema from probert

---

subiquity/controllers/filesystem.py
subiquity/models/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/filesystem/tests/test_partition.py

Another thing looking forward to reusing existing partitions/devices.
One user-visible change here: the devices list now lists constructed
devices, most recently created first, followed by the disks. This feels
better to me.

Use a single list on FilesystemModel to store all the actions

---

subiquity/controllers/installprogress.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/tests/test_installprogress.py

Run u-u in the target after all configuration is done. If the user clicks reboot before it finishes, run  unattended-upgrade-shutdown --stop-only and wait for u-u to exit before actually rebooting.
Dry run version: https://asciinema.org/a/ZwDriz1Oos5e87D2ZuUZ4gCKq
Includes a large refactoring of the way postinstall steps are run, oops.

(interruptibly) install security updates after install 

---

subiquity/controllers/ssh.py

https://bugs.launchpad.net/subiquity/+bug/1824404

do not crash when the ssh keys are downloaded after curtin fails

---

subiquity/cmd/tui.py
subiquitycore/core.py

On ppc64el we are observing that subiquity is running both on tty1 and hvc0 (serial console), in automatic mode.
I think we should still spawn subiquity in all the places we need to spawn it on, but we shall lock the answers file, such that only one instance of subiquity is actually installing things. As two subiquities installing things simultaneously is not good.

Lock answers file.

---

subiquity/controllers/filesystem.py
subiquity/controllers/identity.py
subiquity/controllers/installpath.py
subiquity/controllers/keyboard.py
subiquity/controllers/mirror.py
subiquity/controllers/proxy.py
subiquity/controllers/refresh.py
subiquity/controllers/snaplist.py
subiquity/controllers/ssh.py
subiquity/controllers/welcome.py
subiquitycore/controllers/network.py
subiquitycore/core.py

my best guess at why CI is currently hanging sometimes is that the
'next-screen' signal is being sent too often / too early.  add some
logging around this so that we will be able to confirm / deny this by
reading the logs.

add some logging around moving between screens

---

subiquity/controllers/refresh.py

The symptom of this is that the post install steps don't get run.
If you get to the refresh screen before the check for a snap update is
completed, you are shown a screen that indicates this. If the check
completes and shows no update, you are moved onto the next screen. The
problem is, this happens even if the user has already clicked the
"Continue without updating" button! This means (if the timing works out)
that the SSH screen gets skipped without its done method being called
and the postinstall steps never start because they are endlessly waiting
for the ssh config to be decided on.
Fortunately the fix is much simpler than the diagnosis: don't hang on to
the view after we stop showing it, so that when the check completes we
don't call methods on the view that can call back into the …

fix race in refresh view that can lead to done being called twice

---

subiquity/controllers/filesystem.py
subiquity/models/filesystem.py
subiquity/models/subiquity.py
subiquity/ui/views/filesystem/probing.py
subiquity/ui/views/filesystem/tests/test_partition.py
subiquitycore/prober.py
subiquitycore/ui/utils.py

This changes storage probing in a few ways:
* it runs in the background thread
* if storage probing fails or takes more than 5 seconds, it probes again but just for block devices
* if probing still fails, it displays an error rather than just crashing out
If we'd done this before disco release we'd be able to fix bugs like https://bugs.launchpad.net/subiquity/+bug/1825479 via a snap update. Oh well.

reorganize storage probing

---

subiquity/controllers/filesystem.py
subiquity/models/filesystem.py
subiquity/ui/views/filesystem/raid.py
subiquity/ui/views/filesystem/tests/test_raid.py

These names are what end up in udev as MD_LEVEL and so in the probert
output and so will end up in the regenerated curtin config for a system
with an existing RAID. It makes life a little bit easier for subiquity
to use the same names too.

Use the names mdadm uses for the raid levels in mdadm --detail --export

---

scripts/validate-yaml.py
subiquity/models/filesystem.py

Existing partitions can turn up with flags like "linux" and these are
fine to put into a RAID. I also checked all the other places we inspect
flag to check they weren't being over strict and they seem fine.

Flags that do not indicate a bootloader partition are ok_for_raid

---

subiquitycore/netplan.py

Normally netplan.Config().config is a dict as produced by
yaml.safe_load(). However, on systems without any netplan configs that
is not true. The subiquity code that calls into this function expects
.config to be a dictionary. When it's not
subiquitycore/models/network.py produces traceback that "list does not
have get method" when trying to get 'network' key.

netplan.Config().config should initialize to a dict

---

subiquity/controllers/filesystem.py
subiquity/models/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/filesystem/partition.py
subiquity/ui/views/filesystem/tests/test_partition.py

1. we can't assume we know all filesystems we'll end up seeing, so don't blow up in that case (we assume here that any unknown filesystems are mountable, which given where they come from -- libblkid via udev -- should be the case)
2. get rid of the FS() objects that used to be passed around for filesystem types and just pass strings or None -- works out simpler in practice.

rework how we handle filesystem types a bit

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/tests/test_partition.py

This generalizes the way we display if a VG is encrypted and the way we
display the bootloader partitions, and will be how new/existing is
displayed when reusing existing partitions happens.

Introduce the idea of filesystem action annotations

---

console_conf/core.py
subiquity/controllers/welcome.py
subiquity/core.py
subiquity/models/filesystem.py
subiquity/models/installpath.py
subiquity/models/keyboard.py
subiquity/models/locale.py
subiquity/models/mirror.py
subiquity/models/proxy.py
subiquity/models/subiquity.py
subiquity/models/tests/test_subiquity.py
subiquity/ui/views/tests/test_welcome.py
subiquity/ui/views/welcome.py
subiquitycore/core.py
subiquitycore/i18n.py

Basically each model now produces a fragment of a complete curtin config
and they are combined using curtin's merge_config function rather than
SubiquityModel.render knowing the shape of the config produced by each
model.
I've been meaning to do this for a while. It would be easy to mess things up here so please review with a bit of care.

Refactor how model configs are combined

---

Makefile
subiquity/cmd/tui.py
subiquity/controllers/filesystem.py
subiquity/controllers/tests/test_filesystem.py
subiquity/models/filesystem.py
subiquity/ui/views/filesystem/tests/test_filesystem.py

This includes #477 so go review that first.
The upshot is that we no longer set grub_device on any disks but rather track the boot device as grub_install_device on the FilesystemModel object if necessary -- it's not needed for s390x or UEFI boots. This should be easier to make work with existing partitions.

reorganize handling of bootloader partitions

---

subiquity/models/subiquity.py

This will not actually do with the version of curtin we currently build
but it will not hurt either.

configure curtin to avoid writing files to /target/etc/grub.d

---

subiquity/controllers/filesystem.py

"for x in obj.partitions(): self.delete_partition(x)" is unsafe when
delete_partition mutates the list .partitions() returns...

fix deletion of raid/volgroup with >1 partition/lv

---

subiquity/controllers/filesystem.py
subiquity/ui/views/filesystem/delete.py

The guided "use a whole disk" flow in reusing existing partitions is
going to need to be able to generically destroy the existing users of
a disk, something that subiquity does not currently let you do (you
can't delete a RAID if is part of another RAID, for example). So add
generic ways of clearing and deleting objects.

Add generic clear and delete methods to FilesystemController

---

subiquity/models/filesystem.py
subiquity/ui/mount.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/partition.py

This includes a workaround for the issue causing RAID installs to fail (which will make LVM installs fail), so should not be landed as is.
I also had got the impression that when /boot was on RAID, grub would always show its menu. That didn't happen in my test.

 allow /boot to be on any kind of device

---

subiquity/controllers/tests/test_filesystem.py
subiquity/models/filesystem.py

A recent refactoring left MAKE_BOOT action always enabled for the UEFI
bootloader mode. Fix + test.

Fix Disk._can_MAKE_BOOT on a UEFI system

---

subiquity/controllers/filesystem.py

This means you can use an answers file that leaves you on the filesystem
screen, click "back" to choose a different option and not have
everything fall over in a heap.

only run filesystem actions from answers once

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

also make the various implementations more consistent.

add tests for ok_for_raid/ok_for_lvm_vg

---

subiquity/ui/views/filesystem/filesystem.py

As per my previous comments on the "single-line-fs" pull request this further reduces indents on the left.
This makes the page look very balanced and left aligned. And headings don't jump when one e.g. resets the page, or starts using the very first device.
Also we get extra two characters of table width now.

Left align filesystems layout page.

---

subiquity/ui/views/filesystem/filesystem.py

for https://bugs.launchpad.net/subiquity/+bug/1837215
A bit simpler, this one.

display new/existing-ness of fs and volume in filesystem summary

---

subiquitycore/controllers/network.py

it seems netlink routing table messages are more of a notifications of
changes being explicitly made vs notifications of all changes to
routing.
for https://bugs.launchpad.net/subiquity/+bug/1837822

assume a default route on a down link has gone away

---

subiquitycore/i18n.py

Set fallback=True on gettext.translation() call such that it returns
NullTranslation object. This means subiquity/console-conf can start,
even if .mo files are not build in the tree, or are outright missing.

Allow starting subiquity/console-conf without translations.

---

subiquity/controllers/filesystem.py

This means my careful code to do rich probing of block devices and fall
back to simple probing doesn't work! Oh well, at least the fix is
trivial.
Seen in the logs from this bug report:
https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1839529

the probe_types argument of probert.storage.Storage.probe takes a set, not a list

---

console_conf/cmd/tui.py
subiquity/cmd/tui.py
subiquitycore/core.py

For whatever reason, urwid puts the terminal into cbreak mode during
initialization. If we put the terminal into raw mode instead, then we
don't have to ignore SIGINT and SIGQUIT, which is good, because when we
support dropping to a subshell we don't want to run that subshell with
those signals ignored, because that is extremely confusing.
This also lets me dump the code that puts the terminal into raw mode
during keyboard detection.

put the terminal into raw mode

---

subiquitycore/ui/stretchy.py
subiquitycore/view.py

And return the overlay from show_stretchy_overlay, so you can do things
when the overlay is closed.
Will be used by the help-showing stuff.

define a 'closed' signal on StretchyOverlay

---

console_conf/cmd/tui.py
subiquity/cmd/tui.py
subiquity/core.py
subiquity/ui/frame.py
subiquitycore/core.py
subiquitycore/ui/anchors.py
subiquitycore/ui/frame.py

I want to add a key combination to subiquity to allow the user drop to shell at any time. That means we need a way to discover this key combination, which means we want a help button. That means we need an application (i.e. subiquity or console-conf) to be able to put a widget in the bottom right of the screen. That means this PR.
It doesn't actually add a non-trivial widget there yet.

allow the application to have a widget in the bottom right

---

DESIGN.md
console_conf/controllers/identity.py
console_conf/palette.py
subiquity/controllers/installprogress.py
subiquity/core.py
subiquity/palette.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/keyboard.py
subiquity/ui/views/snaplist.py
subiquity/ui/views/welcome.py
subiquity/ui/views/zdev.py
subiquitycore/ui/anchors.py
subiquitycore/ui/frame.py
subiquitycore/ui/utils.py
subiquitycore/ui/views/network.py
subiquitycore/view.py

In Paris mpt asked if we could use unicode half-blocks (▄ / ▀) to make the header a bit narrower. As, coincidentally, I'd added these characters to the console font subiquity bundles the week before, this was very easy, and looked good. This also allows us to remove the ever present blank line beneath the header, which gets us another line of usable vertical space, something that is at a bit of a premium in subiquity's smallest target screen of 80x24.
The only problem was that it now looked out of balance with the footer. The footer has been a bit of a sore point for a while: mpt has previously complained that progress bars in installers have been observed to cause confusion in users, and the messages we displayed in the footer were largely a waste of space. So, let's delete the footer …

remove footer, make header narrower

---

scripts/runtests.sh
subiquitycore/log.py

Log to subiquity-debug.log.$PID instead of just subiquity-debug.log.
When we implement error reports we'll obviously attach the log to the
error report. There's no point adding log messages from previous runs of
subiquity.

create one log file per invocation

---

subiquity/core.py
subiquity/palette.py
subiquity/ui/views/help.py
subiquity/ui/views/welcome.py
subiquitycore/ui/buttons.py
subiquitycore/ui/frame.py
subiquitycore/ui/utils.py
subiquitycore/ui/width.py
subiquitycore/view.py

This adds a help menu to the header, currently containing general about this installer, help on the current screen and help on global shortcut keys.
I'm pretty happy with how this looks (https://asciinema.org/a/AYUYgKvaWPq7kIIJrYKxgEuc6) and the code is OK enough. There are some things I would like opinions on though:
* The wording for the "about" dialog (I currently have separate content for LTS/non-LTS, maybe I should add content for devel series too? Totally happy to do whatever someone else says here ;-p)
* More content for help on the current screen (this does not have to be in this branch of course, but we should populate this a bit more before the next release)
* The behaviour of the help menu when looking at help content. Currently the help menu is disabled/non-focusable when help …

Add help menu

---

subiquitycore/ui/views/network.py

I don't think the strings 'DHCPv4' and 'DHCPv6' warrant translation because they are names, not words; and almost no translator is going to know what to do with the {v} syntax (gettext does provide some guardrails, marking this as "python-brace-format", but I'm not sure that results in an error early enough to be useful to translators).

Don't mark 'DHCPv{v}' as translatable

---

subiquity/palette.py
subiquity/ui/views/help.py
subiquitycore/core.py

Oops, this wasn't what I was supposed to be working on today...
This adds a way to turn colors on and off (a hot key and a help menu item). It also refactors the screen implementation we use away from the linux console to be more compatible in mono mode.

enable turning colors on and off

---

bin/subiquity-service
subiquity/cmd/tui.py

This way `sudo snap run subiquity` will have the correct PATH for
probert/utils/curtin, as needed when running subiquity from ssh
session.

Move PATH setup from agetty service into subiquity itself

---

subiquity/controllers/filesystem.py
subiquity/core.py
subiquitycore/core.py

Forgot about this!
It's not maximally clever really -- maybe it would be better to reprobe on udev block events instead? And we could automatically reprobe until the user makes a configuration change vs showing the storage ui but well. Still an improvement I think.

Reprobe block devices on debug shell exit

---

snapcraft.yaml

Otherwise we have no ppc64le installer or s390x one.

Use 19.2-33-gedfdb1d1 curtin from master for all the bugfixes.

---

subiquity/ui/views/help.py

pages without local help, have the inactive Help on this screen button missaligned.

Align non-clicable Help title

---

subiquitycore/ui/actionmenu.py
subiquitycore/ui/selector.py

this fixes a slight visual glitch in gnome-terminal

wrap actionmenu/selector popups in Color.body

---

snap/hooks/post-refresh

For https://bugs.launchpad.net/subiquity/+bug/1848182.
This was easy? As a bonus, the hook from the refresh-to snap is executed so this will work even when the user is running current media.

add post-refresh hook to restart subiquity on the serial line

---

scripts/replay-curtin-log.py
subiquity/controllers/filesystem.py
subiquity/controllers/installprogress.py
subiquity/core.py
subiquity/ui/views/help.py
subiquitycore/controller.py

In dry-run mode, treat SUBIQUITY_DEBUG as a comma-separated list of
things to fail:
* install-fail: curtin install fails
* bpfail-full: full block device probing fails
* bpfail-restricuted: restricted block device probing fails
In addition, control-u makes the UI crash in dry-run mode.
(This is all for testing of crash report generation but does not depend
on that).

add a controlled way to make various things fail

---

scripts/raid-size-tests.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

I found the code in mdadm that decides how much of a device is usable
for data and copied it. It's a bit hairy!
For https://bugs.launchpad.net/subiquity/+bug/1816777 and many similar
bugs.

More accurate estimation of the size of a RAID

---

subiquity/controllers/error.py
subiquity/controllers/filesystem.py
subiquity/controllers/installprogress.py
subiquity/core.py
subiquity/ui/views/error.py
subiquity/ui/views/filesystem/probing.py
subiquity/ui/views/help.py
subiquity/ui/views/installprogress.py
subiquitycore/core.py
subiquitycore/ui/utils.py

What this conspicuously lacks is any support for submitting reports to Daisy or reporting bugs via apport. We'll decide what to do about those later I guess. You can play around with various kinds of failures in dry-run mode by using control-e, control-r, control-u or setting SUBIQUITY_DEBUG.

first cut at error report ui

---

subiquity/ui/views/error.py

* do not present other options while a report is uploading
* clarify what "try again" means when presenting a ui crash

small tweaks to error reporting ui

---

DESIGN.md
subiquity/async_helpers.py
subiquity/controllers/error.py
subiquity/controllers/keyboard.py
subiquity/controllers/mirror.py
subiquity/controllers/refresh.py
subiquity/controllers/snaplist.py
subiquity/core.py
subiquity/models/keyboard.py
subiquity/models/tests/test_keyboard.py
subiquity/snapd.py
subiquity/ui/views/snaplist.py
subiquitycore/core.py
subiquitycore/utils.py

The thought of implementing autoinstall stuff with our existing concurrency APIs just seemed too painful so I tried moving to first trio (which is neat but requires quite a new Python and isn't packaged for bionic) and then asyncio. There are many more things that could be switched to asyncio but this is enough to prove to my own satisfaction that it's worth it.

switch to AsyncioEventLoop and start using asyncio APIs

---

subiquity/ui/views/error.py
subiquitycore/core.py

this fixes a crash loop when the users updates the subiquity snap
then hits an install failure and selects restart

remove last-screen file before restarting subiquity

---

console_conf/cmd/tui.py
subiquitycore/prober.py

storage is not required in consoleconf, and is not installed, ensure we don't import it.
ascii argument is required.

Unbreak console-conf in UC20 images

---

DESIGN.md
subiquity/controllers/error.py
subiquity/controllers/tests/test_filesystem.py
subiquity/core.py
subiquitycore/controller.py
subiquitycore/core.py
subiquitycore/utils.py

This branch, which has #593 and #594 merged into it, removes the run_in_bg style of concurrency completely \o/

remove run_in_bg

---

subiquity/controllers/filesystem.py
subiquitycore/async_helpers.py

There is a common problem in concurrent / asynchronous code of what to
do with unhandled exceptions. If a (conceptual) thread of execution
fails, there's no guarantee (and no way of telling) if there's anything
listening.  By default, I chose to have a failing task propagate the
exception up to the run loop for two reasons:
1) Unhandled exceptions are generally bad
2) urwid.ExitMainLoop needs to be propagated to the run loop to have
any effect
But this means that tasks that are expected to fail (and have this
failure handled) like block probing crash the process, which is
obviously a Bad Thing. This branch adds a way to turn off exception
propagation per-task, which is a bit hackish but works ok it seems.

stop block probing failures from crashing the process

---

console_conf/controllers/identity.py
console_conf/controllers/welcome.py
subiquity/controllers/filesystem.py
subiquity/controllers/identity.py
subiquity/controllers/installprogress.py
subiquity/controllers/keyboard.py
subiquity/controllers/mirror.py
subiquity/controllers/proxy.py
subiquity/controllers/refresh.py
subiquity/controllers/snaplist.py
subiquity/controllers/ssh.py
subiquity/controllers/welcome.py
subiquity/controllers/zdev.py
subiquitycore/controllers/network.py
subiquitycore/core.py

Signals only make sense when you don't always know who the listener is. For next-screen/prev-screen/quit it's always the app.

stop some pointless use of urwid signals

---

subiquity/controllers/filesystem.py
subiquity/controllers/mirror.py
subiquity/ui/views/refresh.py
subiquitycore/async_helpers.py

I think this will fix an observed failure mode where block probing is endlessly cancelled.

add helper to avoid SingleInstanceTask clients caring about cancellation

---

subiquity/controllers/installprogress.py
subiquity/core.py
subiquitycore/core.py

if we want to do things after install has completed (e.g.: run late
commands), we can't have the code that runs the install invoking
/sbin/reboot directly.

refactor how subiquity is exited after install

---

subiquity/controller.py
subiquity/controllers/mirror.py
subiquity/controllers/proxy.py
subiquity/controllers/welcome.py

The installprogress controller waits for various model objects to be
configured before proceeding. But model objects whose state was loaded
from disk after a snap refresh were not marked as configured :( This
meant that, in particular, the postinstall steps waited on the language
being configured indefinitely. The fix is simple: mark model objects as
configured when their state is loaded from disk post-refresh.

fix installation hang after refreshing snap

---

subiquity/controllers/mirror.py
subiquity/models/mirror.py
subiquity/models/subiquity.py
subiquity/models/tests/test_mirror.py
subiquity/models/tests/test_subiquity.py
subiquity/ui/views/mirror.py

This is prep work for allowing autoinstalls to specify a complete apt
config.

refactor how mirror data is handled

---

examples/autoinstall-interactive.yaml
examples/autoinstall.yaml
subiquity/autoinstall.py
subiquity/cmd/tui.py
subiquity/controller.py
subiquity/controllers/__init__.py
subiquity/controllers/cmdlist.py
subiquity/controllers/filesystem.py
subiquity/controllers/identity.py
subiquity/controllers/installprogress.py
subiquity/controllers/keyboard.py
subiquity/controllers/mirror.py
subiquity/controllers/network.py
subiquity/controllers/proxy.py
subiquity/controllers/refresh.py
subiquity/controllers/reporting.py
subiquity/controllers/snaplist.py
subiquity/controllers/ssh.py
subiquity/controllers/tests/test_filesystem.py
subiquity/controllers/welcome.py
subiquity/core.py
subiquity/models/mirror.py
subiquitycore/core.py

The branch implements the first cut of autoinstall for subiquity. What is there:
* support for fully non-interactive and partially interactive installs
* support for early and late commands
What is not there:
* any sort of decent error handling
* this includes any sort of sensible data validation. Get your autoinstall.yaml wrong and things will just blow up in a mess
* support for the packages, debconf-selections, snaplist, user-data sections of the config file
* sensible behaviour when more than one subiquity is running (e.g. on tty1 and serial)
* generation of an autoinstall file at the end of install
* any kind of sensible storage configuration, it just supports lvm or direct installation on the largest disk in the system
But I have plans for all of these things :)

autoinstall!

---

subiquity/controllers/filesystem.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/ui/views/filesystem/partition.py
subiquity/ui/views/filesystem/tests/test_partition.py

This makes things a bit more generic, because I am going to need to
track which partition table type a disk originally.
The special cases around swap are annoying.

Refactor how we track what filesystem a volume originally had

---

debian/console-conf.console-conf@.service
debian/console-conf.serial-console-conf@.service

The PR introduces changes to `(serial-)console-conf@.service` that ensure the right ordering on core20 devices.
The first bit for core18 was already included in https://github.com/CanonicalLtd/subiquity/pull/389 for bionic branch from @mvo5. The relevant service is named `core.start-snapd.service` in core20.
The last patches introduces an ordering dependency on `snapd.recovery-chooser-trigger.service`, which is new in core20. The change was moved from https://github.com/snapcore/core20/pull/23 based on advice from @xnox.

debian/console-conf.service: ensure correct order with respect to snapd services

---

subiquity/models/filesystem.py

so they can actually be instantiated

do not have Dasd model class inherit from _Device

---

subiquity/models/filesystem.py

Fixed the following:
- missing variable
- typo in the word „existing”
- ending comma for consistency

Typos in a localizable string

---

bin/console-conf-wrapper

On UC20 devices, there's a specialized process that monitors the user activity on input devices during the boot process in an attempt to detect when the user wants to invoke the UC20 recovery menu. Once the interrupt is detected an empty file at `/run/snapd-recovery-chooser-triggered` is created. See related PR https://github.com/snapcore/snapd/pull/8156.
When the file is present, the console-conf-wrapper should be replaced with the actual chooser UI. By the time this runs, the `usr-lib-snapd.mount` should already be done, but I've added some extra checks to make sure that the chooser binary is present.
The naming of the chooser binary is agreed on within the snapd team (well, mostly). We haven't agreed whether there should be a way to limit the chooser to specific ttys only. In which …

bin/console-conf-wrapper: detect whether snapd recovery chooser should run

---

bin/console-conf-wrapper

Right now the console-conf wrapper assumes that the "snap" command
is available. However in a core18 world this may not be the case.
The snap command is provided by the snapd snap which needs to get
seeded first. If this seeding fails no snap command is available.
This PR changes console-conf-wrapper to deal more gracefully with
the error condition by at least showing the relevant log and
explaining what is going on to the user.

console-conf-wrapper: deal more gracefully with seeding failures

---

subiquity/controller.py
subiquity/controllers/mirror.py
subiquity/controllers/proxy.py
subiquity/controllers/refresh.py
subiquity/controllers/welcome.py
subiquity/core.py
subiquitycore/core.py

There is a broken situation in tip: if you refresh the snap, installation subsequently fails and you chose to restart, things get very confusing. What happens is that subiquity goes into the "restarting after snap refresh" mode, loads state for all screens and marks them all configured. This means the install starts again, but with a super bogus config and fails very quickly.
This PR tackles this by removing the last-state file before restarting, and using different logic for when to consider an already-seen screen as configured.

fix various restarting snafus

---

subiquity/controllers/filesystem.py

In https://bugs.launchpad.net/subiquity/+bug/1868817 we see reports of block probing failing with CancelledError. That's not supposed to happen: if block probing is cancelled (usually because a udev block event is seen before probing completes) we should restart block probing, not fail. And I tested all this stuff, carefully, when I implemented it. But! I was testing on focal (or maybe eoan) and not bionic, which is where the Python in the subiquity snap comes from. And in Python 3.6 asyncio.CancelledError inherits from Exception and so is caught by the "except Exception" block and reported as a failure. Argh.

asyncio.CancelledError inherits from Exception in Python 3.6 :(

---

subiquity/cmd/tui.py
subiquity/core.py

The code to extract the config was doing the wrong thing on bionic. Will test this somewhat more before merging!

do not look at cloud config at all if cloud-init is disabled

---

Makefile
console_conf/cmd/tui.py
console_conf/controllers/__init__.py
console_conf/controllers/chooser.py
console_conf/controllers/test_chooser.py
console_conf/controllers/welcome.py
console_conf/core.py
console_conf/models/systems.py
console_conf/models/test_systems.py
console_conf/ui/views/__init__.py
console_conf/ui/views/chooser.py
console_conf/ui/views/welcome.py
subiquity/core.py
subiquitycore/core.py

The PR adds an implementation of a recovery chooser for UC20.
Based on discussion, we've decided to implement the chooser as part of console-conf, because it is included in `core*` snaps.
The `snap-recovery-chooser` binary acts as a proxy between the chooser UI and snapd. It works as follows:
* fetches the list of available seed systems through snapd API
* starts the relevant chooser process (console-conf in this case)
* passes a list of available seed systems as a JSON over the stdin to the child process
* wait for the UI process to finish
* read the response from the child's process stdout
For reference, the implementation of the proxy is up for review in snapd now: https://github.com/snapcore/snapd/pull/8305

console_conf: implement UC20 recovery chooser

---

examples/autoinstall-interactive.yaml
subiquity/cmd/tui.py
subiquity/controllers/filesystem.py
subiquity/controllers/installprogress.py
subiquity/controllers/refresh.py
subiquity/core.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/installprogress.py

Currently, if subiquity finds an autoinstall config, it just runs. This would make it too easy to create a USB stick that destroys a machine it is plugged into at boot, so this branch stops and asks unless 'autoinstall' is on the kernel command line.
I added a small bit of docs about this: https://wiki.ubuntu.com/FoundationsTeam/AutomatedServerInstalls?action=diff&rev2=51&rev1=50
This branch also refactors the interactive confirmation so that it is shown even if we are not showing the filesystem screen at all.

be a bit less cavalier about running the install in autoinstall mode

---

examples/autoinstall-invalid.yaml
subiquity/controllers/cmdlist.py
subiquity/controllers/error.py

allow commands to be lists or strings
consider errors to be failures (except in error-commands)

tweak autoinstall command lists

---

subiquity/ui/views/refresh.py

if the user has already moved on, we shouldn't advance!

obscure race: if no refresh available, only advance past refresh screen

---

subiquitycore/core.py

The KeyCodesFilter assumed that /proc/self/fd/0 is actual stdin and proceeded to
toy with that fd. This broke the recovery mode chooser where console-conf is fed
a list of recovery systems over stdin. The `sys.stdin` is already correctly
updated to use the real tty and that should be used elsewhere instead of
hardcoding the fd number.

subiquitycore: do not assume that stdin is /proc/self/fd/0

---

subiquity/context.py
subiquity/controller.py
subiquity/controllers/installprogress.py
subiquity/core.py
subiquity/ui/frame.py
subiquity/ui/views/installprogress.py
subiquitycore/context.py
subiquitycore/core.py

When some screens are interactive and some not, the current behaviour if applying the autoinstall config takes some time is very confusing. This branch shows a progress view if applying autoinstall config takes more than 0.1 s (and ensures it shows progress for at least a second if it shows at all to avoid flickering).
It uses the progress view from the installation, with some added hair because subiquity events can overlap, unlike curtin events.

better experience for partially-interactive installs

---

subiquity/models/proxy.py

about two years ago I copy-pasted this from a shell script and never
noticed I had included the EOF until now

remove stray line from proxy from snapd_proxy dropin

---

console_conf/controllers/chooser.py
console_conf/controllers/tests/test_chooser.py
console_conf/controllers/welcome.py
console_conf/models/systems.py
console_conf/models/tests/test_systems.py
console_conf/ui/views/chooser.py
console_conf/ui/views/tests/test_chooser.py
console_conf/ui/views/welcome.py
subiquitycore/core.py

A bunch of tweaks for the recovery chooser UI based on the discussion with @niemeyer.
Most important changes:
- drop the ABORT button
- introduce BACK button, goes back to the correct previous screen
- sort actions in the order of run -> recover -> install -> rest
- capitalize action title strings
- simplify current model actions screen
- user hints in the confirm screen for well known modes
- generic hint for unknown modes
- use model's display name in the top banner
- use `(installed)` instead of `(current)` in the all-systems screen for the current system

console_conf: various recover chooser tweaks

---

subiquity/cmd/tui.py

otherwise, a subiquity restart or whatever could lead to changes made by early-commands
being lost
this also allows supplying autoinstall.yaml by sticking it on the iso

do not overwrite autoinstall file

---

subiquity/controllers/ssh.py

According to ConfigReference document, key name is "install-server" instead of "install_server" to install openssh-server via autoinstall.

fix typo at openssh-server installer

---

examples/answers-preserve.yaml
scripts/runtests.sh
scripts/validate-yaml.py
subiquity/controllers/filesystem.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/ui/views/filesystem/tests/test_partition.py

This also includes the fix for including the partition number in the config for preserved partitions, as we will quite often be not including some partitions in the config now.

do not include unreferenced devices in curtin storage config 

---

subiquity/controllers/filesystem.py

.clear() is called on any object that is about to be put into a RAID or
VG (and also before things are deleted but that does not matter here).
Change it to always set wipe=superblock, and preserve=False on disks.
This fixes making a RAID out of disks and might fix
https://bugs.launchpad.net/subiquity/+bug/1837214 once and for all.

set wipe, preserve more consistently

---

snapcraft.yaml
subiquity/cmd/tui.py

This fixes https://bugs.launchpad.net/subiquity/+bug/1872349
It's slightly poor in that we now only run the apport hooks from apport in bionic, but at least we know that they work with the python3-apport code subiquity is using...

Use apport hooks from snap

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

always emit actions for all partitions, even if otherwise unused

---

console_conf/controllers/identity.py
subiquity/cmd/tui.py
subiquity/ui/views/help.py
subiquitycore/ssh.py

Add --ssh option, which simply prints ssh login details and quits.
```
$ sudo python3 -m subiquity --ssh --dry-run
It is possible to connect to the installer over the network, which
might allow the use of a more capable terminal.
To connect, SSH to any of these addresses:
installer@192.168.1.103
installer@2a01:4b00:85fd:d700:c5d5:d33:cfd5:9062
installer@2a01:4b00:85fd:d700:f17b:dafd:6e61:e6fb
installer@fd00::c5d5:d33:cfd5:9062
installer@fd00::f022:ccd1:f8de:53f5
The password you should use is "rAnd0Mpass".
The host key fingerprints are:
RSA     SHA256:IcNSi/MT/PE3seH5SWYNKld31Quq8GW6K8Tzqt5gHtE
ECDSA   SHA256:EvXsL7GMuLSjchGhN1oeZWlAsmIP3nimEazn00mr1sc
ED25519 SHA256:iRM07uEWhq+uouCMRBSZHbeKkC6mT64JHmlyZE2DTnc
```
This is similar to console_conf write-login-details standalone, but uses …

subiquity: add --ssh option to print ssh login details.

---

subiquity/controllers/filesystem.py

apparently preexisting raids have devices and spare_devices set to lists

fix deleting preexisting raids

---

subiquity/models/filesystem.py
subiquity/ui/views/filesystem/tests/test_partition.py

kinda ridiculous that this wasn't explicitly ensured before! it came up
with existing partitions and while I think it was probably unlikely to
happen with new ones, I'm not completely sure...

ensure partitions are emitted in order

---

examples/autoinstall-interactive.yaml
subiquity/core.py

otherwise the confiration dialog appears for 0.1s and then disappears, leaving the user stranded

have asking for confirmation cancel showing progress

---

snapcraft.yaml

All subiquity logs reference curtin's version which only captures the major.minor value.
For debs builds, the current commit hash is extracted and injected into the source via sed
so that the output at runtime includes a more specific version string identifying what
curtin content was provided.
This PR uses override-pull to inject this commit has in the version module of curtin.
I've done a snapcraft build with this, and confirmed that version.py gets the correct
value.

snapcraft: inject curtin commit has into version

---

subiquity/ui/views/help.py

ipdb> get_installer_password(opts.dry_run)
'f48BpRGUMSbYjA68nGdQ\n'
Because iterating file object's lines includes them.
LP: #1874009

help: strip trailing newline from get_installer_password\n

---

subiquity/ui/views/zdev.py
subiquitycore/ui/table.py

this required adding TableListRow.set_contents.
it fixes (partly by accident) a crash when a row becomes unselectable
after a refresh (https://bugs.launchpad.net/subiquity/+bug/1874114), it
also makes the home and end keys do something sane.
really this view should not rebuild every row on any change, but that's
something for another day.

put zdev rows directly in a listbox, not in a pile in a listbox

---

snapcraft.yaml

https://git.launchpad.net/~ubuntu-core-dev/curtin/commit/?h=ubuntu-20.04&id=8ef4aba5c2b5d2041d4b7eebc3fdfe8062392371
is the new change.
Note that parent is the old commit id, thus this is the only new change on top of sil's hot fix.

Ship rharper hotfix for dm-name

---

snapcraft.yaml

Don't think we need this any more, needs testing though.

stop staging libc6 now we are core18 based

---

examples/autoinstall.yaml
scripts/runtests.sh
subiquity/controllers/network.py
subiquity/core.py

Mostly this is about allowing the config to look like this:
```
network:
version: 2
ethernets:
eth0: {'dhcp4': True}
```
and not 
```
network:
network:
version: 2
ethernets:
eth0: {'dhcp4': True}
```
but there are also some fixes around handling netplan apply failures better

fix some autoinstall network oopses

---

subiquity/ui/views/refresh.py
subiquitycore/controllers/network.py

we usually do not get to this point, but we do when logged in via ssh.
see https://bugs.launchpad.net/subiquity/+bug/1874034
tested in a VM, seems to work

restart subiquity when snap refresh completes

---

bin/console-conf-wrapper

For now, we want to just block console-conf from doing anything in install mode, i.e. allowing a user to login etc. but eventually we will probably want to show more useful status information from snapd during the install mode process.

bin/console-conf-wrapper: don't do anything during install mode

---

subiquity/core.py
subiquity/ui/frame.py
subiquity/ui/views/error.py
subiquity/ui/views/help.py
subiquitycore/ssh.py~
subiquitycore/tests/test_view.py
subiquitycore/tests/test_view.py~
subiquitycore/ui/utils.py
subiquitycore/view.py

a problem with my previous merge was that the top overlay was always
removed when the install finished, but if the user had opened a help
topic in the mean time that was the wrong thing to do. also if the
view was switched under the install notification (which is a bit
unlikely but could happen) the dialog would disappear.
this finally pushed me to generically handle "global overlays" that are
not tied to the underlying, controller-controlled view. there are a few
of these now:
* help dialogs
* error reports
* the "are you sure?" install confirmation
* now the install notification
this adds an api for adding and removing them, and the api for removing
them includes which overlay to remove.

add and use the concept of a "global overlay"

---

subiquity/models/subiquity.py

this does not actually have much effect, because we write out a config file
that disables cloud-init networking anyway, but it is confusing to still have
a curtin-written cloud-init networking config too

disable curtin networking entirely

---

subiquity/models/filesystem.py
subiquity/ui/views/filesystem/delete.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/filesystem/lvm.py
subiquity/ui/views/filesystem/partition.py
subiquity/ui/views/filesystem/probing.py
subiquity/ui/views/filesystem/raid.py
subiquity/ui/views/refresh.py
subiquity/ui/views/snaplist.py
subiquity/ui/views/ssh.py
subiquitycore/ui/form.py
subiquitycore/ui/selector.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_configure_manual_interface.py
subiquitycore/ui/views/network_configure_wlan_interface.py

* annotate a few missed string literals with _()
* try to consistently use named placeholders when formatting strings
for display (i.e. _("frob the {thing}") not _("frob the {}")
* run selector values, form captions and form help through _() before
display
* use ngettext in one place. not sure if there need to be more...
* reduce cuteness about how strings are constructed in a few places

attempt to make providing a good translation easier

---

subiquity/controllers/filesystem.py
subiquity/controllers/installprogress.py
subiquity/core.py

Some people for whatever reason have subiquity installed on their systems
and their error reports flood the tracker.

do not generate a crash report if we are not in a live session

---

subiquity/controllers/keyboard.py

Documentation allows toggle to be null and it's the default value.
Signed-off-by: Igor Ryzhov <iryzhov@nfware.com>

allow keyboard/toggle to be null

---

bin/console-conf-wrapper
debian/console-conf.console-conf@.service

Use triggering conditions for controlling when console-conf should run. We effectively want it to start if there is no `/var/lib/console-conf/complete` file *or* the snapd recovery marker file exists. 
By converting both conditions into triggers we ensure that console-conf will run the recovery chooser even when console-conf is soft-disabled.
This unblocks https://github.com/snapcore/snapd/pull/8661

console-conf: always run when triggered for the chooser

---

Makefile
setup.cfg
setup.py
snapcraft.yaml
subiquity/controllers/zdev.py
subiquity/core.py
subiquity/models/filesystem.py
subiquity/models/locale.py
subiquity/ui/views/filesystem/compound.py
subiquity/ui/views/filesystem/delete.py
subiquity/ui/views/filesystem/disk_info.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/lvm.py
subiquity/ui/views/filesystem/partition.py
subiquity/ui/views/filesystem/raid.py
subiquity/ui/views/identity.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/snaplist.py
subiquitycore/gettext38.py
subiquitycore/i18n.py
subiquitycore/models/network.py
subiquitycore/ui/form.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_configure_manual_interface.py

This is not yet finished but it adds support for using pgettext to provide a translation context for strings (doing this it seemed to make most sense to dump build_i18n and intltool from the default build path), uses this in a few places, adds comments for the translator to several more places and also changes several translatable strings to use {} formatting style with named arguments.
https://bugs.launchpad.net/subiquity/+bug/1846434

more work towards being able to provide good translations

---

bin/console-conf-wrapper

This will help finding some of the current install problems by
showing the snapd log on the terminal during the install.

console-conf-wrapper: show snapd log during install

---

subiquity/models/subiquity.py

The key lock-passwd in the user_info is incorrect, should be lock_passwd.

Fix incorrect key in user_info

---

subiquitycore/controllers/network.py

for https://bugs.launchpad.net/subiquity/+bug/1881887

do not crash in NetworkController._data_ready if ui.body is not a widgetwrap

---

subiquity/models/filesystem.py

In addition to matching the largest disk it would be great to have a matcher for the smallest disk as well. This is helpful if you have a large disk for data and a smaller one for the OS, both being SSD/HDD.

Add disk size match smallest

---

scripts/check-yaml-fields.py
scripts/runtests.sh
subiquity/models/subiquity.py

Using the NoCloud source meant that a filesystem label of "cidata"
(probably containing autoinstall config) could override the cloud-init
nocloud seed subiquity wrote and then users would not get created. So
instead write cloud config directly that hardcodes using the
DataSourceNone source and config for it.
https://bugs.launchpad.net/subiquity/+bug/1879103

use the "None" datasource for on-first-boot configuration

---

snapcraft.yaml

for https://bugs.launchpad.net/ubuntu-z-systems/+bug/1884027
Not really sure why this only shows up now.

set PYTHONIOENCODING to utf-8 in snapcraft.yaml for subiquity{,-service}

---

subiquity/models/filesystem.py

This lets autoinstall configs set them, even though nothing in subiquity
can set them yet.

add all documented fields to filesystem model classes

---

subiquity/controllers/refresh.py

for https://bugs.launchpad.net/subiquity/+bug/1886816

a snap refresh failure means the refresh state is unknown

---

snap/hooks/install

This will prevent subiquity service starting/crashing in a loop, when installed on regular systems.
Separately this allows to e.g. run subiquity in --dry-run mode on regular installed machines.
However, it still hits segmentation fault when run as `$ sudo subiquity --dry-run` But at least it's not piling up crash reports anymore.
Thanks to @anonymouse64 for the know-how!

Stop subiquity-service on non-installer media.

---

subiquity/ui/views/snaplist.py

When no snaps are seeded in the filesystem, empty string is returned,
which yaml safe load interprets as None.
But snapd seed.yaml is defined as a dictionary with snaps key. Ensure
that when no seed.yaml is present (or readable), that at least an
empty dictionary is returned, such that later calls to `.get("snaps",
[])` succeed.
LP: #1889429

snaplist: fix snaplist with filesystem without snaps

---

subiquity/models/filesystem.py

The above commit introduced regression
https://bugs.launchpad.net/subiquity/+bug/1889749
This means that https://bugs.launchpad.net/subiquity/+bug/1889749
remains unfixed.
This reverts commit 73f311690e66845101b9a5b698f0f78958cf3613.

Revert "add all documented fields to filesystem model classes"

---

Makefile
scripts/inject-subiquity-snap.sh
snapcraft.yaml

This pull request is the result of me trying to build Subiquity in a clean environment, with the goal of having an ISO with the injected freshly-built snap.
Environment:
* ESXi 6.7U3 host hypervisor
* Clean Ubuntu Server 20.04 as the host VM
* Multipass (Ubuntu Server 18.04, core18) for building the actual snap
Here's how I was doing it:
```console
$ sudo apt install make
$ make install_deps
$ sudo snap install snapcraft --classic
$ snapcraft snap --output subiquity_test.snap
$ sudo ./scripts/inject-subiquity-snap.sh ../focal-live-server-amd64.iso subiquity_test.snap focal-custom.iso
```
Doing the steps above, I've encountered multiple errors, that I tried to fix within this pull request:
1. `languagelists` step failing due to missing translation files in a minimised core image. Fixed in …

Add missing build dependencies, improve ISO generation

---

subiquitycore/models/network.py

Add CAN and unknown interfaces to `NETDEV_IGNORED_IFACE_TYPES`, otherwise `rander_config()` will throw a KeyError exception when a unsupported interface shows up.

Ignore CAN and unknown interfaces (LP: #1890397)

---

examples/autoinstall-interactive.yaml

Fixes a duplicate `snaps` key in `examples/autoinstall-interactive.yaml`.

examples/autoinstall-interactive: remove duplicate "snaps" section

---

subiquity/ui/views/welcome.py

This is a tyny tipo fix PR which fixes "unicde" to "unicode" on the "Welcome!" screen shown when using a serial console.
**Screenshot**

Fix a typo: "unicde" to "unicode"

---

subiquitycore/controllers/network.py
subiquitycore/models/network.py
subiquitycore/ui/views/network.py
subiquitycore/ui/views/network_configure_manual_interface.py
subiquitycore/ui/views/network_configure_wlan_interface.py
subiquitycore/ui/views/tests/test_network_configure_manual_interface.py

The network view code used to crawl all over the network model object,
which isn't really going to work with the upcoming client/server split.
So this adds a much better defined interface between the view and
controller.
Sorry for doing this in one commit, I spent a while trying to split it up and just got nowhere.

make network view use a plain-old-data view of a nic

---

subiquity/controllers/installprogress.py
subiquity/core.py
subiquity/journald.py
subiquitycore/core.py
subiquitycore/tui.py

The main point here is to have the event loop running earlier, so the loading of autoinstall data can "await" the execution of the early commands rather than having to play games involving starting and stopping the event loop. There are some other consequent cleanups too.

refactor startup a bit

---

subiquity/common/apidef.py
subiquity/common/errorreport.py
subiquity/common/types.py
subiquity/core.py
subiquity/server/dryrun.py
subiquity/server/errors.py
subiquity/server/server.py
subiquity/ui/views/error.py

This requires some machinery around handling errors generated in the server in the client and some plumbing to restart the server too when 'restart' is clicked in an error report.

handle server errors nicely

---

bin/console-conf-wrapper

After the user has pressed enter to being using console-conf, we should invoke
the snapd routine for console-conf, which currently does the following:
* Unconditionally delays refreshes for 20 minutes from when first invoked.
* Blocks waiting for all pending refreshes to complete, including if those
involve a reboot.
This is the first step towards a more integrated user story where console-conf
is a part of the first-boot process, and at least will minimize user confusion
where console-conf proceeds asking about network configuration and then just
hangs when snapd starts a refresh as soon as network is available.
The snap routine console-conf-start command was merged to snapd with 
https://github.com/snapcore/snapd/pull/9418 and will be first available in snapd
2.48.

bin/console-conf-wrapper: start snapd console-conf routine after user interacts

---

subiquity/client/client.py
subiquity/cmd/server.py
subiquity/cmd/tui.py
subiquity/common/types.py
subiquity/server/server.py
subiquity/ui/views/welcome.py

We're seeing an intermittent problem where cloud-init never completes. Waiting forever for cloud-init (the current behaviour) doesn't help anyone, so this branch times out after 10 minutes. I also noticed that it was the *client* doing the waiting for cloud-init, which makes no kind of sense, so I moved that to the server. And added a message to show the user if the server gave up waiting for cloud-init.

do not wait forever for cloud-init

---

subiquity/server/controllers/filesystem.py

Otherwise subiquity kicks off probes when there are the inevitable block
device changes during the installation, which is at best useless but
seems to occasionally cause install failures too.

stop listening to udev events when the filesystem gets configured

---

subiquitycore/log.py

The log file names have pids in now, but when subiquity re-execs itself
to fake a snap refresh the pid doesn't change. Having the pre "refresh"
logs get overwritten does not help anything and is sometimes very
annoying.

append, do not overwrite logs

---

subiquity/server/controllers/refresh.py

Crazily, the code interpreted the presence of an 'update' key as meaning
a refresh should be attempted and ignored its value.

putting "update: no" in autoinstall for refresh section should prevent update

---

subiquity/common/errorreport.py

I am going to add code that generates an error report for an unhandled
exception soon and we do not want to generate two reports for one
exception...

add a way of mapping an exception to an error report

---

DESIGN.md
subiquity/client/client.py
subiquity/client/controllers/progress.py
subiquity/common/apidef.py
subiquity/common/types.py
subiquity/server/controllers/cmdlist.py
subiquity/server/controllers/install.py
subiquity/server/controllers/locale.py
subiquity/server/controllers/reboot.py
subiquity/server/controllers/reporting.py
subiquity/server/server.py
subiquity/ui/views/installprogress.py
subiquity/ui/views/tests/test_installprogress.py

Having these be separate was slightly confusing, particular as I need to
add an "ERROR" state that isn't necessarily due to the install step
itself failing. Now we have one enum for the overall status of the
installer and a separate field that indicates whether the client should
be in interactive or non-interactive mode (or "not-yet-known" which is
handled more or less like non-interactive mode).

smoosh InstallState into ApplicationState

---

subiquity/ui/views/help.py

Attempts to look them up directly fail due to an empty app.base_model.
Add an API call invocation to grab the public IPs.

client: lookup machine IPs via API call

---

subiquity/client/client.py
subiquity/cmd/server.py
subiquity/common/types.py
subiquity/server/server.py

Currently the api server waits for cloud-init to complete very very
early, before starting the API server. This can leave the client at a
message that just says "connecting...." for quite a few seconds. This
branch adds a couple more states to ApplicationState to use during
startup and has the client print appropriate messages for each one.

wait for cloud-init to complete after starting api server

---

subiquity/common/apidef.py
subiquity/server/controllers/refresh.py
subiquitycore/snapd.py

for https://bugs.launchpad.net/subiquity/+bug/1913417

fix crash on refresh: change ids are strings in the snapd api

---

subiquity/client/controllers/welcome.py
subiquity/server/controllers/locale.py

there were two issues: the client never set up translation based on the
initial setting and the server contined to strip ".UTF-8" off the $LANG
value so the client didn't find a matching value to highlight the
initial language correctly.

fix initial language selection

---

.github/workflows/build.yaml
scripts/installdeps.sh
scripts/test-in-lxd.sh

apparently on mwhudson/subiquity ubuntu-latest means 18.04 and on here it means 20.04...

make github action work on ubuntu-20.04

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

If an autoinstall storage config with the last lvm_partition
is set to use all remaining space in the volgroup (`size: -1`)
and it is not aligned with the lvm chunk size, `lvcreate` will
round it up, and that will not fit into the actual free size.
That might happen depending on the size used by the previous
(lvm) partitions (e.g., may use percentage) and size of disk.
Fix that by rounding it down to the LVM chunk size.
This passed `make check` and `make lint` with exit code 0.
LP: #1919053
Before:
```
Running command ['lvcreate', 'vg', '--name', 'lv-root', '--zero=y',
'--wipesignatures=y', '--size', '6435110912.0B'] with allowed return
codes [0] (capture=False)
Rounding up size to full physical extent <6.00 GiB
Volume group "vg" has insufficient free space (1534 extents): 1535
required. …
```

lvm_partition: align down all remaining space to chunk size

---

subiquity/common/serialize.py
subiquity/common/tests/test_serialization.py

This adds a way of serializing objects to lists, which makes the results
much less self-documenting but also much smaller.  (I want to ship
keyboard data serialized with this code with the snap, but do not really
want to ship JSON data that is way bigger than it needs to be.)

add a more compact way of serializing objects

---

scripts/quick-test-this-branch.sh
scripts/slimy-update-snap.sh

The first of these scripts mashes the current branch's code over that of
a pre-existing subiquity snap.
The second uses the first to mash the current branch's code over the
subiquity snap from an ISO and then creates a new ISO with this new
snap.
It's all a bit terrifying but being able to get your changes into a
bootable ISO in about 30s is quite a large improvement on building the
snap from scratch.

add a couple of super hacky scripts for quickly testing subiquity changes

---

subiquity/ui/views/identity.py

The NAME_REGEX currently used is "[a-z_][a-z0-9_-]*" which does correctly prevent hostnames starting with a hyphen.. but also prevents otherwise perfectly valid hostnames that start with a number. (Interestingly, an underscore is not defined as a valid hostname character, but is included as valid in the regex, I'm not sure why this is included but am leaving it in for backwards compatibility)
This patch adds 0-9 as valid characters at the start of a hostname, as per https://man7.org/linux/man-pages/man7/hostname.7.html#:~:text=Valid%20characters%20for%20hostnames%20are,to%20an%20address%20for%20use.
Each element of the hostname must be from 1 to 63 characters long
and the entire hostname, including the dots, can be at most 253
characters long. Valid characters for hostnames are ASCII(7) …

Update NAME_REGEX as per bug #1916325

---

subiquity/common/types.py
subiquity/server/controllers/zdev.py

I checked the lszdev source and for all the other fields that we are
assume are boolean, it can only output "yes" or "no". Today, at least --
not sure how to make sure this is not broken by future changes. Still
this is a help.
for https://bugs.launchpad.net/subiquity/+bug/1919420

handle pers="auto" in lszdev output

---

subiquity/server/controllers/reboot.py

If the install is part-interactive, the client still runs and still
POSTs to the /reboot endpoint, so do not reject all requests to its
methods

fix rebooting after a partially interactive install

---

subiquity/client/controllers/filesystem.py
subiquity/common/apidef.py
subiquity/common/filesystem.py
subiquity/common/types.py
subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquitycore/tui.py

Not completely sure of the approach here. The types in the API in this PR expose pretty much exactly the information needed to implement subiquity's current UI for the guided storage config screen which is fine for a start I guess.
The part that makes me uncertain going on from this is how much to do server side vs client side. For example: when a RAID device is created, the disks or partitions that go into it should gain a label saying 'part of RAID mdX'. If we keep labels something the server decides, then there needs to be an API call to create the RAID device that then somehow indicates that the label of the partition should change. If we keep it client side, as currently implemented, there is more chance that the clients will diverge in behaviour, which is _probably_ bad?
Probably in …

create and use an API for guided disk usage

---

snap/hooks/post-refresh
subiquity/server/controllers/refresh.py
subiquitycore/snapd.py

Splitting subiquity into server and client means that in general
old versions of the client can still be running when the server is
updated (the client running on tty1 will be restarted by snapd/systemd
when the snap is updated but clients running via e.g. ssh will not). I
implemented a way for the client to detect this and restart itself: the
server sets a header in all responses that indicates if it has been
updated. So far so good. But the way it knows that it has been updated
is to check the presence of a file that is only created when subiquity
itself triggers the refresh, so it's not there in the case of manual
refresh, and as reported in https://bugs.launchpad.net/bugs/1921820 this
can lead to the client crashing because it cannot parse the new server's
response. This simply …

more reliably restart client when server restarts

---

subiquity/common/apidef.py
subiquity/common/types.py
subiquity/server/controllers/filesystem.py

Example:
curl --silent --unix-socket .subiquity/socket a/storage/has_rst ->
false
Origin commit:
https://git.launchpad.net/ubiquity/commit/?id=e5c7a06d97f017296bedf593c5966e931e9a8aec
Note that ubiquity believed this detection to be incomplete, so we
should explore the possibility that there is more to do here.
But then again, the comment predates the actual commit, so maybe it's ok?

Leverage code from Ubiquity to get rst presence

---

subiquity/client/controllers/filesystem.py
subiquity/common/apidef.py
subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py

Caller to guided_GET can now specify a minimum size disk that is
acceptable for guided partitioning.  The unit is bytes.
The default value if this is unspecified is 6GiB.
Note that this default value is wholly inadequate for Desktop, which by
my measurements needs at least 8GiB to get the install completed if you
tell it to install everything, even though later it settles to a lower
installed size of 6.6GiB.

guided_GET: allow caller to specify min size

---

subiquity/models/subiquity.py

While playing with interactive-sections I found that I could trigger a keyerror exception where 'updates' was not found.
Here's a quick fix for now and I want to ponder adding a test case.

fix keyerror: updates

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/ui/views/filesystem/tests/test_filesystem.py

Because the server and any clients can create action objects now,
per-process global counters are not going to cut it.
For https://bugs.launchpad.net/subiquity/+bug/1925063.

make sure freshly allocated action ids are really unique

---

subiquity/ui/frame.py

https://bugs.launchpad.net/subiquity/+bug/1925068 reports a crash that
fails with the "self.global_overlays.remove(overlay)" in
remove_global_overlay failing because the overlay is not in the list. I
don't know how it happened but staring at the code I did guess one way
this could happen: if you have two non-interactive screens in a row
where the requests both take long enough to trip the 0.1s threshold to
show the progress screen, app.ui.set_body will get called twice with the
same view. Each call will layer all global overlays over the view, so
doing it twice will show the views twice.
This all makes me thing that the way global overlays are shown is a bit
wrong -- they should be "outside" the controller-supplied view! -- but,
well, it's easy enough to make sure that calling set_body …

avoid situation where overlays can be shown twice

---

subiquity/client/controllers/ssh.py

There is a larger problem here of the UI body changing underneath of us,
but this is at least a baby step in the right direction.
Also this matches existing client/controllers/ssh.py behavior.
At least log the event when it happens.
LP: #1925048

Drop the confirm_ssh_keys call if UI not as expected

---

console_conf/cmd/write_login_details.py

Also make the log files resulting from console-conf-write-login-details
execution a bit easier to spot.

have console-conf-write-login-details exit with code 2 when no IPs found

---

bin/subiquity-configure-apt

The pool is loaded off the same media as the installer and the
filesystem being installed so there's no real loss of security doing
this and it makes it easier for people to master custom ISOs with extra
packages in the pool and systems with inaccurate clocks (that cannot
reach ntp.ubuntu.com).

set trusted=yes,check-date=no for cdrom pool during installation

---

bin/subiquity-configure-apt

It's not safe in the netboot case.

verify signatures on the cdrom pool again

---

examples/answers-serial.yaml
scripts/runtests.sh
subiquity/client/controllers/serial.py
subiquity/server/controllers/locale.py
subiquity/ui/views/serial.py

The subiquity client does not ask about language in non-rich mode on a
serial port, and that's OK. But we still need the install to complete :)
There are other ways to fix this I guess -- we could not wait on the
locale model to get configured, for example, or explicitly select a
C.UTF-8 locale when "Continue in basic mode" is selected, or probably
some other things. But this works and seems OK.

mark the locale model as configured at start up

---

subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py

https://bugs.launchpad.net/subiquity/+bug/1927103 reports a regression
where a subiquity-installed system has a swapfile even if a swap
partition has been explicitly configured.
The reason this broke is that previously subiquity tracked whether a
swap file should be allowed or not by keeping track of whether a swap
partition was mounted in add_mount / remove_mount. But since the
client/server split, those methods aren't called in the server process
any more.
Just get rid of all the cleverness and call _should_add_swapfile when
rendering the curtin config.

decide whether to let curtin create a swapfile when rendering config

---

DESIGN.md
subiquity/common/api/server.py

example:
$ curl  --unix-socket .subiquity/socket a/dry_run/crash
File "/home/mwhudson/src/subiquity/subiquity/common/api/server.py", line 122, in handler
File "/home/mwhudson/src/subiquity/subiquity/server/dryrun.py", line 24, in crash_GET
1/0
ZeroDivisionError: division by zero

include the traceback in the response when a server method fails

---

Makefile

`make dryrun` will now use the simple sample machine config instead of
probing local hardware.   That local probe only seems to be viable
anyhow if we're running as root, and that's vulnerable to real problems
if dryrun is less than 100% insulated from making real machine changes.

dryrun: use the simple machine config

---

subiquity/client/client.py
subiquity/server/server.py

otherwise, especially on a serial console, there is not really any way
to debug what is going on.
also, when non-interactive defer setting the applicationstate to ERROR
until the information in the error report has been collected and the
error-commands have run.

offer to run a shell after an autoinstall fails

---

subiquity/common/errorreport.py

they are slow and can hang in CI

do not run most apport hooks in dry-run mode

---

.github/workflows/build.yaml
Makefile
scripts/runtests.sh

Unit tests should be quick and run frequently.
Integration tests can be longer and run less often.
Split them up.

Split unit / integration tests a bit

---

subiquity/client/client.py
subiquity/ui/views/installprogress.py

There are two places that remove from this list, and the current arm64
crash is running into a scenario where we try to remove from the
overlays list only to find that it's not actually there.
So don't remove if it's already gone.
LP: #1925068

Don't redundantly remove from the overlay list

---

subiquity/server/server.py

such as desktop (for now) and bionic (oops)

do not crash in server start up if cloud-init is not running

---

subiquity/common/api/server.py
subiquity/server/server.py

Installer clients can be non-root.
Installer clients run in an environment where root is just a
password-less sudo away.

Open the permissions on the socket

---

po/POTFILES.in
subiquity/common/filesystem/actions.py
subiquity/common/filesystem/labels.py
subiquity/common/filesystem/tests/test_labels.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/ui/views/filesystem/compound.py
subiquity/ui/views/filesystem/delete.py
subiquity/ui/views/filesystem/disk_info.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/guided.py
subiquity/ui/views/filesystem/helpers.py
subiquity/ui/views/filesystem/partition.py

This has the nice side-effect that subiquity.models.filesystem now contains very few translatable strings, which seems appropriate somehow.

move storage description functionality to singledispatch methods

---

autoinstall-schema.json
subiquity/models/kernel.py
subiquity/models/subiquity.py
subiquity/server/controllers/__init__.py
subiquity/server/controllers/kernel.py
subiquity/server/server.py

This is partly prep for the oem kernel support that we'll get to eventually but it also allows the autoinstall file to override the choice of kernel, something I'm sure at least one person asked for once.

move kernel package selection to its own controller/model

---

snapcraft.yaml
subiquitycore/controllers/network.py
subiquitycore/models/network.py
subiquitycore/ui/views/network_configure_wlan_interface.py

Trying to enable wlan support in subiquity revealed a bunch of mostly trivialish bugs, mostly introduced by the refactoring I did in aid of the client/server split -- several of these affect console-conf too.
It also adds some code to work with mac80211_hwsim emulated wlan NICs -- that needs https://github.com/canonical/probert/pull/105 too though.

subiquitycore wlan fixes

---

subiquity/common/api/tests/test_endtoend.py
subiquity/common/api/tests/test_server.py
subiquity/common/geoip.py
subiquity/common/tests/test_geoip.py
subiquity/server/controllers/mirror.py
subiquity/tests/util.py

Split GeoIP out to a distinct class.
Add timezone support to it.
Add GeoIP tests.
(I saw the comment about aiohttp and didn't attempt it as part of this PR)

GeoIP: split out, add timezone

---

scripts/runtests.sh
subiquity/server/controllers/install.py

Move unattended-upgrades to part of postinstall, so it can be done
before the restore_apt_config umount, which lets us get rid of the
redundant external_temp_file logic.

Refactor - drop external_temp_file

---

subiquity/server/controllers/keyboard.py

With multiple users of subiquity in different ways, this may not be
always available at this specific location.

Unhardcode path to subiquity-loadkeys

---

Makefile
scripts/runtests.sh

Impish is adding more timezones, which is cool, but breaks my schema
check, so disable this there for now and come back later with a better
answer.
Also schema check seems to need curtin.

Temp disable schema check on Impish

---

bin/subiquity-service
snapcraft.yaml
subiquity/common/resources.py
subiquity/models/subiquity.py
subiquity/server/controllers/keyboard.py
subiquity/ui/views/identity.py
subiquity/ui/views/welcome.py

Using SNAP to find the resource files is a bit of an odd requirement for
non-subiquity clients.  Start abstracting that away so it's easier to
change later.
Also move loadkeys to lookup from this, since the previous solution is
still a problem for ubuntu-desktop-installer.

Abstract resource file lookup relative to SNAP

---

scripts/runtests.sh
scripts/schema-cmp.py

Improve the schema comparison - mostly I'm worried about the
non-timezone items, spot check the timezone list for a few that should
be there.

Add new schema comparison, robust to timezone changes

---

console_conf/cmd/tui.py
subiquity/cmd/server.py
subiquitycore/prober.py

If machine-config is pointed to a non-existant file, dryrun can kind of
unhelpfully hang without much indication that anything is happening.

Verify that machine-config arg is a file

---

examples/autoinstall.yaml
scripts/runtests.sh

Until a proper fix can be finished, remove the set of timezone from the
integration tests.

Workaround dryrun test actually setting timezone

---

examples/autoinstall.yaml
scripts/runtests.sh
subiquity/server/controllers/timezone.py
subiquity/tests/test_timezonecontroller.py
subiquitycore/tests/mocks.py

* Remove the workaround for timezone set escaping dryrun
* Replace above workaround with a fix
* Reenable tests for above 
* Change behavior of GET /timezone, to no longer trigger timezone set to system
* Add tests for dryrun escape and GET not setting timezone
LP: #1936310

timezone: dryrun, GET with less side effects

---

.gitignore
scripts/inject-subiquity-snap.sh
scripts/make-edge-iso.sh
scripts/quick-test-this-branch.sh

a while ago I rewrote inject-subiquity-snap in python, generalized it
and put it at https://github.com/mwhudson/livefs-editor.  TBH, it's
always been better than the shell version but now there's a reason to
switch to it: the impish live server ISO use layers, which the current
shell scripts do not support and livefs-editor now does.

use livefs-editor to make customized isos

---

subiquity/server/controllers/install.py

Currently, attempting to follow ubuntu-desktop-installer 'flutter run' steps results in the simulated curtin failing with exit code 1.

In dryrun, run simulated curtin with same python

---

snapcraft.yaml

I don't know if we want to wait for https://code.launchpad.net/~mwhudson/curtin/+git/curtin/+merge/406515 to land first.

update curtin to get raid, zipl config, unmounting fixes

---

Makefile

On a clean system running subiquity_client tests would throw
ModuleNotFoundError: No module named 'curtin'

Make install_deps depend on gitdeps

---

system_setup/ui/views/identity.py

Revert commit duplicating code and use inheritance for IdentityForm.
The previous composition version had some flaws due to multiple instances of a given Field with different addresses when reinstalled in the parent class. This caused the field validation validate_ to not work as it was not taken the expected referenced values.
Instead of duplicating the code, we use an inherited version, taking and overriding only our desired fields.
We still need to derive WSLIdentityView from the base class instead of IdentityView, as this is what is instantiating the form (WSLIdentityForm instead of IdentityForm).

Use inheritance for IdentityForm

---

Makefile
scripts/installdeps.sh

Getting the apt packages needs to be first, as processing probert is
more than a trivial git clone and needs some of those apt packages.
Drop probert as a requirement since it's redundant with the git
checkout.  Also +build-essential to the list.

make: fix install_deps order

---

DESIGN.md
subiquity/models/subiquity.py
subiquity/models/tests/test_subiquity.py
subiquity/server/controller.py
subiquity/server/controllers/install.py
subiquity/server/controllers/timezone.py
subiquity/server/server.py

This is probably a bit overkill, but the thrust here is to allow the source variant (i.e. desktop or server) to change more than once. This isn't going to happen for a long time obviously but I wanted to clean this up sooner rather than later. There are ways this could be made still more general of course, but well. I think this is OK.

redo how install variant determines which models to wait for

---

scripts/update-part.py

Otherwise very confusing things happen (it turns out GIT_DIR is set when
running an exec command during rebase).

unset GIT_DIR in update-part.py

---

scripts/slimy-update-snap.sh

I mean we /probably/ shouldn't be using the snaps this makes for
anything serious but it can be useful for testing emergency fixes...

make the snaps produced by slimy-update-snap.sh pass review

---

subiquity/common/types.py
subiquity/server/controllers/mirror.py
subiquity/server/controllers/proxy.py
subiquity/server/controllers/refresh.py
subiquity/server/controllers/snaplist.py
subiquity/server/geoip.py
subiquity/server/server.py
subiquity/server/types.py
subiquitycore/controllers/network.py
subiquitycore/pubsub.py
subiquitycore/tests/test_pubsub.py

* Adjust existing usage of EventCallback to use MessageHub instead.
* Add constants for use with MessageHub.
* Adapt EventCallback test for MessageHub instead.

pubsub: Obsolete EventCallback

---

system_setup/server/controllers/wslconfadvanced.py
system_setup/ui/views/wslconfadvanced.py

There was some remaining duplicated fields in the controllers and models
between base and advanced configuration, which made the code crash.
This is a follow up to PR #1041.
Co-authored-by: Didier Roche <didrocks@ubuntu.com>

DE-97 - system-setup: finished removing duplicated fields

---

subiquity/cmd/server.py
subiquity/server/server.py

If autoinstall is set on the command line, don't override that with a
pre-baked file or from cloud-init.  The intent here is to allow
ubuntu-desktop-installer to temporarily say --autoinstall="" to disable
autoinstall until UI support for autoinstall is in place.

autoinstall: skip autoinstall on empty arg

---

.github/workflows/cla-check.yaml

Canonical employees who have not signed the CLA, and sign commits with
their ubuntu.com alias, fall into a weird gap where their commits are
covered (as employees) but there is no great way for the CLA check to
determine that.
https://github.com/canonical/subiquity/pull/1044#issuecomment-916764603

actions: +accept-existing-contributors for CLA

---

scripts/runtests.sh

* remove a stray space
* remove an extra call to check-yaml-fields.py, which can accept a list
of directives
* remove an entire redundant autoinstall run that I added as part of
bitlocker work but isn't actually verified in any way other than not
timing out

runtests: misc cleanup

---

system_setup/cmd/tui.py
system_setup/server/server.py

2 fixes after running in real mode (no dry run) on a WSL system:
1. The server must be started by the client when it is not socket activated
2. When there is no cloud init, the client was waiting on it forever

WSL OOBE - no dry mode

---

autoinstall-schema.json
examples/answers-bond.yaml
examples/answers-guided-lvm.yaml
examples/answers-imsm.yaml
examples/answers-lvm-dmcrypt.yaml
examples/answers-lvm.yaml
examples/answers-preserve.yaml
examples/answers-raid-lvm.yaml
examples/answers-raid.yaml
examples/answers-serial.yaml
examples/answers-swap.yaml
examples/answers.yaml
subiquity/client/controllers/snaplist.py
subiquity/common/types.py
subiquity/models/snaplist.py
subiquity/server/controllers/kernel.py
subiquity/server/controllers/snaplist.py
subiquity/ui/views/snaplist.py

Fix autoinstall output for kernel & snaplist.
This is necessary but not sufficient to roundtrip an autoinstall file.

autoinstall: fix issues in autoinstall roundtrip

---

scripts/zdev-generate.py
subiquity/server/controllers/zdev.py

Adding "--quiet" as additional option to "lszdev" omits additional progress status messages that "lszdev" might produce in case a significant amount of ccw devices are present (in the range of thousands of devices), since such progress messages will eventually cause parsing issues, like mentioned in LP#1944516.

Add '--quiet' to 'lszdev' to omit additional progress msg - lp1944516

---

Makefile
autoinstall-system-setup-schema.json
examples/autoinstall-system-setup.yaml
scripts/runtests.sh
scripts/schema-cmp.py
subiquity/models/subiquity.py
system_setup/cmd/schema.py
system_setup/server/controllers/__init__.py
system_setup/server/controllers/identity.py
system_setup/server/controllers/shutdown.py
system_setup/server/controllers/wslconfadvanced.py
system_setup/server/controllers/wslconfbase.py
system_setup/server/server.py

This is the auto configuration of system-setup on first boot based on the autoinstall feature of subiquity.
The most noticeable change is the support of non-systemd systems (like WSL). This systems cannot rely on journald for communication. In this case we fallback to a file based mechanism. 
This is covered by answer and autoinstall tests.
There are also few fixes for the controllers that are not available in all the modes, the schema for WSL, and loading the right controller for identify.

DE-91 - System Setup autoinstall

---

subiquity/common/serialize.py
subiquity/common/tests/test_serialization.py

Optional means a field can be none.
A field having a default means we don't have to supply it.
Explicitly reject non-real fields.

Serializer: clarify default / optional

---

subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

Sometimes empty CD drives or SD card readers show up as block devices
with 0 size. It never makes sense to select these when converting
autoinstall config to curtin config (and size: smallest is quite likely
to do so!)
For https://bugs.launchpad.net/subiquity/+bug/1943609

never match a disk with 0 size when converting autoinstall config

---

subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/ui/views/filesystem/partition.py

LVM logical volumes can only be multiples of the VG's extent size, which is 4MiB by default.
https://bugs.launchpad.net/subiquity/+bug/1935969

fixes around logical volume size

---

subiquity/server/controllers/cmdlist.py
system_setup/server/server.py

DEENG-29 
On WSL and any system without systemd the server crashes because the syslog id is always set (and never None) and `systemd-cat` cannot connect to the journal.
We can't set the id to None because the API expects a string, so the check `is not None` is always true.
```2021-10-04 20:05:11,992 INFO root:39 start: subiquity/Meta/status_GET: 
2021-10-04 20:05:12,883 DEBUG root:39 start: subiquity/Early/run: 
2021-10-04 20:05:12,883 DEBUG root:39 start: subiquity/Early/run/command_0: echo a
2021-10-04 20:05:12,884 DEBUG subiquitycore.utils:74 arun_command called: ['systemd-cat', '--level-prefix=false', '--identifier=', 'sh', '-c', 'echo a']
2021-10-04 20:05:12,890 DEBUG subiquitycore.utils:83 arun_command ['systemd-cat', '--level-prefix=false', '--identifier=', 'sh', '-c', 'echo a'] …
```

Fix crash with autoinstall on non-systemd env

---

subiquity/ui/views/snaplist.py

when done() is called before the snap has loaded this causes an attribute error on the following line
'log.debug("snaps to install %s", self.selections_by_name)'

Fix advancing from snap list screen before snaps have loaded

---

system_setup/cmd/tui.py

This PR tries to update TUI command line name and remove unneeded options.
The first commit is confirmed not useful one; 
The second commit is the one I am not sure that should be removed; they could be used in debugging.

DEENG-41 - Update TUI command line name and remove unneeded options.

---

.github/workflows/build.yaml

Impish systemd-resolved seems unhappy and it's interfering with the
other test runs.

workflows: skip impish

---

Makefile
scripts/installdeps.sh

pytest-3 lets us set exclude directories, which is helpful with the
desired API testing to seperate them from 'unittest discover' so that we
can keep unit test runtime short.

unittest: use pytest-3

---

subiquity/common/resources.py
subiquity/models/subiquity.py
subiquity/models/tests/test_subiquity.py

The current `merge_config()` function from curtin does not merge lists in any way, but overwrites them. This is generally a good idea, and curtin depends on such behaviour, but in case of user-data we may want to merge lists instead.
One of the possible use cases is defining the main user in the `identity` section, and some extra users in the user-data `users` section.
Before this change, the user defined in the `identity` section overwrote any users defined in user-data. With this change, the user list can now be automatically merged, with user-data having lower priority than autoinstall configuration.
I have mentioned this earlier [on the forums](https://discourse.ubuntu.com/t/please-test-autoinstalls-for-20-04/15250/101?u=forst).
The bonus is that we now also avoid a deep copy here. …

Add support for merging lists when merging user-data

---

system_setup/cmd/tui.py
system_setup/server/server.py
system_setup/ui/views/summary.py

Avoid a crash due to in progress state when summary is displayed.
Fixes on non systemd machines on output printing.
Use correct path in dry-run for socket.
This is part 2 (over 3) on fixing `make integration`.

system_setup: Many fixes for ci

---

subiquity/client/client.py

The progress controller was already optional in
subiquity/server/controllers/cmdlist.py. However, there was one missing
place in show_progress(). Use a similar getattr strategy.
This is part 1 on getting the `make integration` fix (subiquity side).

Make progress controller optional.

---

system_setup/client/controllers/identity.py
system_setup/client/controllers/summary.py
system_setup/ui/views/summary.py

Shows immediately the summary page. Before, this one was making a GET
request to the server, which was stuck on any long running command in
the controller.
Now, affect correctly the identity in memory and reuse it if needed.
Show a progress message while the configuration is happening and replace
it with a "completed" text on success.
Co-authored-by: Jean-Baptiste Lallement <jean-baptiste@ubuntu.com>

Summary page to show immediately and update once the setup is done

---

system_setup/server/controllers/configure.py

Those commands needs to be async to be able to still answer GET/POST
request while configure is running.
This allows showing up the summary page immediately.
Co-authored-by: Jean-Baptiste Lallement <jean-baptiste@ubuntu.com>

Don’t block on running commands in configure

---

system_setup/cmd/tui.py

On system_setup, we always run the subiquity server. On WSL, ensure we
wipe the server-state file (no systemd fallback) before starting the
server.
Co-authored-by: Jean-Baptiste Lallement <jean-baptiste@ubuntu.com>

Fix reruning in production system_setup on WSL

---

system_setup/server/controllers/configure.py

useradd -R does chroot.
useradd -P doesn't.
We'll improve the design later. I couldn't resist to temptation of doing this one-letter PR. :smile:

Temporary fix for integration tests chroot'ing

---

scripts/runtests.sh
subiquity/journald.py
subiquity/server/controllers/install.py

I want to rewrite subiquity-configure-apt in Python and somehow that led me to doing a bunch of refactoring of how we execute commands and particularly curtin.

create helper classes for running install commands

---

scripts/test-in-lxd.sh

Hi @dbungert !
I hope you guys find this one useful and nothing breaks GitHub side. I changed the `test-in-lxd` script to preserve existing instances and starting then, which is useful for develop environment. I used that in debugging one issue preventing the server to start on Focal only.
The name of the instance changes from `tester` to the adjective of the Ubuntu Release (extracted from the image name). That enables preserving instances from different releases while doing matrix builds. That makes the dev environment closer to the CI.
Feel free to discard or modify that in case it doesn't fit well for everybody working on Subiquity.

Enables preserving existing container instances.

---

system_setup/cmd/tui.py
system_setup/server/controllers/locale.py

Without adding the 'prefill' option to the TUI it would only work if under dry-run mode.
Also lifting up CLI parsing to outside of the if clause enables some simplification of the decision-making.

Fix prefill only dryrun

---

system_setup/server/server.py

Without this change, `wsl_configuration` variant is not recognized without client_variant.POST. The server is expected to start in that variant if the environment is properly set.
Issue and suggestions of fixes originally reported by @jpnurmi.

SystemSetupModel now acks the variant at start.

---

Makefile
scripts/installdeps.sh
scripts/runtests.sh
system_setup/server/controllers/configure.py

Since WSL cannot count on Cloud-Init, Subiquity System Setup Locale controller needs to take all necessary steps to install the locale selected by the user.
This PR achieves that goal by manipulating `/etc/locale.gen` file, running `locale-gen` command and installing language packs recommended by `check-language-support` script.

System locale manipulation wired into Subiquity.

---

system_setup/server/controllers/configure.py

The check-language-support on my machine was providing a single empty
newline as output, and the length check isn't catching that as the
resulting packages array has a value of `['']`.
Drop empty values from the list to avoid a `KeyError: ''` exception.

check-language-support: fix empty pkg list

---

snapcraft.yaml

The python links in the bin dir of the snap were resolving to system
python instead of the python binary found at usr/bin.  This appears to
be the root cause of why python scripts would fail to find their own
resources, such as ssh-import-id and lsb_release.

snapcraft: remove python links from snap bin dir

---

subiquity/tests/api/test_api.py

* Fix misuse of process communicate which resulted in a race condition
* Observe server state at startup to wait longer for a happy state
* Improve how timeouts are specified

Make api tests less flaky

---

subiquity/common/snap.py
subiquity/common/tests/test_snap.py
subiquity/server/controllers/refresh.py

Hello,
In specific scenarios, subiquity was suggesting to upgrade to a version that is older to the one currently running ; as in the following example [1]
_Version 21.01.2 of the installer is now available (21.06.01 is currently running)._
- To check if an update is available, subiquity queries the snapd daemon through its HTTP API
- The response sent back by snapd seems to 1:1 correspond to what is returned by `$ snap refresh --list`. I’d assume it’s using the same API call internally
- If snapd response contains a result with the “subiquity” title, then it is considered an new available version ; and the update available screen will effectively be displayed. subiquity does not do any filtering based e.g. on the version name returned.
I implemented basic filtering of the snap versions …

Compare the snaps versions to avoid suggesting a downgrade

---

subiquity/common/filesystem/labels.py
subiquity/common/types.py
subiquity/models/filesystem.py
subiquity/tests/api/test_api.py

Read ID_MODEL/VENDOR_ENC for disks to allow the GUI installer to show
pretty disk names without having to call libudev through FFI.
As a bonus, this also fixes disk names to match the machine config in
dry-run mode.
Related issues
- FR-1710
- canonical/ubuntu-desktop-installer#415

filesystem: add disk model and vendor name

---

examples/win10.json
snapcraft.yaml
subiquity/common/filesystem/labels.py
subiquity/common/types.py
subiquity/models/filesystem.py
subiquity/tests/api/test_api.py

On the Partition objects, add a 'os' field.
This contains os-prober results for that partition.

storage/v2: add os-prober data

---

scripts/runtests.sh
system_setup/server/controllers/configure.py

Hi, @dbungert !
This fix avoids integration tests to fail even if `check-language-support` returns an empty list of packages, which would be the case when all packages needed by one specific configuration of locale are already installed.
This complements #1127 .

Complementary to 1127 on integration side

---

snapcraft.yaml

Rollback the Probert version until os-prober is correctly present in the
Subiquity snap.

probert: rollback to pre os-prober

---

subiquity/client/controllers/filesystem.py
subiquity/common/filesystem/actions.py
subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/labels.py
subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/tests/test_actions.py
subiquity/common/filesystem/tests/test_manipulator.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/ui/views/filesystem/filesystem.py
subiquity/ui/views/filesystem/helpers.py
subiquity/ui/views/filesystem/partition.py

Currently this just puts a gap at the end of the list of partitions if it's possible to add a partition (or logical volume) to a disk. And then you can select the gap in the ui to add a partition.
The idea of course is that when it comes to editing partitions, there may be more than one gap to put a partition in.
I should probably write some tests for this version of the parts_and_gaps function (I do have a batch of tests written for the more interesting 'partition editing supporting' version).

add an object to represent a gap between partitions

---

subiquity/common/serialize.py
subiquity/models/filesystem.py
subiquity/server/controllers/refresh.py
subiquity/ui/mount.py
subiquitycore/ui/selector.py
subiquitycore/ui/width.py

Hello,
While working on `UbuntuAdvantageView`, I got the following exception (because I was doing something wrong):
```python
----> 1 raise Exception("don't know how to find width of %r", w)
Exception: ("don't know how to find width of %r", None)
```
I think the expected output would be:
```python
Exception: "don't know how to find width of None"
```
This happens because, unlike the functions from the `logging.*` family, `Exceptions` don't perform string interpolation. If we want string interpolation, we need to do it ourselves, either using f-string, `.format` or the old string modulo operator: `%`.
Fixed by using f-string to do the interpolation.
I also fixed other occurrences across the tree.
Thanks,
Olivier

Fix exception messages not interpolated properly

---

subiquity/client/controllers/filesystem.py
subiquity/client/controllers/ubuntu_advantage.py
subiquity/server/apt.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/kernel.py
subiquity/ui/views/help.py
subiquitycore/lsb_release.py
subiquitycore/tests/test_lsb_release.py

Hello,
This PR introduces a new parameter `dry_run` to `lsb_release`.
When this parameter evaluates to true, we will load the file `examples/lsb-release-focal` instead of the default `/etc/lsb-release`.
```python
lsb_release(dry_run=True)
lsb_release(path="/dummy")
lsb_release()
lsb_release(dry_run=False)
lsb_release(path="/dummy", dry_run=True)
```
All calls to `lsb_release` from Subiquity now explicitly pass the application-wide `dry_run` variable. Therefore, the returned value is consistent.
Also added unit tests to cover the `lsb_release` module / function.
This change was requested at https://github.com/canonical/subiquity/pull/1140#discussion_r770999254
Thanks,
Olivier

Make consistent calls to lsb_release

---

scripts/runtests.sh

Hello,
While looking at the logs from the integration tests, I observed some weird behavior:
```bash
++ ls .subiquity/var/cache/apt/archives/
+ '[' -z 'language-pack-en:amd64
wamerican:amd64
wbritish:amd64 | grep ' ']'
```
this comes from this instruction:
```bash
if [ -z "$( ls .subiquity/var/cache/apt/archives/) | grep $lang" ] ; then
```
One issue is that the `grep` is not being executed. It is used as a string literal and therefore causes the `-z` check to always be false. I rewrote the test and dropped the use of the subshell since we don't need it.
The other issue is that the lang variable is empty. I figured out it's empty because etc/default/locale contains:
```bash
LANG=en_US
```
and we expect it to contain:
```bash
LANG="en_US"
```
I changed the pattern matching to not expect …

Fix language packs detection in integration tests

---

examples/autoinstall.yaml
scripts/runtests.sh
subiquity/models/mirror.py
subiquity/models/tests/test_mirror.py
subiquity/server/controllers/mirror.py
subiquity/server/server.py

* The mixture of storage for disable_components in and out of the config
dict was confusing and caused bugs, depending on the flow
* disable_components now solely lives in the dict, like other items

apt: fix disable_components w/ autoinstall

---

autoinstall-schema.json
examples/autoinstall.yaml
scripts/runtests.sh
snapcraft.yaml
subiquity/server/controllers/mirror.py

Hello,
This PR adds partial support to Subiquity for apt preferences (aka. pinning / priorities) when using autoinstall.
The autoinstall schema for "apt" now supports the "preferences" configuration. Each preference element should contain the properties described below, that 1:1 map with the keywords from apt_preferences(5):
```
* package      <-> Package:
* pin          <-> Pin:
* pin-priority <-> Pin-Priority:
```
These preferences are forwarded to curtin through subiquity-curtin-apt.conf. Another PR will need to be done in curtin to have full support for this feature.

Add support for APT preferences through autoinstall in Subiquity

---

scripts/kvm-test.py

The function `drive()` used to return a string in the following format:
`"-drive file=/path/to/iso,..."`
However, qemu/kvm expects `"-drive"` to be an argument and`"file=/path/to/iso,..."` to be another argument.
The command was constructed as below since the beginning:
```python
kvm = [
"kvm",
"-cdrom", "custom.iso",          # <- OK
"-drive file=/path/to/iso,...",  # <- NOK
]
```
Before 06ac3f92, we would join all the arguments using spaces before executing the kvm command. Therefore we would luckily end up with a correct command:
`" ".join(kvm)  ->  "kvm -cdrom custom.iso -drive file=/path/to/iso,..."`
However, now that we supply the command to `subprocess.run` directly, the problem shows up.
Fixed by returning a `tuple("-drive", "file=/path/to/iso,...")` from the `drive()` function. …

Fix -drive option and -append option from kvm-test.sh

---

subiquity/ui/views/ubuntu_advantage.py

Hello,
Small adjustments following observations from @mwhudson in https://github.com/canonical/subiquity/pull/1151
* select the relevant button by default when applicable
* make the list of services scroll properly
* add empty lines consistently
* mention that services can be enabled through `ua`
Updated dialogs:

Small improvements for Ubuntu Advantage dialogs

---

snapcraft.yaml
subiquity/client/controllers/ubuntu_advantage.py
subiquity/common/tests/test_ubuntu_advantage.py
subiquity/common/ubuntu_advantage.py

We now embed the package `ubuntu-advantage-tools` in the Subiquity snap.
The goal is to make sure that u-a-c implements the `status --simulate-with-token` option, that might not be present in old ISOs.
We now have two different installations of ubuntu-advantage-tools (one from the ISO and one from the snap).
When invoking `ubuntu-advantage`, we need to make sure we use the Python installation from the snap rather than from base ISO. Similarly, we also need to make sure we use right `ubuntu-advantage` entry point (the one from the snap).
NOTE: the version of `ubuntu-advantage` that we place in the snap is currently too old. The version is picked up from `focal-updates`. We need to wait until 27.5~20.04.1 lands in `focal-updates` to get `--simulate-with-token` to work.

Embed ubuntu-advantage-tools into Subiquity snap and use it

---

subiquity/server/apt.py
subiquity/server/controllers/mirror.py

* apt_configurer cleanup is async, so needs an await
* ovmnt.lowers is a str, so fix list concatenation

Fix two bug reports from ubuntu-desktop-installer

---

subiquity/server/controllers/mirror.py

* apt cleanup often fails due to the temporary apt instances still being
around.  Skip the cleanup step, sadly, until that bug is addressed.

mirror: don't call apt cleanup

---

subiquity/client/client.py
subiquity/client/controller.py
subiquity/common/snap.py
subiquity/common/tests/test_snap.py
subiquity/common/ubuntu_advantage.py
subiquity/server/controller.py
subiquity/ui/views/ubuntu_advantage.py
subiquitycore/controller.py
system_setup/server/controllers/configure.py

I ran mypy over the source tree and had a look at some of the most obvious issues reported.
One of the most concerning was this one:
```
subiquity/common/snap.py:84: error: Unsupported operand types for > ("int" and "None")
subiquity/common/snap.py:84: error: Unsupported operand types for < ("int" and "None")
subiquity/common/snap.py:84: error: Unsupported left operand type for > ("None")
subiquity/common/snap.py:84: note: Both left and right operands are union
```
There is a part of a false-positive here. mypy is not able to infer that, but the operands in question can't be a mix of`int` and `None` based on the logic that happens before.
However, there is one scenario that leads to both operands of the comparison being `None`. And this scenario occurs when comparing a snap version to …

Fix some typing issues reported by mypy, including potential crash when comparing snap versions

---

Makefile
scripts/kvm-test.py

Passing `--use-fuse` to `scripts/kvm-test.py --install` allows to run as non-root.
It requires installation of the package fuseiso so the switch is disabled by default.

Add --use-fuse switch to kvm-test --install so it can run as non-root

---

snapcraft.yaml

The previous version of curtin that we were using would discard the APT preferences when running curthooks. Therefore, the APT preferences would not apply when installation packages from the "packages" autoinstall section.
Bump the version to fix the issue.

Bump curtin version to fix APT preferences being discarded

---

Makefile
console_conf/cmd/tui.py
console_conf/controllers/identity.py
scripts/installdeps.sh
subiquity/cmd/server.py
subiquity/cmd/tui.py
subiquity/server/controllers/install.py
subiquity/server/curtin.py
subiquity/server/server.py
subiquity/tests/api/test_api.py
subiquitycore/controllers/network.py
subiquitycore/core.py
subiquitycore/snapd.py
system_setup/cmd/server.py
system_setup/cmd/tui.py
system_setup/server/server.py

By splitting up the output directory instead of just writing to .subiquity,
we can run api tests in parallel.  About 7x speedup on my machine over running
them serially.

api test: run in parallel

---

examples/answers-bond.yaml
examples/answers-guided-lvm.yaml
examples/answers-imsm.yaml
examples/answers-lvm-dmcrypt.yaml
examples/answers-lvm.yaml
examples/answers-preserve.yaml
examples/answers-raid-lvm.yaml
examples/answers-raid.yaml
examples/answers-serial.yaml
examples/answers-swap.yaml
examples/answers.yaml
scripts/runtests.sh
scripts/validate-autoinstall-user-data.py
subiquity/models/ssh.py
subiquity/server/controllers/ubuntu_advantage.py

When running integration tests, we now automatically validate the generated autoinstall data (i.e., `.subiquity/var/log/installer/autoinstall-user-data`) against the JSON schema.
I added a script that does the validation: `scripts/validate-autoinstall-user-data.py`.
The script can be used for autoinstall files that have data enclosed inside the cloud-config header:
```bash
$ head -n 3 .subiquity/var/log/installer/autoinstall-user-data 
#cloud-config
autoinstall:
apt:
$ scripts/validate-autoinstall-user-data.py .subiquity/var/log/installer/autoinstall-user-data
```
or it can be used with the `--no-expect-cloudconfig` for our example files:
```bash
$ head -n 3 examples/autoinstall.yaml 
version: 1
early-commands:
- echo a
$ scripts/validate-autoinstall-user-data.py --no-expect-cloudconfig …
```

Validate output autoinstall data in integration tests

---

examples/uaclient-status-valid.json
subiquity/client/controllers/ubuntu_advantage.py
subiquity/common/tests/test_ubuntu_advantage.py
subiquity/common/ubuntu_advantage.py
subiquity/ui/views/ubuntu_advantage.py

Hello,
So far, for a valid contract token, we would list all the UA services that are marked "available".
After discussing with @alnvdl, it turns out that we also want to make sure these services are marked "entitled":
_available_ means it is available for the current machine type (e.g., fips may be available for a x86_64 machine running focal). This is irrespective of the contract; whereas
_entitled_ means that your contract gives you access to the service
Instead of only checking if a given UA service is available, we now also check if it is entitled.
Also fixed the unit test that expected "entitled" to be a boolean field ; but is actually a "yes" or a "no" string.

Don't list UA services that are not entitled

---

Makefile
scripts/installdeps.sh
subiquity/server/geoip.py
subiquity/server/server.py
subiquity/server/tests/test_geoip.py

GeoIP requests used to run on the default executor thread and would prevent the application from exiting if the GeoIP service would not respond quickly enough. We witnessed an obvious impact during an incident on geoip.ubuntu.com.
Move to aiohttp so that the HTTP calls are non blocking.
Also don't actually run HTTP requests in dry-run mode. We now use an hardcoded response.

Implement geoip using asyncio

---

subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/tests/test_manipulator.py
subiquity/server/controllers/filesystem.py

Add a scaling system to adjust the size of /boot and efi partitions in
response to the size of the disk.
Caveat:  scaling for efi is not smart enough to know if /boot is needed or not.

filesystem: add disk scaling for /boot and efi

---

system_setup/server/controllers/configure.py

By providing alternative directories to find LC_* locale definitions.
libc-bin package was recently updated to include the locale files for C.UTF-8 in `/usr/lib/locale/C.utf8` , breaking the system_setup tests. With this PR alternative directory paths are provided and tested for existence (and error checking as well) before attempting to copy the directory tree.

Fixes missing directory for system_setup integration test

---

snapcraft.yaml

os-prober is leaving around invalid devices and we don't know what to do
about it yet, but we do know that we don't require os-prober for
20.04.4.  Back this out.  LP: #1961640 LP: #1961628

Revert probert again to remove os-prober usage

---

snapcraft.yaml

The one installed by pip no longer works with our error report code.

snapcraft.yaml: remove bson from python-packages

---

subiquity/server/apt.py
subiquity/server/controllers/source.py
subiquity/server/tests/test_apt.py

Hello,
After struggling quite a bit with issues related to how we use overlays, I decided to do some improvements (hopefully?) to make it easier to work with overlays:
* added type hints where relevant to make it easier to understand what is what in the different contexts. Sometimes we expect `str` objects, sometimes we expect `Mountpoints` objects, sometimes expect `OverlayMountpoints` objects, or a combination of all the above ; with usually the name for the variables irrespective of the type. The recent refactoring of APT configuration also changed the type returned by the overlay-related functions (i.e., from the upperdir to the mountpoint) so it felt challenging to figure out what was what. I hope that the type hints make it a little simpler now.
* added some unit tests for the …

Add type hints to overlayfs helpers and add some unit tests.

---

snapcraft.yaml

The version of os-prober in focal has some device mapper code that we don't
want.  So instead pick up a version including the v1.75 changes.  Also pick up
my branch that allows setting env variables to find the os-prober dependent
scripts and utility program.

os-prober: installer newer version

---

subiquity/server/controllers/drivers.py

In the following patch, I changed the signature of the POST request handler for `/drivers` so that we expect the a JSON body instead of query string parameters:
3c9e5ca98fee453c37660c961de26ebe8e7dcaa8  Use body for parameters of POST /drivers
I forgot to update the function calling `self.POST` explicitly (i.e. without making an actual HTTP request). Therefore, it prevents the `drivers` component from being marked configured when drivers are found - subsequently making Subiquity hang on "executing late commands".

Fix POST to drivers not using payload wrapper for install

---

scripts/installdeps.sh

It's nice for the desktop installer contributors to be able to run
"./path/to/subiquity/scripts/installdeps.sh" without changing dir.

Allow calling installdeps.sh from anywhere

---

subiquity/server/controllers/drivers.py
subiquity/server/ubuntu_drivers.py

The `ensure_cmd_exists()` coroutine from ubuntu_drivers was never awaited. Therefore, the check would always silently succeed. Taking a look in `server-output` would show the warning though:
```
RuntimeWarning: coroutine 'UbuntuDriversHasDriversInterface.ensure_cmd_exists' was never awaited
self.ubuntu_drivers.ensure_cmd_exists(d.mountpoint)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
Also, the implementation of `ensure_cmd_exists()` when `SUBIQUITY_DEBUG=run-drivers` is set was failing because we use a shell builtin as an executable. This was not noticed since `ensure_cmd_exists()` was not executed and `arun_command` does not check for errors by default.

Fix not awaited ubuntu-drivers command existence check

---

subiquity/server/controllers/keyboard.py

This helps to fix https://github.com/canonical/ubuntu-desktop-installer/issues/250. Related discussion at https://github.com/canonical/ubuntu-desktop-installer/pull/154#issuecomment-878660593.

keyboard: run setxkbmap for the desktop installer

---

scripts/runtests.sh
subiquity/cmd/tui.py
system_setup/cmd/tui.py

Hello,
https://github.com/canonical/subiquity/pull/1201 showcased that some important server-side warnings could slip through our tests because we don't check the content of `server-output` for warnings.
A simple way to make sure we detect any warning is to check if the server's standard error is empty. Unfortunately, not only does the `server-output` file contain the server's standard error, but it also contains the server's standard output (sometimes interleaved?)
By redirecting the server's standard output and standard error to two distinct files instead of one, we can simplify the detection of warnings / errors.
I implemented the following change in both subiquity and system_setup:
* the server's standard output goes to `server-stdout` ; whereas
* the server's standard error goes to …

Better detect server-side warnings / errors in integration tests

---

subiquity/client/controllers/filesystem.py
subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/tests/test_manipulator.py
subiquity/server/controllers/filesystem.py

Move these around so that we don't need a manipulator instance to use.
Part 1 of breaking #1200 into chunks.

sizing: scaling funcs usage & constants

---

apt-deps.txt

Running `make install_depends` does not (always) pull python3-systemdwhich is a dependency of Subiquity.
In environments having Install-Recommends enabled, python3-systemd is pulled by apport which is itself pulled by python3-apport.
Fixed by adding it to the list of dependencies in apt-deps.txt

Add python3-systemd as an explicit dependency

---

apt-deps.txt

The build instruction contain a step
PYTHONPATH=probert ./probert/bin/probert --all > mymachine.json
This requires package os-prober.
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>

atp-deps.txt: add os-prober

---

snapcraft.yaml

Building with --destructive-mode fails with error:
dh install
dh_testroot
dh_testroot: error: You must run this as root (or use fakeroot).
make: *** [debian/rules:6: install] Error 255
Use fakeroot for installation.
Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>

Installing os-probe requires fakeroot

---

subiquity/server/controllers/network.py
subiquitycore/controllers/network.py

If you run dryrun for console-conf, go to the network page, go to an
interface, then info, a crash of the form
TypeError: object str can't be used in 'await' expression
can be seen.  The signature for the core version of get_info_for_netdev
is not async, but a non-async method returning str.
So skip the loading dialog, which wants the awaitable.

console-conf: fix crash on network info

---

snapcraft.yaml

synchronize with https://git.launchpad.net/curtin
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>

curtin: Add riscv64 to supported UEFI architectures

---

scripts/validate-yaml.py

- The 20.04 autoinstaller expects a swap path of 'none'
- Added support for the working units for partition sizes
Both changes where needed for my customized partition layout to be valid. The installation afterwards was successful.
Opening this PR because the script otherwise helped finding errors in my customized partition layout :slightly_smiling_face:.
```
config:
- {ptable: msdos, size: "largest", preserve: false, name: '', grub_device: true, type: disk, id: bootdrive}
- {device: bootdrive, size: 1MB, flag: bios_grub, number: 1, preserve: false, grub_device: false, type: partition, id: bios_boot_partition}
- {device: bootdrive, size: '512M', wipe: superblock, flag: 'boot', number: 2, preserve: false, grub_device: false, type: partition, id: bootpart}
- {fstype: ext4, volume: bootpart, …
```

fixing swap path + support partition size units

---

autoinstall-system-setup-schema.json
examples/answers-system-setup-reconf.yaml
examples/autoinstall-system-setup-full.yaml
subiquity/common/types.py
system_setup/client/controllers/wslconfadvanced.py
system_setup/common/wsl_conf.py
system_setup/models/wslconfadvanced.py
system_setup/server/controllers/wslconfadvanced.py
system_setup/tests/golden/answers-reconf/wsl.conf
system_setup/tests/golden/autoinstall-full/wsl.conf
system_setup/ui/views/wslconfadvanced.py

Grow a new API for enabling/disabling systemd experimental support. We do this by chaining a specific command= in the boot section. We preserve the user customized command= content when systemd experimental support is not enabled.

Systemd experimental support

---

subiquity/cmd/server.py
subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/tests/test_gaps.py
subiquity/common/types.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py
subiquity/server/controllers/filesystem.py

Add a way to turn on more interesting gaps behaviour on the command line, and enable deleting preserved partitions in that mode. I think this approach has legs, it lets us break everything in the new world while not worrying about breaking existing behaviour. With a finished version of [dbungert:offsets-and-stretchy](https://github.com/dbungert/subiquity/tree/offsets-and-stretchy) merged in it might not even result in completely mad behaviour!

Optional v2 storage

---

examples/answers-bond.yaml
examples/answers-guided-lvm.yaml
examples/answers-imsm.yaml
examples/answers-lvm-dmcrypt.yaml
examples/answers-lvm.yaml
examples/answers-preserve.yaml
examples/answers-raid-lvm.yaml
examples/answers-raid.yaml
examples/answers-serial.yaml
examples/answers-swap.yaml
examples/answers.yaml
subiquity/client/client.py
subiquity/client/controllers/__init__.py
subiquity/client/controllers/drivers.py
subiquity/server/controllers/drivers.py
subiquity/ui/views/drivers.py

We now have a GUI component to control whether we want to install available third-party drivers.
In normal conditions, the page shows a checkbox "Install the available drivers" alongside the list of drivers that are available. However, if no drivers are available, we will skip the page upon reaching it.
Now, if by the time we reach the page, we haven't been able to find the list of drivers available yet, then a progress bar will be displayed instead.
Then we will either display the list of drivers or show "no drivers are available". 
Hitting the "continue" button while the progress bar ls displayed will not install drivers if they are available.
To test the feature using dry-run:
```bash
SUBIQUITY_DEBUG=has-drivers make dry-run
make dry-run
```

Add client-side controller and view to install third-party drivers on server installer

---

subiquity/tests/api/test_api.py

This calls add_boot_partition on disks that are filled by pre-existing
partitions. That should not work, and does not in a branch I am working
on.

make test_v2_multi_disk_multi_boot api test more correct

---

subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/sizes.py
subiquity/common/filesystem/tests/test_manipulator.py
subiquity/common/filesystem/tests/test_sizes.py
subiquity/server/controllers/filesystem.py

This avoids a circular import in another branch I am working on.

move partition size related stuff to its own module

---

subiquity/server/tests/test_ubuntu_advantage.py
subiquity/server/ubuntu_advantage.py

Fixed in main as part of #1202 
RFC3339 allows dates to use the Z suffix instead of a time zone offset of 0. Unfortunately, this is not supported by Python
datetime.date.fromisoformat. Work around the issue by replacing the optional Z character with +00:00 before parsing the date.
(cherry picked from commit 23a66ad33599096e3744db62615bc11df1e7f2e7)

Fix crash when UA token expiration date has Z suffix

---

subiquity/server/tests/test_ubuntu_drivers.py
subiquity/server/ubuntu_drivers.py

The command used in run-drivers mode is not spelled correctly.
This was not noticed before because:
* on my machine, `ubuntu-drivers` does not report anything to install.
* it is considered a valid use-case that the command `ubuntu-drivers` does not exist.

Fix command used in run-drivers mode

---

scripts/runtests.sh
system_setup/server/controllers/configure.py

It's been quite painful trying to work with apt python library in the WSL snap environment so far, so today we decided to drop it in favor of `subprocess.run` with the environment adjusted to ensure we can run system `apt` instead of adding it to the snap.
This pull request only affects the scope of `system_setup` and adjusts `apply_locale()` and `create_user()` functions to perform their duties using system binaries.
Besides the subiquity CI tests, this code has been tested in WSL and behaved as expected.

Removes apt python library from system_setup

---

subiquity/server/runner.py
subiquity/server/tests/test_runner.py

Allow the TIMESCALE value to flow to the curtin command runner.

Faster curtin replay tests

---

subiquity/client/controllers/ubuntu_advantage.py

Don't show the ubuntu-advantage screen for Ubuntu 22.04.0 but keep the possibility to provide a contract token through autoinstall.

ubuntu-advantage: disable for 22.04.0 release

---

system_setup/cmd/tui.py

The `system_setup` server was prepared to receive this CLI option, but the TUI client was not, thus in live-run that option had no effect.

Enables passing the autoinstall CLI to the server.

---

system_setup/server/controllers/configure.py

UDI sets the SNAP env var to '.' for development purposes, affecting the behavior of `system_setup`, which server is started by the GUI.
See: https://github.com/canonical/ubuntu-desktop-installer/commit/9eb6f04
It is unlikely that under test or production that env var will ever by just '.'. On the other hand in dry-run we want this controller to interpret it as '/' if not properly set, thus discarding the '.' directory.

Ensures snap_dir='/' if not better specified.

---

subiquity/client/controllers/filesystem.py

I created https://bugs.launchpad.net/subiquity/+bug/1968161 earlier today.
In the normal workflow, if the "Waiting for storage probing to complete" screen is shown, it will automatically be replaced by the "Guided storage configuration" screen when the probing operation finishes.
However, sometimes, it seems that we skip refreshing the display after the probing operation finishes.
My theory is that sometimes we try to replace the "Waiting for storage" screen with the "Guided storage configuration" screen *before* the "Waiting for storage" screen is actually displayed.
To confirm or refute this theory, I am adding a log line that shows what the current display is when we decide to skip refreshing the screen. When we reproduce the issue in the future, a quick look at the client logs should …

storage: log reason for not updating the screen after probing finishes

---

subiquity/ui/views/installprogress.py

None of these four states should be common, but it is possible at least
to hit CLOUD_INIT_WAIT with an ill-timed server process restart.

install progress: handle obscure states

---

snapcraft.yaml
subiquity/server/controllers/filesystem.py

* Cherry-pick 119f17b3
* Point to Curtin ubuntu/jammy branch commit

curtin / block-probe: pick up risc-v fixes for Jammy

---

subiquity/client/client.py
subiquity/common/filesystem/boot.py
subiquity/models/filesystem.py
subiquity/models/network.py
subiquity/server/apt.py
subiquity/server/controllers/network.py
subiquity/server/controllers/reporting.py
subiquity/server/curtin.py
subiquity/server/runner.py
subiquity/server/server.py
subiquity/server/tests/test_ubuntu_advantage.py
subiquitycore/lsb_release.py
subiquitycore/models/network.py
subiquitycore/utils.py

Changes included:
* added/updated type hints where type used was ambiguous/wrong
* avoided redefinition of types that would mask the former symbol
* ~~introduced `ProcessWithArgs` to avoid adding member variables dynamically (type checkers don't like it)~~
* fixed typo in `addresses` variable name
* renamed `arun_command` variable that was interfering the `arun_command` function when using `ctags -R`
* accepted `Sequence[str]` (aka. `List[str]` or `Tuple[str]`) for commands instead of just `List[str]` in `utils.py`. ubuntu_pro.py was already passing a `Tuple[str]` to one of these functions so mypy was not happy about it.
* helped type checkers figure out that `returncode` cannot be `None` anymore after calling `.communicate()`
When using `mypy`, it lowers the number of errors by 21.

Some more code cleanup

---

subiquity/client/controllers/filesystem.py
subiquity/ui/views/filesystem/filesystem.py

Per LP: #1968160, with 2 or more disks, go to guided storage config, hit
done.  At file system summary, hit back, and choose the other disk.
While this screen does say so, one might not notice that the first disk
is still setup to be formatted.
Instead, when going back to guided storage, a reset is also done.

filesystem: going back to guided also does reset

---

subiquity/common/filesystem/manipulator.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

A scenario that should happen nearly always for guided direct, when we
add_boot_disk from partition_disk_handler we must update the gap or the
target partition is at the wrong offset.
(This bug was introduced with the offsets&gap work and is not preset on Jammy)

Fix guided direct

---

subiquity/common/apidef.py
subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/tests/test_manipulator.py
subiquity/common/types.py
subiquity/server/controllers/filesystem.py
subiquity/tests/api/test_api.py

Move storage/v2/reformat_disk to body instead of query args.
Add optional ptable arg, which can be used to format to a msdos table.

v2/reformat: accept ptable argument

---

system_setup/server/controllers/locale.py

TUI client was able to GET() the language before it was set with the prefilled option in production. This attempts to ensure the earliest initialization possible.

Sets with the prefilled language before starting controllers

---

apt-deps.txt
subiquity/server/geoip.py
subiquity/server/tests/test_geoip.py

https://bugs.launchpad.net/ubuntu-power-systems/+bug/1969393
The patch that moved from requests to aiohttp for geoip seems to be the trigger that makes Subiquity crash with bad DNS.
The root cause is still TBD but reverting the patch seems to prevent Subiquity from crashing.
Let's test this patch again should we decide to merge it.

Revert "Move to aiohttp for GeoIP requests"

---

system_setup/server/server.py

EarlyController was still logging to systemd journal for WSL.

Fix WSL crash on autoinstall due attempts to log to systemd journal

---

subiquity/server/controllers/drivers.py
subiquity/tests/api/test_api.py

When a HTTP client sends a query but closes the socket before an answer is received,  aiohttp signals it on the server end by raising an `asyncio.CancelledError` in the associated query handler.
By default, when a task is cancelled with asyncio, the task(s) that it is currently awaiting on are cancelled as well.
The GET handler for `/drivers?wait=true` awaits on the "list drivers" task. Therefore, if the GET handler gets cancelled, so will be the "list drivers" task.
When that happens, any subsequent call to `GET /drivers?wait=true` will make the server raise an `asyncio.CancelledError` because the "list drivers" task has already been cancelled. This results in:
* the socket being closed from the server end
* an `aiohttp.client_exceptions.ServerDisconnectedError` exception raised on the …

drivers: prevent client crash if GET /drivers is closed from client side

---

subiquity/client/client.py
subiquity/client/controllers/filesystem.py
subiquitycore/tui.py

_Not the greatest nor the worst way to fix https://bugs.launchpad.net/subiquity/+bug/1968161_
We now implement an _optional_ indirection mechanism for `make_ui()` functions and use it in the filesystem controller to work around the screen not refreshing issue.
Hopefully, the commit messages should explain in details what's going on and what the patches bring to the table.

Fix storage screen sometimes not refreshing after slow probing

---

scripts/runtests.sh

The use of `sh -c "$command"` to run the subiquity commands was not necessary and it makes it easy to forget to quote arguments here and there.
Instead, we can execute commands directly with, which saves us the shell invocation + potential trouble where quoting properly is not straightforward.
Also, I took the opportunity to reorder the arguments passed to Subiquity in a consistent order across the different invocations that we have:
1. Arguments used by the client & the server (e.g., `--dry-run`, `--output-base`) 
2. Arguments used by the client only
3. Arguments used by the server only

tests: consistently run Subiquity commands

---

subiquity/client/controllers/filesystem.py

In order to fix a screen not refreshing issue, the following patch changed the return type of `make_ui` from an object to a callable in the storage controller:
414a2235 storage: fix screen sometimes not refreshing after slow probing
The storage controller is the only one that reuses its `make_ui()` coroutine internally. Unfortunately, the code that calls `await make_ui()` was not updated in the storage controller:
```python
File "/home/olivier/dev/canonical/subiquity/subiquity/client/controllers/filesystem.py", line 257, in _guided
self.ui.set_body(await self.make_ui())
File "/home/olivier/dev/canonical/subiquity/subiquity/ui/frame.py", line 41, in set_body
super().set_body(widget)
File "/home/olivier/dev/canonical/subiquity/subiquitycore/ui/frame.py", line 59, in set_body …
```

storage: fix crash when coming back from FS screen

---

apt-deps.txt
subiquity/server/geoip.py
subiquity/server/tests/test_geoip.py

python3-aiohttp has been fixed and released in focal-updates.
New Subiquity builds should not be affected by LP: #1969393 anymore.
This reverts commit 413cc873379fa15964575047e3c76f99439a8e54.

geoip: move from requests to aiohttp again

---

subiquity/server/controllers/filesystem.py
subiquitycore/async_helpers.py
subiquitycore/tests/test_async_helpers.py
subiquitycore/tests/test_pubsub.py

If the probert probe triggers a udev event, we can loop forever.
Fixed by not restarting an active probe, which can lose information if
it appears mid-probe but that's better than an infinite loop.

filesystem: fix udev infinite loop

---

subiquity/client/client.py
subiquity/ui/views/help.py
system_setup/client/client.py
system_setup/models/system_setup.py

WSL installer TUI currently crashes if user clicks on Help menu due missing network parameter in the app basemodel. When fixing that we noticed that the Help/About message required some customisation. This PR aims to provide the customisation point for variants and provide the fix for the WSL case.
This aims to close https://github.com/ubuntu/WSL/issues/202

TUI Help/About message customisation point for variants

---

scripts/runtests.sh
system_setup/cmd/server.py
system_setup/server/server.py

Per aiohttp documentation, the `host` parameter of the TCPSite sets the interface on which the server will listen on. Listening on 127.0.0.1, as you know, means only clients running on the same host can reach that server. Interestingly, with WSL2, clients running on Windows can make requests to 127.0.0.1 which crosses the vEthernet adapter and reach the VM as if it was the same host. This behavior was tested on Windows 10 and 11. Thus by simply locking to the loopback interface can give us some level of security and keep the solution simple.
This PR enables the component in charge of starting the server to choose which port to bind to. This is a key feature to enable migrating the OOBE GUI to a Windows application.

Enables TCPSite for WSL

---

subiquity/common/types.py
subiquity/server/tests/test_ubuntu_advantage.py
subiquity/server/ubuntu_advantage.py

The JSON returned by uaclient for a status request contains the `auto_enabled` property for each service. This property tells whether a given service is enabled automatically when `ua attach` is done. We will need this information going forward so we now include it in the success response to `/ubuntu_pro/check_token`:
```json
{
"status": "VALID_TOKEN",
"services": [
{
"name": "esm-infra",
"description": "UA Infra: Extended Security Maintenance (ESM)",
"auto_enabled": true
},
{
"name": "fips",
"description": "NIST-certified core packages",
"auto_enabled": false
}
]
}
```

ubuntu-pro: add auto_enabled property for services

---

snapcraft.yaml
subiquity/client/client.py
subiquitycore/tests/test_utils.py
subiquitycore/utils.py

Per LP: #1975629, environment variables used to run Subiquity are leaked
into the debug environment, and in the case of things like PYTHONPATH
can harm commands run in that shell.

debug shell: use a clean environment

---

subiquity/ui/views/filesystem/guided.py
subiquitycore/ui/form.py
subiquitycore/ui/tests/test_form.py

When the validation of a field fails in a form, we disable the Done button. With child forms, however, it did not work because they have their own set of hidden buttons ; that are not the ones the users interacts with.
This patch makes parent forms recurse on the child forms when checking if any field is in error. Also, when a child form undertakes validation, it now propagates to the parent, so that the done button can be immediately enabled/disabled.
Having a validation error in a child form that is not currently enabled should not prevent the user from moving forward, so we disable recursion for child forms that are disabled.
--
The above change was needed as part of the Ubuntu Pro changes where we make use of child forms for manual token or Ubuntu One email. Since Guided Storage also …

Check child forms status when disabling/enabling Done button of a form

---

subiquity/tests/test_timezonecontroller.py

Fix missing python3-mock dep which allows folks to run unittests on a new jammy container
lxc launch ubuntu-daily:jammy dev-j
lxc exec dev-j bash
git clone https://github.com/canonical/subiquity.git
apt install make
make aptdeps
make unit
....
======================= 436 passed, 68 warnings in 4.88s =======================
```
_________ ERROR collecting subiquity/tests/test_timezonecontroller.py __________
ImportError while importing test module '/root/subiquity/subiquity/tests/test_timezonecontroller.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
subiquity/tests/test_timezonecontroller.py:16: in <module>
import mock
E …
```

deps: fix missing developer dep python3-mock for apt-deps make target

---

system_setup/cmd/server.py

This is the end result (much better than printing the whole range of valid port numbers):
```
starting server
usage: system_setup [-h] [--dry-run] [--socket SOCKET]
[--autoinstall AUTOINSTALL] [--prefill PREFILL]
[--output-base OUTPUT_BASE] [--tcp-port [49152 to 60999]]
System Setup - Initial Boot Setup
options:
-h, --help            show this help message and exit
--dry-run             menu-only, do not call installer function
--socket SOCKET
--autoinstall AUTOINSTALL
--prefill PREFILL     Prefills UI models with data provided in a
prefill.yaml file yet allowing overrides.
--output-base OUTPUT_BASE
in dryrun, control basedir of files
--tcp-port [49152 to 60999]
The TCP port Subiquity must listen to. It means TCP
will be used instead of Unix domain sockets. Only
localhost connections are …
```

Better help message for system setup

---

scripts/runtests.sh

`timeout 60` might be too short for someone with lots of network interfaces.
Since we grab the PID and run the server in the background, the timeout is not critically necessary.

[system_setup] Avoid integration test failure due server exited

---

subiquity/models/tests/test_subiquity.py

The recently changed group list check is a bit fragile to the exact
groups available on the system.  Mock out the list of actually existing
groups.

unittests: fix group check

---

subiquity/common/filesystem/boot.py
subiquity/common/filesystem/manipulator.py
subiquity/common/filesystem/sizes.py
subiquity/common/filesystem/tests/test_manipulator.py
subiquity/common/filesystem/tests/test_sizes.py
subiquity/server/controllers/filesystem.py

* send gaps of the intended partition size to create_partition
* create_partition now uses the gap size instead of spec size
* partition size scaling functions for boot & uefi expect an available space value instead of a disk (which it would only use to get the total disk size)

filesystem: several size related tweaks

---

subiquity/client/controllers/ubuntu_pro.py

During the development cycle of 22.04, jammy was not yet marked an LTS
version. To have Ubuntu Pro screen fire up on that version, we had to
explicitly make an exception for Jammy.
Since Jammy is official LTS now, we can drop this explicit check.

ubuntu-pro: remove hardcoded test for jammy

---

subiquity/server/controllers/tests/test_filesystem.py

Add coverage for LVM cases
Use parameterized to reduce some redundancy.

filesystem: guided lvm unit tests

---

subiquity/common/filesystem/boot.py
subiquity/common/filesystem/tests/test_manipulator.py

The BIOS boot plan check assumes that there is at least one result in
the list from gaps.parts_and_gaps(), but that isn't the case if the disk
is small.
Showed up in VM testing using cloud-localds to seed the autoinstall
file.

boot: handle small disk case

---

subiquity/tests/api/test_api.py

Running the API tests in Ubuntu 22.04 or newer versions result in the following warning:
```python
DeprecationWarning: with timeout() is deprecated, use async with timeout() instead
```
The deprecation message was introduced as part of async-timeout 4.0.0:
https://github.com/aio-libs/async-timeout/blob/master/CHANGES.rst#400-2021-11-01
The ability to use `async_timeout.timeout` as an async context manager was introduced in version 1.3.0 in 2017 so there is no problem using it:
https://github.com/aio-libs/async-timeout/blob/master/CHANGES.rst#130-2017-08-23
The version of python3-async-timeout present in the archives at the time of writing is:
* 4.0.1 in jammy.
* 3.0.1 in focal.
* 2.0.0 in bionic.

test/api: replace use of deprecated "with timeout()"

---

subiquity/common/resources.py
subiquity/models/subiquity.py
subiquity/models/tests/test_subiquity.py

Align with latest cloud-init schema avoid using depracated
value types for users. groups definitions in cloud-config.
Also fix get_users_and_groups to return a list instead of
dict as all call sites expected it to return a list.
Also fix the unit tests.
Cherry-pick
7f233bc09b00cc885a76a3d9305bea0707bf0c31
62ad68bd7668149e1eb9acf661bc0e98e951f66b
Co-authored-by: Chad Smith <chad.smith@canonical.com>

cloud-config: schema drop deprecated dict user.groups value type (jammy branch)

---

subiquity/common/filesystem/sizes.py
subiquity/common/filesystem/tests/test_sizes.py
subiquity/common/types.py
subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py

Add calculations for a suggested minimum install size that contains
padding for swap, updates, boot.
Add calculations for helping resize, to examine the space available and
make suggestions about what the existing partition might be resized to.
(not used yet)

sizes: calculations for install_min and resize

---

subiquity/client/controllers/ubuntu_pro.py
subiquity/server/ubuntu_advantage.py
subiquity/ui/views/ubuntu_pro.py

Hello,
This PR updates the different Ubuntu Pro screens to match the new mockups.
I deliberately did not include any of the related magic-attach related screens ; because I'm still working on that part.
The presence of the radio button in the screen asking to input the contract token can look stupid because there is no other radio button.
When magic-attach comes in, the user will either choose to manually input the token or to supply a Ubuntu One email address ; so the radio button will make sense when we get there. I could try to hide the radio button for now but the mechanism we have to manage subforms is a bit of an adventure ; so I'd prefer to keep it.
I've uploaded screen captures at https://people.canonical.com/~ogayot/subiquity-captures
Besides purely visual changes, the PR also …

ubuntu-pro: update screens to match design mockups

---

subiquity/server/tests/test_ubuntu_advantage.py
subiquity/server/ubuntu_advantage.py

In case of error, u-a-c exits with status 1. When the contract token supplied is invalid, it is also considered an error ; which previously made us unable to make the distinction between:
* an invalid token
* a more generic error such as network error or service unavailable error
Thanks to an update in u-a-c, we can now determine if the token was invalid, by parsing the standard output of the process, even when it exits with status 1.
The output is expected to be a JSON object that includes an array of errors where each error has a specific error code.
The error code for an invalid token is `attach-invalid-token` ; which we now look for in the output to determine if the contract token was invalid.

ubuntu-advantage: determine on error if token was invalid

---

subiquity/client/controllers/ubuntu_pro.py
subiquity/common/types.py
subiquity/server/ubuntu_advantage.py
subiquity/ui/views/ubuntu_pro.py

What we used to call the services screen now includes the following information about the subscription:
* owner of the contract
* contract token
* name of the contract
The information is obtained via the `/ubuntu_pro/check_token` API which itself leans on u-a-c.
It also makes sense to call the screen "subscription screen" rather than "services screen" from now on.

ubuntu-pro: add info about subscription in former services screen

---

subiquity/server/controllers/filesystem.py

When running `make lint` with flake8 >= 4.0.0 (available in jammy), the following error is reported:
`subiquity/server/controllers/filesystem.py:158:33:F541 f-string is missing placeholders`
Github runs the lint job in a focal container, where only version 3.8.4 of flake8 is installed. F541 is not implemented in 3.8.4 so it does not fail.

filesystem: fix use of f-string without placeholder

---

.github/workflows/build.yaml

Add a second linter container to also lint against the newer python.

workflow: +kinetic for linter

---

snapcraft.yaml
subiquity/client/client.py
subiquity/server/controllers/refresh.py
subiquitycore/tests/test_utils.py
subiquitycore/utils.py

* LP: #[1974077](http://pad.lv/1974077) cherry-pick fix 44464480a60c9c415ef3f4c51beddf76b9aa3e7b for autoinstall interactive-sections
* LP: #[1975629](http://pad.lv/1975629) cherry-pick fixes 74e118d735c7f361b8e3dc129f32e3a0906e4dd5 and 5b30732f148f5ae6260037121adda9f0b0fb7ebf for debug shell
* cherry-pick improvements bd6647d6ec5366778df38a2a1b8e6aed8ba5ca22 for snap metadata to set source-code and issues fields
* LP: #[1978139](http://pad.lv/1978139) cherry-pick a9520b71003b292be286e0ffdb8b3909a4e1ea6c, 135a870509a521f6e5088767e5367f2c41bd4763, 942e5f5f1bd9dcf44d41ce3fb64da4529210a0f1 for fix related to snap refresh when using SSH

fixes targetting jammy.1

---

examples/simple.json
subiquity/tests/api/test_api.py

Increase size of the disk in the simple machine config to 100 GiB.
This file is used heavily as a basic starting machine config and it
should be large enough for many types of tests.

examples: make the 'simple' mc disk bigger

---

subiquity/common/types.py
subiquity/server/controllers/install.py
subiquity/tests/api/test_api.py
subiquity/ui/views/installprogress.py
system_setup/server/controllers/configure.py

With the plan to call curtin multiple times where each invocation has a specific purpose, we want the client to have a simple way to monitor the status of the installation.
Instead of defining new application states for each stage, we will report the more generic `WAITING` / `NEEDS_CONFIRMATION` / `RUNNING` states in a loop until we get to the final stages of the installation.
To start with, we are dropping `POST_WAIT` and `POST_RUNNING` in favor or `WAITING` and `RUNNING`.
Since this impacts both Subiquity, the desktop installer and console-setup. I'm marking the PR a draft until enough testing is done.

meta/status: replace POST_WAIT and POST_RUNNING by generic states

---

subiquity/common/filesystem/tests/test_labels.py
subiquity/models/filesystem.py

This is pretty ugly but it expect it fixes the crash.
For https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1982903

add .path to Raid so for_client(raid-with-partitions) works

---

subiquity/client/controllers/ubuntu_pro.py

mypy reported the following:
```
subiquity/client/controllers/ubuntu_pro.py:103: error: Missing return statement
```
The function `is_token_added_overlay` supposedly returns a boolean. But the absence of a final `return False` statement made it return `None` by accident.
In practice, it should not make a difference because returning `False` or `None` evaluate to `False` in a boolean context. But returning `False` is cleaner (sorry Perl).

ubuntu-pro: fix missing return statement

---

autoinstall-schema.json
examples/autoinstall-user-data.yaml
scripts/runtests.sh
subiquity/models/source.py
subiquity/server/controllers/source.py

This PR brings support for the following data in autoinstall configuration:
```yaml
source:
id: ubuntu-server-minimal
```
One of the particularity of the source controller is that it does not have access to the source catalog by the time the autoinstall data is loaded. Therefore, we have to store the data first and do the magic later in `apply_autoinstall_config`.
The `search_drivers` key used to be required as part of the `source` section. This made sense (I wonder, really?) when `search_drivers` was the only key supported (what's the point of declaring the section if we're not setting any value?) but it should be made optional now since the user may want to specify the source ID without bothering with drivers stuff.
<details>
<summary>moved to …

source: allow to specify source ID in autoinstall config

---

subiquity/models/filesystem.py

The filesystem object IDs are really only meant to be a semireadable
unique string, and not for display to end users.  Partitions in
particular were bad in this respect, as they could look like the number
on the end was the partition number.
Uglify the object IDs a bit to try to convey the above.

filesystem: part ids are not part nums

---

Makefile
examples/postinst.d/copy_nm_connections
subiquity/cmd/server.py
subiquity/server/controllers/cmdlist.py

This PR extends the early / late / error controllers so that they can declare builtin commands.
Builtin commands are executed before other commands declared in the relevant autoinstall section.
In the late controller, we now declare a builtin command that runs `run-parts /etc/subiquity/postinst.d`. The desktop installer can use this and place executable scripts under `/etc/subiquity/postinst.d` to copy network-manager connections and do other things.

Execute run-parts on /etc/subiquity/postinst.d before executing any other late_commands

---

subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/tests/test_gaps.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

* simplify `guided()` with singledispatch
* move gaps.within to a gap object method
* add warning about autoinstall having layout and manual config
* expand a side-by-side unit test to also cover gpt

guided: singledispatch and other refactors

---

subiquity/client/controllers/ubuntu_pro.py
subiquity/common/apidef.py
subiquity/common/types.py
subiquity/server/contract_selection.py
subiquity/server/controllers/ubuntu_pro.py
subiquity/server/tests/test_contract_selection.py
subiquity/server/tests/test_ubuntu_advantage.py
subiquity/server/ubuntu_advantage.py
subiquity/tests/api/test_api.py
subiquity/ui/views/ubuntu_pro.py
subiquitycore/palette.py
subiquitycore/ui/utils.py

Apologies for the size of the diff :/
This adds the support for magic-attach / contract-selection in Subiquity.
Unfortunately, testing this PR on a current ubuntu server ISO will fail because we are relying on an unreleased feature of ubuntu-advantage-tools. Also the ubuntu.com/pro/attach website is not yet available for the user to do the contract selection.
The dry-run implementation exists but is limited. 
Upon reaching the Ubuntu Pro screen, the user is presented the user-code `AAAAAA`.
The user-code expires after 10 minutes (affected by `SUBIQUITY_REPLAY_TIMESCALE`).
When the user-code expires, a new contract selection is initiated and the next user-code (`AAAAAB`) will be presented instead,
The user has no way to select a contract in dry-run mode so the user-code will keep expiring …

Updates for Ubuntu-Pro with magic-attach

---

subiquitycore/palette.py

Per Design's recommendation in:
https://github.com/canonical/ubuntu-desktop-installer/issues/1073#issuecomment-1225569053
`#808080` choosen due its value being part of the xterm256-color color space.

Makes our gray ligther to increase contrast.

---

subiquitycore/models/network.py

Because it affects `/etc/apt/sources.list`.
```
2022-08-26 13:08:37,225 INFO root:37 start: subiquity/Meta/mark_configured_POST: 
2022-08-26 13:08:37,225 DEBUG subiquitycore.models.network:419 has_network True
2022-08-26 13:08:37,226 DEBUG subiquity.models.subiquity:219 model network for install stage is configured, to go {'filesystem'}
2022-08-26 13:08:37,226 DEBUG subiquity.models.subiquity:219 model network for postinstall stage is configured, to go {'timezone', 'identity'}
2022-08-26 13:08:37,226 INFO root:37 finish: subiquity/Meta/mark_configured_POST: SUCCESS: 200 null
2022-08-26 13:08:37,226 INFO aiohttp.access:206  [26/Aug/2022:13:08:37 +0000] "POST /meta/mark_configured?endpoint_names=%5B%22network%22%5D HTTP/1.1" 200 190 "-" "Dart/2.17 (dart:io)"
```

Log NetworkModel.has_network changes

---

scripts/runtests.sh
scripts/test-system-setup-loopback-only.py

This speeds up the system_setup test that makes sure only the loopback interface listens to TCP connections.
The test used to take at most `10 * 2 * number_interfaces` seconds. On my machine, it took over one minute.
We now run all `curl` calls in parallel so it takes 10 seconds at most.

integration: speed up check for listening interfaces in system_setup

---

autoinstall-system-setup-schema.json
examples/answers-system-setup-init.yaml
examples/autoinstall-system-setup-full.yaml
subiquity/client/client.py
subiquity/client/controllers/welcome.py
subiquity/common/apidef.py
subiquity/common/types.py
subiquity/tests/api/test_api.py
subiquity/ui/views/tests/test_welcome.py
subiquity/ui/views/welcome.py
system_setup/client/client.py
system_setup/client/controllers/__init__.py
system_setup/client/controllers/wslsetupoptions.py
system_setup/models/system_setup.py
system_setup/models/wslsetupoptions.py
system_setup/server/controllers/__init__.py
system_setup/server/controllers/configure.py
system_setup/server/controllers/wslsetupoptions.py
system_setup/server/server.py
system_setup/ui/views/wslsetupoptions.py

All this chunk of code because of one boolean flag.
The motivation for this work is detailed in https://github.com/canonical/ubuntu-desktop-installer/issues/1073 and https://github.com/ubuntu/WSL/issues/174. In short, 
setting up Ubuntu on WSL 2 with our OOBE may take a while, specially on slower connections or machines. Also, WSL 2 is known by having some internal issue limiting the internet speed when compared to the host system. That may turn the moment of installing language packs into an eternity.
I can foresee opportunity for extending the customisability of our setup experience with other options that won't reflect in the `/etc/wsl.conf` (where the options set in the types `WSLConfBase` and `WSLConfAdvanced` currently are writtent to). So I chose to create a new type and endpoint …

[WSL] Enables users to skip installing language packs

---

system_setup/server/controllers/wslsetupoptions.py
system_setup/server/server.py

We have strong defaults for that controller, so clients should only need to POST if the desired options are not the default ones.
This PR makes sure the controller is configured even if clients won't POST anything. That's useful for the GUI.

Sets WslSetupOptions as an optional controller

---

subiquitycore/ui/form.py

Per https://github.com/canonical/ubuntu-desktop-installer/issues/1073#issuecomment-1224493840 help texts should be styled in gray color.
With those canges in place one can still apply custom styles. Otherwise the gray is defaulted accross the board.

Defaults help text style to gray

---

examples/autoinstall-user-data.yaml
subiquity/models/subiquity.py
subiquity/models/tests/test_subiquity.py
subiquity/server/controllers/tests/test_userdata.py
subiquity/server/controllers/userdata.py

This will raise noisy SchemaValidationErrors if either deprecated keys
or schema errors are provided in autoinstall.user-data or in the
merged userdata_raw provided to cloud-init in the installed target.
This is part of a series of PRs to support cloud-init/subiquity live-installer usability:
1.  [Add /etc/cloud-init/clean.d/90-installer script to allow cloud-init clean to remove any installer artifacts for golden image creation](https://github.com/canonical/subiquity/pull/1347)
2. [subiquity to read `/run/cloud-init/instance-data-sensitive.json` for autoinstall: config directives instead of initializing `Init.read_cfg()`](https://github.com/canonical/subiquity/pull/1352)
3. [This PR] Perform schema initial validation on merged userdata_raw config within the installer environment to catch …

subiquitymodel: validate merged cloud-config userdata_raw before reboot

---

subiquity/tests/api/test_api.py

When removing some unused command line options from the function responsible for spawning the system_setup server under API test, I ended up introducing a hidden dependency on `.subiquity` directory, when the function that starts the server already provides a proper temporary directory to break such dependency.
This addresses that bug by respecting the `output_base` directory supplied by the `start_server` function.

Respects the output base dir on server.spawn() on API tests

---

subiquity/ui/views/snaplist.py

When pressing the "Try again" button on the snaps list, Subiquity would crash with:
`TypeError: SnapListView.wait_load() takes 1 positional argument but 2 were given`
This happens because urwid passes the sender to the callback as a parameter - which we need to discard (or accept it in the signature).
Fixed by discarding the sender.
The screen showing the "Try again" button is shown when the initial GET call to /snaplist (without `wait=True`) returns `LOADING` and then the second call (with `wait=True`) returns `FAILED`.
The below patch can be applied to get to this screen in dry-run mode:
```diff
diff --git a/subiquity/server/controllers/snaplist.py b/subiquity/server/controllers/snaplist.py
index 53be46b2..b8993dba 100644
--- a/subiquity/server/controllers/snaplist.py
+++ …
```

snaplist: fix crash when pressing "Try again" on snaplist

---

subiquity/client/controllers/ubuntu_pro.py

I ran mypy against the code base and it reported some errors in the new ubuntu pro implementation.
1. The type for a callable that takes no argument should be `Callable[[], ...]` and not `Callable[[None], ...]`.
2. The `on_initiated` callback only takes a single parameter today. It used to take two parameters when the expiry date was shown to the client, but we don't show it anymore.
3. There is no way (that I know of?)  to indicate expected keyword arguments for a callable. Maybe introducing a protocol [1] could solve this but for now let's call the callbacks with positional arguments only.
_None of these should impact subiquity at runtime so they don't need to be backported to ubuntu/kinetic_ 
[1] https://peps.python.org/pep-0544/

ubuntu-pro: fix type hints for contract selection callbacks

---

subiquity/client/controllers/ubuntu_pro.py

To disable Ubuntu Pro, I recently wrote a patch that raises a Skip exception from the make_ui function. Unfortunately, I forgot that one must mark the ubuntu_pro model configured. 
On non-LTS releases, Ubuntu Pro is already skipped properly so this does not cause any trouble.
While testing an install of 22.04.1 though, this bug prevents the installation from executing the late stages (Subiquity is waiting on Ubuntu Pro to be marked configured).
This fix needs to be back-ported to the ubuntu/kinetic branch.

ubuntu-pro: fixed model not being marked configured on LTS

---

system_setup/common/__init__.py

When Subiquity is packaged as its own snap, that subdirectory is not present.
That is due the lack of an `__init__.py` file.

Fix the missing `system_setup.common` error.

---

subiquity/client/controllers/snaplist.py

When creating the UI for snaplist, if the server returns a FAILED status when we request the list of snaps, we want to move on to the next screen.
However, calling self.next_screen in the make_ui function while also returning an actual view triggers a race condition. Depending on the order of execution of the instructions (which are asynchronous), the snaplist view can end up being shown even though we moved to the next screen. This ends up doing funny things upon clicking done.
Fixed by raising the Skip exception after making sure we mark snaplist configured.

Cherry-pick to kinetic: snaplist: avoid showing snaplist screen on failure

---

subiquity/common/filesystem/gaps.py
subiquity/common/filesystem/tests/test_gaps.py
subiquity/models/tests/test_filesystem.py

When editing a LVM logical volume (LV), Subiquity would crash with the following error:
```python
filesystem/gaps.py", line 244, in movable_trailing_partitions_and_gap_size
pgs = parts_and_gaps(partition.device)
AttributeError: 'LVM_LogicalVolume' object has no attribute 'device'
```
When we changed the implementation to use `movable_trailing_partitions_and_gap_size`, we did not pay attention to the LVM use case.

filesystem: fix crash when editing LVM logical volume

---

subiquity/tests/api/test_api.py
system_setup/common/wsl_conf.py
system_setup/server/controllers/wslconfadvanced.py
system_setup/server/controllers/wslconfbase.py
system_setup/server/controllers/wslsetupoptions.py

The recent WSLSetupOptions controller init method is misusing the default_loader().
That's meant for loading /etc/wsl.conf, but the WSLSetupOptions controller is, by design, not related to that config file.
That means it's init method is not necessary.
To be able to demonstrate that with tests, I had to revisit some older code, to make it testable, so I could inject a conf file causing (a very nasty) break.
When reviewing this, the last commit (2a598a8b5de72df0357a73a4fdf67020f49f0d5b) is the one that actually contains the fix. The previous ones were solely added for testability.

[WSL] Fixes wrong parameters being passed to init WslSetupOptions

---

subiquity/common/api/client.py
subiquity/common/api/defs.py
subiquity/common/api/server.py
subiquity/common/api/tests/test_client.py
subiquity/common/api/tests/test_endtoend.py
subiquity/common/api/tests/test_server.py

Two things really:
* snapd does not expect query arguments to be JSON, just strings
* snapd sometimes has part of the path by an argument to the method (e.g. /v2/snaps/{snap_name})
I've been looking for an excuse to support the second part here for ages ;-)

api extensions needed to talk to snapd API

---

snapcraft.yaml
system_setup/ubuntu-wsl-setup

As part of porting the WSL OOBE GUI to Windows we need to replace the UDI snap seeded in our rootfs by Subiquity. Doing so we lose a script that was originally added in https://github.com/canonical/ubuntu-desktop-installer/pull/349 acting as a launcher for the GUI application, which has lots of dependencies.
This set of changes place a similar script allowing the WSL environment, which still cannot support snapd, to somewhat be able to launch Subiquity from a snap. We achieve this result by essentially removing from the original script part of the UDI package anything strictly related to GUI support, such as OpenGL, GTK and GI related definitions and setups.
I attempted to remove not too much from it, i.e., definitions related to font config or XDG directories could have impact on the …

[WSL] Two stage snap launching

---

subiquity/server/controllers/snaplist.py
subiquity/server/controllers/tests/test_snaplist.py

This general idea about this PR is to make the snaplist more robust and fix some of the known issues.
List of changes in no particular order:
1. The list tasks now raises an exception in case of error.
* To check if the task was successful, once can call `task.done() and not task.exception()`.
* To check if it failed, one can call `task.done() and task.exception()`.
* To check if the task was cancelled, one can call `task.cancelled()`
* To check if the task is still running, one can call `not task.done()`
2. The use of `SingleInstanceTask` was replaced by a standard `asyncio.Task` object. This allows us to control better what happens in case of cancellation.
3. When waiting in the GET handler for `/snaplist`, if the loader is recreated (i.e., if a network event occurs), we catch the error …

Make snaplist more robust to races and fix snap info prefetch

---

reserved-usernames
snapcraft.yaml

The package udev (part of the systemd source package) creates system groups at installation.
In version 251.4, the following system groups are created:
* input
* sgx
* kvm
* render
When a user accidentally picks a username that corresponds to one of these udev groups, Subiquity gladly accepts it. However, on first boot, cloud-init fails to create the user because a group of the same name already exists.
Added these 4 groups to reserved-usernames so that they get rejected in the identity screen.
fixes https://bugs.launchpad.net/subiquity/+bug/1987341

reserved-usernames: add groups created by udev (src:systemd)

---

system_setup/client/client.py

In WSL, the environment variable SNAP_VERSION is unknown. This causes issue https://github.com/ubuntu/WSL/issues/212 to happen.
This PR fixes this by writing the revision instead of the version.
The revision is known by WSL thanks to [this line](https://github.com/ubuntu/wsl-setup/blob/7e6c9abb46cd7f370fc7d5647804278ebd03c976/wsl-setup#L71)

Fix unset SNAP_VERSION in WSL

---

subiquity/models/filesystem.py

This reverts commit 5fcd6776c1a27f16bccaf9cd56fd6abfdd3b7362.
I think I'd rather just ask people to avoid displaying the object IDs.

Revert "filesystem: part ids are not part nums"

---

scripts/runtests.sh
snapcraft.yaml
subiquity/models/filesystem.py
subiquity/models/keyboard.py
subiquity/models/subiquity.py

* cherry-picked bd79c1d from #1438 to revert the change to filesystem object IDs.  Curtin action object IDs are completely arbitrary, so one should not assume they have meaning.
* cherry-picked 2928ab8 from #1436 to fix success reporting for integration tests
* cherry-picked 76b1fae..870c99b from #1411 for LP: #[1894009](http://pad.lv/1894009)
* advance curtin to https://github.com/canonical/curtin/commit/47c222681c81110a185497a64749f23596e29b16 for LP: #[1987236](http://pad.lv/1987236) and to help ensure that cryptsetup is installed in the target system

Kinetic merge 2022-09-29

---

subiquity/common/filesystem/tests/test_gaps.py
subiquity/models/filesystem.py
subiquity/models/tests/test_filesystem.py

~Marking a draft until tested in KVM. Using dry-run looked promising so far.~ :heavy_check_mark: 
Our documentation of autoinstall mentions that one can specify the size of a partition as -1 to use the remaining space on the disk.
Because it only makes sense in practice to support this option for the right-most partition of a given disk, specifying size: -1 is only accepted when defining the last partition of the disk.
Having said that, when making an autoinstall configuration that includes an extended partition, the user must define the logical partitions after the extended partition.
For the following configuration:
```
|                                  disk                                |
+--------------+--------------+--------------+-------------------------|
| p1 (primary) | p2 …
```

filesystem: accept extended partition with size -1 in autoinstall

---

scripts/replay-curtin-log.py
snapcraft.yaml
subiquity/models/filesystem.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/install.py
subiquity/server/curtin.py

Doing this for the non-core boot classic path is unnecessary but it does let me check the code works, which is nice.
I haven't VM tested this yet, but the over-elaborate dry-run / replay support gives some confidence it's not completely broken.

track fs model objects device paths

---

subiquity/server/apt.py

When the apt overlay fails to umount, this directory removal will also fail due to the mount still being present.
LP: #1992531

apt: workaround umount failure

---

subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

Certain disk sizes could trigger unaligned bootfs size.  This can result in the next partition overlapping into the bootfs partition.
LP: #1992541

filesystem: ensure bootfs at aligned size

---

snapcraft.yaml
subiquity/server/apt.py
subiquity/server/controllers/filesystem.py
subiquity/server/controllers/tests/test_filesystem.py

* cherry-picked 62ed925 from #1450 to fix bad partition placement for some disk sizes with guided LVM LP: #[1992541](http://pad.lv/1992541)
* cherry-picked 24c28a8 from #1449 to fix a crash related to cleaning up mounts after running `ubuntu-drivers` LP: #[1992531](http://pad.lv/1992531)
* advance Probert to https://github.com/canonical/probert/commit/5324d262aca47e11ea8c137eec31af3119bdc26c to pick up fix for a crash related to `/dev/loop0` not being found LP: #[1992115](http://pad.lv/1992115)

Kinetic merge 2022-10-11

---

snapcraft.yaml
subiquity/server/apt.py
subiquity/server/controllers/drivers.py

* cherry-picked 631fbca..6954b30 from #1453 to make non-fatal more unmount failures for LP: #[1992977](http://pad.lv/1992977)
* advance Curtin to https://github.com/canonical/curtin/commit/1fc717df52ec15f616d26fff3c10bff181599b30 to ensure flash-kernel runs for LP: #[1992990](http://pad.lv/1992990)

Kinetic merge 2022-10-17
